{
  "hash": "09890ab330a8c5d9bfb39e3984554439",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Mémoire\"\ndate: \"2024-06-12\"\nformat: \n  html:\n    toc: true\n    toc_float: \n      collapsed: false\n      smooth_scroll: true\n      css: styles.css\ncategories: [Séries temporelles, R, MCO, ARMAX]\nimage: \"soy.jpg\" \n---\n\n\n\n**Sensibilité des prix agricoles face aux chocs climatiques**\n\n**Séries temporelles au Brésil de janvier 2000 à décembre 2022**\n\n# **Présentation**\n\nCette étude analyse les prix des produits agricoles au Brésil, un acteur clé des enjeux agricoles mondiaux, en utilisant l'indice des prix à la production agricole (IPA) de janvier 2000 à décembre 2022. L'étude a intégré des variables climatiques pour évaluer leur impact, en utilisant des modèles de régression tels que les Moindres Carrés Ordinaires (MCO) et ARMAX. Dans notre approche par les MCO, nous avons rencontré des difficultés telles que l'autocorrélation des résidus et l'hétéroscédasticité. Malgré plusieurs tentatives, le modèle MCO n'a pas pu être validé et nous avons adopté le modèle ARMAX qui s'est avéré plus efficace. Les résultats montrent que le taux de change, le prix du pétrole et l'influence des valeurs passées de l'IPA ont eu un impact statistiquement significatif. Nos recherches révèlent que, bien que les variables climatiques n'aient pas eu un effet notable, la complexité du système agricole suggère qu'une approche globale et uniforme n'est pas adéquate. Ainsi, nous préconisons, tant dans les études que dans l'élaboration des stratégies, l'adoption de mesures localisées qui répondent mieux aux besoins spécifiques des communautés agricoles.\n\n**Mots clés *:*** *Prix agricoles, Brésil, MCO, ARMAX,  R*\n\n### Sujet d’étude\n\nLe Brésil, l'un des plus grands producteurs agricoles mondiaux, est également riche en biodiversité et ressources environnementales. Toutefois, le pays est marqué par d'importantes disparités économiques et sociales, reflétées dans son secteur agricole qui se divise entre l'agriculture familiale et l'agrobusiness. Depuis 2000, les politiques brésiliennes ont alterné entre progrès et régression. Sous Lula da Silva, des avancées significatives ont été réalisées, tandis que les administrations suivantes ont vu des reculs, notamment avec la suppression de ministères clés et la libéralisation de la politique de réforme agraire. L'administration de Bolsonaro a augmenté les tensions entre développement agricole et conservation environnementale, en particulier avec l'augmentation de la déforestation en Amazonie. En tant que membre des BRICS et du MERCOSUR, le Brésil joue un rôle important dans les discussions internationales. Le traité de libre-échange entre l'UE et le MERCOSUR est un bon exemple de l'importance croissante du pays sur la scène internationale. L’objectif est de comprendre les facteurs qui influencent les prix à la production agricole du pays que beaucoup surnomment « la ferme du monde ».\n\n### Présentation des données\n\nLes données s'étendant de janvier 2000 à décembre 2022 avec une fréquence mensuelle, proviennent de trois sources : l'Institut de Recherche Économique Appliquée (IPEA DATA), les Statistiques de l'ONU pour l'alimentation et l'agriculture (FAO STAT), et le Portail de connaissances sur le changement climatique de la Banque mondiale (CCKP). Les variables explicatives incluent les variations de température (°C), les précipitations (mm), le nombre de jours secs consécutifs, le prix du pétrole, le taux de change (BRL/USD), le salaire minimum nominal (SMIC), et les indices des exportations et importations agricoles.\n\nDes statistiques descriptives ont mis en évidence une hausse marquée de l’IPA, particulièrement après 2016.\n\n![](memoire_y.png)\n\nSur le plan climatique, les données indiquent des périodes de sécheresse plus longues et des fluctuations de température tendant vers des valeurs maximales. En ce qui concerne les variables économiques, le prix du pétrole a subi de fortes fluctuations au cours des deux dernières décennies, principalement en raison du contexte géopolitique mondial. Le taux de change a connu une dévaluation notable depuis 2019, en réponse à la crise du COVID-19, ce qui a contribué à une augmentation exponentielle des exportations, accentuant une tendance déjà forte depuis 2010. Un prétraitement de nos données a été nécessaire en raison de la présence de valeurs atypiques.\n\n### Méthodologie\n\nPour analyser les variations de l'IPA, nous avons utilisé deux méthodes : MCO et ARMAX. Afin d’éviter les régressions fallacieuses et assurer la validité de nos modèles, nous avons vérifié la stationnarité avec les tests ADF et KPSS.\n\nLes séries temporelles présentant une saisonnalité ont été décomposées afin de corriger les variations saisonnières, permettant de mieux isoler les effets des variables explicatives. Nous avons aussi utilisé les tests de Breusch-Godfrey et Breusch-Pagan pour détecter l'autocorrélation et l'hétéroscédasticité, le test de Kolmogorov-Smirnov pour la normalité des résidus, et le test RESET pour la spécification du modèle, confirmant l'adéquation des modèles et la fiabilité des estimations des coefficients.\n\nNous avons exploré plusieurs modèles en utilisant l'approche MCO. Les problèmes d'hétéroscédasticité et de spécificité ont été corrigés en adoptant une forme semi-logarithmique. Cependant, malgré diverses tentatives, telles que l'introduction d'une variable temporelle, la correction de la tendance déterministe, et l’ajustement des résidus avec un modèle AR(1), les modèles ont continué de présenter une capacité explicative limitée et des problèmes de conformité aux hypothèses. Nous avons alors opté pour des modèles ARMAX, lesquels intègrent les effets des variables exogènes ainsi que la dynamique interne des séries temporelles.\n\n![](memoire_modeles.png)\n\nLe modèle révèle que les valeurs futures de notre série temporelle sont significativement influencées par les valeurs immédiatement antérieures, avec un niveau de significativité de 1%. Par ailleurs, le prix du pétrole est statistiquement significatif au seuil de risque de 5%. Avec un coefficient positif, lorsque les prix du pétrole augmentent, l'indice IPA augmente également. Il en est de même pour le taux de change, cela signifie que lorsque le real brésilien se déprécie,  les prix à la production agricole tendent à augmenter.\n\nConcernant les autres variables du modèle, elles ne montrent pas d'impact significatif . Quant à notre variable climatique, la précipitation, elle s'est révélée non significative, indiquant que , dans le cadre de cette étude,  les variations des précipitations n'ont pas un impact notable sur l'indice des prix à la production agricole de manière statistiquement mesurable.\n\n### Conclusion et discussion\n\nCette étude nous a montré la complexité du système agricole brésilien et, bien que nos résultats n'aient pas été ceux attendus, cela peut s'expliquer par la manière dont l'agriculture s'adapte aux changements climatiques. Alors que certaines régions voient leur production agricole diminuer en raison de conditions défavorables, d'autres connaissent une augmentation ou délocalisent leur production. Lorsque ces variations régionales sont agrégées au niveau national, les impacts locaux peuvent être masqués, minimisant ainsi les effets perceptibles sur les prix nationaux.\n\nPar ailleurs, les progrès technologiques en agriculture, bien qu'ils puissent améliorer les rendements et la gestion des cultures, introduisent une complexité supplémentaire dans l'évaluation des impacts directs du climat. Les innovations, comme les variétés résistantes à la sécheresse et l'optimisation des intrants, ont renforcé la résilience des cultures face aux aléas climatiques, permettant de maintenir des niveaux de production élevés même dans des conditions difficiles. Cependant, cette intensification pose des défis environnementaux significatifs, tels que l'épuisement des sols et une dépendance accrue aux produits chimiques, qui compliquent l'attribution précise des impacts du changement climatique dans les analyses économiques agricoles.\n\nIl est donc important de mettre en œuvre les avancées technologiques de manière réfléchie pour éviter des conséquences indésirables et de revoir les politiques agricoles pour assurer la durabilité et la sécurité alimentaire dans un climat changeant, en adaptant les pratiques agricoles aux nouvelles réalités climatiques et économiques.\n\n::: {style=\"text-align: center;\"}\n<iframe src=\"/pdf/memoire.pdf\" width=\"80%\" height=\"500px\">\n\n</iframe>\n:::\n\nVous avez la possibilité de télécharger le document ici :) [📥 Télécharger le fichier PDF](/pdf/memoire.pdf)\n\n**Présentation du code**\n\nJe vous présente ci-dessous, le code utilisé pour mener à bien ce projet, avec les étapes et explications correspondantes.\n\n### Librairies\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({\nlibrary(readxl)\nlibrary(ggplot2)\nlibrary(plotly)\nlibrary(tidyr)\nlibrary(dplyr)\nlibrary(ggcorrplot)\nlibrary(PerformanceAnalytics)\nlibrary(trend)\nlibrary(seastests)\nlibrary(tseries)\nlibrary(forecast)\nlibrary(tsoutliers)\nlibrary(EnvStats)\nlibrary(RJDemetra)\nlibrary(TSA)\nlibrary(lubridate)\nlibrary(tsoutliers)\nlibrary(leaps)\nlibrary(MASS)\nlibrary(car)\nlibrary(lmtest)\nlibrary(BeSS)\nlibrary(nlme)\nlibrary(here)\n})\n```\n:::\n\n\n\n# Analyse exploratoire\n\n## Chargement de données\n\nLes données de la variable du prix du pétrole ont une fréquence journalière, nous calculons donc la moyenne pour avoir un prix moyen mensuel\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npetrole <- read_excel(here(\"data\", \"donnees_br.xlsx\"), sheet = 'prix_petrole')\n\npetrole$date <- as.Date(petrole$date)\n\n#  Colonnes pour l'année et le mois\npetrole <- petrole %>%\n  mutate(\n    year = year(date),\n    month = month(date)\n  )\n\nprix_petrole <- petrole %>%\n  group_by(year, month) %>%\n  summarise(\n    prix_moyen = mean(prix, na.rm = TRUE), \n    .groups = 'drop'  # regroupement après le summarise\n  )\nrm(petrole) # supprime pétrole en jours\n```\n:::\n\n\n\nRécupération de l'ensemble de nos variables et remplacement de la variable prix du pétrole en jours, par le prix moyen mensuel\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ensemble de variables\n\ndata <- read_excel(here(\"data\", \"donnees_br.xlsx\"))\n\ndata$petrole <- prix_petrole$prix_moyen \n```\n:::\n\n\n\n### Valeurs manquantes et format des données\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(data)) # vérification des valeurs manquants\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 48\n```\n\n\n:::\n\n```{.r .cell-code}\ndata <- drop_na(data)\ndim(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 276  10\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(data) # vérification format\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [276 × 10] (S3: tbl_df/tbl/data.frame)\n $ date         : chr [1:276] \"2000.01\" \"2000.02\" \"2000.03\" \"2000.04\" ...\n $ IPA          : num [1:276] 199 196 193 192 193 ...\n $ CDD          : num [1:276] 2.86 2.94 3.03 4.61 12.14 ...\n $ precipitation: num [1:276] 255 241 247 206 124 ...\n $ temperature  : num [1:276] 0.558 0.226 0.159 0.607 0.548 ...\n $ exportations : num [1:276] 7.5 8.4 11.7 20.2 23.2 22.7 22.1 27.4 16.5 16 ...\n $ importations : num [1:276] 81.8 113 117.5 116.5 128.4 ...\n $ SMIC         : num [1:276] 136 136 136 151 151 151 151 151 151 151 ...\n $ taux_change  : num [1:276] 1.8 1.78 1.74 1.77 1.83 ...\n $ petrole      : num [1:276] 25.5 27.8 27.5 22.8 27.7 ...\n```\n\n\n:::\n\n```{.r .cell-code}\n# On transforme la variable smic en numérique\ndata$SMIC <- as.numeric(data$SMIC)\n\n\n# Conversion la colonne de date en type  yearmon\ndata$date <- as.yearmon(data$date, \"%Y.%m\")\n```\n:::\n\n\n\nLes données climatiques sont complètes jusqu'au mois de décembre 2022, on conserve donc l'ensemble des données du mois de janvier 2000 à décembre 2022. Au total nous avons 276 observations pour 13 variables.\n\n## Statistiques descriptives\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      date           IPA              CDD         precipitation   \n Min.   :2000   Min.   : 191.6   Min.   : 2.380   Min.   : 33.16  \n 1st Qu.:2006   1st Qu.: 401.5   1st Qu.: 4.728   1st Qu.: 72.14  \n Median :2011   Median : 649.3   Median : 8.440   Median :148.39  \n Mean   :2011   Mean   : 748.4   Mean   :10.107   Mean   :147.15  \n 3rd Qu.:2017   3rd Qu.: 944.3   3rd Qu.:15.315   3rd Qu.:212.66  \n Max.   :2023   Max.   :2133.2   Max.   :23.340   Max.   :288.10  \n  temperature       exportations     importations         SMIC       \n Min.   :-0.0920   Min.   :  7.50   Min.   : 50.80   Min.   : 136.0  \n 1st Qu.: 0.7768   1st Qu.: 31.70   1st Qu.: 81.00   1st Qu.: 300.0  \n Median : 1.0695   Median : 48.40   Median : 92.60   Median : 545.0  \n Mean   : 1.0869   Mean   : 59.26   Mean   : 93.65   Mean   : 602.5  \n 3rd Qu.: 1.3250   3rd Qu.: 82.65   3rd Qu.:107.47   3rd Qu.: 937.0  \n Max.   : 2.4310   Max.   :194.10   Max.   :149.80   Max.   :1212.0  \n  taux_change       petrole      \n Min.   :1.564   Min.   : 18.47  \n 1st Qu.:2.002   1st Qu.: 42.53  \n Median :2.473   Median : 62.81  \n Mean   :2.901   Mean   : 65.40  \n 3rd Qu.:3.521   3rd Qu.: 85.50  \n Max.   :5.651   Max.   :134.03  \n```\n\n\n:::\n:::\n\n\n\n### Boxplot\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata|>\npivot_longer(\ncols = where(is.numeric)\n) |>\nggplot() +\naes(y = value) +\nfacet_wrap(~ name, scales = \"free_y\") +\ngeom_boxplot() +\ntheme_light()\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n### Graphiques des séries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$date <- as.Date(as.yearmon(data$date))\n\n# Boucle sur chaque colonne sauf la date pour créer des graphiques\nfor (column_name in names(data)[-1]) {\np <- ggplot(data, aes(x = date, y = .data[[column_name]], colour = .data[[column_name]])) + \n        geom_line() +\n        scale_color_gradient(low = \"blue\", high = \"red\") + \n        labs(title = paste(\"Série temporelle: \", column_name),\n             x = \"Date\",\n             y = column_name,\n             colour = \"Intensité\") +  \n        theme_minimal()\n print(p)\n}\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-9.png){width=672}\n:::\n\n```{.r .cell-code}\n    print(p)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-7-10.png){width=672}\n:::\n:::\n\n\n\n### Convertir en time series\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Boucle pour convertir chaque colonne en ts et les stocker comme variables séparées\nfor(column_name in names(data)[-1]) {  # Exclure la colonne de date\n    # Créer une série temporelle pour la colonne actuelle\n    ts_data <- ts(data[[column_name]], start = c(2000, 1), frequency = 12)\n  # variable dans l'environnement global avec un nom dynamique\n    assign(paste0(\"ts_\", column_name), ts_data)\n}\n```\n:::\n\n\n\n## Points atypiques ou Outliers\n\n(attention cela peut prendre quelques minutes, possibilité de charger le fichier après correction data.adj (pour données ajustées))\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|warning: false\n#|message: false\n\n# on utilise tso() pour chercher les outliers\nfit_CDD <- tso(ts_CDD)\nfit_IPA <- tso(ts_IPA)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in locate.outliers.iloop(resid = resid, pars = pars, cval = cval, :\nstopped when 'maxit.iloop' was reached\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in locate.outliers.oloop(y = y, fit = fit, types = types, cval = cval,\n: stopped when 'maxit.oloop = 4' was reached\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_importations <- tso(ts_importations)\nfit_exportations <- tso(ts_exportations)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in locate.outliers.iloop(resid = resid, pars = pars, cval = cval, :\nstopped when 'maxit.iloop' was reached\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_petrole <- tso(ts_petrole)\nfit_taux_change <- tso(ts_taux_change)\nfit_SMIC <- tso(ts_SMIC)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in locate.outliers.iloop(resid = resid, pars = pars, cval = cval, :\nstopped when 'maxit.iloop' was reached\nWarning in locate.outliers.iloop(resid = resid, pars = pars, cval = cval, :\nstopped when 'maxit.oloop = 4' was reached\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_precipitation <- tso(ts_precipitation)\nfit_temperature <- tso(ts_temperature)\n\n\n# pour regarder les points atypiques de chaque serie \nfit_CDD # sans outliers \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries:  \nARIMA(0,0,2)(2,1,2)[12] \n\nCoefficients:\n         ma1     ma2     sar1     sar2     sma1     sma2\n      0.4183  0.2297  -0.8083  -0.0933  -0.0277  -0.6980\ns.e.  0.0635  0.0596   0.1733   0.0830   0.1735   0.1586\n\nsigma^2 = 2.206:  log likelihood = -484.75\nAIC=983.5   AICc=983.94   BIC=1008.53\n\nNo outliers were detected.\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_IPA \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts_IPA \nRegression with ARIMA(1,1,0) errors \n\nCoefficients:\n         ar1      LS252     TC258     TC263\n      0.6912  -149.6890  -77.9185  -42.7527\ns.e.  0.0435    13.6418   11.6972   11.6982\n\nsigma^2 = 275.1:  log likelihood = -1160.87\nAIC=2331.73   AICc=2331.96   BIC=2349.82\n\nOutliers:\n  type ind    time coefhat   tstat\n1   LS 252 2020:12 -149.69 -10.973\n2   TC 258 2021:06  -77.92  -6.661\n3   TC 263 2021:11  -42.75  -3.655\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_importations \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts_importations \nRegression with ARIMA(1,1,2)(1,0,0)[12] errors \n\nCoefficients:\n         ar1      ma1      ma2    sar1      LS47     AO98    LS195     LS206\n      0.0432  -0.7165  -0.1532  0.2900  -29.4529  47.8804  40.0092  -30.3560\ns.e.  0.3300   0.3263   0.2703  0.0597    7.4462  12.0018   7.3329    7.3662\n\nsigma^2 = 175.7:  log likelihood = -1097.94\nAIC=2213.88   AICc=2214.56   BIC=2246.43\n\nOutliers:\n  type ind    time coefhat  tstat\n1   LS  47 2003:11  -29.45 -3.955\n2   AO  98 2008:02   47.88  3.989\n3   LS 195 2016:03   40.01  5.456\n4   LS 206 2017:02  -30.36 -4.121\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_exportations \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts_exportations \nRegression with ARIMA(1,0,0)(0,1,1)[12] errors \n\nCoefficients:\n         ar1     sma1     AO33    AO114    LS185     AO254\n      0.7625  -0.6238  25.6306  31.0681  26.0407  -27.9435\ns.e.  0.0426   0.0510   6.9851   6.8995   6.8729    7.1521\n\nsigma^2 = 94.47:  log likelihood = -975.31\nAIC=1964.61   AICc=1965.05   BIC=1989.65\n\nOutliers:\n  type ind    time coefhat  tstat\n1   AO  33 2002:09   25.63  3.669\n2   AO 114 2009:06   31.07  4.503\n3   LS 185 2015:05   26.04  3.789\n4   AO 254 2021:02  -27.94 -3.907\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_petrole  # sans outliers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries:  \nARIMA(1,1,0) \n\nCoefficients:\n         ar1\n      0.3497\ns.e.  0.0567\n\nsigma^2 = 32.51:  log likelihood = -868.48\nAIC=1740.95   AICc=1741   BIC=1748.19\n\nNo outliers were detected.\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_taux_change \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts_taux_change \nRegression with ARIMA(0,1,1) errors \n\nCoefficients:\n         ma1    AO34\n      0.3165  0.3361\ns.e.  0.0573  0.0697\n\nsigma^2 = 0.0143:  log likelihood = 194.75\nAIC=-383.5   AICc=-383.41   BIC=-372.65\n\nOutliers:\n  type ind    time coefhat tstat\n1   AO  34 2002:10  0.3361 4.824\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_SMIC \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts_SMIC \nRegression with ARIMA(0,0,5)(0,0,2)[12] errors \n\nCoefficients:\n         ma1     ma2     ma3     ma4     ma5     sma1    sma2  intercept\n      0.8636  0.6544  0.5548  0.3908  0.1828  -0.9308  0.3063   144.4274\ns.e.  0.0632  0.0802  0.0792  0.0747  0.0548   0.0625  0.0594     4.3551\n         LS16     LS40     LS65     LS88    AO121     LS122    LS145    LS157\n      44.9926  61.3801  71.3287  94.4402  76.0256  120.9066  88.0599  44.6969\ns.e.   5.7660   4.2806   3.8698   3.8999   5.0530    4.4605   8.0303  10.7124\n        LS169     LS193    AO229     LS230    LS253     LS265\n      77.6692  177.1326  95.2608  104.2519  74.4118  107.2180\ns.e.   7.9620    4.3219   5.1179    4.4431   8.0232   11.0379\n\nsigma^2 = 69.78:  log likelihood = -972.05\nAIC=1990.11   AICc=1994.49   BIC=2073.38\n\nOutliers:\n   type ind    time coefhat  tstat\n1    LS  16 2001:04   44.99  7.803\n2    LS  40 2003:04   61.38 14.339\n3    LS  65 2005:05   71.33 18.432\n4    LS  88 2007:04   94.44 24.216\n5    AO 121 2010:01   76.03 15.046\n6    LS 122 2010:02  120.91 27.106\n7    LS 145 2012:01   88.06 10.966\n8    LS 157 2013:01   44.70  4.172\n9    LS 169 2014:01   77.67  9.755\n10   LS 193 2016:01  177.13 40.985\n11   AO 229 2019:01   95.26 18.613\n12   LS 230 2019:02  104.25 23.464\n13   LS 253 2021:01   74.41  9.275\n14   LS 265 2022:01  107.22  9.714\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_precipitation \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: ts_precipitation \nRegression with ARIMA(0,0,1)(2,1,0)[12] errors \n\nCoefficients:\n         ma1     sar1     sar2     TC49    AO193\n      0.2476  -0.6126  -0.3736  59.2558  86.5774\ns.e.  0.0571   0.0580   0.0589  14.5850  18.3329\n\nsigma^2 = 424.8:  log likelihood = -1174.07\nAIC=2360.14   AICc=2360.46   BIC=2381.59\n\nOutliers:\n  type ind    time coefhat tstat\n1   TC  49 2004:01   59.26 4.063\n2   AO 193 2016:01   86.58 4.723\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_temperature # sans outliers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries:  \nARIMA(0,1,2) \n\nCoefficients:\n          ma1      ma2\n      -0.6600  -0.1641\ns.e.   0.0588   0.0651\n\nsigma^2 = 0.1426:  log likelihood = -121.87\nAIC=249.74   AICc=249.83   BIC=260.59\n\nNo outliers were detected.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Graphique\nplot(fit_IPA)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(fit_SMIC)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(fit_precipitation)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-9-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(fit_taux_change)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-9-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(fit_exportations)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-9-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(fit_importations)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-9-6.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(fit_CDD )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'x' does not contain outliers to display\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\n# recuperation des séries ajustés \nadj_IPA <- fit_IPA$yadj \nadj_CDD <- fit_CDD$yadj \nadj_importations <- fit_importations$yadj \nadj_exportations <- fit_exportations$yadj \nadj_petrole <- fit_petrole$yadj \nadj_taux_change <- fit_taux_change$yadj \nadj_SMIC <- fit_SMIC$yadj \nadj_precipitation <- fit_precipitation$yadj \nadj_temperature <- fit_temperature$yadj \n```\n:::\n\n\n\n### Enregistrement données ajustés\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# création d'un dataframe où les séries ajustés seront stockés pour êtres réutilises si nécessaire plus tard \ndata_adj <- data.frame(\n  Date = data$date,  \n  IPA = adj_IPA,\n  CDD = adj_CDD,\n  importations = adj_importations,\n  exportations = adj_exportations,\n  petrole = adj_petrole,\n  taux_change = adj_taux_change,\n  SMIC = adj_SMIC,\n  precipitation = adj_precipitation,\n  temperature = adj_temperature\n)\n\n#write.csv(data_adj, \"data_adj.csv\", row.names = FALSE)\n```\n:::\n\n\n\n## Récupération base de données ajustées\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#data_adj <- read.csv(\"/Users/Isabel/Desktop/memoire3/data_adj.csv\")\n\ndata_adj$Date <- as.Date(data_adj$Date)\n\n\n#  variables\nvariables <- c(\"IPA\", \"CDD\", \"precipitation\", \"temperature\",  \"exportations\", \"importations\", \"taux_change\", \"SMIC\", \"petrole\")\n```\n:::\n\n\n\n### Skewness, kurtosis\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskew_kurt_df <- data.frame(\n  Variable = variables,\n  # Calcul de skewness\n  Skewness = sapply(data_adj[variables], PerformanceAnalytics::skewness),\n  # Calcul de kurtosis\n  Kurtosis = sapply(data_adj[variables], PerformanceAnalytics::kurtosis)\n)\nskew_kurt_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Variable     Skewness    Kurtosis\nIPA                     IPA  1.587451131  2.02938496\nCDD                     CDD  0.515154009 -1.09215980\nprecipitation precipitation  0.003335255 -1.39981138\ntemperature     temperature  0.354093594  0.24637826\nexportations   exportations  0.991190627  0.83599348\nimportations   importations -0.035585053 -0.48953698\ntaux_change     taux_change  0.982023281 -0.04678673\nSMIC                   SMIC  0.038077541 -0.44421037\npetrole             petrole  0.340169157 -0.94096896\n```\n\n\n:::\n:::\n\n\n\n### Test de normalité\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#vérification de la normalité des variables \nlapply(data_adj[variables], shapiro.test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$IPA\n\n\tShapiro-Wilk normality test\n\ndata:  X[[i]]\nW = 0.81162, p-value < 2.2e-16\n\n\n$CDD\n\n\tShapiro-Wilk normality test\n\ndata:  X[[i]]\nW = 0.90346, p-value = 2.662e-12\n\n\n$precipitation\n\n\tShapiro-Wilk normality test\n\ndata:  X[[i]]\nW = 0.92737, p-value = 2.312e-10\n\n\n$temperature\n\n\tShapiro-Wilk normality test\n\ndata:  X[[i]]\nW = 0.98853, p-value = 0.02765\n\n\n$exportations\n\n\tShapiro-Wilk normality test\n\ndata:  X[[i]]\nW = 0.93141, p-value = 5.389e-10\n\n\n$importations\n\n\tShapiro-Wilk normality test\n\ndata:  X[[i]]\nW = 0.99312, p-value = 0.2348\n\n\n$taux_change\n\n\tShapiro-Wilk normality test\n\ndata:  X[[i]]\nW = 0.87498, p-value = 3.167e-14\n\n\n$SMIC\n\n\tShapiro-Wilk normality test\n\ndata:  X[[i]]\nW = 0.97073, p-value = 2.005e-05\n\n\n$petrole\n\n\tShapiro-Wilk normality test\n\ndata:  X[[i]]\nW = 0.94924, p-value = 3.449e-08\n```\n\n\n:::\n:::\n\n\n\n### Corrélation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|warning: false\n#|message: false\n\n#  Matrice de corrélation\ncor_matrix <- cor(data_adj[, variables], use = \"complete.obs\", method = \"spearman\")\ncor_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      IPA         CDD precipitation temperature exportations\nIPA            1.00000000  0.07576372   -0.04386296  0.37647867   0.64924172\nCDD            0.07576372  1.00000000   -0.96428022  0.32220175   0.39372744\nprecipitation -0.04386296 -0.96428022    1.00000000 -0.33938317  -0.35647340\ntemperature    0.37647867  0.32220175   -0.33938317  1.00000000   0.28936878\nexportations   0.64924172  0.39372744   -0.35647340  0.28936878   1.00000000\nimportations   0.53493377 -0.11595776    0.14735573  0.09049610   0.42171195\ntaux_change    0.60748523  0.07445183   -0.06679673  0.36570691   0.32702233\nSMIC           0.01955579 -0.02748573    0.02980255  0.00564068   0.04615657\npetrole        0.42210699  0.08940170   -0.05840727 -0.02391271   0.44837226\n              importations taux_change         SMIC     petrole\nIPA            0.534933773  0.60748523  0.019555787  0.42210699\nCDD           -0.115957758  0.07445183 -0.027485733  0.08940170\nprecipitation  0.147355729 -0.06679673  0.029802545 -0.05840727\ntemperature    0.090496098  0.36570691  0.005640680 -0.02391271\nexportations   0.421711949  0.32702233  0.046156570  0.44837226\nimportations   1.000000000  0.06006558 -0.008959876  0.50385277\ntaux_change    0.060065584  1.00000000  0.098030177 -0.30572061\nSMIC          -0.008959876  0.09803018  1.000000000 -0.08122171\npetrole        0.503852770 -0.30572061 -0.081221712  1.00000000\n```\n\n\n:::\n\n```{.r .cell-code}\n# Visualiser la matrice de corrélation\n\nggcorrplot(cor_matrix,\n  hc.order = TRUE, type = \"lower\",\n  lab = TRUE,\n  ggtheme = ggplot2::theme_gray,\n  colors = c(\"blue\", \"white\", \"red\"))\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# spearman correlation test\n#chart.Correlation(data_adj[variables], histogram=TRUE, pch=19,method = c(\"spearman\"))\n```\n:::\n\n\n\nLe calcul de la corrélation de Spearman est recommandé lorsque les variables ne suivent pas une loi normalece type de corrélation est dit robuste car il ne dépend pas de la distribution des données. (cours M.Travers)\n\n## Composants\n\nNous commençons cette partie par deux tests : le premier est le test de tendance monotone de Mann-Kendall,et le deuxième est le test de saisonalité\n\n## Test de tendance Mann-Kendall\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test de tenance pour chaque variable \nlapply(data_adj[variables], function(x) {\n  mk.test(x, alternative = \"greater\")\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$IPA\n\n\tMann-Kendall trend test\n\ndata:  x\nz = 22.407, n = 276, p-value < 2.2e-16\nalternative hypothesis: true S is greater than 0\nsample estimates:\n           S         varS          tau \n3.434000e+04 2.348683e+06 9.048748e-01 \n\n\n$CDD\n\n\tMann-Kendall trend test\n\ndata:  x\nz = 1.4414, n = 276, p-value = 0.07474\nalternative hypothesis: true S is greater than 0\nsample estimates:\n           S         varS          tau \n2.210000e+03 2.348661e+06 5.825141e-02 \n\n\n$precipitation\n\n\tMann-Kendall trend test\n\ndata:  x\nz = -0.87893, n = 276, p-value = 0.8103\nalternative hypothesis: true S is greater than 0\nsample estimates:\n            S          varS           tau \n-1.348000e+03  2.348683e+06 -3.552042e-02 \n\n\n$temperature\n\n\tMann-Kendall trend test\n\ndata:  x\nz = 6.3914, n = 276, p-value = 8.22e-11\nalternative hypothesis: true S is greater than 0\nsample estimates:\n           S         varS          tau \n9.796000e+03 2.348657e+06 2.582176e-01 \n\n\n$exportations\n\n\tMann-Kendall trend test\n\ndata:  x\nz = 12.289, n = 276, p-value < 2.2e-16\nalternative hypothesis: true S is greater than 0\nsample estimates:\n           S         varS          tau \n1.883500e+04 2.348658e+06 4.964745e-01 \n\n\n$importations\n\n\tMann-Kendall trend test\n\ndata:  x\nz = 9.3009, n = 276, p-value < 2.2e-16\nalternative hypothesis: true S is greater than 0\nsample estimates:\n           S         varS          tau \n1.425500e+04 2.348659e+06 3.757397e-01 \n\n\n$taux_change\n\n\tMann-Kendall trend test\n\ndata:  x\nz = 10.163, n = 276, p-value < 2.2e-16\nalternative hypothesis: true S is greater than 0\nsample estimates:\n           S         varS          tau \n1.557600e+04 2.348681e+06 4.104456e-01 \n\n\n$SMIC\n\n\tMann-Kendall trend test\n\ndata:  x\nz = 0.57934, n = 276, p-value = 0.2812\nalternative hypothesis: true S is greater than 0\nsample estimates:\n           S         varS          tau \n8.880000e+02 2.344153e+06 2.385489e-02 \n\n\n$petrole\n\n\tMann-Kendall trend test\n\ndata:  x\nz = 8.2693, n = 276, p-value < 2.2e-16\nalternative hypothesis: true S is greater than 0\nsample estimates:\n           S         varS          tau \n1.267400e+04 2.348683e+06 3.339657e-01 \n```\n\n\n:::\n:::\n\n\n\n## Test Saisonnière\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# On transforme en format tsv\nts_data <- ts(data_adj[, 2:10], frequency = 12,  start = c(2000, 1))\n\n## Verfication de la saisonnalité \ntest_saison <- vector(\"logical\", ncol(ts_data))  # vecteur pour stocker les résultats\nnames(test_saison) <- colnames(ts_data)  # nomme les résultats selon les variables\n\nfor (i in 1:ncol(ts_data)) {\n  test_saison[i] <- isSeasonal(ts_data[, i], test = \"wo\")\n}\ntest_saison\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          IPA           CDD  importations  exportations       petrole \n        FALSE          TRUE          TRUE          TRUE         FALSE \n  taux_change          SMIC precipitation   temperature \n        FALSE         FALSE          TRUE          TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\n# Deuxième test Seasonal dummies\nfor (i in 1:ncol(ts_data)) {\n  nom_var <- colnames(ts_data)[i]\n  result <- seasdum(ts_data[, i])\n  cat(\"\\nTest Seasonal dummies: \", nom_var, \":\\n\")\n  print(result)\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest Seasonal dummies:  IPA :\nTest used:  SeasonalDummies \n \nTest statistic:  1.27 \nP-value:  0.2414814\n\nTest Seasonal dummies:  CDD :\nTest used:  SeasonalDummies \n \nTest statistic:  283.33 \nP-value:  0\n\nTest Seasonal dummies:  importations :\nTest used:  SeasonalDummies \n \nTest statistic:  6.31 \nP-value:  2.993919e-09\n\nTest Seasonal dummies:  exportations :\nTest used:  SeasonalDummies \n \nTest statistic:  23.43 \nP-value:  0\n\nTest Seasonal dummies:  petrole :\nTest used:  SeasonalDummies \n \nTest statistic:  1.06 \nP-value:  0.390488\n\nTest Seasonal dummies:  taux_change :\nTest used:  SeasonalDummies \n \nTest statistic:  1.31 \nP-value:  0.218587\n\nTest Seasonal dummies:  SMIC :\nTest used:  SeasonalDummies \n \nTest statistic:  0.06 \nP-value:  0.999995\n\nTest Seasonal dummies:  precipitation :\nTest used:  SeasonalDummies \n \nTest statistic:  351.69 \nP-value:  0\n\nTest Seasonal dummies:  temperature :\nTest used:  SeasonalDummies \n \nTest statistic:  4.35 \nP-value:  5.416069e-06\n```\n\n\n:::\n:::\n\n\n\nLes variables pressentant une saisonnalité d’après les tests sont CDD, importations, Exportations, Précipitation et température\n\nLe code ci-dessous et similaire à celui que nous avons fait precedement pour transformer les variables en time series, on a besoin si nous téléchargeons le fichier data.adj\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Boucle pour convertir chaque colonne en ts et les stocker comme variables séparées\nfor(column_name in names(data_adj)[-1]) {  # Exclure la colonne de date\n    # Créer une série temporelle pour la colonne actuelle\n    ts_list <- ts(data_adj[[column_name]], start = c(2000, 1), frequency = 12)\n  # variable dans l'environnement global avec un nom dynamique\n    assign(paste0(\"ts_\", column_name), ts_list)\n}\n```\n:::\n\n\n\n### Correlogramme des variables saisonnières\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,2))\n\n# ACF pour les variables presentant une saisonalité \n# CDD\nacf(ts_CDD, main = \"ACF CDD sur la série en niveau\")\nacf(diff(ts_CDD,differences = 1), main = \"ACF CDD sur la série en différence premiére\")\n# Précipitation\nacf(ts_precipitation, main = \"ACF Precipitations sur la série en niveau\")\nacf(diff(ts_precipitation,differences = 1), main = \"ACF Precipitations sur la série en différence premiére\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Témperature\nacf(ts_temperature, main = \"ACF Témperature sur la série en niveau \")\nacf(diff(ts_temperature,differences = 1), main = \"ACF Témperature sur la série en différence premiére\")\n# Importations\nacf(ts_importations, main = \"ACF Importations sur la série en niveau\")\nacf(diff(ts_importations, differences = 1),main = \"ACF Importations sur la série en différence premiére\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Exportations\nacf(ts_exportations, main = \"ACF Exportations sur la série en niveau\")\nacf(diff(ts_exportations,differences = 1), main = \"ACF Exportations sur la série en différence premiére\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-18-3.png){width=672}\n:::\n:::\n\n\n\n### Périodogramme\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Périodogramme ou filtre spectra pour les sérires presentant une saisonalité\n# CDD\nperiodogram(ts_CDD, main = \"Périodogramme CDD sur la série en niveau\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n```{.r .cell-code}\nperiodogram(diff(ts_CDD,differences = 1), main = \"Périodogramme CDD sur la série en différence premiére\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Precipitations\nperiodogram(ts_precipitation, main = \"Périodogramme Precipitations sur la série en niveau\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-3.png){width=672}\n:::\n\n```{.r .cell-code}\nperiodogram(diff(ts_precipitation,differences = 1), main = \"Périodogramme Precipitations sur la série en différence premiére\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# Temperature\nperiodogram(ts_temperature, main = \"Périodogramme Témperature sur la série en niveau \")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-5.png){width=672}\n:::\n\n```{.r .cell-code}\nperiodogram(diff(ts_temperature,differences = 1), main = \"Périodogramme Témperature sur la série en différence premiére\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-6.png){width=672}\n:::\n\n```{.r .cell-code}\n# Importations\nperiodogram(ts_importations, main = \"Périodogramme Importations sur la série en niveau\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-7.png){width=672}\n:::\n\n```{.r .cell-code}\nperiodogram(diff(ts_importations, differences = 1),main = \"Périodogramme Importations sur la série en différence premiére\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-8.png){width=672}\n:::\n\n```{.r .cell-code}\n# Exportations \nperiodogram(ts_exportations, main = \"Périodogramme Exportations sur la série en niveau\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-9.png){width=672}\n:::\n\n```{.r .cell-code}\nperiodogram(diff(ts_exportations,differences = 1), main = \"Périodogramme Exportations sur la série en différence premiére\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-19-10.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,2))\n\n# Boxplots pour les variables climatiques avec les cycles correspondants à chaque série\nboxplot(ts_CDD ~ cycle(ts_CDD), main = \"Boîte à moustaches des CDD par cycle\", xlab = \"Cycle\", ylab = \"CDD en jours\")\nboxplot(ts_precipitation ~ cycle(ts_precipitation), main = \"Boîte à moustaches des précipitations par cycle\", xlab = \"Cycle\", ylab = \"Précipitations en mm\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(ts_temperature ~ cycle(ts_temperature), main = \"Boîte à moustaches de la température par cycle\", xlab = \"Cycle\", ylab = \"Variations de température\")\n\n# Variables export - importation\nboxplot(ts_importations ~ cycle(ts_importations), main = \"Boîte à moustaches des importations par cycle\", xlab = \"Cycle\", ylab = \"Valeurs des importations\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(ts_exportations ~ cycle(ts_exportations), main = \"Boîte à moustaches des exportations par cycle\", xlab = \"Cycle\", ylab = \"Valeurs des exportations\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-20-3.png){width=672}\n:::\n:::\n\n\n\n## Test ADF\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|warning: false\n#|message: false\n\n# test ADF \nlapply(data_adj[variables], function(x) {\n  adf.test(x, alternative = \"stationary\")\n})\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$IPA\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -2.0623, Lag order = 6, p-value = 0.5498\nalternative hypothesis: stationary\n\n\n$CDD\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -15.661, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$precipitation\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -12.168, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$temperature\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -4.9028, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$exportations\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -8.6625, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$importations\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -3.7022, Lag order = 6, p-value = 0.02434\nalternative hypothesis: stationary\n\n\n$taux_change\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -1.4862, Lag order = 6, p-value = 0.7925\nalternative hypothesis: stationary\n\n\n$SMIC\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -6.0839, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$petrole\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -2.178, Lag order = 6, p-value = 0.5011\nalternative hypothesis: stationary\n```\n\n\n:::\n:::\n\n\n\n### Graphiques des variables non stationnaires Test ADF\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Graphique pour la série IPA\nggplot(data = data_adj, aes(x = Date, y = IPA)) +\n  geom_line(color = \"blue\", size = 0.5) +\n  stat_smooth(color = \"red\", fill = \"red\", method = \"loess\", show.legend = TRUE,  size = 0.2) +\n  ggtitle(\"Analyse de la tendance de l'IPA-DI sur la période 01/2000 - 12/2022\") +\n  xlab(\"Date\") +\n  ylab(\"IPA Value\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDon't know how to automatically pick scale for object of type <ts>. Defaulting\nto continuous.\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Graphique pour la série petrole\n\nggplot(data = data_adj, aes(x = Date, y = petrole)) +\n  geom_line(color = \"blue\", size = 0.5) +\n  stat_smooth(color = \"red\", fill = \"red\", method = \"loess\", show.legend = TRUE, size = 0.2) +\n  ggtitle(\"Analyse de la tendance du prix du pétrole sur la période 01/2000 - 12/2022\") +\n  xlab(\"Date\") +\n  ylab(\"Petrole Value\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDon't know how to automatically pick scale for object of type <ts>. Defaulting\nto continuous.\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-22-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Graphique pour la série taux de change \n\nggplot(data = data_adj, aes(x = Date, y = taux_change)) +\n  geom_line(color = \"blue\", size = 0.5) +\n  stat_smooth(color = \"red\", fill = \"red\", method = \"loess\", show.legend = TRUE, size = 0.2) +\n  ggtitle(\"Analyse de la tendance du taux de change sur la période 01/2000 - 12/2022\") +\n  xlab(\"Date\") +\n  ylab(\"Taux de change\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDon't know how to automatically pick scale for object of type <ts>. Defaulting\nto continuous.\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-22-3.png){width=672}\n:::\n:::\n\n\n\nLa fonction stat_smooth(method = \"loess\") ajoute une courbe de lissage aux données, utilisant la méthode LOESS (Locally Estimated Scatterplot Smoothing). Cette courbe est utile pour visualiser une tendance centrale plus lisse dans les données, ce qui peut être particulièrement bénéfique dans les cas où les données sont bruyantes ou volatiles\n\n## Test KPSS\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|warning: false\n#|message: false\n\n## Trend \nfor (i in 1:ncol(ts_data)) {\n  nom_var <- colnames(ts_data)[i]\n  result <- kpss.test(ts_data[, i], null = \"Trend\")\n  cat(\"\\nTest KPSS: \", nom_var, \":\\n\")\n  print(result)\n}\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Trend\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  IPA :\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_data[, i]\nKPSS Trend = 0.59792, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Trend\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  CDD :\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_data[, i]\nKPSS Trend = 0.0099421, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Trend\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  importations :\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_data[, i]\nKPSS Trend = 0.37607, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Trend\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  exportations :\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_data[, i]\nKPSS Trend = 0.034185, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Trend\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  petrole :\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_data[, i]\nKPSS Trend = 0.63433, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Trend\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  taux_change :\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_data[, i]\nKPSS Trend = 0.94899, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Trend\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  SMIC :\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_data[, i]\nKPSS Trend = 0.018996, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Trend\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  precipitation :\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_data[, i]\nKPSS Trend = 0.010157, Truncation lag parameter = 5, p-value = 0.1\n\n\nTest KPSS:  temperature :\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_data[, i]\nKPSS Trend = 0.13529, Truncation lag parameter = 5, p-value = 0.06984\n```\n\n\n:::\n\n```{.r .cell-code}\n## Level \nfor (i in 1:ncol(ts_data)) {\n  nom_var <- colnames(ts_data)[i]\n  result <- kpss.test(ts_data[, i], null = \"Level\")\n  cat(\"\\nTest KPSS: \", nom_var, \":\\n\")\n  print(result)\n}\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Level\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  IPA :\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_data[, i]\nKPSS Level = 3.5331, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Level\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  CDD :\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_data[, i]\nKPSS Level = 0.089483, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Level\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  importations :\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_data[, i]\nKPSS Level = 2.666, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Level\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  exportations :\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_data[, i]\nKPSS Level = 3.1023, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Level\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  petrole :\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_data[, i]\nKPSS Level = 1.2759, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Level\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  taux_change :\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_data[, i]\nKPSS Level = 2.6251, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Level\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  SMIC :\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_data[, i]\nKPSS Level = 0.020247, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Level\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  precipitation :\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_data[, i]\nKPSS Level = 0.030274, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_data[, i], null = \"Level\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTest KPSS:  temperature :\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_data[, i]\nKPSS Level = 1.7517, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n:::\n\n\n\n## Correction\n\nNous allons maintenant déterminer le type de schéma des séries, multiplicatif ou addif\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Approche Graphique \nplot(ts_CDD)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(ts_precipitation)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-24-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(ts_temperature)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-24-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(ts_importations)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-24-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(ts_exportations)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-24-5.png){width=672}\n:::\n\n```{.r .cell-code}\n#  Test log-level\nregx13_CDD <- regarima_x13(ts_CDD, spec =\"RG5c\") \ns_transform(regx13_CDD)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n tfunction adjust aicdiff\n      Auto   None      -2\n```\n\n\n:::\n\n```{.r .cell-code}\nregx13_precipitation <- regarima_x13(ts_precipitation, spec =\"RG5c\") \ns_transform(regx13_precipitation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n tfunction adjust aicdiff\n      Auto   None      -2\n```\n\n\n:::\n\n```{.r .cell-code}\nregx13_temperature <- regarima_x13(ts_temperature, spec =\"RG5c\") \ns_transform(regx13_temperature)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n tfunction adjust aicdiff\n      Auto   None      -2\n```\n\n\n:::\n\n```{.r .cell-code}\nregx13_importations <- regarima_x13(ts_importations, spec =\"RG5c\") \ns_transform(regx13_importations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n tfunction adjust aicdiff\n      Auto   None      -2\n```\n\n\n:::\n\n```{.r .cell-code}\nregx13_exportations <- regarima_x13(ts_exportations, spec =\"RG5c\") \ns_transform(regx13_exportations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n tfunction adjust aicdiff\n      Auto   None      -2\n```\n\n\n:::\n:::\n\n\n\nCe test est spécifiquement conçu pour décider si une transformation logarithmique des données est appropriée\n\n### Décomposition\n\nUtilisation de decompose pour une décomposition additive\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Décomposition \ndecom_CDD <- decompose(ts_CDD, type=\"additive\")\ndecom_precipitations<- decompose(ts_precipitation, type=\"additive\")\ndecom_temperature <- decompose(ts_temperature, type=\"additive\")\ndecom_importations <- decompose(ts_importations, type=\"additive\")\ndecom_importations <- decompose(ts_importations, type=\"additive\")\ndecom_exportations <- decompose(ts_exportations, type = \"additive\")\n\n# Plot \n\n\nplot(decom_CDD)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(decom_temperature)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-25-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(decom_precipitations)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-25-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(decom_importations)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-25-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(decom_exportations)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-25-5.png){width=672}\n:::\n:::\n\n\n\nChacune de nos variables saisonnières est décomposé en 'trend', 'seasonl', 'random'\n\n### Désaisonalitation\n\nCDD\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCDD_deseason <- ts_CDD - decom_CDD$seasonal\ncdd <- ts.intersect(ts_CDD, CDD_deseason)\n# Graphique \nplot.ts(cdd, \n        plot.type = \"single\",\n        col = c(\"red\", \"blue\"),\n        main = \"CDD série originale (rouge) et désaisonnalisée (bleu)\",\n        xlab = \"Période\",\n        ylab= \"Nombre de jours\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\nTempérature\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemperature_deseason <- ts_temperature - decom_temperature$seasonal\ntemperature <- ts.intersect(ts_temperature, temperature_deseason)\n# Graphique \nplot.ts(temperature, \n        plot.type = \"single\",\n        col = c(\"red\", \"blue\"),\n        main = \"Témperature série originale (rouge) et désaisonnalisée (bleu)\",\n        xlab = \"Période\",\n        ylab= \"Variation de la témperature\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\nPrécipitations\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecipitations_deseason <- ts_precipitation - decom_precipitations$seasonal\n\nprecipitations <- ts.intersect(ts_precipitation, precipitations_deseason)\n# Graphique \nplot.ts(precipitations, \n        plot.type = \"single\",\n        col = c(\"red\", \"blue\"),\n        main = \"Précipitations série originale (rouge) et désaisonnalisée (bleu)\",\n        xlab = \"Période\",\n        ylab= \"Précipations en mm\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n\nExportation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexportations_deseason <- ts_exportations - decom_exportations$seasonal\n\nexportations <- ts.intersect(ts_exportations, exportations_deseason)\n# Graphique \nplot.ts(exportations, \n        plot.type = \"single\",\n        col = c(\"red\", \"blue\"),\n        main = \"Exportations série originale (rouge) et désaisonnalisée (bleu)\",\n        xlab = \"Période\",\n        ylab= \"Indice exportation\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\nImportation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimportations_deseason <- ts_importations - decom_importations$seasonal\n\nimportations <- ts.intersect(ts_importations, importations_deseason)\n# Graphique \nplot.ts(importations, \n        plot.type = \"single\",\n        col = c(\"red\", \"blue\"),\n        main = \"Importations série originale (rouge) et désaisonnalisée (bleu)\",\n        xlab = \"Période\",\n        ylab= \"Indice importations\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# CDD \nadf.test(CDD_deseason, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(CDD_deseason, alternative = \"stationary\"): p-value smaller\nthan printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  CDD_deseason\nDickey-Fuller = -6.1831, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(CDD_deseason,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(CDD_deseason, null = \"Trend\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  CDD_deseason\nKPSS Trend = 0.053447, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(CDD_deseason,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(CDD_deseason, null = \"Level\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  CDD_deseason\nKPSS Level = 0.85893, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# temperature \nadf.test(temperature_deseason, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  temperature_deseason\nDickey-Fuller = -3.9825, Lag order = 6, p-value = 0.01032\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(temperature_deseason,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  temperature_deseason\nKPSS Trend = 0.14896, Truncation lag parameter = 5, p-value = 0.04753\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(temperature_deseason,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(temperature_deseason, null = \"Level\"): p-value smaller\nthan printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  temperature_deseason\nKPSS Level = 1.7965, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# precipitation\nadf.test(precipitations_deseason, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(precipitations_deseason, alternative = \"stationary\"):\np-value smaller than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  precipitations_deseason\nDickey-Fuller = -5.8362, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(precipitations_deseason,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(precipitations_deseason, null = \"Trend\"): p-value greater\nthan printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  precipitations_deseason\nKPSS Trend = 0.078174, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(precipitations_deseason,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(precipitations_deseason, null = \"Level\"): p-value greater\nthan printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  precipitations_deseason\nKPSS Level = 0.22839, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importations\nadf.test(importations_deseason, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  importations_deseason\nDickey-Fuller = -3.3037, Lag order = 6, p-value = 0.07096\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(importations_deseason,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(importations_deseason, null = \"Trend\"): p-value smaller\nthan printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  importations_deseason\nKPSS Trend = 0.39913, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(importations_deseason,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(importations_deseason, null = \"Level\"): p-value smaller\nthan printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  importations_deseason\nKPSS Level = 2.7696, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n\n```{.r .cell-code}\n# Differenciaiton\nimportation_diff <- diff(importations_deseason, differences = 1)\nadf.test(importation_diff, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(importation_diff, alternative = \"stationary\"): p-value\nsmaller than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  importation_diff\nDickey-Fuller = -10.305, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(importation_diff,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(importation_diff, null = \"Trend\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  importation_diff\nKPSS Trend = 0.014578, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(importation_diff,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(importation_diff, null = \"Level\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  importation_diff\nKPSS Level = 0.031579, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exportations \nadf.test(exportations_deseason, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(exportations_deseason, alternative = \"stationary\"): p-value\nsmaller than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  exportations_deseason\nDickey-Fuller = -6.2104, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(exportations_deseason,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(exportations_deseason, null = \"Trend\"): p-value greater\nthan printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  exportations_deseason\nKPSS Trend = 0.067186, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(exportations_deseason,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(exportations_deseason, null = \"Level\"): p-value smaller\nthan printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  exportations_deseason\nKPSS Level = 3.7622, Truncation lag parameter = 5, p-value = 0.01\n```\n\n\n:::\n:::\n\n\n\n### Différenciation des séries non stationnaires par la tendance stochastique\n\n### Tests après corrections\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|warning: false\n#|message: false\n\n# Differenciation \nipa_diff <- diff(ts_data[, \"IPA\"])\ntaux_change_diff <- diff(ts_data[, \"taux_change\"])\npetrole_diff <- diff(ts_data[, \"petrole\"])\n\n# TESTS FINAL ADF ET KPSS \n\n#IPA\nadf.test(ipa_diff, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  ipa_diff\nDickey-Fuller = -3.9389, Lag order = 6, p-value = 0.01251\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(ipa_diff,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ipa_diff\nKPSS Trend = 0.12657, Truncation lag parameter = 5, p-value = 0.08599\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(ipa_diff,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  ipa_diff\nKPSS Level = 0.58846, Truncation lag parameter = 5, p-value = 0.02369\n```\n\n\n:::\n\n```{.r .cell-code}\n# Taux de change\nadf.test(taux_change_diff, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(taux_change_diff, alternative = \"stationary\"): p-value\nsmaller than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  taux_change_diff\nDickey-Fuller = -6.4556, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(taux_change_diff,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(taux_change_diff, null = \"Trend\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  taux_change_diff\nKPSS Trend = 0.070678, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(taux_change_diff,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(taux_change_diff, null = \"Level\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  taux_change_diff\nKPSS Level = 0.17753, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Pétrole\nadf.test(petrole_diff, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(petrole_diff, alternative = \"stationary\"): p-value smaller\nthan printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  petrole_diff\nDickey-Fuller = -6.3498, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(petrole_diff,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(petrole_diff, null = \"Trend\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  petrole_diff\nKPSS Trend = 0.038075, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(petrole_diff,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(petrole_diff, null = \"Level\"): p-value greater than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  petrole_diff\nKPSS Level = 0.055257, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\n# smic\nadf.test(ts_SMIC, alternative = \"stationary\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(ts_SMIC, alternative = \"stationary\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  ts_SMIC\nDickey-Fuller = -6.0839, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(ts_SMIC,  null = \"Trend\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_SMIC, null = \"Trend\"): p-value greater than printed\np-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Trend Stationarity\n\ndata:  ts_SMIC\nKPSS Trend = 0.018996, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(ts_SMIC,  null = \"Level\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(ts_SMIC, null = \"Level\"): p-value greater than printed\np-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  ts_SMIC\nKPSS Level = 0.020247, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n:::\n\n\n\n### Data frame avec les variables stationnaires\n\nMaintenant que nos séries ont été rendues stationnaires, nous allons créer un nouveau dataframe avec ces variables. Cependant, du fait que la différenciation entraîne la perte de la première observation, nous devrons également supprimer la première observation des séries qui étaient déjà stationnaires. Ainsi, nous ajusterons toutes les séries pour aligner leurs longueurs.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|warning: false\n#|message: false\n# Suppression de la première observation des séries non différenciées\n\n#  dataframe avec des longueurs alignées\nstationnaire_data <- data.frame(\n  Date = data_adj$Date[-1],\n  IPA = ipa_diff,  \n  CDD = CDD_deseason[-1],  \n  importations = importation_diff,\n  exportations = exportations_deseason[-1],\n  petrole = petrole_diff, \n  taux_change = taux_change_diff,  \n  SMIC = ts_SMIC[-1],\n  precipitation = precipitations_deseason[-1],\n  temperature = temperature_deseason[-1]\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#|warning: false\n#|message: false\n\n\n# Re vérification du test ADF \nlapply(stationnaire_data[variables], function(x) {\n  adf.test(x, alternative = \"stationary\")\n})\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\nWarning in adf.test(x, alternative = \"stationary\"): p-value smaller than\nprinted p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$IPA\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -3.9389, Lag order = 6, p-value = 0.01251\nalternative hypothesis: stationary\n\n\n$CDD\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -6.4265, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$precipitation\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -5.8847, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$temperature\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -3.9132, Lag order = 6, p-value = 0.01379\nalternative hypothesis: stationary\n\n\n$exportations\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -6.2011, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$importations\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -10.305, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$taux_change\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -6.4556, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$SMIC\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -6.0722, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n\n\n$petrole\n\n\tAugmented Dickey-Fuller Test\n\ndata:  x\nDickey-Fuller = -6.3498, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\n# test kpss \nlapply(stationnaire_data[variables], function(x) {\n  kpss.test(x, null = \"Trend\")\n})\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(x, null = \"Trend\"): p-value greater than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(x, null = \"Trend\"): p-value greater than printed p-value\nWarning in kpss.test(x, null = \"Trend\"): p-value greater than printed p-value\nWarning in kpss.test(x, null = \"Trend\"): p-value greater than printed p-value\nWarning in kpss.test(x, null = \"Trend\"): p-value greater than printed p-value\nWarning in kpss.test(x, null = \"Trend\"): p-value greater than printed p-value\nWarning in kpss.test(x, null = \"Trend\"): p-value greater than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$IPA\n\n\tKPSS Test for Trend Stationarity\n\ndata:  x\nKPSS Trend = 0.12657, Truncation lag parameter = 5, p-value = 0.08599\n\n\n$CDD\n\n\tKPSS Test for Trend Stationarity\n\ndata:  x\nKPSS Trend = 0.052585, Truncation lag parameter = 5, p-value = 0.1\n\n\n$precipitation\n\n\tKPSS Test for Trend Stationarity\n\ndata:  x\nKPSS Trend = 0.081222, Truncation lag parameter = 5, p-value = 0.1\n\n\n$temperature\n\n\tKPSS Test for Trend Stationarity\n\ndata:  x\nKPSS Trend = 0.14976, Truncation lag parameter = 5, p-value = 0.04686\n\n\n$exportations\n\n\tKPSS Test for Trend Stationarity\n\ndata:  x\nKPSS Trend = 0.066037, Truncation lag parameter = 5, p-value = 0.1\n\n\n$importations\n\n\tKPSS Test for Trend Stationarity\n\ndata:  x\nKPSS Trend = 0.014578, Truncation lag parameter = 5, p-value = 0.1\n\n\n$taux_change\n\n\tKPSS Test for Trend Stationarity\n\ndata:  x\nKPSS Trend = 0.070678, Truncation lag parameter = 5, p-value = 0.1\n\n\n$SMIC\n\n\tKPSS Test for Trend Stationarity\n\ndata:  x\nKPSS Trend = 0.019059, Truncation lag parameter = 5, p-value = 0.1\n\n\n$petrole\n\n\tKPSS Test for Trend Stationarity\n\ndata:  x\nKPSS Trend = 0.038075, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\n# test kpss \nlapply(stationnaire_data[variables], function(x) {\n  kpss.test(x, null = \"Level\")\n})\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(x, null = \"Level\"): p-value smaller than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(x, null = \"Level\"): p-value greater than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(x, null = \"Level\"): p-value smaller than printed p-value\nWarning in kpss.test(x, null = \"Level\"): p-value smaller than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in kpss.test(x, null = \"Level\"): p-value greater than printed p-value\nWarning in kpss.test(x, null = \"Level\"): p-value greater than printed p-value\nWarning in kpss.test(x, null = \"Level\"): p-value greater than printed p-value\nWarning in kpss.test(x, null = \"Level\"): p-value greater than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$IPA\n\n\tKPSS Test for Level Stationarity\n\ndata:  x\nKPSS Level = 0.58846, Truncation lag parameter = 5, p-value = 0.02369\n\n\n$CDD\n\n\tKPSS Test for Level Stationarity\n\ndata:  x\nKPSS Level = 0.83849, Truncation lag parameter = 5, p-value = 0.01\n\n\n$precipitation\n\n\tKPSS Test for Level Stationarity\n\ndata:  x\nKPSS Level = 0.21186, Truncation lag parameter = 5, p-value = 0.1\n\n\n$temperature\n\n\tKPSS Test for Level Stationarity\n\ndata:  x\nKPSS Level = 1.7803, Truncation lag parameter = 5, p-value = 0.01\n\n\n$exportations\n\n\tKPSS Test for Level Stationarity\n\ndata:  x\nKPSS Level = 3.7628, Truncation lag parameter = 5, p-value = 0.01\n\n\n$importations\n\n\tKPSS Test for Level Stationarity\n\ndata:  x\nKPSS Level = 0.031579, Truncation lag parameter = 5, p-value = 0.1\n\n\n$taux_change\n\n\tKPSS Test for Level Stationarity\n\ndata:  x\nKPSS Level = 0.17753, Truncation lag parameter = 5, p-value = 0.1\n\n\n$SMIC\n\n\tKPSS Test for Level Stationarity\n\ndata:  x\nKPSS Level = 0.019994, Truncation lag parameter = 5, p-value = 0.1\n\n\n$petrole\n\n\tKPSS Test for Level Stationarity\n\ndata:  x\nKPSS Level = 0.055257, Truncation lag parameter = 5, p-value = 0.1\n```\n\n\n:::\n:::\n\n\n\n## Sélection des variables\n\n1er méthode\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleaps <- regsubsets(IPA ~ CDD +  importations + exportations +  petrole +  taux_change + SMIC + precipitation + temperature, data=stationnaire_data, nbest=1, method=c(\"exhaustive\"))\n\nsummary(leaps)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSubset selection object\nCall: regsubsets.formula(IPA ~ CDD + importations + exportations + \n    petrole + taux_change + SMIC + precipitation + temperature, \n    data = stationnaire_data, nbest = 1, method = c(\"exhaustive\"))\n8 Variables  (and intercept)\n              Forced in Forced out\nCDD               FALSE      FALSE\nimportations      FALSE      FALSE\nexportations      FALSE      FALSE\npetrole           FALSE      FALSE\ntaux_change       FALSE      FALSE\nSMIC              FALSE      FALSE\nprecipitation     FALSE      FALSE\ntemperature       FALSE      FALSE\n1 subsets of each size up to 8\nSelection Algorithm: exhaustive\n         CDD importations exportations petrole taux_change SMIC precipitation\n1  ( 1 ) \" \" \" \"          \"*\"          \" \"     \" \"         \" \"  \" \"          \n2  ( 1 ) \"*\" \" \"          \"*\"          \" \"     \" \"         \" \"  \" \"          \n3  ( 1 ) \" \" \" \"          \"*\"          \"*\"     \" \"         \" \"  \"*\"          \n4  ( 1 ) \" \" \" \"          \"*\"          \"*\"     \"*\"         \" \"  \"*\"          \n5  ( 1 ) \"*\" \" \"          \"*\"          \"*\"     \"*\"         \" \"  \"*\"          \n6  ( 1 ) \"*\" \"*\"          \"*\"          \"*\"     \"*\"         \" \"  \"*\"          \n7  ( 1 ) \"*\" \"*\"          \"*\"          \"*\"     \"*\"         \" \"  \"*\"          \n8  ( 1 ) \"*\" \"*\"          \"*\"          \"*\"     \"*\"         \"*\"  \"*\"          \n         temperature\n1  ( 1 ) \" \"        \n2  ( 1 ) \" \"        \n3  ( 1 ) \" \"        \n4  ( 1 ) \" \"        \n5  ( 1 ) \" \"        \n6  ( 1 ) \" \"        \n7  ( 1 ) \"*\"        \n8  ( 1 ) \"*\"        \n```\n\n\n:::\n\n```{.r .cell-code}\n# Résumé des critères pour choisir le modèle optimal\nres.sum <- summary(leaps)\noptimal_model <- data.frame(\n  Adj.R2 = which.max(res.sum$adjr2),\n  CP = which.min(res.sum$cp),\n  BIC = which.min(res.sum$bic)\n)\n\n# Affichage des résultats\nprint(optimal_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Adj.R2 CP BIC\n1      5  5   3\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(res.sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSubset selection object\nCall: regsubsets.formula(IPA ~ CDD + importations + exportations + \n    petrole + taux_change + SMIC + precipitation + temperature, \n    data = stationnaire_data, nbest = 1, method = c(\"exhaustive\"))\n8 Variables  (and intercept)\n              Forced in Forced out\nCDD               FALSE      FALSE\nimportations      FALSE      FALSE\nexportations      FALSE      FALSE\npetrole           FALSE      FALSE\ntaux_change       FALSE      FALSE\nSMIC              FALSE      FALSE\nprecipitation     FALSE      FALSE\ntemperature       FALSE      FALSE\n1 subsets of each size up to 8\nSelection Algorithm: exhaustive\n         CDD importations exportations petrole taux_change SMIC precipitation\n1  ( 1 ) \" \" \" \"          \"*\"          \" \"     \" \"         \" \"  \" \"          \n2  ( 1 ) \"*\" \" \"          \"*\"          \" \"     \" \"         \" \"  \" \"          \n3  ( 1 ) \" \" \" \"          \"*\"          \"*\"     \" \"         \" \"  \"*\"          \n4  ( 1 ) \" \" \" \"          \"*\"          \"*\"     \"*\"         \" \"  \"*\"          \n5  ( 1 ) \"*\" \" \"          \"*\"          \"*\"     \"*\"         \" \"  \"*\"          \n6  ( 1 ) \"*\" \"*\"          \"*\"          \"*\"     \"*\"         \" \"  \"*\"          \n7  ( 1 ) \"*\" \"*\"          \"*\"          \"*\"     \"*\"         \" \"  \"*\"          \n8  ( 1 ) \"*\" \"*\"          \"*\"          \"*\"     \"*\"         \"*\"  \"*\"          \n         temperature\n1  ( 1 ) \" \"        \n2  ( 1 ) \" \"        \n3  ( 1 ) \" \"        \n4  ( 1 ) \" \"        \n5  ( 1 ) \" \"        \n6  ( 1 ) \" \"        \n7  ( 1 ) \"*\"        \n8  ( 1 ) \"*\"        \n```\n\n\n:::\n\n```{.r .cell-code}\n# plot a table of models showing variables in each model.\n# models are ordered by the selection statistic\n# Other options for plot( ) are bic, Cp, and adjr2\npar(mfrow=c(1,1))\n\nplot(leaps, scale=\"adjr2\", main = \"Adjusted R^2\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(leaps, scale=\"Cp\", main = \"Mallow's Cp\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-39-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(leaps, scale=\"bic\", main = \"BIC\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-39-3.png){width=672}\n:::\n:::\n\n\n\n## Deuxième approche de sélection\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modele avec toutes les variables, ne sera pas utilisé dans notre analyse - voir méthode STEP\n\nmodele1 <- lm(IPA ~  CDD +  importations + exportations +  petrole +  taux_change + SMIC + precipitation + temperature, data=stationnaire_data)\n\nsummary(modele1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ CDD + importations + exportations + petrole + \n    taux_change + SMIC + precipitation + temperature, data = stationnaire_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-63.082  -9.647  -1.660   7.512 114.297 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    3.50014   21.25705   0.165 0.869338    \nCDD            1.67054    0.95321   1.753 0.080834 .  \nimportations   0.04751    0.08371   0.568 0.570832    \nexportations   0.23078    0.05235   4.409 1.51e-05 ***\npetrole        0.75790    0.21168   3.580 0.000408 ***\ntaux_change   21.03398   10.31384   2.039 0.042399 *  \nSMIC           0.00493    0.05341   0.092 0.926529    \nprecipitation -0.16864    0.08630  -1.954 0.051731 .  \ntemperature   -1.30279    3.41350  -0.382 0.703021    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.1 on 266 degrees of freedom\nMultiple R-squared:  0.1708,\tAdjusted R-squared:  0.1458 \nF-statistic: 6.847 on 8 and 266 DF,  p-value: 3.489e-08\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step : Sélection des variables explicatives significatives (modèle linéaire = modele1 )\n\nmodele0 <- lm(IPA~1,data=stationnaire_data)\nsummary(modele0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ 1, data = stationnaire_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-60.985 -10.203  -3.965   5.489 132.912 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    7.146      1.311   5.449 1.13e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 21.75 on 274 degrees of freedom\n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode ascendante\nstep1 <- step(modele0, scope=list(lower=modele0, upper=modele1), data=stationnaire_data, direction=\"forward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=1694.75\nIPA ~ 1\n\n                Df Sum of Sq    RSS    AIC\n+ exportations   1   10514.2 119087 1673.5\n+ CDD            1    7482.6 122118 1680.4\n+ precipitation  1    5178.7 124422 1685.5\n+ petrole        1    3258.2 126343 1689.8\n+ temperature    1    2522.9 127078 1691.3\n<none>                       129601 1694.8\n+ taux_change    1     396.9 129204 1695.9\n+ importations   1     388.0 129213 1695.9\n+ SMIC           1       4.3 129597 1696.7\n\nStep:  AIC=1673.48\nIPA ~ exportations\n\n                Df Sum of Sq    RSS    AIC\n+ CDD            1    4509.8 114577 1664.9\n+ precipitation  1    4286.2 114801 1665.4\n+ petrole        1    3708.8 115378 1666.8\n<none>                       119087 1673.5\n+ temperature    1     526.8 118560 1674.3\n+ taux_change    1     294.5 118792 1674.8\n+ importations   1     277.5 118809 1674.8\n+ SMIC           1      36.9 119050 1675.4\n\nStep:  AIC=1664.86\nIPA ~ exportations + CDD\n\n                Df Sum of Sq    RSS    AIC\n+ petrole        1    3654.2 110923 1658.0\n+ precipitation  1    1121.9 113455 1664.2\n<none>                       114577 1664.9\n+ taux_change    1     394.5 114182 1665.9\n+ importations   1     341.6 114235 1666.0\n+ SMIC           1      13.6 114563 1666.8\n+ temperature    1       0.1 114577 1666.9\n\nStep:  AIC=1657.95\nIPA ~ exportations + CDD + petrole\n\n                Df Sum of Sq    RSS    AIC\n+ taux_change    1   1630.73 109292 1655.9\n+ precipitation  1   1545.06 109378 1656.1\n<none>                       110923 1658.0\n+ importations   1    220.08 110703 1659.4\n+ temperature    1     33.87 110889 1659.9\n+ SMIC           1     27.01 110896 1659.9\n\nStep:  AIC=1655.88\nIPA ~ exportations + CDD + petrole + taux_change\n\n                Df Sum of Sq    RSS    AIC\n+ precipitation  1   1608.85 107683 1653.8\n<none>                       109292 1655.9\n+ importations   1    239.66 109052 1657.3\n+ temperature    1     26.53 109265 1657.8\n+ SMIC           1      0.14 109292 1657.9\n\nStep:  AIC=1653.8\nIPA ~ exportations + CDD + petrole + taux_change + precipitation\n\n               Df Sum of Sq    RSS    AIC\n<none>                      107683 1653.8\n+ importations  1   150.885 107532 1655.4\n+ temperature   1    77.809 107605 1655.6\n+ SMIC          1     3.351 107680 1655.8\n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode descendante\nstep2 <- step(modele1,data=stationnaire_data,direction=\"backward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=1659.26\nIPA ~ CDD + importations + exportations + petrole + taux_change + \n    SMIC + precipitation + temperature\n\n                Df Sum of Sq    RSS    AIC\n- SMIC           1       3.4 107474 1657.3\n- temperature    1      58.9 107530 1657.4\n- importations   1     130.1 107601 1657.6\n<none>                       107471 1659.3\n- CDD            1    1240.9 108712 1660.4\n- precipitation  1    1542.9 109014 1661.2\n- taux_change    1    1680.4 109151 1661.5\n- petrole        1    5179.2 112650 1670.2\n- exportations   1    7852.3 115323 1676.7\n\nStep:  AIC=1657.26\nIPA ~ CDD + importations + exportations + petrole + taux_change + \n    precipitation + temperature\n\n                Df Sum of Sq    RSS    AIC\n- temperature    1      58.0 107532 1655.4\n- importations   1     131.1 107605 1655.6\n<none>                       107474 1657.3\n- CDD            1    1240.1 108714 1658.4\n- precipitation  1    1539.4 109014 1659.2\n- taux_change    1    1722.5 109197 1659.6\n- petrole        1    5182.5 112657 1668.2\n- exportations   1    7890.1 115364 1674.8\n\nStep:  AIC=1655.41\nIPA ~ CDD + importations + exportations + petrole + taux_change + \n    precipitation\n\n                Df Sum of Sq    RSS    AIC\n- importations   1     150.9 107683 1653.8\n<none>                       107532 1655.4\n- CDD            1    1194.3 108727 1656.5\n- precipitation  1    1520.1 109052 1657.3\n- taux_change    1    1708.8 109241 1657.8\n- petrole        1    5262.3 112795 1666.5\n- exportations   1    8068.0 115600 1673.3\n\nStep:  AIC=1653.8\nIPA ~ CDD + exportations + petrole + taux_change + precipitation\n\n                Df Sum of Sq    RSS    AIC\n<none>                       107683 1653.8\n- CDD            1    1142.0 108825 1654.7\n- precipitation  1    1608.9 109292 1655.9\n- taux_change    1    1694.5 109378 1656.1\n- petrole        1    5390.6 113074 1665.2\n- exportations   1    8176.7 115860 1671.9\n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode double\n#méthode dans les 2 sens\nstep3 <- step(modele0,scope=list(upper=modele1),data=stationnaire_data,direction=\"both\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=1694.75\nIPA ~ 1\n\n                Df Sum of Sq    RSS    AIC\n+ exportations   1   10514.2 119087 1673.5\n+ CDD            1    7482.6 122118 1680.4\n+ precipitation  1    5178.7 124422 1685.5\n+ petrole        1    3258.2 126343 1689.8\n+ temperature    1    2522.9 127078 1691.3\n<none>                       129601 1694.8\n+ taux_change    1     396.9 129204 1695.9\n+ importations   1     388.0 129213 1695.9\n+ SMIC           1       4.3 129597 1696.7\n\nStep:  AIC=1673.48\nIPA ~ exportations\n\n                Df Sum of Sq    RSS    AIC\n+ CDD            1    4509.8 114577 1664.9\n+ precipitation  1    4286.2 114801 1665.4\n+ petrole        1    3708.8 115378 1666.8\n<none>                       119087 1673.5\n+ temperature    1     526.8 118560 1674.3\n+ taux_change    1     294.5 118792 1674.8\n+ importations   1     277.5 118809 1674.8\n+ SMIC           1      36.9 119050 1675.4\n- exportations   1   10514.2 129601 1694.8\n\nStep:  AIC=1664.86\nIPA ~ exportations + CDD\n\n                Df Sum of Sq    RSS    AIC\n+ petrole        1    3654.2 110923 1658.0\n+ precipitation  1    1121.9 113455 1664.2\n<none>                       114577 1664.9\n+ taux_change    1     394.5 114182 1665.9\n+ importations   1     341.6 114235 1666.0\n+ SMIC           1      13.6 114563 1666.8\n+ temperature    1       0.1 114577 1666.9\n- CDD            1    4509.8 119087 1673.5\n- exportations   1    7541.5 122118 1680.4\n\nStep:  AIC=1657.95\nIPA ~ exportations + CDD + petrole\n\n                Df Sum of Sq    RSS    AIC\n+ taux_change    1    1630.7 109292 1655.9\n+ precipitation  1    1545.1 109378 1656.1\n<none>                       110923 1658.0\n+ importations   1     220.1 110703 1659.4\n+ temperature    1      33.9 110889 1659.9\n+ SMIC           1      27.0 110896 1659.9\n- petrole        1    3654.2 114577 1664.9\n- CDD            1    4455.3 115378 1666.8\n- exportations   1    7928.8 118852 1674.9\n\nStep:  AIC=1655.88\nIPA ~ exportations + CDD + petrole + taux_change\n\n                Df Sum of Sq    RSS    AIC\n+ precipitation  1    1608.9 107683 1653.8\n<none>                       109292 1655.9\n+ importations   1     239.7 109052 1657.3\n+ temperature    1      26.5 109265 1657.8\n+ SMIC           1       0.1 109292 1657.9\n- taux_change    1    1630.7 110923 1658.0\n- CDD            1    4665.5 113958 1665.4\n- petrole        1    4890.5 114182 1665.9\n- exportations   1    7751.2 117043 1672.7\n\nStep:  AIC=1653.8\nIPA ~ exportations + CDD + petrole + taux_change + precipitation\n\n                Df Sum of Sq    RSS    AIC\n<none>                       107683 1653.8\n- CDD            1    1142.0 108825 1654.7\n+ importations   1     150.9 107532 1655.4\n+ temperature    1      77.8 107605 1655.6\n+ SMIC           1       3.4 107680 1655.8\n- precipitation  1    1608.9 109292 1655.9\n- taux_change    1    1694.5 109378 1656.1\n- petrole        1    5390.6 113074 1665.2\n- exportations   1    8176.7 115860 1671.9\n```\n\n\n:::\n:::\n\n\n\n# MODELES\n\nAprès les méthodes de sélections les variables IPA \\~ exportations + CDD + petrole + taux_change + precipitation\n\n## 1. Modèle\n\n1 retenue\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_model1 <- lm(IPA ~ exportations + CDD + petrole + taux_change + precipitation, data=stationnaire_data)\n\nsummary(lm_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ exportations + CDD + petrole + taux_change + \n    precipitation, data = stationnaire_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-62.049  -9.874  -1.524   7.272 114.365 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    2.78407   18.61192   0.150 0.881204    \nexportations   0.22733    0.05030   4.520 9.29e-06 ***\nCDD            1.57990    0.93540   1.689 0.092376 .  \npetrole        0.77049    0.20997   3.670 0.000293 ***\ntaux_change   20.96618   10.19045   2.057 0.040608 *  \nprecipitation -0.16106    0.08034  -2.005 0.045992 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.01 on 269 degrees of freedom\nMultiple R-squared:  0.1691,\tAdjusted R-squared:  0.1537 \nF-statistic: 10.95 on 5 and 269 DF,  p-value: 1.316e-09\n```\n\n\n:::\n:::\n\n\n\n### Hypothèses\n\nTest de normalité des résidus\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Résidus\n# Test de normalité des résidus\nresidus <- residuals(lm_model1)\n# Test de normalité des résidus\nks.test(residus, \"pnorm\", mean = mean(residus), sd = sd(residus))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residus\nD = 0.11327, p-value = 0.001723\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n\np-value = 0.001723, Refus de l’hypothèse de normalité des résidus au seuil de risque de 5%\n\nTest d’homoscédasticité des résidus\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test de Breusch-Pagan pour l'hétéroscédasticité\nbptest(lm_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  lm_model1\nBP = 26.02, df = 5, p-value = 8.844e-05\n```\n\n\n:::\n:::\n\n\n\np-value = 8.844e-05, Refus de l’hypothèse d’homoscédacticité des résidus au seuil de risque de 5%\n\nForme fonctionnelle\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test RESET\nreset(lm_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  lm_model1\nRESET = 6.6669, df1 = 2, df2 = 267, p-value = 0.001495\n```\n\n\n:::\n:::\n\n\n\np-value = 0.001495; Forme fonctionnelle linéaire du modèle spécifié acceptée au seuil de 5%\n\nAnalyse des observations influençant l’estimation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distance de Cook pour identifier les points influents\nplot(cooks.distance(lm_model1), type = \"h\", main = \"Distance de Cook\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n\nmulticollinéarité\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(lm_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n exportations           CDD       petrole   taux_change precipitation \n     1.048992      1.531173      1.115762      1.107182      1.482521 \n```\n\n\n:::\n:::\n\n\n\nAutocorrelation de résidus\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheckresiduals(lm_model1)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBreusch-Godfrey test for serial correlation of order up to 10\n\ndata:  Residuals\nLM test = 109.93, df = 10, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\np-value \\< 2.2e-16. il existe des preuves significatives d’auto-corrélation résiduelle dans les données.\n\n## 2. Modèle 2: différencié - logarithmique\n\nDans ce model nous appliquons le logarithme avant la différenciation p\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_l_IPA <- diff(log(data_adj$IPA), differences = 1)\nplot(ts(d_l_IPA))\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n\n```{.r .cell-code}\nadf.test(d_l_IPA) # on verifie stationnarité \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in adf.test(d_l_IPA): p-value smaller than printed p-value\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  d_l_IPA\nDickey-Fuller = -5.2389, Lag order = 6, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\n# creation df avec la dif du log de ipa\nst2_data <- data.frame(\n  Date = data_adj$Date[-1],\n  IPA = d_l_IPA,  \n  CDD = CDD_deseason[-1],  \n  importations = importation_diff,\n  exportations = exportations_deseason[-1],\n  petrole = petrole_diff, \n  taux_change = taux_change_diff,  \n  SMIC = ts_SMIC[-1],\n  precipitation = precipitations_deseason[-1],\n  temperature = temperature_deseason[-1]\n)\n\n# estimation modele avec ipa differencié et log\nmodele1_2 <- lm(IPA ~ CDD +  importations + exportations +  petrole +  taux_change + SMIC + precipitation + temperature, data=st2_data)\nsummary(modele1_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ CDD + importations + exportations + petrole + \n    taux_change + SMIC + precipitation + temperature, data = st2_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.053209 -0.013832 -0.001854  0.010430  0.074676 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    4.582e-02  2.275e-02   2.014 0.045005 *  \nCDD            7.037e-05  1.020e-03   0.069 0.945062    \nimportations   5.464e-05  8.959e-05   0.610 0.542481    \nexportations   1.068e-04  5.603e-05   1.907 0.057611 .  \npetrole        8.162e-04  2.266e-04   3.602 0.000376 ***\ntaux_change    4.257e-02  1.104e-02   3.856 0.000144 ***\nSMIC          -3.741e-05  5.717e-05  -0.654 0.513451    \nprecipitation -2.346e-04  9.237e-05  -2.540 0.011646 *  \ntemperature   -3.939e-03  3.654e-03  -1.078 0.281995    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02151 on 266 degrees of freedom\nMultiple R-squared:  0.1119,\tAdjusted R-squared:  0.08523 \nF-statistic: 4.191 on 8 and 266 DF,  p-value: 9.593e-05\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step : Sélection des variables explicatives significatives (modèle linéaire = modele1 )\n\nmodele0_2 <- (lm(IPA~1,data=st2_data))\nsummary(modele0_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ 1, data = st2_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.060967 -0.014968 -0.002519  0.011062  0.082152 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.008686   0.001356   6.403 6.58e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02249 on 274 degrees of freedom\n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode ascendante\nstep(modele0_2, scope=list(lower=modele0_2, upper=modele1_2), data=st2_data, direction=\"forward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-2085.99\nIPA ~ 1\n\n                Df Sum of Sq     RSS     AIC\n+ taux_change    1 0.0035569 0.13508 -2091.1\n+ precipitation  1 0.0032765 0.13536 -2090.6\n+ petrole        1 0.0027049 0.13593 -2089.4\n+ exportations   1 0.0016087 0.13703 -2087.2\n+ CDD            1 0.0015048 0.13713 -2087.0\n<none>                       0.13864 -2086.0\n+ importations   1 0.0004699 0.13817 -2084.9\n+ temperature    1 0.0001474 0.13849 -2084.3\n+ SMIC           1 0.0001195 0.13852 -2084.2\n\nStep:  AIC=-2091.13\nIPA ~ taux_change\n\n                Df Sum of Sq     RSS     AIC\n+ petrole        1 0.0054703 0.12961 -2100.5\n+ precipitation  1 0.0033626 0.13172 -2096.1\n+ CDD            1 0.0016667 0.13341 -2092.6\n+ exportations   1 0.0014833 0.13359 -2092.2\n<none>                       0.13508 -2091.1\n+ importations   1 0.0005565 0.13452 -2090.3\n+ SMIC           1 0.0003469 0.13473 -2089.8\n+ temperature    1 0.0000998 0.13498 -2089.3\n\nStep:  AIC=-2100.5\nIPA ~ taux_change + petrole\n\n                Df Sum of Sq     RSS     AIC\n+ precipitation  1 0.0041454 0.12546 -2107.4\n+ CDD            1 0.0017392 0.12787 -2102.2\n+ exportations   1 0.0016606 0.12795 -2102.1\n<none>                       0.12961 -2100.5\n+ importations   1 0.0003904 0.12922 -2099.3\n+ SMIC           1 0.0003829 0.12923 -2099.3\n+ temperature    1 0.0002855 0.12932 -2099.1\n\nStep:  AIC=-2107.44\nIPA ~ taux_change + petrole + precipitation\n\n               Df  Sum of Sq     RSS     AIC\n+ exportations  1 0.00135287 0.12411 -2108.4\n<none>                       0.12546 -2107.4\n+ importations  1 0.00026866 0.12519 -2106.0\n+ temperature   1 0.00019464 0.12527 -2105.9\n+ SMIC          1 0.00016345 0.12530 -2105.8\n+ CDD           1 0.00004282 0.12542 -2105.5\n\nStep:  AIC=-2108.42\nIPA ~ taux_change + petrole + precipitation + exportations\n\n               Df  Sum of Sq     RSS     AIC\n<none>                       0.12411 -2108.4\n+ temperature   1 0.00062530 0.12348 -2107.8\n+ importations  1 0.00023504 0.12387 -2106.9\n+ SMIC          1 0.00020702 0.12390 -2106.9\n+ CDD           1 0.00000092 0.12411 -2106.4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ taux_change + petrole + precipitation + exportations, \n    data = st2_data)\n\nCoefficients:\n  (Intercept)    taux_change        petrole  precipitation   exportations  \n    3.342e-02      4.133e-02      8.381e-04     -2.054e-04      9.054e-05  \n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode descendante\nstep(modele1_2,data=st2_data,direction=\"backward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-2102.63\nIPA ~ CDD + importations + exportations + petrole + taux_change + \n    SMIC + precipitation + temperature\n\n                Df Sum of Sq     RSS     AIC\n- CDD            1 0.0000022 0.12312 -2104.6\n- importations   1 0.0001721 0.12329 -2104.2\n- SMIC           1 0.0001982 0.12331 -2104.2\n- temperature    1 0.0005379 0.12366 -2103.4\n<none>                       0.12312 -2102.6\n- exportations   1 0.0016830 0.12480 -2100.9\n- precipitation  1 0.0029868 0.12610 -2098.0\n- petrole        1 0.0060068 0.12912 -2091.5\n- taux_change    1 0.0068828 0.13000 -2089.7\n\nStep:  AIC=-2104.63\nIPA ~ importations + exportations + petrole + taux_change + SMIC + \n    precipitation + temperature\n\n                Df Sum of Sq     RSS     AIC\n- importations   1 0.0001705 0.12329 -2106.2\n- SMIC           1 0.0002043 0.12332 -2106.2\n- temperature    1 0.0005374 0.12366 -2105.4\n<none>                       0.12312 -2104.6\n- exportations   1 0.0017558 0.12487 -2102.7\n- precipitation  1 0.0039845 0.12710 -2097.9\n- petrole        1 0.0060420 0.12916 -2093.4\n- taux_change    1 0.0068808 0.13000 -2091.7\n\nStep:  AIC=-2106.25\nIPA ~ exportations + petrole + taux_change + SMIC + precipitation + \n    temperature\n\n                Df Sum of Sq     RSS     AIC\n- SMIC           1 0.0001947 0.12348 -2107.8\n- temperature    1 0.0006130 0.12390 -2106.9\n<none>                       0.12329 -2106.2\n- exportations   1 0.0018247 0.12512 -2104.2\n- precipitation  1 0.0041861 0.12748 -2099.1\n- petrole        1 0.0061623 0.12945 -2094.8\n- taux_change    1 0.0068525 0.13014 -2093.4\n\nStep:  AIC=-2107.81\nIPA ~ exportations + petrole + taux_change + precipitation + \n    temperature\n\n                Df Sum of Sq     RSS     AIC\n- temperature    1 0.0006253 0.12411 -2108.4\n<none>                       0.12348 -2107.8\n- exportations   1 0.0017835 0.12527 -2105.9\n- precipitation  1 0.0044267 0.12791 -2100.1\n- petrole        1 0.0061497 0.12963 -2096.4\n- taux_change    1 0.0066743 0.13016 -2095.3\n\nStep:  AIC=-2108.42\nIPA ~ exportations + petrole + taux_change + precipitation\n\n                Df Sum of Sq     RSS     AIC\n<none>                       0.12411 -2108.4\n- exportations   1 0.0013529 0.12546 -2107.4\n- precipitation  1 0.0038376 0.12795 -2102.1\n- petrole        1 0.0063937 0.13050 -2096.6\n- taux_change    1 0.0065890 0.13070 -2096.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ exportations + petrole + taux_change + precipitation, \n    data = st2_data)\n\nCoefficients:\n  (Intercept)   exportations        petrole    taux_change  precipitation  \n    3.342e-02      9.054e-05      8.381e-04      4.133e-02     -2.054e-04  \n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode double\n#méthode dans les 2 sens\nstep(modele0_2,scope=list(upper=modele1_2),data=st2_data,direction=\"both\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-2085.99\nIPA ~ 1\n\n                Df Sum of Sq     RSS     AIC\n+ taux_change    1 0.0035569 0.13508 -2091.1\n+ precipitation  1 0.0032765 0.13536 -2090.6\n+ petrole        1 0.0027049 0.13593 -2089.4\n+ exportations   1 0.0016087 0.13703 -2087.2\n+ CDD            1 0.0015048 0.13713 -2087.0\n<none>                       0.13864 -2086.0\n+ importations   1 0.0004699 0.13817 -2084.9\n+ temperature    1 0.0001474 0.13849 -2084.3\n+ SMIC           1 0.0001195 0.13852 -2084.2\n\nStep:  AIC=-2091.13\nIPA ~ taux_change\n\n                Df Sum of Sq     RSS     AIC\n+ petrole        1 0.0054703 0.12961 -2100.5\n+ precipitation  1 0.0033626 0.13172 -2096.1\n+ CDD            1 0.0016667 0.13341 -2092.6\n+ exportations   1 0.0014833 0.13359 -2092.2\n<none>                       0.13508 -2091.1\n+ importations   1 0.0005565 0.13452 -2090.3\n+ SMIC           1 0.0003469 0.13473 -2089.8\n+ temperature    1 0.0000998 0.13498 -2089.3\n- taux_change    1 0.0035569 0.13864 -2086.0\n\nStep:  AIC=-2100.5\nIPA ~ taux_change + petrole\n\n                Df Sum of Sq     RSS     AIC\n+ precipitation  1 0.0041454 0.12546 -2107.4\n+ CDD            1 0.0017392 0.12787 -2102.2\n+ exportations   1 0.0016606 0.12795 -2102.1\n<none>                       0.12961 -2100.5\n+ importations   1 0.0003904 0.12922 -2099.3\n+ SMIC           1 0.0003829 0.12923 -2099.3\n+ temperature    1 0.0002855 0.12932 -2099.1\n- petrole        1 0.0054703 0.13508 -2091.1\n- taux_change    1 0.0063223 0.13593 -2089.4\n\nStep:  AIC=-2107.44\nIPA ~ taux_change + petrole + precipitation\n\n                Df Sum of Sq     RSS     AIC\n+ exportations   1 0.0013529 0.12411 -2108.4\n<none>                       0.12546 -2107.4\n+ importations   1 0.0002687 0.12519 -2106.0\n+ temperature    1 0.0001946 0.12527 -2105.9\n+ SMIC           1 0.0001635 0.12530 -2105.8\n+ CDD            1 0.0000428 0.12542 -2105.5\n- precipitation  1 0.0041454 0.12961 -2100.5\n- petrole        1 0.0062530 0.13172 -2096.1\n- taux_change    1 0.0067044 0.13217 -2095.1\n\nStep:  AIC=-2108.42\nIPA ~ taux_change + petrole + precipitation + exportations\n\n                Df Sum of Sq     RSS     AIC\n<none>                       0.12411 -2108.4\n+ temperature    1 0.0006253 0.12348 -2107.8\n- exportations   1 0.0013529 0.12546 -2107.4\n+ importations   1 0.0002350 0.12387 -2106.9\n+ SMIC           1 0.0002070 0.12390 -2106.9\n+ CDD            1 0.0000009 0.12411 -2106.4\n- precipitation  1 0.0038376 0.12795 -2102.1\n- petrole        1 0.0063937 0.13050 -2096.6\n- taux_change    1 0.0065890 0.13070 -2096.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ taux_change + petrole + precipitation + exportations, \n    data = st2_data)\n\nCoefficients:\n  (Intercept)    taux_change        petrole  precipitation   exportations  \n    3.342e-02      4.133e-02      8.381e-04     -2.054e-04      9.054e-05  \n```\n\n\n:::\n\n```{.r .cell-code}\n# MODELO 3 RETENUE\nlm_model2 <- lm(IPA ~ taux_change + petrole + precipitation + exportations, \n    data = st2_data)\nsummary(lm_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ taux_change + petrole + precipitation + exportations, \n    data = st2_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.053072 -0.013313 -0.002177  0.009744  0.072178 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    3.342e-02  1.095e-02   3.053 0.002494 ** \ntaux_change    4.133e-02  1.092e-02   3.786 0.000189 ***\npetrole        8.381e-04  2.247e-04   3.730 0.000234 ***\nprecipitation -2.054e-04  7.110e-05  -2.889 0.004173 ** \nexportations   9.054e-05  5.277e-05   1.716 0.087389 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02144 on 270 degrees of freedom\nMultiple R-squared:  0.1048,\tAdjusted R-squared:  0.09151 \nF-statistic:   7.9 on 4 and 270 DF,  p-value: 4.911e-06\n```\n\n\n:::\n\n```{.r .cell-code}\n## TESTS \nresidus2 <- residuals(lm_model2)\n# Test de normalité des résidus\nks.test(residus2, \"pnorm\", mean = mean(residus2), sd = sd(residus2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residus2\nD = 0.075036, p-value = 0.09039\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(lm_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  lm_model2\nBP = 3.7142, df = 4, p-value = 0.4461\n```\n\n\n:::\n\n```{.r .cell-code}\nreset(lm_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  lm_model2\nRESET = 0.21788, df1 = 2, df2 = 268, p-value = 0.8044\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(lm_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  taux_change       petrole precipitation  exportations \n     1.106656      1.113121      1.011154      1.005594 \n```\n\n\n:::\n\n```{.r .cell-code}\ncheckresiduals(lm_model2)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-48-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBreusch-Godfrey test for serial correlation of order up to 10\n\ndata:  Residuals\nLM test = 85.459, df = 10, p-value = 4.237e-14\n```\n\n\n:::\n:::\n\n\n\nLe modèle 3 inclut une variable de temps pour capturer la tendance déterministe. Cela permet de modéliser explicitement les effets de la tendance dans les données et peut aider à réduire l'autocorrélation dans les résidus.\n\n## 3. Modèle 3 index temporel\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ajout d'un index temporel\nst3_data <- st2_data\nst3_data$time <- 1:nrow(st3_data)\n\n# Modèle de régression avec la variable de temps\nmodele1_3 <- lm(IPA ~ CDD +  importations + exportations +  petrole +  taux_change + SMIC + precipitation + temperature+ time, data = st3_data)\nsummary(modele1_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ CDD + importations + exportations + petrole + \n    taux_change + SMIC + precipitation + temperature + time, \n    data = st3_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.051688 -0.013833 -0.002295  0.010354  0.074510 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    3.707e-02  2.287e-02   1.621 0.106247    \nCDD            3.555e-04  1.019e-03   0.349 0.727494    \nimportations   4.968e-05  8.887e-05   0.559 0.576620    \nexportations   2.756e-04  9.090e-05   3.032 0.002672 ** \npetrole        8.462e-04  2.250e-04   3.760 0.000209 ***\ntaux_change    4.474e-02  1.099e-02   4.073 6.14e-05 ***\nSMIC          -4.162e-05  5.672e-05  -0.734 0.463764    \nprecipitation -2.047e-04  9.248e-05  -2.214 0.027695 *  \ntemperature   -9.079e-04  3.847e-03  -0.236 0.813582    \ntime          -7.058e-05  3.009e-05  -2.346 0.019739 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02133 on 265 degrees of freedom\nMultiple R-squared:   0.13,\tAdjusted R-squared:  0.1004 \nF-statistic:   4.4 on 9 and 265 DF,  p-value: 2.248e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nmodele0_3 <- (lm((IPA)~1,data=st3_data))\nsummary(modele0_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = (IPA) ~ 1, data = st3_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.060967 -0.014968 -0.002519  0.011062  0.082152 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.008686   0.001356   6.403 6.58e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02249 on 274 degrees of freedom\n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode ascendante\nstep(modele0_3, scope=list(lower=modele0_3, upper=modele1_3), data=st3_data, direction=\"forward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-2085.99\n(IPA) ~ 1\n\n                Df Sum of Sq     RSS     AIC\n+ taux_change    1 0.0035569 0.13508 -2091.1\n+ precipitation  1 0.0032765 0.13536 -2090.6\n+ petrole        1 0.0027049 0.13593 -2089.4\n+ exportations   1 0.0016087 0.13703 -2087.2\n+ CDD            1 0.0015048 0.13713 -2087.0\n<none>                       0.13864 -2086.0\n+ importations   1 0.0004699 0.13817 -2084.9\n+ temperature    1 0.0001474 0.13849 -2084.3\n+ SMIC           1 0.0001195 0.13852 -2084.2\n+ time           1 0.0000569 0.13858 -2084.1\n\nStep:  AIC=-2091.13\n(IPA) ~ taux_change\n\n                Df Sum of Sq     RSS     AIC\n+ petrole        1 0.0054703 0.12961 -2100.5\n+ precipitation  1 0.0033626 0.13172 -2096.1\n+ CDD            1 0.0016667 0.13341 -2092.6\n+ exportations   1 0.0014833 0.13359 -2092.2\n<none>                       0.13508 -2091.1\n+ importations   1 0.0005565 0.13452 -2090.3\n+ SMIC           1 0.0003469 0.13473 -2089.8\n+ temperature    1 0.0000998 0.13498 -2089.3\n+ time           1 0.0000143 0.13506 -2089.2\n\nStep:  AIC=-2100.5\n(IPA) ~ taux_change + petrole\n\n                Df Sum of Sq     RSS     AIC\n+ precipitation  1 0.0041454 0.12546 -2107.4\n+ CDD            1 0.0017392 0.12787 -2102.2\n+ exportations   1 0.0016606 0.12795 -2102.1\n<none>                       0.12961 -2100.5\n+ importations   1 0.0003904 0.12922 -2099.3\n+ SMIC           1 0.0003829 0.12923 -2099.3\n+ temperature    1 0.0002855 0.12932 -2099.1\n+ time           1 0.0000179 0.12959 -2098.5\n\nStep:  AIC=-2107.44\n(IPA) ~ taux_change + petrole + precipitation\n\n               Df  Sum of Sq     RSS     AIC\n+ exportations  1 0.00135287 0.12411 -2108.4\n<none>                       0.12546 -2107.4\n+ importations  1 0.00026866 0.12519 -2106.0\n+ temperature   1 0.00019464 0.12527 -2105.9\n+ SMIC          1 0.00016345 0.12530 -2105.8\n+ CDD           1 0.00004282 0.12542 -2105.5\n+ time          1 0.00000487 0.12546 -2105.4\n\nStep:  AIC=-2108.42\n(IPA) ~ taux_change + petrole + precipitation + exportations\n\n               Df  Sum of Sq     RSS     AIC\n+ time          1 0.00300963 0.12110 -2113.2\n<none>                       0.12411 -2108.4\n+ temperature   1 0.00062530 0.12348 -2107.8\n+ importations  1 0.00023504 0.12387 -2106.9\n+ SMIC          1 0.00020702 0.12390 -2106.9\n+ CDD           1 0.00000092 0.12411 -2106.4\n\nStep:  AIC=-2113.17\n(IPA) ~ taux_change + petrole + precipitation + exportations + \n    time\n\n               Df  Sum of Sq     RSS     AIC\n<none>                       0.12110 -2113.2\n+ SMIC          1 2.6657e-04 0.12083 -2111.8\n+ importations  1 1.3613e-04 0.12096 -2111.5\n+ CDD           1 6.2070e-05 0.12104 -2111.3\n+ temperature   1 3.7371e-05 0.12106 -2111.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = (IPA) ~ taux_change + petrole + precipitation + \n    exportations + time, data = st3_data)\n\nCoefficients:\n  (Intercept)    taux_change        petrole  precipitation   exportations  \n    3.606e-02      4.359e-02      8.601e-04     -2.207e-04      2.781e-04  \n         time  \n   -7.182e-05  \n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode descendante\nstep(modele1_3,data=st3_data,direction=\"backward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-2106.28\nIPA ~ CDD + importations + exportations + petrole + taux_change + \n    SMIC + precipitation + temperature + time\n\n                Df Sum of Sq     RSS     AIC\n- temperature    1 0.0000254 0.12064 -2108.2\n- CDD            1 0.0000554 0.12067 -2108.2\n- importations   1 0.0001422 0.12076 -2108.0\n- SMIC           1 0.0002450 0.12086 -2107.7\n<none>                       0.12061 -2106.3\n- precipitation  1 0.0022306 0.12284 -2103.2\n- time           1 0.0025039 0.12312 -2102.6\n- exportations   1 0.0041834 0.12480 -2098.9\n- petrole        1 0.0064351 0.12705 -2094.0\n- taux_change    1 0.0075490 0.12816 -2091.6\n\nStep:  AIC=-2108.22\nIPA ~ CDD + importations + exportations + petrole + taux_change + \n    SMIC + precipitation + time\n\n                Df Sum of Sq     RSS     AIC\n- CDD            1 0.0000503 0.12069 -2110.1\n- importations   1 0.0001542 0.12079 -2109.9\n- SMIC           1 0.0002519 0.12089 -2109.7\n<none>                       0.12064 -2108.2\n- precipitation  1 0.0023802 0.12302 -2104.8\n- time           1 0.0030165 0.12366 -2103.4\n- exportations   1 0.0043266 0.12497 -2100.5\n- petrole        1 0.0065290 0.12717 -2095.7\n- taux_change    1 0.0075587 0.12820 -2093.5\n\nStep:  AIC=-2110.11\nIPA ~ importations + exportations + petrole + taux_change + SMIC + \n    precipitation + time\n\n                Df Sum of Sq     RSS     AIC\n- importations   1 0.0001447 0.12083 -2111.8\n- SMIC           1 0.0002752 0.12096 -2111.5\n<none>                       0.12069 -2110.1\n- time           1 0.0029679 0.12366 -2105.4\n- precipitation  1 0.0040219 0.12471 -2103.1\n- exportations   1 0.0043276 0.12502 -2102.4\n- petrole        1 0.0065981 0.12729 -2097.5\n- taux_change    1 0.0075334 0.12822 -2095.5\n\nStep:  AIC=-2111.78\nIPA ~ exportations + petrole + taux_change + SMIC + precipitation + \n    time\n\n                Df Sum of Sq     RSS     AIC\n- SMIC           1 0.0002666 0.12110 -2113.2\n<none>                       0.12083 -2111.8\n- time           1 0.0030692 0.12390 -2106.9\n- precipitation  1 0.0041255 0.12496 -2104.6\n- exportations   1 0.0044615 0.12529 -2103.8\n- petrole        1 0.0067392 0.12757 -2098.9\n- taux_change    1 0.0075131 0.12835 -2097.2\n\nStep:  AIC=-2113.17\nIPA ~ exportations + petrole + taux_change + precipitation + \n    time\n\n                Df Sum of Sq     RSS     AIC\n<none>                       0.12110 -2113.2\n- time           1 0.0030096 0.12411 -2108.4\n- exportations   1 0.0043576 0.12546 -2105.4\n- precipitation  1 0.0043997 0.12550 -2105.4\n- petrole        1 0.0067228 0.12782 -2100.3\n- taux_change    1 0.0072794 0.12838 -2099.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ exportations + petrole + taux_change + precipitation + \n    time, data = st3_data)\n\nCoefficients:\n  (Intercept)   exportations        petrole    taux_change  precipitation  \n    3.606e-02      2.781e-04      8.601e-04      4.359e-02     -2.207e-04  \n         time  \n   -7.182e-05  \n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode double\n#méthode dans les 2 sens\nstep(modele0_3,scope=list(upper=modele1_3),data=st3_data,direction=\"both\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-2085.99\n(IPA) ~ 1\n\n                Df Sum of Sq     RSS     AIC\n+ taux_change    1 0.0035569 0.13508 -2091.1\n+ precipitation  1 0.0032765 0.13536 -2090.6\n+ petrole        1 0.0027049 0.13593 -2089.4\n+ exportations   1 0.0016087 0.13703 -2087.2\n+ CDD            1 0.0015048 0.13713 -2087.0\n<none>                       0.13864 -2086.0\n+ importations   1 0.0004699 0.13817 -2084.9\n+ temperature    1 0.0001474 0.13849 -2084.3\n+ SMIC           1 0.0001195 0.13852 -2084.2\n+ time           1 0.0000569 0.13858 -2084.1\n\nStep:  AIC=-2091.13\n(IPA) ~ taux_change\n\n                Df Sum of Sq     RSS     AIC\n+ petrole        1 0.0054703 0.12961 -2100.5\n+ precipitation  1 0.0033626 0.13172 -2096.1\n+ CDD            1 0.0016667 0.13341 -2092.6\n+ exportations   1 0.0014833 0.13359 -2092.2\n<none>                       0.13508 -2091.1\n+ importations   1 0.0005565 0.13452 -2090.3\n+ SMIC           1 0.0003469 0.13473 -2089.8\n+ temperature    1 0.0000998 0.13498 -2089.3\n+ time           1 0.0000143 0.13506 -2089.2\n- taux_change    1 0.0035569 0.13864 -2086.0\n\nStep:  AIC=-2100.5\n(IPA) ~ taux_change + petrole\n\n                Df Sum of Sq     RSS     AIC\n+ precipitation  1 0.0041454 0.12546 -2107.4\n+ CDD            1 0.0017392 0.12787 -2102.2\n+ exportations   1 0.0016606 0.12795 -2102.1\n<none>                       0.12961 -2100.5\n+ importations   1 0.0003904 0.12922 -2099.3\n+ SMIC           1 0.0003829 0.12923 -2099.3\n+ temperature    1 0.0002855 0.12932 -2099.1\n+ time           1 0.0000179 0.12959 -2098.5\n- petrole        1 0.0054703 0.13508 -2091.1\n- taux_change    1 0.0063223 0.13593 -2089.4\n\nStep:  AIC=-2107.44\n(IPA) ~ taux_change + petrole + precipitation\n\n                Df Sum of Sq     RSS     AIC\n+ exportations   1 0.0013529 0.12411 -2108.4\n<none>                       0.12546 -2107.4\n+ importations   1 0.0002687 0.12519 -2106.0\n+ temperature    1 0.0001946 0.12527 -2105.9\n+ SMIC           1 0.0001635 0.12530 -2105.8\n+ CDD            1 0.0000428 0.12542 -2105.5\n+ time           1 0.0000049 0.12546 -2105.4\n- precipitation  1 0.0041454 0.12961 -2100.5\n- petrole        1 0.0062530 0.13172 -2096.1\n- taux_change    1 0.0067044 0.13217 -2095.1\n\nStep:  AIC=-2108.42\n(IPA) ~ taux_change + petrole + precipitation + exportations\n\n                Df Sum of Sq     RSS     AIC\n+ time           1 0.0030096 0.12110 -2113.2\n<none>                       0.12411 -2108.4\n+ temperature    1 0.0006253 0.12348 -2107.8\n- exportations   1 0.0013529 0.12546 -2107.4\n+ importations   1 0.0002350 0.12387 -2106.9\n+ SMIC           1 0.0002070 0.12390 -2106.9\n+ CDD            1 0.0000009 0.12411 -2106.4\n- precipitation  1 0.0038376 0.12795 -2102.1\n- petrole        1 0.0063937 0.13050 -2096.6\n- taux_change    1 0.0065890 0.13070 -2096.2\n\nStep:  AIC=-2113.17\n(IPA) ~ taux_change + petrole + precipitation + exportations + \n    time\n\n                Df Sum of Sq     RSS     AIC\n<none>                       0.12110 -2113.2\n+ SMIC           1 0.0002666 0.12083 -2111.8\n+ importations   1 0.0001361 0.12096 -2111.5\n+ CDD            1 0.0000621 0.12104 -2111.3\n+ temperature    1 0.0000374 0.12106 -2111.3\n- time           1 0.0030096 0.12411 -2108.4\n- exportations   1 0.0043576 0.12546 -2105.4\n- precipitation  1 0.0043997 0.12550 -2105.4\n- petrole        1 0.0067228 0.12782 -2100.3\n- taux_change    1 0.0072794 0.12838 -2099.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = (IPA) ~ taux_change + petrole + precipitation + \n    exportations + time, data = st3_data)\n\nCoefficients:\n  (Intercept)    taux_change        petrole  precipitation   exportations  \n    3.606e-02      4.359e-02      8.601e-04     -2.207e-04      2.781e-04  \n         time  \n   -7.182e-05  \n```\n\n\n:::\n\n```{.r .cell-code}\n# modele 3 \nlm_model3 <- lm(formula = (IPA) ~ taux_change + petrole + precipitation + \n    exportations + time, data = st3_data)\n\nsummary(lm_model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = (IPA) ~ taux_change + petrole + precipitation + \n    exportations + time, data = st3_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.052038 -0.013781 -0.002281  0.010896  0.074264 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    3.606e-02  1.088e-02   3.313  0.00105 ** \ntaux_change    4.359e-02  1.084e-02   4.021 7.53e-05 ***\npetrole        8.601e-04  2.226e-04   3.864  0.00014 ***\nprecipitation -2.207e-04  7.061e-05  -3.126  0.00197 ** \nexportations   2.781e-04  8.938e-05   3.111  0.00206 ** \ntime          -7.182e-05  2.778e-05  -2.586  0.01025 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02122 on 269 degrees of freedom\nMultiple R-squared:  0.1265,\tAdjusted R-squared:  0.1102 \nF-statistic:  7.79 on 5 and 269 DF,  p-value: 7.282e-07\n```\n\n\n:::\n\n```{.r .cell-code}\n## TESTS \nresidus3 <- residuals(lm_model3)\n# Test de normalité des résidus\nks.test(residus3, \"pnorm\", mean = mean(residus3), sd = sd(residus3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residus3\nD = 0.066946, p-value = 0.1699\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nreset(lm_model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  lm_model3\nRESET = 0.67732, df1 = 2, df2 = 267, p-value = 0.5088\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(lm_model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  lm_model3\nBP = 4.4605, df = 5, p-value = 0.4852\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(lm_model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  taux_change       petrole precipitation  exportations          time \n     1.113852      1.114739      1.018312      2.945289      2.970363 \n```\n\n\n:::\n\n```{.r .cell-code}\ncheckresiduals(lm_model3)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBreusch-Godfrey test for serial correlation of order up to 10\n\ndata:  Residuals\nLM test = 80.408, df = 10, p-value = 4.177e-13\n```\n\n\n:::\n:::\n\n\n\n## 4. Modèle 4 tendance déterministe corrigée\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fonction pour corriger la tendance déterministe par régression\ncorrect_trend <- function(series) {\n  model <- lm(series ~ time(series))\n  residuals(model)\n}\n# Appliquer la correction à chaque variable explicative\nfor (var in variables) {\n  # Corriger la tendance déterministe\n  corrected_series <- correct_trend(stationnaire_data[[var]])\n  # Ajouter les séries corrigées au data frame\n  stationnaire_data[[paste(var, \"detrended\", sep = \"_\")]] <- corrected_series\n}\n\n# Affiche la structure du data frame pour vérifier les changements\nstr(stationnaire_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t275 obs. of  19 variables:\n $ Date                   : Date, format: \"2000-02-01\" \"2000-03-01\" ...\n $ IPA                    : Time-Series  from 2000 to 2023: -2.23 -3.11 -1.59 1.21 6.55 ...\n $ CDD                    : num  8.96 9.14 8.56 11.97 9.15 ...\n $ importations           : Time-Series  from 2000 to 2023: 33.3 -11.7 11.7 14.4 -14 ...\n $ exportations           : num  28.264 -0.125 -2.771 -2.666 7.89 ...\n $ petrole                : Time-Series  from 2000 to 2023: 2.26 -0.29 -4.72 4.97 2.06 ...\n $ taux_change            : Time-Series  from 2000 to 2023: -0.0284 -0.0333 0.0262 0.0597 -0.0196 ...\n $ SMIC                   : num  136 136 151 151 151 151 151 151 151 151 ...\n $ precipitation          : num  163 156 166 135 149 ...\n $ temperature            : num  0.447 0.32 0.527 0.686 0.978 ...\n $ IPA_detrended          : num  -0.267 -1.206 0.25 2.974 8.256 ...\n $ CDD_detrended          : num  -0.426 -0.249 -0.837 2.571 -0.256 ...\n $ precipitation_detrended: num  14.137 6.864 16.623 -13.624 -0.338 ...\n $ temperature_detrended  : num  -0.337 -0.466 -0.261 -0.104 0.185 ...\n $ exportations_detrended : num  12.15 -16.49 -19.39 -19.53 -9.23 ...\n $ importations_detrended : num  32.9 -12.1 11.2 14 -14.5 ...\n $ taux_change_detrended  : num  -0.0273 -0.0323 0.0271 0.0605 -0.0189 ...\n $ SMIC_detrended         : num  -8.06 -8.06 6.94 6.93 6.93 ...\n $ petrole_detrended      : num  1.798 -0.754 -5.185 4.512 1.599 ...\n```\n\n\n:::\n\n```{.r .cell-code}\n# Modele avec toutes les variables, ne sera pas utilisé dans notre analyse - voir méthode STEP\nmodele1_4 <- lm(IPA_detrended ~  CDD_detrended +  importations_detrended + exportations_detrended +  petrole_detrended +    taux_change_detrended + SMIC_detrended + precipitation_detrended + temperature_detrended, data=stationnaire_data)\n\nsummary(modele1_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA_detrended ~ CDD_detrended + importations_detrended + \n    exportations_detrended + petrole_detrended + taux_change_detrended + \n    SMIC_detrended + precipitation_detrended + temperature_detrended, \n    data = stationnaire_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-62.864  -9.706  -1.702   7.561 114.563 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             -1.012e-15  1.212e+00   0.000 1.000000    \nCDD_detrended            1.695e+00  9.600e-01   1.766 0.078523 .  \nimportations_detrended   4.707e-02  8.372e-02   0.562 0.574421    \nexportations_detrended   2.455e-01  8.563e-02   2.867 0.004473 ** \npetrole_detrended        7.605e-01  2.120e-01   3.587 0.000398 ***\ntaux_change_detrended    2.122e+01  1.035e+01   2.051 0.041281 *  \nSMIC_detrended           4.563e-03  5.344e-02   0.085 0.932022    \nprecipitation_detrended -1.660e-01  8.712e-02  -1.906 0.057771 .  \ntemperature_detrended   -1.038e+00  3.624e+00  -0.286 0.774761    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.1 on 266 degrees of freedom\nMultiple R-squared:  0.1187,\tAdjusted R-squared:  0.09224 \nF-statistic:  4.48 on 8 and 266 DF,  p-value: 4.064e-05\n```\n\n\n:::\n\n```{.r .cell-code}\n# Step : Sélection des variables explicatives significatives (modèle linéaire = modele1_4 )\n\nmodele0_4 <- (lm(IPA_detrended~1,data=stationnaire_data))\nsummary(modele0_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA_detrended ~ 1, data = stationnaire_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-69.567  -8.942  -0.549   6.833 125.527 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)\n(Intercept) -7.465e-16  1.272e+00       0        1\n\nResidual standard error: 21.1 on 274 degrees of freedom\n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode ascendante\n step(modele0_4, scope=list(lower=modele0_4, upper=modele1_4), data=stationnaire_data, direction=\"forward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=1677.97\nIPA_detrended ~ 1\n\n                          Df Sum of Sq    RSS    AIC\n+ CDD_detrended            1    4317.9 117613 1670.0\n+ precipitation_detrended  1    4045.9 117885 1670.7\n+ petrole_detrended        1    3518.3 118412 1671.9\n+ exportations_detrended   1    2899.2 119031 1673.3\n<none>                                 121931 1678.0\n+ importations_detrended   1     433.1 121497 1679.0\n+ temperature_detrended    1     225.7 121705 1679.5\n+ taux_change_detrended    1     207.7 121723 1679.5\n+ SMIC_detrended           1       9.6 121921 1680.0\n\nStep:  AIC=1670.05\nIPA_detrended ~ CDD_detrended\n\n                          Df Sum of Sq    RSS    AIC\n+ petrole_detrended        1    3471.6 114141 1663.8\n+ exportations_detrended   1    3054.7 114558 1664.8\n+ precipitation_detrended  1    1049.9 116563 1669.6\n<none>                                 117613 1670.0\n+ importations_detrended   1     483.1 117130 1670.9\n+ taux_change_detrended    1     319.6 117293 1671.3\n+ SMIC_detrended           1      39.6 117573 1672.0\n+ temperature_detrended    1      31.3 117581 1672.0\n\nStep:  AIC=1663.82\nIPA_detrended ~ CDD_detrended + petrole_detrended\n\n                          Df Sum of Sq    RSS    AIC\n+ exportations_detrended   1    3241.0 110900 1657.9\n+ precipitation_detrended  1    1445.8 112695 1662.3\n+ taux_change_detrended    1    1428.6 112712 1662.3\n<none>                                 114141 1663.8\n+ importations_detrended   1     343.1 113798 1665.0\n+ SMIC_detrended           1      61.4 114080 1665.7\n+ temperature_detrended    1       0.3 114141 1665.8\n\nStep:  AIC=1657.89\nIPA_detrended ~ CDD_detrended + petrole_detrended + exportations_detrended\n\n                          Df Sum of Sq    RSS    AIC\n+ taux_change_detrended    1   1675.90 109224 1655.7\n+ precipitation_detrended  1   1537.52 109362 1656.0\n<none>                                 110900 1657.9\n+ importations_detrended   1    212.47 110688 1659.4\n+ temperature_detrended    1     59.16 110841 1659.8\n+ SMIC_detrended           1     26.57 110873 1659.8\n\nStep:  AIC=1655.71\nIPA_detrended ~ CDD_detrended + petrole_detrended + exportations_detrended + \n    taux_change_detrended\n\n                          Df Sum of Sq    RSS    AIC\n+ precipitation_detrended  1   1595.97 107628 1653.7\n<none>                                 109224 1655.7\n+ importations_detrended   1    225.71 108998 1657.1\n+ temperature_detrended    1     66.05 109158 1657.5\n+ SMIC_detrended           1      0.05 109224 1657.7\n\nStep:  AIC=1653.66\nIPA_detrended ~ CDD_detrended + petrole_detrended + exportations_detrended + \n    taux_change_detrended + precipitation_detrended\n\n                         Df Sum of Sq    RSS    AIC\n<none>                                107628 1653.7\n+ importations_detrended  1   141.110 107487 1655.3\n+ temperature_detrended   1    44.973 107583 1655.5\n+ SMIC_detrended          1     2.829 107625 1655.7\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA_detrended ~ CDD_detrended + petrole_detrended + \n    exportations_detrended + taux_change_detrended + precipitation_detrended, \n    data = stationnaire_data)\n\nCoefficients:\n            (Intercept)            CDD_detrended        petrole_detrended  \n             -1.146e-15                1.636e+00                7.729e-01  \n exportations_detrended    taux_change_detrended  precipitation_detrended  \n              2.524e-01                2.129e+01               -1.605e-01  \n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode descendante\nstep(modele1_4,data=stationnaire_data,direction=\"backward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=1659.21\nIPA_detrended ~ CDD_detrended + importations_detrended + exportations_detrended + \n    petrole_detrended + taux_change_detrended + SMIC_detrended + \n    precipitation_detrended + temperature_detrended\n\n                          Df Sum of Sq    RSS    AIC\n- SMIC_detrended           1       2.9 107455 1657.2\n- temperature_detrended    1      33.1 107485 1657.3\n- importations_detrended   1     127.7 107579 1657.5\n<none>                                 107452 1659.2\n- CDD_detrended            1    1260.0 108712 1660.4\n- precipitation_detrended  1    1467.0 108919 1660.9\n- taux_change_detrended    1    1698.7 109150 1661.5\n- exportations_detrended   1    3320.8 110772 1665.6\n- petrole_detrended        1    5198.2 112650 1670.2\n\nStep:  AIC=1657.21\nIPA_detrended ~ CDD_detrended + importations_detrended + exportations_detrended + \n    petrole_detrended + taux_change_detrended + precipitation_detrended + \n    temperature_detrended\n\n                          Df Sum of Sq    RSS    AIC\n- temperature_detrended    1      32.4 107487 1655.3\n- importations_detrended   1     128.5 107583 1655.5\n<none>                                 107455 1657.2\n- CDD_detrended            1    1259.7 108714 1658.4\n- precipitation_detrended  1    1464.1 108919 1658.9\n- taux_change_detrended    1    1741.0 109196 1659.6\n- exportations_detrended   1    3342.6 110797 1663.6\n- petrole_detrended        1    5202.0 112657 1668.2\n\nStep:  AIC=1655.3\nIPA_detrended ~ CDD_detrended + importations_detrended + exportations_detrended + \n    petrole_detrended + taux_change_detrended + precipitation_detrended\n\n                          Df Sum of Sq    RSS    AIC\n- importations_detrended   1     141.1 107628 1653.7\n<none>                                 107487 1655.3\n- CDD_detrended            1    1237.9 108725 1656.5\n- precipitation_detrended  1    1511.4 108998 1657.1\n- taux_change_detrended    1    1743.6 109231 1657.7\n- exportations_detrended   1    3471.1 110958 1662.0\n- petrole_detrended        1    5289.5 112777 1666.5\n\nStep:  AIC=1653.66\nIPA_detrended ~ CDD_detrended + exportations_detrended + petrole_detrended + \n    taux_change_detrended + precipitation_detrended\n\n                          Df Sum of Sq    RSS    AIC\n<none>                                 107628 1653.7\n- CDD_detrended            1    1193.2 108821 1654.7\n- precipitation_detrended  1    1596.0 109224 1655.7\n- taux_change_detrended    1    1734.3 109362 1656.0\n- exportations_detrended   1    3589.6 111218 1660.7\n- petrole_detrended        1    5419.0 113047 1665.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA_detrended ~ CDD_detrended + exportations_detrended + \n    petrole_detrended + taux_change_detrended + precipitation_detrended, \n    data = stationnaire_data)\n\nCoefficients:\n            (Intercept)            CDD_detrended   exportations_detrended  \n             -1.146e-15                1.636e+00                2.524e-01  \n      petrole_detrended    taux_change_detrended  precipitation_detrended  \n              7.729e-01                2.129e+01               -1.605e-01  \n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode double\n#méthode dans les 2 sens\nstep(modele0_4,scope=list(upper=modele1_4),data=stationnaire_data,direction=\"both\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=1677.97\nIPA_detrended ~ 1\n\n                          Df Sum of Sq    RSS    AIC\n+ CDD_detrended            1    4317.9 117613 1670.0\n+ precipitation_detrended  1    4045.9 117885 1670.7\n+ petrole_detrended        1    3518.3 118412 1671.9\n+ exportations_detrended   1    2899.2 119031 1673.3\n<none>                                 121931 1678.0\n+ importations_detrended   1     433.1 121497 1679.0\n+ temperature_detrended    1     225.7 121705 1679.5\n+ taux_change_detrended    1     207.7 121723 1679.5\n+ SMIC_detrended           1       9.6 121921 1680.0\n\nStep:  AIC=1670.05\nIPA_detrended ~ CDD_detrended\n\n                          Df Sum of Sq    RSS    AIC\n+ petrole_detrended        1    3471.6 114141 1663.8\n+ exportations_detrended   1    3054.7 114558 1664.8\n+ precipitation_detrended  1    1049.9 116563 1669.6\n<none>                                 117613 1670.0\n+ importations_detrended   1     483.1 117130 1670.9\n+ taux_change_detrended    1     319.6 117293 1671.3\n+ SMIC_detrended           1      39.6 117573 1672.0\n+ temperature_detrended    1      31.3 117581 1672.0\n- CDD_detrended            1    4317.9 121931 1678.0\n\nStep:  AIC=1663.82\nIPA_detrended ~ CDD_detrended + petrole_detrended\n\n                          Df Sum of Sq    RSS    AIC\n+ exportations_detrended   1    3241.0 110900 1657.9\n+ precipitation_detrended  1    1445.8 112695 1662.3\n+ taux_change_detrended    1    1428.6 112712 1662.3\n<none>                                 114141 1663.8\n+ importations_detrended   1     343.1 113798 1665.0\n+ SMIC_detrended           1      61.4 114080 1665.7\n+ temperature_detrended    1       0.3 114141 1665.8\n- petrole_detrended        1    3471.6 117613 1670.0\n- CDD_detrended            1    4271.3 118412 1671.9\n\nStep:  AIC=1657.89\nIPA_detrended ~ CDD_detrended + petrole_detrended + exportations_detrended\n\n                          Df Sum of Sq    RSS    AIC\n+ taux_change_detrended    1    1675.9 109224 1655.7\n+ precipitation_detrended  1    1537.5 109362 1656.0\n<none>                                 110900 1657.9\n+ importations_detrended   1     212.5 110688 1659.4\n+ temperature_detrended    1      59.2 110841 1659.8\n+ SMIC_detrended           1      26.6 110873 1659.8\n- exportations_detrended   1    3241.0 114141 1663.8\n- petrole_detrended        1    3658.0 114558 1664.8\n- CDD_detrended            1    4429.5 115330 1666.7\n\nStep:  AIC=1655.71\nIPA_detrended ~ CDD_detrended + petrole_detrended + exportations_detrended + \n    taux_change_detrended\n\n                          Df Sum of Sq    RSS    AIC\n+ precipitation_detrended  1    1596.0 107628 1653.7\n<none>                                 109224 1655.7\n+ importations_detrended   1     225.7 108998 1657.1\n+ temperature_detrended    1      66.0 109158 1657.5\n+ SMIC_detrended           1       0.0 109224 1657.7\n- taux_change_detrended    1    1675.9 110900 1657.9\n- exportations_detrended   1    3488.4 112712 1662.3\n- CDD_detrended            1    4716.8 113941 1665.3\n- petrole_detrended        1    4923.0 114147 1665.8\n\nStep:  AIC=1653.66\nIPA_detrended ~ CDD_detrended + petrole_detrended + exportations_detrended + \n    taux_change_detrended + precipitation_detrended\n\n                          Df Sum of Sq    RSS    AIC\n<none>                                 107628 1653.7\n- CDD_detrended            1    1193.2 108821 1654.7\n+ importations_detrended   1     141.1 107487 1655.3\n+ temperature_detrended    1      45.0 107583 1655.5\n+ SMIC_detrended           1       2.8 107625 1655.7\n- precipitation_detrended  1    1596.0 109224 1655.7\n- taux_change_detrended    1    1734.3 109362 1656.0\n- exportations_detrended   1    3589.6 111218 1660.7\n- petrole_detrended        1    5419.0 113047 1665.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA_detrended ~ CDD_detrended + petrole_detrended + \n    exportations_detrended + taux_change_detrended + precipitation_detrended, \n    data = stationnaire_data)\n\nCoefficients:\n            (Intercept)            CDD_detrended        petrole_detrended  \n             -1.146e-15                1.636e+00                7.729e-01  \n exportations_detrended    taux_change_detrended  precipitation_detrended  \n              2.524e-01                2.129e+01               -1.605e-01  \n```\n\n\n:::\n\n```{.r .cell-code}\n# 1. MCO modele retenue\nlm_model4<-  lm(formula = IPA_detrended ~ CDD_detrended + petrole_detrended + \n    exportations_detrended + taux_change_detrended + precipitation_detrended, \n    data = stationnaire_data)\nsummary(lm_model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA_detrended ~ CDD_detrended + petrole_detrended + \n    exportations_detrended + taux_change_detrended + precipitation_detrended, \n    data = stationnaire_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-61.876  -9.716  -1.679   7.230 114.837 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             -1.146e-15  1.206e+00   0.000 1.000000    \nCDD_detrended            1.636e+00  9.472e-01   1.727 0.085330 .  \npetrole_detrended        7.729e-01  2.100e-01   3.680 0.000282 ***\nexportations_detrended   2.524e-01  8.427e-02   2.995 0.002998 ** \ntaux_change_detrended    2.129e+01  1.022e+01   2.082 0.038288 *  \nprecipitation_detrended -1.605e-01  8.034e-02  -1.997 0.046809 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20 on 269 degrees of freedom\nMultiple R-squared:  0.1173,\tAdjusted R-squared:  0.1009 \nF-statistic: 7.149 on 5 and 269 DF,  p-value: 2.673e-06\n```\n\n\n:::\n\n```{.r .cell-code}\n## Hypotheses\n#### Test de normalité des résidus\n# Résidus\nresidus4 <- residuals(lm_model4)\n# Test de normalité des résidus\nks.test(residus4, \"pnorm\", mean = mean(residus4), sd = sd(residus4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residus4\nD = 0.10967, p-value = 0.002679\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de Breusch-Pagan pour l'hétéroscédasticité\nbptest(lm_model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  lm_model4\nBP = 8.9646, df = 5, p-value = 0.1105\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test RESET\nreset(lm_model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  lm_model4\nRESET = 0.58521, df1 = 2, df2 = 267, p-value = 0.5577\n```\n\n\n:::\n\n```{.r .cell-code}\n#### multicollinéarité\nvif(lm_model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          CDD_detrended       petrole_detrended  exportations_detrended \n               1.461501                1.116101                1.004650 \n  taux_change_detrended precipitation_detrended \n               1.110756                1.468620 \n```\n\n\n:::\n\n```{.r .cell-code}\n#### Autocorrelation de résidus\ncheckresiduals(lm_model4)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBreusch-Godfrey test for serial correlation of order up to 10\n\ndata:  Residuals\nLM test = 109.32, df = 10, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n## 5. Modèle 5 avec lag\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Création du lag \nst3_data$IPA_lag1 <- stats::lag(st3_data$IPA, 1) \nst3_data$IPA_lag2 <- stats::lag(st3_data$IPA, 2) \n\nst3_data <- na.omit(st3_data)\n\n\n# Modèle de régression avec Lag 1 , toutes les variables\nmodele1_5 <- lm(IPA ~ CDD +  importations + exportations +  petrole +  taux_change + SMIC + precipitation + temperature+ IPA_lag1 + IPA_lag2, data = st3_data)\nsummary(modele1_5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in summary.lm(modele1_5): essentially perfect fit: summary may be\nunreliable\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ CDD + importations + exportations + petrole + \n    taux_change + SMIC + precipitation + temperature + IPA_lag1 + \n    IPA_lag2, data = st3_data)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-1.009e-16 -7.630e-19  3.920e-19  1.385e-18  8.567e-18 \n\nCoefficients: (1 not defined because of singularities)\n                Estimate Std. Error    t value Pr(>|t|)    \n(Intercept)   -1.241e-17  6.989e-18 -1.776e+00  0.07685 .  \nCDD            1.373e-19  3.110e-19  4.410e-01  0.65935    \nimportations  -4.797e-21  2.733e-20 -1.760e-01  0.86081    \nexportations  -2.301e-20  1.720e-20 -1.338e+00  0.18217    \npetrole       -1.954e-19  7.074e-20 -2.762e+00  0.00614 ** \ntaux_change   -7.414e-18  3.458e-18 -2.144e+00  0.03296 *  \nSMIC           7.534e-21  1.744e-20  4.320e-01  0.66615    \nprecipitation  6.107e-20  2.850e-20  2.143e+00  0.03303 *  \ntemperature    5.892e-19  1.116e-18  5.280e-01  0.59807    \nIPA_lag1       1.000e+00  1.869e-17  5.350e+16  < 2e-16 ***\nIPA_lag2              NA         NA         NA       NA    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.559e-18 on 265 degrees of freedom\nMultiple R-squared:      1,\tAdjusted R-squared:      1 \nF-statistic: 3.581e+32 on 9 and 265 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nmodele0_5 <- (lm((IPA)~1,data=st3_data))\nsummary(modele0_5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = (IPA) ~ 1, data = st3_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.060967 -0.014968 -0.002519  0.011062  0.082152 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.008686   0.001356   6.403 6.58e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02249 on 274 degrees of freedom\n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode ascendante\nstep(modele0_5, scope=list(lower=modele0_5, upper=modele1_5), data=st3_data, direction=\"forward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-2085.99\n(IPA) ~ 1\n\n                Df Sum of Sq     RSS      AIC\n+ IPA_lag1       1  0.138635 0.00000 -21080.7\n+ IPA_lag2       1  0.138635 0.00000 -21080.7\n+ taux_change    1  0.003557 0.13508  -2091.1\n+ precipitation  1  0.003276 0.13536  -2090.6\n+ petrole        1  0.002705 0.13593  -2089.4\n+ exportations   1  0.001609 0.13703  -2087.2\n+ CDD            1  0.001505 0.13713  -2087.0\n<none>                       0.13864  -2086.0\n+ importations   1  0.000470 0.13817  -2084.9\n+ temperature    1  0.000147 0.13849  -2084.3\n+ SMIC           1  0.000120 0.13852  -2084.2\n\nStep:  AIC=-21080.67\n(IPA) ~ IPA_lag1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: attempting model selection on an essentially perfect fit is nonsense\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df  Sum of Sq        RSS    AIC\n+ exportations   1 1.8869e-33 1.3657e-31 -21082\n+ temperature    1 1.3833e-33 1.3707e-31 -21081\n<none>                        1.3845e-31 -21081\n+ importations   1 3.9347e-34 1.3806e-31 -21080\n+ SMIC           1 8.2170e-35 1.3837e-31 -21079\n+ CDD            1 5.1420e-35 1.3840e-31 -21079\n+ precipitation  1 2.0090e-35 1.3844e-31 -21079\n+ taux_change    1 8.1400e-36 1.3845e-31 -21079\n+ petrole        1 2.5000e-36 1.3845e-31 -21079\n\nStep:  AIC=-21082.45\n(IPA) ~ IPA_lag1 + exportations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: attempting model selection on an essentially perfect fit is nonsense\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df  Sum of Sq        RSS    AIC\n<none>                        1.3657e-31 -21082\n+ temperature    1 6.9380e-34 1.3587e-31 -21082\n+ importations   1 3.5406e-34 1.3621e-31 -21081\n+ SMIC           1 5.2300e-35 1.3652e-31 -21081\n+ taux_change    1 5.8700e-36 1.3656e-31 -21080\n+ precipitation  1 5.5600e-36 1.3656e-31 -21080\n+ CDD            1 1.5500e-36 1.3657e-31 -21080\n+ petrole        1 5.0000e-37 1.3657e-31 -21080\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = (IPA) ~ IPA_lag1 + exportations, data = st3_data)\n\nCoefficients:\n (Intercept)      IPA_lag1  exportations  \n  -1.506e-17     1.000e+00     1.072e-19  \n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode descendante\nstep(modele1_5,data=st3_data,direction=\"backward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-21751.32\nIPA ~ CDD + importations + exportations + petrole + taux_change + \n    SMIC + precipitation + temperature + IPA_lag1 + IPA_lag2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: attempting model selection on an essentially perfect fit is nonsense\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStep:  AIC=-21751.32\nIPA ~ CDD + importations + exportations + petrole + taux_change + \n    SMIC + precipitation + temperature + IPA_lag1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: attempting model selection on an essentially perfect fit is nonsense\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df Sum of Sq     RSS      AIC\n- temperature    1   0.00000 0.00000 -22202.5\n<none>                       0.00000 -21751.3\n- exportations   1   0.00000 0.00000 -21503.4\n- SMIC           1   0.00000 0.00000 -21332.8\n- taux_change    1   0.00000 0.00000 -21299.5\n- precipitation  1   0.00000 0.00000 -21291.9\n- importations   1   0.00000 0.00000 -21253.2\n- petrole        1   0.00000 0.00000 -21175.4\n- CDD            1   0.00000 0.00000 -21087.1\n- IPA_lag1       1   0.12312 0.12312  -2102.6\n\nStep:  AIC=-22202.49\nIPA ~ CDD + importations + exportations + petrole + taux_change + \n    SMIC + precipitation + IPA_lag1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: attempting model selection on an essentially perfect fit is nonsense\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df Sum of Sq     RSS      AIC\n<none>                       0.00000 -22202.5\n- precipitation  1   0.00000 0.00000 -22111.0\n- SMIC           1   0.00000 0.00000 -21726.0\n- CDD            1   0.00000 0.00000 -21712.0\n- taux_change    1   0.00000 0.00000 -21535.4\n- importations   1   0.00000 0.00000 -21210.2\n- petrole        1   0.00000 0.00000 -21164.7\n- exportations   1   0.00000 0.00000 -20815.4\n- IPA_lag1       1   0.12366 0.12366  -2103.4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ CDD + importations + exportations + petrole + \n    taux_change + SMIC + precipitation + IPA_lag1, data = st3_data)\n\nCoefficients:\n  (Intercept)            CDD   importations   exportations        petrole  \n    5.633e-18      2.800e-20      1.035e-20      1.892e-20      1.212e-19  \n  taux_change           SMIC  precipitation       IPA_lag1  \n    7.330e-18     -8.519e-21     -2.797e-20      1.000e+00  \n```\n\n\n:::\n\n```{.r .cell-code}\n### Méthode double\n#méthode dans les 2 sens\nstep(modele0_5,scope=list(upper=modele1_5),data=st3_data,direction=\"both\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-2085.99\n(IPA) ~ 1\n\n                Df Sum of Sq     RSS      AIC\n+ IPA_lag1       1  0.138635 0.00000 -21080.7\n+ IPA_lag2       1  0.138635 0.00000 -21080.7\n+ taux_change    1  0.003557 0.13508  -2091.1\n+ precipitation  1  0.003276 0.13536  -2090.6\n+ petrole        1  0.002705 0.13593  -2089.4\n+ exportations   1  0.001609 0.13703  -2087.2\n+ CDD            1  0.001505 0.13713  -2087.0\n<none>                       0.13864  -2086.0\n+ importations   1  0.000470 0.13817  -2084.9\n+ temperature    1  0.000147 0.13849  -2084.3\n+ SMIC           1  0.000120 0.13852  -2084.2\n\nStep:  AIC=-21080.67\n(IPA) ~ IPA_lag1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: attempting model selection on an essentially perfect fit is nonsense\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: attempting model selection on an essentially perfect fit is nonsense\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df Sum of Sq     RSS    AIC\n+ exportations   1   0.00000 0.00000 -21082\n+ temperature    1   0.00000 0.00000 -21081\n<none>                       0.00000 -21081\n+ importations   1   0.00000 0.00000 -21080\n+ SMIC           1   0.00000 0.00000 -21079\n+ CDD            1   0.00000 0.00000 -21079\n+ precipitation  1   0.00000 0.00000 -21079\n+ taux_change    1   0.00000 0.00000 -21079\n+ petrole        1   0.00000 0.00000 -21079\n- IPA_lag1       1   0.13864 0.13864  -2086\n\nStep:  AIC=-21082.45\n(IPA) ~ IPA_lag1 + exportations\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: attempting model selection on an essentially perfect fit is nonsense\nWarning: attempting model selection on an essentially perfect fit is nonsense\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df Sum of Sq     RSS      AIC\n<none>                       0.00000 -21082.4\n+ temperature    1   0.00000 0.00000 -21081.8\n+ importations   1   0.00000 0.00000 -21081.2\n- exportations   1   0.00000 0.00000 -21080.7\n+ SMIC           1   0.00000 0.00000 -21080.6\n+ taux_change    1   0.00000 0.00000 -21080.5\n+ precipitation  1   0.00000 0.00000 -21080.5\n+ CDD            1   0.00000 0.00000 -21080.4\n+ petrole        1   0.00000 0.00000 -21080.4\n- IPA_lag1       1   0.13703 0.13703  -2087.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = (IPA) ~ IPA_lag1 + exportations, data = st3_data)\n\nCoefficients:\n (Intercept)      IPA_lag1  exportations  \n  -1.506e-17     1.000e+00     1.072e-19  \n```\n\n\n:::\n\n```{.r .cell-code}\n# modele 7 \nmodel5 <- lm(formula = (IPA) ~ IPA_lag1 + taux_change + petrole + precipitation,   data = st3_data)\nsummary(model5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in summary.lm(model5): essentially perfect fit: summary may be\nunreliable\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = (IPA) ~ IPA_lag1 + taux_change + petrole + precipitation, \n    data = st3_data)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-3.690e-16  5.900e-19  1.390e-18  2.150e-18  2.202e-17 \n\nCoefficients:\n                Estimate Std. Error    t value Pr(>|t|)    \n(Intercept)   -8.369e-18  1.130e-17 -7.410e-01    0.460    \nIPA_lag1       1.000e+00  6.392e-17  1.564e+16   <2e-16 ***\ntaux_change    1.465e-18  1.183e-17  1.240e-01    0.902    \npetrole       -1.174e-21  2.431e-19 -5.000e-03    0.996    \nprecipitation -1.530e-20  7.617e-20 -2.010e-01    0.841    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.264e-17 on 270 degrees of freedom\nMultiple R-squared:      1,\tAdjusted R-squared:      1 \nF-statistic: 6.76e+31 on 4 and 270 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n## TESTS \nresidus7 <- residuals(model5)\n# Test de normalité des résidus\nks.test(residus7, \"pnorm\", mean = mean(residus7), sd = sd(residus7))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residus7\nD = 0.41462, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model5\nBP = 1.407, df = 4, p-value = 0.843\n```\n\n\n:::\n\n```{.r .cell-code}\nreset(model5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  model5\nRESET = 34.971, df1 = 2, df2 = 268, p-value = 3.2e-14\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in summary.lm(object, ...): essentially perfect fit: summary may be\nunreliable\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     IPA_lag1   taux_change       petrole precipitation \n     1.104992      1.165378      1.167885      1.040446 \n```\n\n\n:::\n\n```{.r .cell-code}\ncheckresiduals(model5)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBreusch-Godfrey test for serial correlation of order up to 10\n\ndata:  Residuals\nLM test = 1.1638, df = 10, p-value = 0.9997\n```\n\n\n:::\n:::\n\n\n\n-   La présence d'hétéroscédasticité signifie que la variance des résidus n'est pas constante. Cela peut affecter la validité des tests de significativité des coefficients.\n\n-   Le test RESET suggère que le modèle pourrait être mal spécifié, indiquant que la relation entre les variables n'est pas correctement capturée par le modèle linéaire.\n\n-   On ne peut donc pas utiliser la méthode des MCO pour estimer le modèle : les coefficients MCO ne sont pas biaisés mais la variance de l’estimateur est non minimale\n\n# Conclusion\n\nTous les modèles estimés avec les MCO présentent de l'autocorrelation de résidus, c'est à dire une corrélation entre les résidus eux-mêmes à travers le temps.\n\nIntroduire des lags peut régler le problème mais cela a généré un surajustement et aussi de l'heteroscedasticité et la forme linéaire n'est pas accepte\n\n# ARMAX\n\nModèle 0 de test avec ARMAX avec toutes les variables et sans stationnaire\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny0 <- ts_data[,1]\nvars0 <- ts_data[,2:9]\n# Estimation du modèle ARMAX\narmax_model0 <- auto.arima(y0, xreg = vars0, stationary=FALSE, seasonal = TRUE)\n# Résumé du modèle ARMAX\nsummary(armax_model0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: y0 \nRegression with ARIMA(0,0,2)(0,0,2)[12] errors \n\nCoefficients:\n         ma1     ma2    sma1    sma2  intercept      CDD  importations\n      1.7037  0.9516  0.9901  0.7025   259.7776  -2.4083       -0.0915\ns.e.  0.0284  0.0267  0.0567  0.0744    73.3117   0.8277        0.0951\n      exportations  petrole  taux_change     SMIC  precipitation  temperature\n            0.1874   2.2594     164.8233  -0.2381        -0.1904      -4.4766\ns.e.        0.1554   0.3452      17.1950   0.1022         0.0555       2.7707\n\nsigma^2 = 3774:  log likelihood = -1533.74\nAIC=3095.47   AICc=3097.08   BIC=3146.16\n\nTraining set error measures:\n                   ME     RMSE      MAE       MPE    MAPE      MASE      ACF1\nTraining set 1.907931 59.96586 44.41014 -3.310016 7.32571 0.4048599 0.4175662\n```\n\n\n:::\n\n```{.r .cell-code}\ncoeftest(armax_model0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nz test of coefficients:\n\n                Estimate Std. Error z value  Pr(>|z|)    \nma1             1.703724   0.028368 60.0583 < 2.2e-16 ***\nma2             0.951628   0.026672 35.6791 < 2.2e-16 ***\nsma1            0.990059   0.056723 17.4542 < 2.2e-16 ***\nsma2            0.702488   0.074445  9.4364 < 2.2e-16 ***\nintercept     259.777581  73.311667  3.5435 0.0003949 ***\nCDD            -2.408346   0.827653 -2.9098 0.0036160 ** \nimportations   -0.091498   0.095088 -0.9622 0.3359263    \nexportations    0.187358   0.155367  1.2059 0.2278520    \npetrole         2.259368   0.345224  6.5446 5.964e-11 ***\ntaux_change   164.823254  17.194956  9.5856 < 2.2e-16 ***\nSMIC           -0.238088   0.102210 -2.3294 0.0198384 *  \nprecipitation  -0.190378   0.055512 -3.4295 0.0006048 ***\ntemperature    -4.476600   2.770688 -1.6157 0.1061593    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test hypotheses \n# Résidus du modèle ARMAX\nresiduals_armax0 <- residuals(armax_model0)\n# Test de normalité des résidus\nks.test(residuals_armax0, \"pnorm\", mean = mean(residuals_armax0), sd = sd(residuals_armax0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residuals_armax0\nD = 0.091781, p-value = 0.01913\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de Ljung-Box pour l'autocorrélation des résidus\ncheckresiduals(armax_model0)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from Regression with ARIMA(0,0,2)(0,0,2)[12] errors\nQ* = 1002.1, df = 20, p-value < 2.2e-16\n\nModel df: 4.   Total lags used: 24\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de Breusch-Pagan pour l'hétéroscédasticité\nbptest(residuals_armax0 ~ vars0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  residuals_armax0 ~ vars0\nBP = 40.396, df = 8, p-value = 2.703e-06\n```\n\n\n:::\n:::\n\n\n\nProblème d’autocorrelation Ljung-Box test p-value \\< 2.2e-16\n\nProblème d’homoscedasticité Breusch-Pagan p-value test 2.703e-06\n\nProblème normalité Kolmogorov-Smirnov test p-value = 0.01913\n\n## 1. Test Modèle ARMAX avec toutes les variables stationnaires\n\nInclut toutes les variables (stationnaires)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Préparation des séries temporelles pour ARMAX\ny1 <- ts(stationnaire_data[,2], start = c(2000, 2), frequency = 12)\nvars1 <- as.matrix(stationnaire_data[, 3:10]) \n# Estimation du modèle ARMAX avec toutes les variables\narmax_model1 <- auto.arima(y1, xreg = vars1, stationary=TRUE)\n# Résumé du modèle ARMAX\nsummary(armax_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: y1 \nRegression with ARIMA(1,0,0) errors \n\nCoefficients:\n         ar1     CDD  importations  exportations  petrole  taux_change     SMIC\n      0.6287  1.1559        0.0637        0.1804   0.4564      17.5248  -0.0450\ns.e.  0.0481  0.6013        0.0484        0.0761   0.1631       7.6201   0.0614\n      precipitation  temperature\n            -0.0359      -2.1677\ns.e.         0.0467       2.7029\n\nsigma^2 = 252.9:  log likelihood = -1146.68\nAIC=2313.35   AICc=2314.19   BIC=2349.52\n\nTraining set error measures:\n                    ME     RMSE      MAE       MPE     MAPE      MASE\nTraining set 0.0270672 15.64079 10.78681 -29.08853 267.4824 0.5550402\n                    ACF1\nTraining set 0.007601316\n```\n\n\n:::\n\n```{.r .cell-code}\ncoeftest(armax_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nz test of coefficients:\n\n               Estimate Std. Error z value  Pr(>|z|)    \nar1            0.628669   0.048053 13.0827 < 2.2e-16 ***\nCDD            1.155934   0.601305  1.9224  0.054558 .  \nimportations   0.063678   0.048399  1.3157  0.188280    \nexportations   0.180353   0.076142  2.3686  0.017854 *  \npetrole        0.456407   0.163119  2.7980  0.005142 ** \ntaux_change   17.524841   7.620106  2.2998  0.021459 *  \nSMIC          -0.045022   0.061439 -0.7328  0.463685    \nprecipitation -0.035863   0.046699 -0.7680  0.442514    \ntemperature   -2.167712   2.702941 -0.8020  0.422563    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test hypotheses \n# Résidus du modèle ARMAX\n# Test de Ljung-Box pour l'autocorrélation des résidus\ncheckresiduals(armax_model1)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from Regression with ARIMA(1,0,0) errors\nQ* = 29.046, df = 23, p-value = 0.1788\n\nModel df: 1.   Total lags used: 24\n```\n\n\n:::\n\n```{.r .cell-code}\nresiduals_armax1 <- residuals(armax_model1)\n# Test de normalité des résidus\nks.test(residuals_armax1, \"pnorm\", mean = mean(residuals_armax1), sd = sd(residuals_armax1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residuals_armax1\nD = 0.10094, p-value = 0.007368\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de Breusch-Pagan pour l'hétéroscédasticité\nbptest(residuals_armax1 ~ vars1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  residuals_armax1 ~ vars1\nBP = 43.638, df = 8, p-value = 6.66e-07\n```\n\n\n:::\n:::\n\n\n\n## 2. ARMAX Avec variables sélectionnes par stepwise et best sub\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny2 <- ts(stationnaire_data[,2], start = c(2000, 2), frequency = 12)\nvars2 <- as.matrix(stationnaire_data[, c(\"exportations\", \"petrole\", \"precipitation\", \"taux_change\", \"CDD\")])\n# Estimation du modèle ARMAX\narmax_model2 <- auto.arima(y2, xreg = vars2, stationary=TRUE)\n# Résumé du modèle ARMAX\nsummary(armax_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: y2 \nRegression with ARIMA(1,0,0) errors \n\nCoefficients:\n         ar1  exportations  petrole  precipitation  taux_change     CDD\n      0.6213        0.1782   0.4950        -0.0589      17.5920  0.6530\ns.e.  0.0483        0.0743   0.1629         0.0335       7.6554  0.4628\n\nsigma^2 = 253.1:  log likelihood = -1148.31\nAIC=2310.62   AICc=2311.04   BIC=2335.94\n\nTraining set error measures:\n                      ME     RMSE      MAE       MPE     MAPE     MASE\nTraining set -0.08807324 15.73433 10.71464 -49.22505 311.8129 0.551327\n                   ACF1\nTraining set 0.00296305\n```\n\n\n:::\n\n```{.r .cell-code}\ncoeftest(armax_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nz test of coefficients:\n\n               Estimate Std. Error z value  Pr(>|z|)    \nar1            0.621273   0.048281 12.8680 < 2.2e-16 ***\nexportations   0.178229   0.074289  2.3991  0.016434 *  \npetrole        0.495043   0.162892  3.0391  0.002373 ** \nprecipitation -0.058927   0.033472 -1.7605  0.078325 .  \ntaux_change   17.591999   7.655369  2.2980  0.021562 *  \nCDD            0.653047   0.462793  1.4111  0.158215    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test hypothèses \n# Résidus du modèle ARMAX\nresiduals_armax2 <- residuals(armax_model2)\n# Test de Ljung-Box pour l'autocorrélation des résidus\ncheckresiduals(armax_model2)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from Regression with ARIMA(1,0,0) errors\nQ* = 29.109, df = 23, p-value = 0.1767\n\nModel df: 1.   Total lags used: 24\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de normalité des résidus\nks.test(residuals_armax2, \"pnorm\", mean = mean(residuals_armax2), sd = sd(residuals_armax2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residuals_armax2\nD = 0.094687, p-value = 0.01444\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de Breusch-Pagan pour l'hétéroscédasticité\nbptest(residuals_armax2 ~ vars2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  residuals_armax2 ~ vars2\nBP = 40.625, df = 5, p-value = 1.117e-07\n```\n\n\n:::\n:::\n\n\n\n## 3. Modèle ARMAX (st2_data utilise le diff_log_IPA)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny3 <- ts(st2_data[,2], start = c(2000, 2), frequency = 12)\nvars3 <- as.matrix(stationnaire_data[, 3:10]) \n# Estimation du modèle ARMAX\narmax_model3 <- auto.arima(y3, xreg = vars3, stationary=TRUE)\n# Résumé du modèle ARMAX\nsummary(armax_model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: y3 \nRegression with ARIMA(1,0,0) errors \n\nCoefficients:\n         ar1    CDD  importations  exportations  petrole  taux_change   SMIC\n      0.5779  1e-03         1e-04         1e-04    5e-04       0.0235  0e+00\ns.e.  0.0497  7e-04         1e-04         1e-04    2e-04       0.0087  1e-04\n      precipitation  temperature\n              0e+00      -0.0022\ns.e.          1e-04       0.0031\n\nsigma^2 = 0.000318:  log likelihood = 721.5\nAIC=-1423.01   AICc=-1422.18   BIC=-1386.84\n\nTraining set error measures:\n                       ME       RMSE        MAE      MPE     MAPE      MASE\nTraining set 0.0001684718 0.01753895 0.01381429 25.05035 248.0198 0.5412742\n                   ACF1\nTraining set 0.03623777\n```\n\n\n:::\n\n```{.r .cell-code}\ncoeftest(armax_model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nz test of coefficients:\n\n                 Estimate  Std. Error z value Pr(>|z|)    \nar1            5.7793e-01  4.9748e-02 11.6172  < 2e-16 ***\nCDD            9.8542e-04  6.8656e-04  1.4353  0.15120    \nimportations   8.0666e-05  8.2173e-05  0.9817  0.32627    \nexportations   1.2371e-04  1.0106e-04  1.2241  0.22090    \npetrole        4.6616e-04  1.9498e-04  2.3908  0.01681 *  \ntaux_change    2.3475e-02  8.7243e-03  2.6907  0.00713 ** \nSMIC           1.4973e-06  9.4345e-05  0.0159  0.98734    \nprecipitation -4.1973e-05  7.6820e-05 -0.5464  0.58480    \ntemperature   -2.2270e-03  3.0740e-03 -0.7244  0.46879    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test hypotheses \n# Résidus du modèle ARMAX\nresiduals_armax3 <- residuals(armax_model3)\n# Test de Ljung-Box pour l'autocorrélation des résidus\ncheckresiduals(residuals_armax3)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals\nQ* = 14.905, df = 24, p-value = 0.9235\n\nModel df: 0.   Total lags used: 24\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de normalité des résidus\nks.test(residuals_armax3, \"pnorm\", mean = mean(residuals_armax3), sd = sd(residuals_armax3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residuals_armax3\nD = 0.045432, p-value = 0.6214\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de Breusch-Pagan pour l'hétéroscédasticité\nbptest(residuals_armax3 ~ vars3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  residuals_armax3 ~ vars3\nBP = 12.266, df = 8, p-value = 0.1397\n```\n\n\n:::\n:::\n\n\n\n## 4. Modèle ARMAX2 - Variables sélectionnés (st2_data utilise le diff_log_IPA)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny4 <- ts(st2_data[,2], start = c(2000, 2), frequency = 12)\nvars4 <- as.matrix(stationnaire_data[, c(\"exportations\", \"petrole\", \"precipitation\", \"taux_change\")])\n\n# Estimation du modèle ARMAX\narmax_model4 <- auto.arima(y4, xreg = vars4, stationary=TRUE, seasonal = FALSE, stepwise=FALSE, approximation=FALSE)\n# Résumé du modèle ARMAX\nsummary(armax_model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: y4 \nRegression with ARIMA(1,0,0) errors \n\nCoefficients:\n         ar1  intercept  exportations  petrole  precipitation  taux_change\n      0.5706     0.0146         1e-04    5e-04         -1e-04       0.0238\ns.e.  0.0501     0.0108         1e-04    2e-04          1e-04       0.0088\n\nsigma^2 = 0.0003175:  log likelihood = 720.18\nAIC=-1426.35   AICc=-1425.94   BIC=-1401.04\n\nTraining set error measures:\n                       ME       RMSE        MAE      MPE     MAPE      MASE\nTraining set 4.259534e-05 0.01762421 0.01372311 13.16189 288.5038 0.5377013\n                   ACF1\nTraining set 0.03113072\n```\n\n\n:::\n\n```{.r .cell-code}\ncoeftest(armax_model4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nz test of coefficients:\n\n                 Estimate  Std. Error z value  Pr(>|z|)    \nar1            5.7057e-01  5.0115e-02 11.3853 < 2.2e-16 ***\nintercept      1.4609e-02  1.0759e-02  1.3578  0.174539    \nexportations   1.2270e-04  1.0064e-04  1.2193  0.222748    \npetrole        5.1753e-04  1.9494e-04  2.6549  0.007934 ** \nprecipitation -8.6525e-05  7.1846e-05 -1.2043  0.228467    \ntaux_change    2.3816e-02  8.7529e-03  2.7209  0.006510 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test hypotheses \n# Résidus du modèle ARMAX\nresiduals_armax <- residuals(armax_model4)\n# Test de normalité des résidus\nks.test(residuals_armax, \"pnorm\", mean = mean(residuals_armax), sd = sd(residuals_armax))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residuals_armax\nD = 0.059652, p-value = 0.2818\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de Ljung-Box pour l'autocorrélation des résidus\n\ncheckresiduals(armax_model4)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from Regression with ARIMA(1,0,0) errors\nQ* = 14.994, df = 23, p-value = 0.8948\n\nModel df: 1.   Total lags used: 24\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test de Breusch-Pagan pour l'hétéroscédasticité\nbptest(residuals_armax ~ vars4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  residuals_armax ~ vars4\nBP = 4.8771, df = 4, p-value = 0.3001\n```\n\n\n:::\n:::\n\n\n\n-   Test de Kolmogorov-Smirnov Une p-value de 0.4388 indique qu'il n'y a pas de preuve statistique pour rejeter l'hypothèse nulle selon laquelle les résidus suivent une distribution normale. Cela signifie que les résidus peuvent être considérés comme normalement distribués\n\n-   Test de Ljung-Box (Box-Ljung Test) Une p-value de 0.593 indique que on ne rejete pas l'hypothèse nulle d'indépendance des résidus et donc pas d'autocorrélation significative dans les résidus du modèle\n\n-   Test de Breusch-Pagan Hypothèse nulle: les variances des résidus sont homogènes, c'est-à-dire qu'il n'y a pas d'hétéroscédasticité dans les résidus de votre modèle. Avec une p-value de 0.3751, on ne rejet pas l'hypothèse nulle car il n'y a pas de preuves statistiquement significatives d'hétéroscédasticité dans les résidus du modèle ARMAX\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# écart pour la bande de prédiction à 80%\nec80 <- sqrt(armax_model4$sigma2) * qnorm(0.90)\n\n# Valeurs ajustées (prédictions)\nvajust <- fitted(armax_model4)\n\n# Matrice avec les valeurs observées, les valeurs ajustées, et les bandes de prédiction\nmatri <- as.ts(cbind(y4, vajust - ec80, vajust + ec80), start = start(y4), frequency = frequency(y4))\n\n# Graphique\nplot(matri, plot.type = 'single', lty = c(1, 2, 2), xlab = \"Temps\", ylab = 'Valeur', main = \"\", cex.main = 0.8)\nlegend(\"topright\", legend = c(\"Valeur observée\", \"Bande de prédiction 80%\"), lwd = 1, lty = c(1, 2), cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Proportion \nindi <- (y4-(vajust-ec80))>0&(vajust+ec80-y4)>0\nprop <- 100*sum(indi)/length(indi)\n\nprop\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 80.36364\n```\n\n\n:::\n:::\n\n\n\nMontre les valeurs observées de notre série temporelle, ainsi que les valeurs ajustées par le modèle ARMAX avec une bande de prédiction à 80%.\n\nLa proportion observée vaut 81%, elle est un peu supérieure à la valeur théorique de 80%. On considérera que l'ajustement est satisfaisant.\n\n# Comparaison lm et armax\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <-arima(y4, order = c(0,0,0), xreg = vars4)\ncoeftest(a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nz test of coefficients:\n\n                 Estimate  Std. Error z value  Pr(>|z|)    \nintercept      3.3422e-02  1.0849e-02  3.0808 0.0020648 ** \nexportations   9.0536e-05  7.9817e-05  1.1343 0.2566699    \npetrole        8.3814e-04  2.3070e-04  3.6331 0.0002801 ***\nprecipitation -2.0544e-04  9.2734e-05 -2.2153 0.0267371 *  \ntaux_change    4.1333e-02  1.0818e-02  3.8209 0.0001330 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nlm_model2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ taux_change + petrole + precipitation + exportations, \n    data = st2_data)\n\nCoefficients:\n  (Intercept)    taux_change        petrole  precipitation   exportations  \n    3.342e-02      4.133e-02      8.381e-04     -2.054e-04      9.054e-05  \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(lm_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ taux_change + petrole + precipitation + exportations, \n    data = st2_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.053072 -0.013313 -0.002177  0.009744  0.072178 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    3.342e-02  1.095e-02   3.053 0.002494 ** \ntaux_change    4.133e-02  1.092e-02   3.786 0.000189 ***\npetrole        8.381e-04  2.247e-04   3.730 0.000234 ***\nprecipitation -2.054e-04  7.110e-05  -2.889 0.004173 ** \nexportations   9.054e-05  5.277e-05   1.716 0.087389 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02144 on 270 degrees of freedom\nMultiple R-squared:  0.1048,\tAdjusted R-squared:  0.09151 \nF-statistic:   7.9 on 4 and 270 DF,  p-value: 4.911e-06\n```\n\n\n:::\n:::\n\n\n\nOn trouve effectivement les mêmes estimations que par lm() dans lm_model2; cependant on note des différences dans les écarts types des estimateurs. Ceci peut s’expliquer par le fait que Arima() fournit une estimation de la matrice des covariances des estimateurs à partir du Hessien de la log-vraisemblance, estimation peu précise.\n\n## ACF - PACF\n\nOn reprend le modèle avec diff log, les variables sélectionnés et\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacf(residuals(lm_model2),lag.max=30,numer=FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in plot.window(...): \"numer\" is not a graphical parameter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in plot.xy(xy, type, ...): \"numer\" is not a graphical parameter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in axis(side = side, at = at, labels = labels, ...): \"numer\" is not a\ngraphical parameter\nWarning in axis(side = side, at = at, labels = labels, ...): \"numer\" is not a\ngraphical parameter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in box(...): \"numer\" is not a graphical parameter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in title(...): \"numer\" is not a graphical parameter\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n\n```{.r .cell-code}\npacf(residuals(lm_model2),lag.max=30,numer=FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in plot.window(...): \"numer\" is not a graphical parameter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in plot.xy(xy, type, ...): \"numer\" is not a graphical parameter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in axis(side = side, at = at, labels = labels, ...): \"numer\" is not a\ngraphical parameter\nWarning in axis(side = side, at = at, labels = labels, ...): \"numer\" is not a\ngraphical parameter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in box(...): \"numer\" is not a graphical parameter\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in title(...): \"numer\" is not a graphical parameter\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-59-2.png){width=672}\n:::\n:::\n\n\n\n# Modèle mix - MCG - AR\n\non rajoute un terme AR 1\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngls_model1 <- gls(IPA ~ taux_change + petrole + precipitation + exportations, \n                 data = st2_data,  corAR1(form = ~ 1))\nsummary(gls_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized least squares fit by REML\n  Model: IPA ~ taux_change + petrole + precipitation + exportations \n  Data: st2_data \n        AIC       BIC   logLik\n  -1358.525 -1333.336 686.2625\n\nCorrelation Structure: AR(1)\n Formula: ~1 \n Parameter estimate(s):\n      Phi \n0.5772593 \n\nCoefficients:\n                     Value   Std.Error   t-value p-value\n(Intercept)    0.014436953 0.009895293  1.458972  0.1457\ntaux_change    0.023704728 0.008770127  2.702895  0.0073\npetrole        0.000515314 0.000186171  2.767966  0.0060\nprecipitation -0.000085580 0.000059949 -1.427533  0.1546\nexportations   0.000123323 0.000080308  1.535635  0.1258\n\n Correlation: \n              (Intr) tx_chn petrol prcptt\ntaux_change    0.003                     \npetrole        0.057  0.161              \nprecipitation -0.875 -0.047 -0.078       \nexportations  -0.390  0.066  0.019 -0.023\n\nStandardized residuals:\n       Min         Q1        Med         Q3        Max \n-2.4484944 -0.6036554 -0.0997161  0.4664663  3.3688730 \n\nResidual standard error: 0.02178264 \nDegrees of freedom: 275 total; 270 residual\n```\n\n\n:::\n\n```{.r .cell-code}\n# Vérification des résidus\nresiduals_gls_model <- residuals(gls_model1)\npar(mfrow = c(1, 2))\nacf(residuals_gls_model, main = \"ACF des résidus du modèle AR(1)\")\npacf(residuals_gls_model, main = \"PACF des résidus du modèle AR(1)\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncheckresiduals(gls_model1)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-60-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals from REML\nQ* = 144.13, df = 24, p-value < 2.2e-16\n\nModel df: 0.   Total lags used: 24\n```\n\n\n:::\n:::\n\n\n\ngls : La fonction gls permet de spécifier des modèles de régression avec des structures de corrélation spécifiques pour les erreurs. corARMA(p = 1, form = \\~ 1) : Cet argument spécifie que les résidus du modèle doivent suivre un processus AR(1).\n\n## Modèle MCO avec les résidus ajustés avec un modèle AR(1)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# On ajuste le modèle avec base st2 (qui utilise diff_log_IPA) pour obtenir les résidus\nlm_base <- lm(IPA ~ taux_change + petrole + precipitation + exportations, data = st2_data)\nresiduals_base <- residuals(lm_base)\n\n#  modèle AR(1) sur les résidus\nar1_residuals <- arima(residuals_base, order = c(1, 0, 0))\nar1_fitted <- fitted(ar1_residuals)\n\n#  les valeurs ajustées de l'AR(1) comme une nouvelle variable\nst2_data$ar1_fitted <- ar1_fitted\n\n# On reajuste le modèle linéaire en incluant la nouvelle variable\nlm_corrected <- lm(IPA ~ taux_change + petrole + precipitation + exportations + ar1_fitted, data = st2_data)\n\n# Résumé du nouveau modèle\nsummary(lm_corrected)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = IPA ~ taux_change + petrole + precipitation + exportations + \n    ar1_fitted, data = st2_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.048087 -0.011929 -0.001883  0.012298  0.046143 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    2.689e-02  9.236e-03   2.912  0.00390 ** \ntaux_change    3.888e-02  9.192e-03   4.229 3.22e-05 ***\npetrole        5.884e-04  1.906e-04   3.087  0.00224 ** \nprecipitation -1.603e-04  6.000e-05  -2.671  0.00802 ** \nexportations   9.157e-05  4.442e-05   2.062  0.04020 *  \nar1_fitted     1.022e+00  9.654e-02  10.589  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01805 on 269 degrees of freedom\nMultiple R-squared:  0.3681,\tAdjusted R-squared:  0.3564 \nF-statistic: 31.35 on 5 and 269 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Vérification des résidus du modèle corrigé\nresiduals_corrected <- residuals(lm_corrected)\npar(mfrow = c(1, 2))\nacf(residuals_corrected, main = \"ACF des résidus du modèle corrigé\")\npacf(residuals_corrected, main = \"PACF des résidus du modèle corrigé\")\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncheckresiduals(residuals_corrected)\n```\n\n::: {.cell-output-display}\n![](memoire_m1_files/figure-html/unnamed-chunk-61-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLjung-Box test\n\ndata:  Residuals\nQ* = 6.4074, df = 10, p-value = 0.78\n\nModel df: 0.   Total lags used: 10\n```\n\n\n:::\n\n```{.r .cell-code}\n# Tests\nks.test(residuals_corrected, \"pnorm\", mean = mean(residuals_corrected), sd = sd(residuals_corrected))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  residuals_corrected\nD = 0.060107, p-value = 0.2735\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(lm_corrected)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  lm_corrected\nBP = 17.395, df = 5, p-value = 0.003808\n```\n\n\n:::\n\n```{.r .cell-code}\nreset(lm_corrected)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  lm_corrected\nRESET = 5.2333, df1 = 2, df2 = 267, p-value = 0.005897\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(lm_corrected)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  taux_change       petrole precipitation  exportations    ar1_fitted \n     1.107362      1.130431      1.016294      1.005598      1.019534 \n```\n\n\n:::\n:::\n",
    "supporting": [
      "memoire_m1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}