{
  "hash": "6906c9f4a0d0383146a5077cd52cb537",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Économétrie linéaire avancée\"\nsubtitle: \"Analyse du temps d’écran chez les français de plus de 18 ans\"\nauthor: \n  - \"J. DUPAU\"\n  - \"V. Trillaud\"\n  - \"Isabel PALACIO\"\nformat: \n  html:\n    toc: true\n    toc_float: \n      collapsed: false\n      smooth_scroll: true\ndate: \"2024-01\"\neditor: visual\ncategories: [Régression, MCO, Questionnaire]\n---\n\n\n\n\n## Analyse du temps d’écran chez les français de plus de 18 ans\n\n(sur un échantillon de 98 personnes en 2023)\n\n**Résumé**\n\nL’objectif de notre étude est d’identifier les facteurs influençant la consommation numérique hebdomadaire chez les adultes Français, à partir de 18 ans, à l’échelle nationale. Nous avons fait appel à la méthode des moindres carrés (MCO) qui nous a permis d’obtenir un modèle fiable validant toutes les conditions requises pour son application. Pour ce faire, nous avons opté pour l’utilisation d’un jeu de données se rapprochant le plus possible de la réalité. Par conséquent, nous avons directement interrogé la population à l’aide d’un questionnaire se basant sur la modélisation faite au préalable à partir de la littérature. Nous avons obtenu un échantillon non représentatif de 98 individus dû à un ratio femmes/hommes élevé.\n\nLe modèle nous a donné d’une part des résultats attendus. En effet, les personnes ayant une vie sociale importante ou ne travaillant pas toute la journée sur un écran ont une consommation numérique hebdomadaire moindre par rapport aux casaniers et à ceux exerçant un métier pour lequel l’écran est le seul outil de travail. Puis, d’autre part, des résultats inattendus. En effet, une personne possédant un nombre d’appareils moindre a une consommation plus importante que celle ayant plus d’appareils, ou encore les personnes n’ayant pas la fibre passent plus de temps sur les écrans que ceux ayant la fibre.\n\n::: {style=\"text-align: center;\"}\n<iframe src=\"/pdf/econometrie.pdf\" width=\"80%\" height=\"500px\">\n\n</iframe>\n:::\n\nVous avez la possibilité de télécharger le document ici :) [📥 Télécharger le fichier PDF](/pdf/Tutorial.pdf)\n\n\n\n# Présentation du code\n\nJe vous présente ci-dessous, le code utilisé pour mener à bien ce projet, avec les étapes et explications correspondantes.\n\n## Préparation des données\n\n-   Librairies\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({\nlibrary(readxl)\nlibrary(writexl)\nlibrary(outliers)\nlibrary(dplyr)\nlibrary(VIM)\nlibrary(car)\nlibrary(MASS)\nlibrary(ggplot2)\nlibrary(EnvStats)\nlibrary(pander)\nlibrary(corrplot)\nlibrary(PerformanceAnalytics)\nlibrary(tidyverse)\nlibrary(questionr)\nlibrary(leaps)\nlibrary(stats)\nlibrary(lmtest)\nlibrary(AER)\nlibrary(here)\n})  \n```\n:::\n\n\n\n-   Vecteur de couleur\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncouleurs_genre <- c(\"#9DBBA4\", \"#395948\")\ncouleurs <- c(\"#9DBBA4\", \"#395948\")\n```\n:::\n\n\n\n## Préparation et visualisation des données\n\n-   Téléchargement et visualisation du fichier, à l'aide de la librairie \"readxl\"\n-   Supprimer la colonne \"horodateur\" qui est inutile\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran <- read_excel(here(\"data\", \"BDD_propre.xlsx\"))\n\n\nhead(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 21\n  Horodateur          A quelle catégorie d’âge apparten…¹ A quel genre vous id…²\n  <dttm>              <chr>                               <chr>                 \n1 2023-11-30 16:40:29 25 - 49 ans                         Femme                 \n2 2023-11-30 16:54:37 50- 69 ans                          Femme                 \n3 2023-12-01 08:30:35 50- 69 ans                          Femme                 \n4 2023-12-02 14:14:23 50- 69 ans                          Homme                 \n5 2023-12-07 10:21:15 25 - 49 ans                         Femme                 \n6 2023-12-07 11:30:43 70 ans et plus                      Femme                 \n# ℹ abbreviated names: ¹​`A quelle catégorie d’âge appartenez-vous ?`,\n#   ²​`A quel genre vous identifiez-vous ?`\n# ℹ 18 more variables:\n#   `Quelle est votre catégorie socioprofessionnelle ?` <chr>,\n#   `Où habitez-vous ?` <chr>,\n#   `Avec combien de personnes vivez-vous dans votre logement principal ? (Par exemple si vous êtes en couple répondez 1)` <dbl>,\n#   `Quel est votre revenu fiscal après impôt du foyer auquel vous êtes rattaché (par an) ? \\r\\nSi vous dépendez de vos parents mettez celui de vos parents.` <chr>, …\n```\n\n\n:::\n\n```{.r .cell-code}\necran <- ecran[,-1]\n```\n:::\n\n\n\n### Renommer les colonnes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(ecran) <- c(\"age\", \"genre\", \"csp\", \"lieu_de_vie\", \"nb_personnes\", \"revenu\", \"temps_ecran\", \"nb_appareils\", \"internet\", \"fibre\", \"forfait_tel\", \"telephone_pro\", \"ecran_travail\", \"sommeil\", \"stress\", \"loisir\", \"vie_sociale\", \"ecran_jour\", \"reseaux_sociaux\", \"nb_abonnements\")\n```\n:::\n\n\n\n### Mettre en numérique les variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [98 × 20] (S3: tbl_df/tbl/data.frame)\n $ age            : chr [1:98] \"25 - 49 ans\" \"50- 69 ans\" \"50- 69 ans\" \"50- 69 ans\" ...\n $ genre          : chr [1:98] \"Femme\" \"Femme\" \"Femme\" \"Homme\" ...\n $ csp            : chr [1:98] \"Cadres et professions intellectuelles supérieures\" \"Professions intermédiaires\" \"Cadres et professions intellectuelles supérieures\" \"Cadres et professions intellectuelles supérieures\" ...\n $ lieu_de_vie    : chr [1:98] \"Ville\" \"Campagne\" \"Périurbaine/ Banlieue\" \"Ville\" ...\n $ nb_personnes   : num [1:98] 1 2 2 1 5 0 1 3 1 3 ...\n $ revenu         : chr [1:98] \"30 000 - 40 000\" \"40 000 - 50 000\" \"70 000 - 80 000\" \"70 000 - 80 000\" ...\n $ temps_ecran    : num [1:98] 35 35 30 60 64 28 28 35 25 21 ...\n $ nb_appareils   : chr [1:98] \"3\" \"5\" \"4\" \"4\" ...\n $ internet       : chr [1:98] \"Oui, avec la fibre\" \"Oui, avec la fibre\" \"Oui, avec la fibre\" \"Oui, avec la fibre\" ...\n $ fibre          : chr [1:98] \"Oui\" \"Oui\" \"Oui\" \"Oui\" ...\n $ forfait_tel    : chr [1:98] \"10 et 15 €\" \"10 et 15 €\" \"15 et 20 €\" \"0\" ...\n $ telephone_pro  : chr [1:98] \"Oui\" \"Non\" \"Oui\" \"Oui\" ...\n $ ecran_travail  : chr [1:98] \"Toute la journée\" \"Fréquemment (Plus de la moitié du temps)\" \"Fréquemment (Plus de la moitié du temps)\" \"Toute la journée\" ...\n $ sommeil        : chr [1:98] \"5h – 7h\" \"7h et 9h\" \"7h et 9h\" \"5h – 7h\" ...\n $ stress         : chr [1:98] \"Parfois\" \"Parfois\" \"Rarement\" \"Fréquemment\" ...\n $ loisir         : num [1:98] 3 10 1 6 12 2 6 21 30 20 ...\n $ vie_sociale    : num [1:98] 14 15 2 8 8 7 10 20 80 10 ...\n $ ecran_jour     : chr [1:98] \"Le soir\" \"L’après midi\" \"Le matin\" \"Le soir\" ...\n $ reseaux_sociaux: chr [1:98] \"5\" \"2\" \"1\" \"0\" ...\n $ nb_abonnements : chr [1:98] \"0\" \"1\" \"3\" \"0\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\necran$loisir <- as.numeric(ecran$loisir)\necran$vie_sociale <- as.numeric(ecran$vie_sociale)\nstr(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [98 × 20] (S3: tbl_df/tbl/data.frame)\n $ age            : chr [1:98] \"25 - 49 ans\" \"50- 69 ans\" \"50- 69 ans\" \"50- 69 ans\" ...\n $ genre          : chr [1:98] \"Femme\" \"Femme\" \"Femme\" \"Homme\" ...\n $ csp            : chr [1:98] \"Cadres et professions intellectuelles supérieures\" \"Professions intermédiaires\" \"Cadres et professions intellectuelles supérieures\" \"Cadres et professions intellectuelles supérieures\" ...\n $ lieu_de_vie    : chr [1:98] \"Ville\" \"Campagne\" \"Périurbaine/ Banlieue\" \"Ville\" ...\n $ nb_personnes   : num [1:98] 1 2 2 1 5 0 1 3 1 3 ...\n $ revenu         : chr [1:98] \"30 000 - 40 000\" \"40 000 - 50 000\" \"70 000 - 80 000\" \"70 000 - 80 000\" ...\n $ temps_ecran    : num [1:98] 35 35 30 60 64 28 28 35 25 21 ...\n $ nb_appareils   : chr [1:98] \"3\" \"5\" \"4\" \"4\" ...\n $ internet       : chr [1:98] \"Oui, avec la fibre\" \"Oui, avec la fibre\" \"Oui, avec la fibre\" \"Oui, avec la fibre\" ...\n $ fibre          : chr [1:98] \"Oui\" \"Oui\" \"Oui\" \"Oui\" ...\n $ forfait_tel    : chr [1:98] \"10 et 15 €\" \"10 et 15 €\" \"15 et 20 €\" \"0\" ...\n $ telephone_pro  : chr [1:98] \"Oui\" \"Non\" \"Oui\" \"Oui\" ...\n $ ecran_travail  : chr [1:98] \"Toute la journée\" \"Fréquemment (Plus de la moitié du temps)\" \"Fréquemment (Plus de la moitié du temps)\" \"Toute la journée\" ...\n $ sommeil        : chr [1:98] \"5h – 7h\" \"7h et 9h\" \"7h et 9h\" \"5h – 7h\" ...\n $ stress         : chr [1:98] \"Parfois\" \"Parfois\" \"Rarement\" \"Fréquemment\" ...\n $ loisir         : num [1:98] 3 10 1 6 12 2 6 21 30 20 ...\n $ vie_sociale    : num [1:98] 14 15 2 8 8 7 10 20 80 10 ...\n $ ecran_jour     : chr [1:98] \"Le soir\" \"L’après midi\" \"Le matin\" \"Le soir\" ...\n $ reseaux_sociaux: chr [1:98] \"5\" \"2\" \"1\" \"0\" ...\n $ nb_abonnements : chr [1:98] \"0\" \"1\" \"3\" \"0\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     age               genre               csp            lieu_de_vie       \n Length:98          Length:98          Length:98          Length:98         \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  nb_personnes      revenu           temps_ecran    nb_appareils      \n Min.   :0.000   Length:98          Min.   : 4.50   Length:98         \n 1st Qu.:1.000   Class :character   1st Qu.:26.25   Class :character  \n Median :1.000   Mode  :character   Median :35.00   Mode  :character  \n Mean   :1.622                      Mean   :35.76                     \n 3rd Qu.:3.000                      3rd Qu.:42.00                     \n Max.   :5.000                      Max.   :85.00                     \n                                                                      \n   internet            fibre           forfait_tel        telephone_pro     \n Length:98          Length:98          Length:98          Length:98         \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n ecran_travail        sommeil             stress              loisir      \n Length:98          Length:98          Length:98          Min.   :  0.00  \n Class :character   Class :character   Class :character   1st Qu.:  4.00  \n Mode  :character   Mode  :character   Mode  :character   Median : 10.00  \n                                                          Mean   : 12.52  \n                                                          3rd Qu.: 15.00  \n                                                          Max.   :100.00  \n                                                          NA's   :7       \n  vie_sociale     ecran_jour        reseaux_sociaux    nb_abonnements    \n Min.   : 0.00   Length:98          Length:98          Length:98         \n 1st Qu.: 5.00   Class :character   Class :character   Class :character  \n Median :12.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :16.36                                                           \n 3rd Qu.:21.00                                                           \n Max.   :80.00                                                           \n NA's   :13                                                              \n```\n\n\n:::\n:::\n\n\n\n### Mettre en facteurs les variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran$age <- as.factor(ecran$age)\necran$genre <- as.factor(ecran$genre)\necran$csp <- as.factor(ecran$csp)\necran$lieu_de_vie <- as.factor(ecran$lieu_de_vie)\necran$revenu <- as.factor(ecran$revenu)\necran$nb_appareils <- as.factor(ecran$nb_appareils)\necran$internet <- as.factor(ecran$internet)\necran$fibre <- as.factor(ecran$fibre)\necran$forfait_tel <- as.factor(ecran$forfait_tel)\necran$telephone_pro <- as.factor(ecran$telephone_pro)\necran$ecran_travail <- as.factor(ecran$ecran_travail)\necran$sommeil <- as.factor(ecran$sommeil)\necran$stress <- as.factor(ecran$stress)\necran$ecran_jour <- as.factor(ecran$ecran_jour)\necran$reseaux_sociaux <- as.factor(ecran$reseaux_sociaux)\necran$nb_abonnements <- as.factor(ecran$nb_abonnements)\n```\n:::\n\n\n\nRésumé des toutes les variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [98 × 20] (S3: tbl_df/tbl/data.frame)\n $ age            : Factor w/ 4 levels \"18 - 24 ans\",..: 2 3 3 3 2 4 2 2 3 2 ...\n $ genre          : Factor w/ 2 levels \"Femme\",\"Homme\": 1 1 1 2 1 1 1 2 1 2 ...\n $ csp            : Factor w/ 8 levels \"Agriculteurs exploitants\",..: 4 7 4 4 5 8 5 5 5 5 ...\n $ lieu_de_vie    : Factor w/ 3 levels \"Campagne\",\"Périurbaine/ Banlieue\",..: 3 1 2 3 1 1 1 2 1 2 ...\n $ nb_personnes   : num [1:98] 1 2 2 1 5 0 1 3 1 3 ...\n $ revenu         : Factor w/ 9 levels \"< 10 000\",\"10 000 - 20 000\",..: 4 5 8 8 7 2 3 5 4 5 ...\n $ temps_ecran    : num [1:98] 35 35 30 60 64 28 28 35 25 21 ...\n $ nb_appareils   : Factor w/ 11 levels \"1\",\"10\",\"2\",\"3\",..: 4 6 5 5 8 4 4 5 9 7 ...\n $ internet       : Factor w/ 4 levels \"Non\",\"Oui, avec l’ADSL\",..: 3 3 3 3 2 2 3 3 3 3 ...\n $ fibre          : Factor w/ 2 levels \"Non\",\"Oui\": 2 2 2 2 1 2 2 2 2 2 ...\n $ forfait_tel    : Factor w/ 9 levels \"0\",\"10 et 15 €\",..: 2 2 3 1 3 8 4 3 3 5 ...\n $ telephone_pro  : Factor w/ 2 levels \"Non\",\"Oui\": 2 1 2 2 1 1 1 2 1 2 ...\n $ ecran_travail  : Factor w/ 5 levels \"Fréquemment (Plus de la moitié du temps)\",..: 5 1 1 5 5 2 3 3 3 4 ...\n $ sommeil        : Factor w/ 4 levels \"3h – 5h\",\"5h – 7h\",..: 2 3 3 2 3 3 2 3 3 3 ...\n $ stress         : Factor w/ 5 levels \"Fréquemment\",..: 3 3 4 1 1 4 1 4 2 4 ...\n $ loisir         : num [1:98] 3 10 1 6 12 2 6 21 30 20 ...\n $ vie_sociale    : num [1:98] 14 15 2 8 8 7 10 20 80 10 ...\n $ ecran_jour     : Factor w/ 7 levels \"L’après midi\",..: 7 1 3 7 1 7 1 7 1 1 ...\n $ reseaux_sociaux: Factor w/ 11 levels \"0\",\"1\",\"2\",\"3\",..: 6 3 2 1 1 1 2 4 3 3 ...\n $ nb_abonnements : Factor w/ 9 levels \"0\",\"1\",\"10\",\"2\",..: 1 2 5 1 2 2 1 2 2 2 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             age       genre   \n 18 - 24 ans   :47   Femme:72  \n 25 - 49 ans   :38   Homme:26  \n 50- 69 ans    :10             \n 70 ans et plus: 3             \n                               \n                               \n                               \n                                                                                         csp    \n Employés                                                                                  :34  \n Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants):31  \n Cadres et professions intellectuelles supérieures                                         :17  \n Professions intermédiaires                                                                : 6  \n Retraités                                                                                 : 4  \n Ouvriers                                                                                  : 3  \n (Other)                                                                                   : 3  \n                lieu_de_vie  nb_personnes               revenu  \n Campagne             :36   Min.   :0.000   40 000 - 50 000:21  \n Périurbaine/ Banlieue:11   1st Qu.:1.000   20 000 - 30 000:18  \n Ville                :51   Median :1.000   10 000 - 20 000:17  \n                            Mean   :1.622   30 000 - 40 000:12  \n                            3rd Qu.:3.000   < 10 000       :11  \n                            Max.   :5.000   (Other)        :10  \n                                            NA's           : 9  \n  temps_ecran     nb_appareils                         internet   fibre   \n Min.   : 4.50   3      :40    Non                         : 1   Non : 5  \n 1st Qu.:26.25   4      :19    Oui, avec l’ADSL            :17   Oui :84  \n Median :35.00   2      :14    Oui, avec la fibre          :71   NA's: 9  \n Mean   :35.76   5      :10    Oui, avec une autre solution: 9            \n 3rd Qu.:42.00   6      : 5                                               \n Max.   :85.00   7      : 3                                               \n                 (Other): 7                                               \n          forfait_tel telephone_pro\n 15 et 20 €     :35   Non:33       \n 10 et 15 €     :20   Oui:65       \n Plus de 35€    :12                \n 20 et 25 €     :11                \n Entre 5 et 10 €: 6                \n 30 et 35 €     : 5                \n (Other)        : 9                \n                                        ecran_travail       sommeil  \n Fréquemment (Plus de la moitié du temps)      :26    3h – 5h   : 9  \n Jamais                                        : 4    5h – 7h   :32  \n Parfois (Entre un quart et la moitié du temps):17    7h et 9h  :54  \n Rarement                                      :11    Plus de 9h: 3  \n Toute la journée                              :37                   \n NA's                                          : 3                   \n                                                                     \n         stress       loisir        vie_sociale   \n Fréquemment:26   Min.   :  0.00   Min.   : 0.00  \n Jamais     : 2   1st Qu.:  4.00   1st Qu.: 5.00  \n Parfois    :39   Median : 10.00   Median :12.00  \n Rarement   :15   Mean   : 12.52   Mean   :16.36  \n Toujours   :16   3rd Qu.: 15.00   3rd Qu.:21.00  \n                  Max.   :100.00   Max.   :80.00  \n                  NA's   :7        NA's   :13     \n                           ecran_jour reseaux_sociaux nb_abonnements\n L’après midi                   : 9   3      :24      1      :34    \n L’après midi, Le soir          :11   2      :14      2      :22    \n Le matin                       : 5   4      :12      0      :17    \n Le matin, L’après midi         : 7   5      :12      3      :12    \n Le matin, L’après midi, Le soir: 7   6      : 9      4      : 8    \n Le matin, Le soir              : 3   1      : 8      5      : 2    \n Le soir                        :56   (Other):19      (Other): 3    \n```\n\n\n:::\n:::\n\n\n\n### Valeurs manquantes - visualisation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(ecran))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 41\n```\n\n\n:::\n\n```{.r .cell-code}\nlapply(ecran, function(x) which(is.na(x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$age\ninteger(0)\n\n$genre\ninteger(0)\n\n$csp\ninteger(0)\n\n$lieu_de_vie\ninteger(0)\n\n$nb_personnes\ninteger(0)\n\n$revenu\n[1] 22 24 26 33 44 45 54 84 88\n\n$temps_ecran\ninteger(0)\n\n$nb_appareils\ninteger(0)\n\n$internet\ninteger(0)\n\n$fibre\n[1] 19 25 37 49 50 70 73 80 82\n\n$forfait_tel\ninteger(0)\n\n$telephone_pro\ninteger(0)\n\n$ecran_travail\n[1] 42 60 88\n\n$sommeil\ninteger(0)\n\n$stress\ninteger(0)\n\n$loisir\n[1] 14 15 23 47 54 62 64\n\n$vie_sociale\n [1] 14 15 22 43 44 47 51 52 54 60 62 64 67\n\n$ecran_jour\ninteger(0)\n\n$reseaux_sociaux\ninteger(0)\n\n$nb_abonnements\ninteger(0)\n```\n\n\n:::\n:::\n\n\n\nNous avons au total 41 valeurs manquantes\n\nRésumé des variables numériques\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(select_if(ecran, is.numeric))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  nb_personnes    temps_ecran        loisir        vie_sociale   \n Min.   :0.000   Min.   : 4.50   Min.   :  0.00   Min.   : 0.00  \n 1st Qu.:1.000   1st Qu.:26.25   1st Qu.:  4.00   1st Qu.: 5.00  \n Median :1.000   Median :35.00   Median : 10.00   Median :12.00  \n Mean   :1.622   Mean   :35.76   Mean   : 12.52   Mean   :16.36  \n 3rd Qu.:3.000   3rd Qu.:42.00   3rd Qu.: 15.00   3rd Qu.:21.00  \n Max.   :5.000   Max.   :85.00   Max.   :100.00   Max.   :80.00  \n                                 NA's   :7        NA's   :13     \n```\n\n\n:::\n\n```{.r .cell-code}\nsapply(select_if(ecran, is.numeric), sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnb_personnes  temps_ecran       loisir  vie_sociale \n    1.350947    15.699702           NA           NA \n```\n\n\n:::\n:::\n\n\n\n### Imputation des valeurs manquantes\n\nL'algorithme des k-plus proches voisins utilisera le voisin le plus proche pour l'imputation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran <- kNN(ecran, dist_var = colnames(ecran), k = 1)\necran <- ecran[, -c(21:40)]\n```\n:::\n\n\n\n### Exportation de la base de données sous format excel\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# write_xlsx(x = ecran, path = \"data/BDD_sans_NA.xlsx\")\n```\n:::\n\n\n\n# Utilisation de cette nouvelle base pour la suite du travail\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran <- read_excel(here(\"data\", \"BDD_sans_NA.xlsx\"), col_names = T )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(ecran) <- c(\"age\", \"genre\", \"csp\", \"lieu_de_vie\", \"nb_personnes\", \"revenu\", \"temps_ecran\", \"nb_appareils\", \"internet\", \"fibre\", \"forfait_tel\", \"telephone_pro\", \"ecran_travail\", \"sommeil\", \"stress\", \"loisir\", \"vie_sociale\", \"ecran_jour\", \"reseaux_sociaux\", \"nb_abonnements\")\n```\n:::\n\n\n\n## Mettre en facteurs les variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [98 × 20] (S3: tbl_df/tbl/data.frame)\n $ age            : chr [1:98] \"25 - 49 ans\" \"50- 69 ans\" \"50- 69 ans\" \"50- 69 ans\" ...\n $ genre          : chr [1:98] \"Femme\" \"Femme\" \"Femme\" \"Homme\" ...\n $ csp            : chr [1:98] \"Cadres et professions intellectuelles supérieures\" \"Professions intermédiaires\" \"Cadres et professions intellectuelles supérieures\" \"Cadres et professions intellectuelles supérieures\" ...\n $ lieu_de_vie    : chr [1:98] \"Ville\" \"Campagne\" \"Périurbaine/ Banlieue\" \"Ville\" ...\n $ nb_personnes   : num [1:98] 1 2 2 1 5 0 1 3 1 3 ...\n $ revenu         : chr [1:98] \"30 000 - 40 000\" \"40 000 - 50 000\" \"70 000 - 80 000\" \"70 000 - 80 000\" ...\n $ temps_ecran    : num [1:98] 35 35 30 60 64 28 28 35 25 21 ...\n $ nb_appareils   : chr [1:98] \"3\" \"5\" \"4\" \"4\" ...\n $ internet       : chr [1:98] \"Oui, avec la fibre\" \"Oui, avec la fibre\" \"Oui, avec la fibre\" \"Oui, avec la fibre\" ...\n $ fibre          : chr [1:98] \"Oui\" \"Oui\" \"Oui\" \"Oui\" ...\n $ forfait_tel    : chr [1:98] \"10 et 15 €\" \"10 et 15 €\" \"15 et 20 €\" \"0\" ...\n $ telephone_pro  : chr [1:98] \"Oui\" \"Non\" \"Oui\" \"Oui\" ...\n $ ecran_travail  : chr [1:98] \"Toute la journée\" \"Fréquemment (Plus de la moitié du temps)\" \"Fréquemment (Plus de la moitié du temps)\" \"Toute la journée\" ...\n $ sommeil        : chr [1:98] \"5h – 7h\" \"7h et 9h\" \"7h et 9h\" \"5h – 7h\" ...\n $ stress         : chr [1:98] \"Parfois\" \"Parfois\" \"Rarement\" \"Fréquemment\" ...\n $ loisir         : num [1:98] 3 10 1 6 12 2 6 21 30 20 ...\n $ vie_sociale    : num [1:98] 14 15 2 8 8 7 10 20 80 10 ...\n $ ecran_jour     : chr [1:98] \"Le soir\" \"L’après midi\" \"Le matin\" \"Le soir\" ...\n $ reseaux_sociaux: chr [1:98] \"5\" \"2\" \"1\" \"0\" ...\n $ nb_abonnements : chr [1:98] \"0\" \"1\" \"3\" \"0\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\necran$age <- as.factor(ecran$age)\necran$genre <- as.factor(ecran$genre)\necran$csp <- as.factor(ecran$csp)\necran$lieu_de_vie <- as.factor(ecran$lieu_de_vie)\necran$revenu <- as.factor(ecran$revenu)\necran$nb_appareils <- as.factor(ecran$nb_appareils)\necran$internet <- as.factor(ecran$internet)\necran$fibre <- as.factor(ecran$fibre)\necran$forfait_tel <- as.factor(ecran$forfait_tel)\necran$telephone_pro <- as.factor(ecran$telephone_pro)\necran$ecran_travail <- as.factor(ecran$ecran_travail)\necran$sommeil <- as.factor(ecran$sommeil)\necran$stress <- as.factor(ecran$stress)\necran$ecran_jour <- as.factor(ecran$ecran_jour)\necran$reseaux_sociaux <- as.factor(ecran$reseaux_sociaux)\necran$nb_abonnements <- as.factor(ecran$nb_abonnements)\nstr(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [98 × 20] (S3: tbl_df/tbl/data.frame)\n $ age            : Factor w/ 4 levels \"18 - 24 ans\",..: 2 3 3 3 2 4 2 2 3 2 ...\n $ genre          : Factor w/ 2 levels \"Femme\",\"Homme\": 1 1 1 2 1 1 1 2 1 2 ...\n $ csp            : Factor w/ 8 levels \"Agriculteurs exploitants\",..: 4 7 4 4 5 8 5 5 5 5 ...\n $ lieu_de_vie    : Factor w/ 3 levels \"Campagne\",\"Périurbaine/ Banlieue\",..: 3 1 2 3 1 1 1 2 1 2 ...\n $ nb_personnes   : num [1:98] 1 2 2 1 5 0 1 3 1 3 ...\n $ revenu         : Factor w/ 9 levels \"< 10 000\",\"10 000 - 20 000\",..: 4 5 8 8 7 2 3 5 4 5 ...\n $ temps_ecran    : num [1:98] 35 35 30 60 64 28 28 35 25 21 ...\n $ nb_appareils   : Factor w/ 11 levels \"1\",\"10\",\"2\",\"3\",..: 4 6 5 5 8 4 4 5 9 7 ...\n $ internet       : Factor w/ 4 levels \"Non\",\"Oui, avec l’ADSL\",..: 3 3 3 3 2 2 3 3 3 3 ...\n $ fibre          : Factor w/ 2 levels \"Non\",\"Oui\": 2 2 2 2 1 2 2 2 2 2 ...\n $ forfait_tel    : Factor w/ 9 levels \"0\",\"10 et 15 €\",..: 2 2 3 1 3 8 4 3 3 5 ...\n $ telephone_pro  : Factor w/ 2 levels \"Non\",\"Oui\": 2 1 2 2 1 1 1 2 1 2 ...\n $ ecran_travail  : Factor w/ 5 levels \"Fréquemment (Plus de la moitié du temps)\",..: 5 1 1 5 5 2 3 3 3 4 ...\n $ sommeil        : Factor w/ 4 levels \"3h – 5h\",\"5h – 7h\",..: 2 3 3 2 3 3 2 3 3 3 ...\n $ stress         : Factor w/ 5 levels \"Fréquemment\",..: 3 3 4 1 1 4 1 4 2 4 ...\n $ loisir         : num [1:98] 3 10 1 6 12 2 6 21 30 20 ...\n $ vie_sociale    : num [1:98] 14 15 2 8 8 7 10 20 80 10 ...\n $ ecran_jour     : Factor w/ 7 levels \"L’après midi\",..: 7 1 3 7 1 7 1 7 1 1 ...\n $ reseaux_sociaux: Factor w/ 11 levels \"0\",\"1\",\"2\",\"3\",..: 6 3 2 1 1 1 2 4 3 3 ...\n $ nb_abonnements : Factor w/ 9 levels \"0\",\"1\",\"10\",\"2\",..: 1 2 5 1 2 2 1 2 2 2 ...\n```\n\n\n:::\n:::\n\n\n\n# Statistiques descriptives\n\n### Analyse univariée des variables qualitatives\n\n#### Tableaux de contingence\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ecran$genre,ecran$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       \n        18 - 24 ans 25 - 49 ans 50- 69 ans 70 ans et plus\n  Femme          36          28          7              1\n  Homme          11          10          3              2\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(ecran$csp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n                                                                  Agriculteurs exploitants \n                                                                                         1 \n                                                      Artisan/commerçant/Chef d’entreprise \n                                                                                         2 \nAutres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants) \n                                                                                        31 \n                                         Cadres et professions intellectuelles supérieures \n                                                                                        17 \n                                                                                  Employés \n                                                                                        34 \n                                                                                  Ouvriers \n                                                                                         3 \n                                                                Professions intermédiaires \n                                                                                         6 \n                                                                                 Retraités \n                                                                                         4 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(ecran$csp, ecran$revenu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                                            \n                                                                                             < 10 000\n  Agriculteurs exploitants                                                                          1\n  Artisan/commerçant/Chef d’entreprise                                                              0\n  Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)        4\n  Cadres et professions intellectuelles supérieures                                                 0\n  Employés                                                                                          6\n  Ouvriers                                                                                          0\n  Professions intermédiaires                                                                        0\n  Retraités                                                                                         0\n                                                                                            \n                                                                                             10 000 - 20 000\n  Agriculteurs exploitants                                                                                 0\n  Artisan/commerçant/Chef d’entreprise                                                                     0\n  Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)               5\n  Cadres et professions intellectuelles supérieures                                                        0\n  Employés                                                                                                 7\n  Ouvriers                                                                                                 0\n  Professions intermédiaires                                                                               4\n  Retraités                                                                                                1\n                                                                                            \n                                                                                             20 000 - 30 000\n  Agriculteurs exploitants                                                                                 0\n  Artisan/commerçant/Chef d’entreprise                                                                     0\n  Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)               6\n  Cadres et professions intellectuelles supérieures                                                        4\n  Employés                                                                                                 9\n  Ouvriers                                                                                                 1\n  Professions intermédiaires                                                                               0\n  Retraités                                                                                                2\n                                                                                            \n                                                                                             30 000 - 40 000\n  Agriculteurs exploitants                                                                                 0\n  Artisan/commerçant/Chef d’entreprise                                                                     1\n  Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)               1\n  Cadres et professions intellectuelles supérieures                                                        2\n  Employés                                                                                                 8\n  Ouvriers                                                                                                 0\n  Professions intermédiaires                                                                               0\n  Retraités                                                                                                0\n                                                                                            \n                                                                                             40 000 - 50 000\n  Agriculteurs exploitants                                                                                 0\n  Artisan/commerçant/Chef d’entreprise                                                                     1\n  Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)              11\n  Cadres et professions intellectuelles supérieures                                                        8\n  Employés                                                                                                 3\n  Ouvriers                                                                                                 2\n  Professions intermédiaires                                                                               1\n  Retraités                                                                                                0\n                                                                                            \n                                                                                             50 000 - 60 000\n  Agriculteurs exploitants                                                                                 0\n  Artisan/commerçant/Chef d’entreprise                                                                     0\n  Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)               1\n  Cadres et professions intellectuelles supérieures                                                        1\n  Employés                                                                                                 0\n  Ouvriers                                                                                                 0\n  Professions intermédiaires                                                                               1\n  Retraités                                                                                                0\n                                                                                            \n                                                                                             60 000 - 70 000\n  Agriculteurs exploitants                                                                                 0\n  Artisan/commerçant/Chef d’entreprise                                                                     0\n  Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)               0\n  Cadres et professions intellectuelles supérieures                                                        0\n  Employés                                                                                                 1\n  Ouvriers                                                                                                 0\n  Professions intermédiaires                                                                               0\n  Retraités                                                                                                1\n                                                                                            \n                                                                                             70 000 - 80 000\n  Agriculteurs exploitants                                                                                 0\n  Artisan/commerçant/Chef d’entreprise                                                                     0\n  Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)               2\n  Cadres et professions intellectuelles supérieures                                                        2\n  Employés                                                                                                 0\n  Ouvriers                                                                                                 0\n  Professions intermédiaires                                                                               0\n  Retraités                                                                                                0\n                                                                                            \n                                                                                             80 000 et plus\n  Agriculteurs exploitants                                                                                0\n  Artisan/commerçant/Chef d’entreprise                                                                    0\n  Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)              1\n  Cadres et professions intellectuelles supérieures                                                       0\n  Employés                                                                                                0\n  Ouvriers                                                                                                0\n  Professions intermédiaires                                                                              0\n  Retraités                                                                                               0\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(ecran$revenu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       < 10 000 10 000 - 20 000 20 000 - 30 000 30 000 - 40 000 40 000 - 50 000 \n             11              17              22              12              26 \n50 000 - 60 000 60 000 - 70 000 70 000 - 80 000  80 000 et plus \n              3               2               4               1 \n```\n\n\n:::\n:::\n\n\n\n#### Diagrammes en bâtons\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot() +\n  aes(x = age, fill = age) +\n  geom_bar(fill = \"#395948\") +\n  ggtitle(\"Répartition de l'âge\") +\n  labs(x = \"âge\", y=\"effectif\") +\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  count(genre) |>\n  ggplot() +\n  aes(x = \"\", y = n, fill = genre) +\n  geom_bar(stat = \"identity\", color=\"white\") +\n  ggtitle(\"\") +\n  theme(plot.title = element_text(hjust = 0.5, size = 12))+\n  coord_polar(\"y\") +\n  scale_fill_manual(values = couleurs_genre) +\n  theme_void() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12))+\n  geom_text(aes(label = n), position = position_stack(vjust = 0.5), color = \"white\",size = 5, fontface = \"bold\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot() +\n  geom_bar(fill = \"#395948\") +\n  ggtitle(\"Répartition des lieux de résidence\") +\n  aes(x = fct_infreq(lieu_de_vie), fill = lieu_de_vie) +\n  labs(x = \"lieux de résidence\",y=\"effectif\") +\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12)) \n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\nNous utilisons 'levels' pour renommer nos variables afin d'améliorer la visualisation. Cependant, il est important de noter que cela modifie également les noms dans la base de données\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#levels(ecran$csp) <- c(\"agriculteurs\",\"artisans\",\"sans activité\", \"cadres\",\"employés\",\"ouvriers\", \"intermédiaire\",\"retraités\")\necran |>\n  ggplot() +\n  aes(x =fct_infreq(csp), fill = csp) +\n  geom_bar(fill = \"blue4\") +\n  ggtitle(\"Répartition de la catégorie socio-professionnelle\") +\n  labs(x = \"csp\", y=\"effectif\") +\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12), \n        axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot() +\n  geom_bar(fill = \"blue4\") +\n  ggtitle(\"Répartition du revenu\") +\n  aes(x = fct_infreq(revenu), fill = revenu) +\n  labs(x = \"Revenu\", y=\"effectif\") +\n  theme_classic() + \n  theme(plot.title = element_text(hjust = 0.5, size = 12),\n         axis.text.x = element_text(angle = 45, hjust = 1)) \n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#levels(ecran$internet) <- c(\"Non\",\"ADSL\",\"Fibre\", \"Autre solution\")\necran |>\n  ggplot(aes(x = internet, fill = internet)) +\n  geom_bar(fill = \"#395948\") +\n  ggtitle(\"Répartition des moyens de connexion\") +\n  aes(x = fct_infreq(internet), fill = internet) +\n  labs(x = \"internet\", y=\"effectif\") +\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot(aes(x = fct_infreq(nb_appareils), fill = nb_appareils)) +\n  geom_bar(fill = \"blue4\") +\n  ggtitle(\"Répartition du nombre d'appareils\") +\n  labs(x = \"appareils\", y=\"effectif\") +\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12)) \n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  count(fibre) |>\n  ggplot() +\n  aes(x = \"\", y = n, fill = fibre) +\n  geom_bar(stat = \"identity\", color = \"white\") +\n  ggtitle(\"Répartition de l'accès à la fibre\") +\n  coord_polar(\"y\") +\n  scale_fill_manual(values = couleurs) +\n  theme_void() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12))+\n  geom_text(aes(label = n), position = position_stack(vjust = 0.5), color = \"white\",size = 5, fontface = \"bold\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot(aes(x = fct_infreq(forfait_tel), fill = forfait_tel)) +\n  geom_bar(fill = \"blue4\") +\n  ggtitle(\"Répartition des forfaits téléphoniques\") +\n  labs(x = \"forfait\", y=\"effectif\")+\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12),\n         axis.text.x = element_text(angle = 45, hjust = 1)) \n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  count(telephone_pro) |>\n  ggplot() +\n  aes(x = \"\", y = n, fill = telephone_pro) +\n  geom_bar(stat = \"identity\", color = \"white\") +\n  ggtitle(\"Répartition de la possession d'un téléphone professionnel\") +\n  coord_polar(\"y\") +\n  scale_fill_manual(values = couleurs) +\n  theme_void() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12))+\n   geom_text(aes(label = n), position = position_stack(vjust = 0.5), color = \"white\",size = 5, fontface = \"bold\") \n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#levels(ecran$ecran_travail) <- c(\"Fréquemment\", \"Jamais\", \"Parfois\", \"Rarement\", \"Toute la journée\")\n\necran |>\n  ggplot(aes(x = fct_infreq(ecran_travail), fill = ecran_travail)) +\n  geom_bar(fill = \"blue4\") +\n  ggtitle(\"Répartition de la consommation numérique au travail\") +\n  labs(x=\"fréquence\",y=\"effectif\")+\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot(aes(x = fct_infreq(sommeil), fill = sommeil)) +\n  geom_bar(fill = \"blue4\") +\n  ggtitle(\"Répartition du temps de sommeil\") +\n  labs(x=\"durée\",y=\"effectif\")+\n  theme_classic()+\n  theme(plot.title = element_text(hjust = 0.5, size = 12))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot(aes(x = fct_infreq(stress), fill = stress)) +\n  geom_bar(fill = \"blue4\") +\n  labs(x=\"fréquence\", y=\"effectif\")+\n  ggtitle(\"Répartition du stress\") +\n  theme_classic()+\n  theme(plot.title = element_text(hjust = 0.5, size = 12))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot(aes(x = fct_infreq(ecran_jour), fill = ecran_jour)) +\n  geom_bar(fill = \"blue4\") +\n  ggtitle(\"Répartition du moment de la journée\") +\n  labs(x=\"fréquence\", y=\"effectif\")+\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12),\n          axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot(aes(x = fct_infreq(reseaux_sociaux), fill = reseaux_sociaux)) +\n  geom_bar(fill = \"blue4\") +\n  ggtitle(\"Répartition des réseaux sociaux\") +\n  labs(x=\"quantité\",y=\"effectif\")+\n  theme_classic()+\n  theme(plot.title = element_text(hjust = 0.5, size = 12))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran |>\n  ggplot(aes(x = fct_infreq(nb_abonnements), fill = nb_abonnements)) +\n  geom_bar(fill = \"blue4\") +\n  ggtitle(\"Répartition des abonnements\") +\n  labs(x=\"quantité\", y=\"effectif\")+\n  theme_classic() +\n  theme(plot.title = element_text(hjust = 0.5, size = 12))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\n### Analyse bivariée des variables qualitatives\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran|>\npivot_longer(\ncols = temps_ecran,\nnames_to = \"mesure\",\nvalues_to = \"valeur\"\n) |>\nggplot() +\naes(y = valeur, x = age, color = age) +\ngeom_boxplot() +\ngeom_jitter(alpha = 0.3) +\n#scale_color_manual(values = vecteur_couleur)\nfacet_wrap(~ mesure, scales = \"free_y\") +\ntheme_bw()\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n\n```{.r .cell-code}\necran|>\npivot_longer(\ncols = temps_ecran,\nnames_to = \"mesure\",\nvalues_to = \"valeur\"\n) |>\nggplot() +\naes(y = valeur, x = csp, color=csp) +\ngeom_boxplot() +\ngeom_jitter(alpha = 0.3) +\n#scale_color_manual(values = vecteur_couleur)\nfacet_wrap(~ mesure, scales = \"free_y\") +\ntheme_bw() +\ntheme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-32-2.png){width=672}\n:::\n\n```{.r .cell-code}\necran|>\npivot_longer(\ncols = temps_ecran,\nnames_to = \"mesure\",\nvalues_to = \"valeur\"\n) |>\nggplot() +\naes(y = valeur, x = ecran_jour, color=ecran_jour) +\ngeom_boxplot() +\ngeom_jitter(alpha = 0.3) +\n#scale_color_manual(values = vecteur_couleur)\nfacet_wrap(~ mesure, scales = \"free_y\") +\ntheme_bw() +\ntheme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-32-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(ecran) +\n    geom_boxplot(aes(x = csp, y = temps_ecran))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-32-4.png){width=672}\n:::\n:::\n\n\n\n### Analyse univariée des variables quantitatives\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [98 × 20] (S3: tbl_df/tbl/data.frame)\n $ age            : Factor w/ 4 levels \"18 - 24 ans\",..: 2 3 3 3 2 4 2 2 3 2 ...\n $ genre          : Factor w/ 2 levels \"Femme\",\"Homme\": 1 1 1 2 1 1 1 2 1 2 ...\n $ csp            : Factor w/ 8 levels \"Agriculteurs exploitants\",..: 4 7 4 4 5 8 5 5 5 5 ...\n $ lieu_de_vie    : Factor w/ 3 levels \"Campagne\",\"Périurbaine/ Banlieue\",..: 3 1 2 3 1 1 1 2 1 2 ...\n $ nb_personnes   : num [1:98] 1 2 2 1 5 0 1 3 1 3 ...\n $ revenu         : Factor w/ 9 levels \"< 10 000\",\"10 000 - 20 000\",..: 4 5 8 8 7 2 3 5 4 5 ...\n $ temps_ecran    : num [1:98] 35 35 30 60 64 28 28 35 25 21 ...\n $ nb_appareils   : Factor w/ 11 levels \"1\",\"10\",\"2\",\"3\",..: 4 6 5 5 8 4 4 5 9 7 ...\n $ internet       : Factor w/ 4 levels \"Non\",\"Oui, avec l’ADSL\",..: 3 3 3 3 2 2 3 3 3 3 ...\n $ fibre          : Factor w/ 2 levels \"Non\",\"Oui\": 2 2 2 2 1 2 2 2 2 2 ...\n $ forfait_tel    : Factor w/ 9 levels \"0\",\"10 et 15 €\",..: 2 2 3 1 3 8 4 3 3 5 ...\n $ telephone_pro  : Factor w/ 2 levels \"Non\",\"Oui\": 2 1 2 2 1 1 1 2 1 2 ...\n $ ecran_travail  : Factor w/ 5 levels \"Fréquemment (Plus de la moitié du temps)\",..: 5 1 1 5 5 2 3 3 3 4 ...\n $ sommeil        : Factor w/ 4 levels \"3h – 5h\",\"5h – 7h\",..: 2 3 3 2 3 3 2 3 3 3 ...\n $ stress         : Factor w/ 5 levels \"Fréquemment\",..: 3 3 4 1 1 4 1 4 2 4 ...\n $ loisir         : num [1:98] 3 10 1 6 12 2 6 21 30 20 ...\n $ vie_sociale    : num [1:98] 14 15 2 8 8 7 10 20 80 10 ...\n $ ecran_jour     : Factor w/ 7 levels \"L’après midi\",..: 7 1 3 7 1 7 1 7 1 1 ...\n $ reseaux_sociaux: Factor w/ 11 levels \"0\",\"1\",\"2\",\"3\",..: 6 3 2 1 1 1 2 4 3 3 ...\n $ nb_abonnements : Factor w/ 9 levels \"0\",\"1\",\"10\",\"2\",..: 1 2 5 1 2 2 1 2 2 2 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(select_if(ecran, is.numeric))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  nb_personnes    temps_ecran        loisir        vie_sociale   \n Min.   :0.000   Min.   : 4.50   Min.   :  0.00   Min.   : 0.00  \n 1st Qu.:1.000   1st Qu.:26.25   1st Qu.:  4.00   1st Qu.: 5.00  \n Median :1.000   Median :35.00   Median : 10.00   Median :10.00  \n Mean   :1.622   Mean   :35.76   Mean   : 12.85   Mean   :15.78  \n 3rd Qu.:3.000   3rd Qu.:42.00   3rd Qu.: 17.25   3rd Qu.:20.75  \n Max.   :5.000   Max.   :85.00   Max.   :100.00   Max.   :80.00  \n```\n\n\n:::\n:::\n\n\n\n#### Histogrammes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(ecran$nb_personnes, main= \"Répartition du nombre de personnes dans le foyer\", xlab=\"personnes\", ylab = \"nombre d'individus\", col = \"#395948\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(ecran$temps_ecran, main= \"Répartition du temps d'écrans\", xlab=\"durée\",ylab = \"nombre d'individus\", col = \"#395948\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-34-2.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(ecran$loisir, main= \"Répartition du temps consacré aux loisirs\", xlab=\"durée\", ylab = \"nombre d'individus\", col = \"#395948\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-34-3.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(ecran$vie_sociale, main= \"Répartition du temps consacré à la vie sociale\", xlab=\"durée\",ylab = \"nombre d'individus\", col = \"#395948\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-34-4.png){width=672}\n:::\n:::\n\n\n\n#### Boxplots\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran|>\npivot_longer(\ncols = where(is.numeric)\n) |>\nggplot() +\naes(y = value) +\nfacet_wrap(~ name, scales = \"free_y\") +\ngeom_boxplot() +\ntheme_light()\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n\n### Valeurs atypiques - Test Rosner\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrosnerTest(ecran$temps_ecran,k=2, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            ecran$temps_ecran\n\nSample Size:                     98\n\nTest Statistics:                 R.1 = 3.136677\n                                 R.2 = 2.324461\n\nTest Statistic Parameter:        k = 2\n\nAlternative Hypothesis:          Up to 2 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     0\n\n  i   Mean.i     SD.i Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1 0 35.75510 15.69970    85      64 3.136677   3.377176   FALSE\n2 1 35.24742 14.95081    70      21 2.324461   3.373658   FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nrosnerTest(ecran$loisir,k=2, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            ecran$loisir\n\nSample Size:                     98\n\nTest Statistics:                 R.1 = 6.501007\n                                 R.2 = 4.368825\n\nTest Statistic Parameter:        k = 2\n\nAlternative Hypothesis:          Up to 2 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     2\n\n  i   Mean.i     SD.i Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1 0 12.85204 13.40530   100      61 6.501007   3.377176    TRUE\n2 1 11.95361 10.08198    56      34 4.368825   3.373658    TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nrosnerTest(ecran$vie_sociale,k=5, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            ecran$vie_sociale\n\nSample Size:                     98\n\nTest Statistics:                 R.1 = 4.546626\n                                 R.2 = 2.773623\n                                 R.3 = 2.908100\n                                 R.4 = 2.892232\n                                 R.5 = 2.778605\n\nTest Statistic Parameter:        k = 5\n\nAlternative Hypothesis:          Up to 5 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     1\n\n  i   Mean.i     SD.i Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1 0 15.77551 14.12575    80       9 4.546626   3.377176    TRUE\n2 1 15.11340 12.57799    50      79 2.773623   3.373658   FALSE\n3 2 14.75000 12.12132    50      90 2.908100   3.370097   FALSE\n4 3 14.37895 11.62461    48      75 2.892232   3.366490   FALSE\n5 4 14.02128 11.14902    45      48 2.778605   3.362836   FALSE\n```\n\n\n:::\n:::\n\n\n\nD'apres le test de Rosner nous avons 2 valeurs atypiques dans la variable \"loisir\" et 1 valeur atypique dans la variable \"vie_sociale\". Les observations 80, 61 et 34 sont donc des valeurs atypiques\n\n#### Supprimer les valeurs atypiques\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran <- ecran[-c(9, 61, 34),]\ndim(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 95 20\n```\n\n\n:::\n:::\n\n\n\n# Statistiques descriptives sans les valeurs atypiques\n\n## Analyse univariée des variables quantitatives\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [95 × 20] (S3: tbl_df/tbl/data.frame)\n $ age            : Factor w/ 4 levels \"18 - 24 ans\",..: 2 3 3 3 2 4 2 2 2 2 ...\n $ genre          : Factor w/ 2 levels \"Femme\",\"Homme\": 1 1 1 2 1 1 1 2 2 1 ...\n $ csp            : Factor w/ 8 levels \"Agriculteurs exploitants\",..: 4 7 4 4 5 8 5 5 5 2 ...\n $ lieu_de_vie    : Factor w/ 3 levels \"Campagne\",\"Périurbaine/ Banlieue\",..: 3 1 2 3 1 1 1 2 2 3 ...\n $ nb_personnes   : num [1:95] 1 2 2 1 5 0 1 3 3 1 ...\n $ revenu         : Factor w/ 9 levels \"< 10 000\",\"10 000 - 20 000\",..: 4 5 8 8 7 2 3 5 5 4 ...\n $ temps_ecran    : num [1:95] 35 35 30 60 64 28 28 35 21 60 ...\n $ nb_appareils   : Factor w/ 11 levels \"1\",\"10\",\"2\",\"3\",..: 4 6 5 5 8 4 4 5 7 5 ...\n $ internet       : Factor w/ 4 levels \"Non\",\"Oui, avec l’ADSL\",..: 3 3 3 3 2 2 3 3 3 3 ...\n $ fibre          : Factor w/ 2 levels \"Non\",\"Oui\": 2 2 2 2 1 2 2 2 2 2 ...\n $ forfait_tel    : Factor w/ 9 levels \"0\",\"10 et 15 €\",..: 2 2 3 1 3 8 4 3 5 3 ...\n $ telephone_pro  : Factor w/ 2 levels \"Non\",\"Oui\": 2 1 2 2 1 1 1 2 2 2 ...\n $ ecran_travail  : Factor w/ 5 levels \"Fréquemment (Plus de la moitié du temps)\",..: 5 1 1 5 5 2 3 3 4 5 ...\n $ sommeil        : Factor w/ 4 levels \"3h – 5h\",\"5h – 7h\",..: 2 3 3 2 3 3 2 3 3 1 ...\n $ stress         : Factor w/ 5 levels \"Fréquemment\",..: 3 3 4 1 1 4 1 4 4 5 ...\n $ loisir         : num [1:95] 3 10 1 6 12 2 6 21 20 4 ...\n $ vie_sociale    : num [1:95] 14 15 2 8 8 7 10 20 10 14 ...\n $ ecran_jour     : Factor w/ 7 levels \"L’après midi\",..: 7 1 3 7 1 7 1 7 1 4 ...\n $ reseaux_sociaux: Factor w/ 11 levels \"0\",\"1\",\"2\",\"3\",..: 6 3 2 1 1 1 2 4 3 7 ...\n $ nb_abonnements : Factor w/ 9 levels \"0\",\"1\",\"10\",\"2\",..: 1 2 5 1 2 2 1 2 2 5 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             age       genre   \n 18 - 24 ans   :45   Femme:70  \n 25 - 49 ans   :38   Homme:25  \n 50- 69 ans    : 9             \n 70 ans et plus: 3             \n                               \n                               \n                               \n                                                                                         csp    \n Employés                                                                                  :33  \n Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants):29  \n Cadres et professions intellectuelles supérieures                                         :17  \n Professions intermédiaires                                                                : 6  \n Retraités                                                                                 : 4  \n Ouvriers                                                                                  : 3  \n (Other)                                                                                   : 3  \n                lieu_de_vie  nb_personnes               revenu  \n Campagne             :35   Min.   :0.000   40 000 - 50 000:26  \n Périurbaine/ Banlieue:11   1st Qu.:1.000   20 000 - 30 000:22  \n Ville                :49   Median :1.000   10 000 - 20 000:17  \n                            Mean   :1.663   < 10 000       :11  \n                            3rd Qu.:3.000   30 000 - 40 000:10  \n                            Max.   :5.000   50 000 - 60 000: 3  \n                                            (Other)        : 6  \n  temps_ecran     nb_appareils                         internet  fibre   \n Min.   : 4.50   3      :39    Non                         : 1   Non: 6  \n 1st Qu.:26.50   4      :18    Oui, avec l’ADSL            :17   Oui:89  \n Median :35.00   2      :14    Oui, avec la fibre          :68           \n Mean   :35.88   5      :10    Oui, avec une autre solution: 9           \n 3rd Qu.:45.00   6      : 5                                              \n Max.   :85.00   7      : 3                                              \n                 (Other): 6                                              \n          forfait_tel telephone_pro\n 15 et 20 €     :34   Non:32       \n 10 et 15 €     :20   Oui:63       \n Plus de 35€    :11                \n 20 et 25 €     :10                \n Entre 5 et 10 €: 6                \n 30 et 35 €     : 5                \n (Other)        : 9                \n                                        ecran_travail       sommeil  \n Fréquemment (Plus de la moitié du temps)      :25    3h – 5h   : 9  \n Jamais                                        : 4    5h – 7h   :32  \n Parfois (Entre un quart et la moitié du temps):16    7h et 9h  :51  \n Rarement                                      :12    Plus de 9h: 3  \n Toute la journée                              :38                   \n                                                                     \n                                                                     \n         stress       loisir      vie_sociale   \n Fréquemment:26   Min.   : 0.0   Min.   : 0.00  \n Jamais     : 1   1st Qu.: 4.0   1st Qu.: 5.00  \n Parfois    :38   Median :10.0   Median :10.00  \n Rarement   :15   Mean   :11.3   Mean   :15.12  \n Toujours   :15   3rd Qu.:15.0   3rd Qu.:20.50  \n                  Max.   :42.0   Max.   :50.00  \n                                                \n                           ecran_jour reseaux_sociaux nb_abonnements\n L’après midi                   : 8   3      :24      1      :33    \n L’après midi, Le soir          :10   2      :13      2      :21    \n Le matin                       : 5   5      :12      0      :17    \n Le matin, L’après midi         : 7   4      :11      3      :12    \n Le matin, L’après midi, Le soir: 7   6      : 9      4      : 8    \n Le matin, Le soir              : 3   1      : 8      5      : 2    \n Le soir                        :55   (Other):18      (Other): 2    \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(select_if(ecran, is.numeric))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  nb_personnes    temps_ecran        loisir      vie_sociale   \n Min.   :0.000   Min.   : 4.50   Min.   : 0.0   Min.   : 0.00  \n 1st Qu.:1.000   1st Qu.:26.50   1st Qu.: 4.0   1st Qu.: 5.00  \n Median :1.000   Median :35.00   Median :10.0   Median :10.00  \n Mean   :1.663   Mean   :35.88   Mean   :11.3   Mean   :15.12  \n 3rd Qu.:3.000   3rd Qu.:45.00   3rd Qu.:15.0   3rd Qu.:20.50  \n Max.   :5.000   Max.   :85.00   Max.   :42.0   Max.   :50.00  \n```\n\n\n:::\n:::\n\n\n\n### Histogrammes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2,2))\nhist(ecran$nb_personnes, main= \"Répartition du nombre de personnes dans le foyer\", xlab=\"personnes\",ylab = \"nombre d'individus\", col = \"blue4\")\nhist(ecran$temps_ecran, main= \"Répartition du temps d'écrans\", xlab=\"durée\", ylab = \"nombre d'individus\", col = \"blue4\")\nhist(ecran$loisir, main= \"Répartition du temps consacré aux loisirs\", xlab=\"durée\", ylab = \"nombre d'individus\", col = \"blue4\")\nhist(ecran$vie_sociale, main= \"Répartition du temps consacré à la vie sociale\", xlab=\"durée\",ylab = \"nombre d'individus\", col = \"blue4\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n\n## Analyse bivariée des variables quantitatives\n\nNous observons à l'aide de nuages de points le lien entre \"temps_ecran\" (y) et les variables explicatives\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2,2))\npurrr::map2(\n.x = c(\"nb_personnes\", \"loisir\", \"vie_sociale\"),\n.y = c(\"temps_ecran\", \"temps_ecran\", \"temps_ecran\"),\n.f = ~ ggplot(ecran) +\naes(x = get(.x), y = get(.y)) +\ngeom_point() +\nlabs(x = .x, y = .y) +\nggtitle(paste(\"Corrélation entre\", .x, \"et\", .y)) +\ntheme_classic() +\ntheme(plot.title = element_text(hjust = 0.5, size = 12, face=\"bold\"))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-40-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[3]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-40-3.png){width=672}\n:::\n:::\n\n\n\n### Correlation\n\nSous forme de matrice :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmydata <- ecran[,c(\"nb_personnes\",\"temps_ecran\",\"loisir\",\"vie_sociale\")]\ncorr_mat=cor(mydata,method=\"s\")\ncorr_mat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             nb_personnes temps_ecran     loisir vie_sociale\nnb_personnes   1.00000000  0.04474111 -0.0634830  0.08655831\ntemps_ecran    0.04474111  1.00000000 -0.2013519 -0.07046714\nloisir        -0.06348300 -0.20135191  1.0000000  0.44449510\nvie_sociale    0.08655831 -0.07046714  0.4444951  1.00000000\n```\n\n\n:::\n\n```{.r .cell-code}\ncorrplot(corr_mat, method = 'number',type=\"upper\", tl.srt=45)\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncorrplot(corr_mat,type=\"upper\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-41-2.png){width=672}\n:::\n:::\n\n\n\nNous pouvons voir que la corrélation est très faible entre chaque variable explicative.De plus, la variable à expliquer a une corrélation négative avec les variables \"loisir\" et \"vie_sociale\" et positive avec la variable \"nb_personnes\".\n\n-   Test de normalité des variables numeriques :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nks.test(ecran$nb_personnes,\"pnorm\",mean(ecran$nb_personnes),sd(ecran$nb_personnes))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in ks.test.default(ecran$nb_personnes, \"pnorm\",\nmean(ecran$nb_personnes), : ties should not be present for the\nKolmogorov-Smirnov test\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  ecran$nb_personnes\nD = 0.24631, p-value = 1.972e-05\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nks.test(ecran$loisir,\"pnorm\",mean(ecran$loisir),sd(ecran$loisir))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in ks.test.default(ecran$loisir, \"pnorm\", mean(ecran$loisir),\nsd(ecran$loisir)): ties should not be present for the Kolmogorov-Smirnov test\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  ecran$loisir\nD = 0.15804, p-value = 0.01738\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nks.test(ecran$vie_sociale,\"pnorm\",mean(ecran$vie_sociale),sd(ecran$vie_sociale))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in ks.test.default(ecran$vie_sociale, \"pnorm\", mean(ecran$vie_sociale),\n: ties should not be present for the Kolmogorov-Smirnov test\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  ecran$vie_sociale\nD = 0.18785, p-value = 0.00245\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n\nLes variables ne suivent pas la loi normale , on va donc utiliser le coefficient de Spearman\n\nSous forme de tableau :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(ecran[,c(\"nb_personnes\",\"temps_ecran\",\"loisir\",\"vie_sociale\")],\n    use=\"complete.obs\",method = c(\"spearman\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             nb_personnes temps_ecran     loisir vie_sociale\nnb_personnes   1.00000000  0.04474111 -0.0634830  0.08655831\ntemps_ecran    0.04474111  1.00000000 -0.2013519 -0.07046714\nloisir        -0.06348300 -0.20135191  1.0000000  0.44449510\nvie_sociale    0.08655831 -0.07046714  0.4444951  1.00000000\n```\n\n\n:::\n:::\n\n\n\nPour avoir un aperçu visuel, nous utilisons une matrice de corrélation complétée par les nuages de points et les histogrammes.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#chart.Correlation(mydata, histogram=TRUE, pch=19,method = c(\"spearman\"))\n```\n:::\n\n\n\n-   Conclusion : Pas de corrélation entre ces variables explicatives donc nous allons les conserver.\n\n# Catégories\n\nPour avoir un nombre de variables correctes et pas démesurés ; Création ecran2\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran2 <- ecran\nsummary(ecran2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             age       genre   \n 18 - 24 ans   :45   Femme:70  \n 25 - 49 ans   :38   Homme:25  \n 50- 69 ans    : 9             \n 70 ans et plus: 3             \n                               \n                               \n                               \n                                                                                         csp    \n Employés                                                                                  :33  \n Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants):29  \n Cadres et professions intellectuelles supérieures                                         :17  \n Professions intermédiaires                                                                : 6  \n Retraités                                                                                 : 4  \n Ouvriers                                                                                  : 3  \n (Other)                                                                                   : 3  \n                lieu_de_vie  nb_personnes               revenu  \n Campagne             :35   Min.   :0.000   40 000 - 50 000:26  \n Périurbaine/ Banlieue:11   1st Qu.:1.000   20 000 - 30 000:22  \n Ville                :49   Median :1.000   10 000 - 20 000:17  \n                            Mean   :1.663   < 10 000       :11  \n                            3rd Qu.:3.000   30 000 - 40 000:10  \n                            Max.   :5.000   50 000 - 60 000: 3  \n                                            (Other)        : 6  \n  temps_ecran     nb_appareils                         internet  fibre   \n Min.   : 4.50   3      :39    Non                         : 1   Non: 6  \n 1st Qu.:26.50   4      :18    Oui, avec l’ADSL            :17   Oui:89  \n Median :35.00   2      :14    Oui, avec la fibre          :68           \n Mean   :35.88   5      :10    Oui, avec une autre solution: 9           \n 3rd Qu.:45.00   6      : 5                                              \n Max.   :85.00   7      : 3                                              \n                 (Other): 6                                              \n          forfait_tel telephone_pro\n 15 et 20 €     :34   Non:32       \n 10 et 15 €     :20   Oui:63       \n Plus de 35€    :11                \n 20 et 25 €     :10                \n Entre 5 et 10 €: 6                \n 30 et 35 €     : 5                \n (Other)        : 9                \n                                        ecran_travail       sommeil  \n Fréquemment (Plus de la moitié du temps)      :25    3h – 5h   : 9  \n Jamais                                        : 4    5h – 7h   :32  \n Parfois (Entre un quart et la moitié du temps):16    7h et 9h  :51  \n Rarement                                      :12    Plus de 9h: 3  \n Toute la journée                              :38                   \n                                                                     \n                                                                     \n         stress       loisir      vie_sociale   \n Fréquemment:26   Min.   : 0.0   Min.   : 0.00  \n Jamais     : 1   1st Qu.: 4.0   1st Qu.: 5.00  \n Parfois    :38   Median :10.0   Median :10.00  \n Rarement   :15   Mean   :11.3   Mean   :15.12  \n Toujours   :15   3rd Qu.:15.0   3rd Qu.:20.50  \n                  Max.   :42.0   Max.   :50.00  \n                                                \n                           ecran_jour reseaux_sociaux nb_abonnements\n L’après midi                   : 8   3      :24      1      :33    \n L’après midi, Le soir          :10   2      :13      2      :21    \n Le matin                       : 5   5      :12      0      :17    \n Le matin, L’après midi         : 7   4      :11      3      :12    \n Le matin, L’après midi, Le soir: 7   6      : 9      4      : 8    \n Le matin, Le soir              : 3   1      : 8      5      : 2    \n Le soir                        :55   (Other):18      (Other): 2    \n```\n\n\n:::\n:::\n\n\n\n# Regrouper en catégories plus larges et création de catégories binaires\n\n## Variables quali en binaire\n\n-   Réseaux sociaux\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$reseaux_sociaux)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         0          1          2          3          4          5          6 \n         5          8         13         24         11         12          9 \n         7          8          9 Plus de 10 \n         6          3          0          4 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(cat_reseau_0_2 = ifelse(reseaux_sociaux %in% c(\"0\",\"1\",\"2\"), 1, 0),\n         cat_reseau_3_5 = ifelse(reseaux_sociaux %in% c(\"3\",\"4\",\"5\"), 1, 0),\n         cat_reseau_6_sup6 = ifelse(reseaux_sociaux %in% c(\"6\",\"7\",\"8\",\"9\",\"Plus de 10\"), 1, 0))\n```\n:::\n\n\n\n-   Age\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(cat_18_24 = ifelse(age == \"18 - 24 ans\", 1, 0),\n         cat_25_49 = ifelse(age == \"25 - 49 ans\", 1, 0),\n         cat_plus_50 = ifelse(age %in% c(\"50- 69 ans\",\"70 ans et plus\"), 1, 0))\n```\n:::\n\n\n\n-   Forfait téléphone\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$forfait_tel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              0      10 et 15 €      15 et 20 €      20 et 25 €      25 et 30 € \n              2              20              34              10               3 \n     30 et 35 € Entre 5 et 10 €   Moins  de 5 €     Plus de 35€ \n              5               6               4              11 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(tel_inf_15 = ifelse(forfait_tel %in% c(\"0\", \"Moins  de 5 €\",\"Entre 5 et 10 €\",\"10 et 15 €\" ), 1, 0),\n         tel_15_25 = ifelse(forfait_tel %in% c(\"15 et 20 €\",\"20 et 25 €\"), 1, 0),\n         tel_sup_25 = ifelse(forfait_tel %in% c(\"25 et 30 €\",\"30 et 35 €\",\"Plus de 35€\"), 1, 0))\n```\n:::\n\n\n\n-   Nombre d'appareils\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$nb_appareils)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         1         10          2          3          4          5          6 \n         1          2         14         39         18         10          5 \n         7          8          9 Plus de 10 \n         3          0          1          2 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(appareils_1_2 = ifelse(nb_appareils %in% c(\"1\", \"2\"), 1, 0),\n         appareils_3_4 = ifelse(nb_appareils %in% c(\"3\", \"4\"), 1, 0),\n         appareils_plus_4 = ifelse(nb_appareils %in% c(\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"Plus de 10\"), 1, 0))\n```\n:::\n\n\n\n-   Nombre d'abonnements\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$nb_abonnements)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         0          1         10          2          3          4          5 \n        17         33          1         21         12          8          2 \n         7 Plus de 10 \n         0          1 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(abo_0 = ifelse(nb_abonnements == \"0\", 1, 0),\n         abo_1 = ifelse(nb_abonnements == \"1\", 1, 0),\n         abo_2 = ifelse(nb_abonnements == \"2\", 1, 0),\n         abo_3_sup = ifelse(nb_abonnements %in% c(\"3\",\"4\",\"5\",\"6\",\"7\", \"8\",\"9\",\"10\",\"Plus de 10\"), 1, 0))\n```\n:::\n\n\n\n-   Genre\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$genre)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFemme Homme \n   70    25 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(homme = ifelse(genre == \"Homme\", 1, 0),\n         femme = ifelse(genre == \"Femme\", 1, 0))\n```\n:::\n\n\n\n-   Lieu de vie\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$lieu_de_vie)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Campagne Périurbaine/ Banlieue                 Ville \n                   35                    11                    49 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(pas_ville = ifelse(lieu_de_vie %in% c(\"Campagne\",\"Périurbaine/ Banlieue\"), 1, 0),\n         ville = ifelse(lieu_de_vie == \"Ville\", 1, 0))\n```\n:::\n\n\n\n-   CSP\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$csp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                                  Agriculteurs exploitants \n                                                                                         1 \n                                                      Artisan/commerçant/Chef d’entreprise \n                                                                                         2 \nAutres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants) \n                                                                                        29 \n                                         Cadres et professions intellectuelles supérieures \n                                                                                        17 \n                                                                                  Employés \n                                                                                        33 \n                                                                                  Ouvriers \n                                                                                         3 \n                                                                Professions intermédiaires \n                                                                                         6 \n                                                                                 Retraités \n                                                                                         4 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(cat_Employes = ifelse(csp == \"Employés\", 1, 0),\n         cat_sans_activite = ifelse(csp == \"Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants)\", 1, 0),\n         cat_cadres = ifelse(csp == \"Cadres et professions intellectuelles supérieures\", 1, 0),\n         cat_autres = ifelse(csp %in% c(\"Professions intermédiaires\",\"Retraités\", \"Ouvriers\", \"Artisan/commerçant/Chef d’entreprise\",\"Agriculteurs exploitants\"), 1, 0))\n```\n:::\n\n\n\n-   Ecran au travail\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$ecran_travail)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Fréquemment (Plus de la moitié du temps) \n                                            25 \n                                        Jamais \n                                             4 \nParfois (Entre un quart et la moitié du temps) \n                                            16 \n                                      Rarement \n                                            12 \n                              Toute la journée \n                                            38 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(ecran_travail_plein = ifelse(ecran_travail == \"Toute la journée\", 1, 0),\n         ecran_travail_bcp = ifelse(ecran_travail == \"Fréquemment (Plus de la moitié du temps)\", 1, 0),\n         ecran_travail_peu = ifelse(ecran_travail %in% c(\"Parfois (Entre un quart et la moitié du temps)\",\"Rarement\",\"Jamais\"), 1, 0))\n```\n:::\n\n\n\n-   Internet\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$internet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         Non             Oui, avec l’ADSL \n                           1                           17 \n          Oui, avec la fibre Oui, avec une autre solution \n                          68                            9 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(pas_internet = ifelse(internet == \"Non\", 1, 0),\n         internet_autre = ifelse(internet %in% c(\"Oui, avec l’ADSL\", \"Oui, avec une autre solution\"), 1, 0),\n         internet_fibre = ifelse(internet == \"Oui, avec la fibre\", 1, 0))\n```\n:::\n\n\n\n-   Sommeil\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$sommeil)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   3h – 5h    5h – 7h   7h et 9h Plus de 9h \n         9         32         51          3 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(nuit_inf_7 = ifelse(sommeil %in% c(\"3h – 5h\", \"5h – 7h\"), 1, 0),\n         nuit_5_7 = ifelse(sommeil %in% c(\"7h et 9h\",\"Plus de 9h\"), 1, 0))\n```\n:::\n\n\n\n-   Ecran jour\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$ecran_jour)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   L’après midi           L’après midi, Le soir \n                              8                              10 \n                       Le matin          Le matin, L’après midi \n                              5                               7 \nLe matin, L’après midi, Le soir               Le matin, Le soir \n                              7                               3 \n                        Le soir \n                             55 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(jour_3 = ifelse(ecran_jour == \"Le matin, L’après midi, Le soir\", 1, 0),\n         jour_2 = ifelse(ecran_jour %in% c(\"L’après midi, Le soir\", \"Le matin, L’après midi\", \"Le matin, Le soir\"), 1, 0),\n         jour_1 = ifelse(ecran_jour %in% c(\"L’après midi\",\"Le matin\",\"Le soir\"), 1, 0))\n```\n:::\n\n\n\n## Variables instruments\n\n-   Revenu\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$revenu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       < 10 000 10 000 - 20 000 20 000 - 30 000 30 000 - 40 000 40 000 - 50 000 \n             11              17              22              10              26 \n50 000 - 60 000 60 000 - 70 000 70 000 - 80 000  80 000 et plus \n              3               2               3               1 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(cat_inf_20000 = ifelse(revenu %in% c(\"< 10 000\",\"10 000 - 20 000\"), 1, 0),\n         cat_20_40000 = ifelse(revenu %in% c(\"20 000 - 30 000\",\"30 000 - 40 000\"), 1, 0),\n         cat_sup_40000 = ifelse(revenu %in% c(\"40 000 - 50 000\",\"50 000 - 60 000\",\"60 000 - 70 000\", \"70 000 - 80 000\",\"80 000 et plus\"), 1, 0))\n```\n:::\n\n\n\n-   Fibre\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$fibre)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNon Oui \n  6  89 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(fibre_oui = ifelse(fibre == \"Oui\", 1, 0),\n         fibre_non = ifelse(fibre == \"Non\", 1, 0))\n```\n:::\n\n\n\n-   Téléphone pro\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$telephone_pro)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNon Oui \n 32  63 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(tel_pro_non = ifelse(telephone_pro == \"Non\", 1, 0),\n         tel_pro_oui = ifelse(telephone_pro == \"Oui\", 1, 0))\n```\n:::\n\n\n\n-   Stress\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2$stress)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFréquemment      Jamais     Parfois    Rarement    Toujours \n         26           1          38          15          15 \n```\n\n\n:::\n\n```{.r .cell-code}\necran2 <- ecran2 |> \n  mutate(stress_toujours = ifelse(stress == \"Toujours\", 1, 0),\n         stress_bcp = ifelse(stress == \"Fréquemment\", 1, 0),\n         stress_peu = ifelse(stress %in% c(\"Parfois\", \"Rarement\",\"Jamais\"),1, 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ecran2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             age       genre   \n 18 - 24 ans   :45   Femme:70  \n 25 - 49 ans   :38   Homme:25  \n 50- 69 ans    : 9             \n 70 ans et plus: 3             \n                               \n                               \n                               \n                                                                                         csp    \n Employés                                                                                  :33  \n Autres personnes sans activité professionnelle (par exemple les chômeurs ou les étudiants):29  \n Cadres et professions intellectuelles supérieures                                         :17  \n Professions intermédiaires                                                                : 6  \n Retraités                                                                                 : 4  \n Ouvriers                                                                                  : 3  \n (Other)                                                                                   : 3  \n                lieu_de_vie  nb_personnes               revenu  \n Campagne             :35   Min.   :0.000   40 000 - 50 000:26  \n Périurbaine/ Banlieue:11   1st Qu.:1.000   20 000 - 30 000:22  \n Ville                :49   Median :1.000   10 000 - 20 000:17  \n                            Mean   :1.663   < 10 000       :11  \n                            3rd Qu.:3.000   30 000 - 40 000:10  \n                            Max.   :5.000   50 000 - 60 000: 3  \n                                            (Other)        : 6  \n  temps_ecran     nb_appareils                         internet  fibre   \n Min.   : 4.50   3      :39    Non                         : 1   Non: 6  \n 1st Qu.:26.50   4      :18    Oui, avec l’ADSL            :17   Oui:89  \n Median :35.00   2      :14    Oui, avec la fibre          :68           \n Mean   :35.88   5      :10    Oui, avec une autre solution: 9           \n 3rd Qu.:45.00   6      : 5                                              \n Max.   :85.00   7      : 3                                              \n                 (Other): 6                                              \n          forfait_tel telephone_pro\n 15 et 20 €     :34   Non:32       \n 10 et 15 €     :20   Oui:63       \n Plus de 35€    :11                \n 20 et 25 €     :10                \n Entre 5 et 10 €: 6                \n 30 et 35 €     : 5                \n (Other)        : 9                \n                                        ecran_travail       sommeil  \n Fréquemment (Plus de la moitié du temps)      :25    3h – 5h   : 9  \n Jamais                                        : 4    5h – 7h   :32  \n Parfois (Entre un quart et la moitié du temps):16    7h et 9h  :51  \n Rarement                                      :12    Plus de 9h: 3  \n Toute la journée                              :38                   \n                                                                     \n                                                                     \n         stress       loisir      vie_sociale   \n Fréquemment:26   Min.   : 0.0   Min.   : 0.00  \n Jamais     : 1   1st Qu.: 4.0   1st Qu.: 5.00  \n Parfois    :38   Median :10.0   Median :10.00  \n Rarement   :15   Mean   :11.3   Mean   :15.12  \n Toujours   :15   3rd Qu.:15.0   3rd Qu.:20.50  \n                  Max.   :42.0   Max.   :50.00  \n                                                \n                           ecran_jour reseaux_sociaux nb_abonnements\n L’après midi                   : 8   3      :24      1      :33    \n L’après midi, Le soir          :10   2      :13      2      :21    \n Le matin                       : 5   5      :12      0      :17    \n Le matin, L’après midi         : 7   4      :11      3      :12    \n Le matin, L’après midi, Le soir: 7   6      : 9      4      : 8    \n Le matin, Le soir              : 3   1      : 8      5      : 2    \n Le soir                        :55   (Other):18      (Other): 2    \n cat_reseau_0_2   cat_reseau_3_5   cat_reseau_6_sup6   cat_18_24     \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000    Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000    1st Qu.:0.0000  \n Median :0.0000   Median :0.0000   Median :0.0000    Median :0.0000  \n Mean   :0.2737   Mean   :0.4947   Mean   :0.2316    Mean   :0.4737  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.0000    3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000    Max.   :1.0000  \n                                                                     \n   cat_25_49    cat_plus_50       tel_inf_15       tel_15_25        tel_sup_25 \n Min.   :0.0   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0  \n 1st Qu.:0.0   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0  \n Median :0.0   Median :0.0000   Median :0.0000   Median :0.0000   Median :0.0  \n Mean   :0.4   Mean   :0.1263   Mean   :0.3368   Mean   :0.4632   Mean   :0.2  \n 3rd Qu.:1.0   3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.0  \n Max.   :1.0   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0  \n                                                                               \n appareils_1_2    appareils_3_4 appareils_plus_4     abo_0       \n Min.   :0.0000   Min.   :0.0   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :0.0000   Median :1.0   Median :0.0000   Median :0.0000  \n Mean   :0.1579   Mean   :0.6   Mean   :0.2421   Mean   :0.1789  \n 3rd Qu.:0.0000   3rd Qu.:1.0   3rd Qu.:0.0000   3rd Qu.:0.0000  \n Max.   :1.0000   Max.   :1.0   Max.   :1.0000   Max.   :1.0000  \n                                                                 \n     abo_1            abo_2          abo_3_sup          homme       \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :0.0000   Median :0.0000   Median :0.0000   Median :0.0000  \n Mean   :0.3474   Mean   :0.2211   Mean   :0.2526   Mean   :0.2632  \n 3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.5000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n                                                                    \n     femme          pas_ville          ville         cat_Employes   \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :1.0000   Median :0.0000   Median :1.0000   Median :0.0000  \n Mean   :0.7368   Mean   :0.4842   Mean   :0.5158   Mean   :0.3474  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n                                                                    \n cat_sans_activite   cat_cadres       cat_autres     ecran_travail_plein\n Min.   :0.0000    Min.   :0.0000   Min.   :0.0000   Min.   :0.0        \n 1st Qu.:0.0000    1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0        \n Median :0.0000    Median :0.0000   Median :0.0000   Median :0.0        \n Mean   :0.3053    Mean   :0.1789   Mean   :0.1684   Mean   :0.4        \n 3rd Qu.:1.0000    3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:1.0        \n Max.   :1.0000    Max.   :1.0000   Max.   :1.0000   Max.   :1.0        \n                                                                        \n ecran_travail_bcp ecran_travail_peu  pas_internet     internet_autre  \n Min.   :0.0000    Min.   :0.0000    Min.   :0.00000   Min.   :0.0000  \n 1st Qu.:0.0000    1st Qu.:0.0000    1st Qu.:0.00000   1st Qu.:0.0000  \n Median :0.0000    Median :0.0000    Median :0.00000   Median :0.0000  \n Mean   :0.2632    Mean   :0.3368    Mean   :0.01053   Mean   :0.2737  \n 3rd Qu.:1.0000    3rd Qu.:1.0000    3rd Qu.:0.00000   3rd Qu.:1.0000  \n Max.   :1.0000    Max.   :1.0000    Max.   :1.00000   Max.   :1.0000  \n                                                                       \n internet_fibre     nuit_inf_7        nuit_5_7          jour_3       \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.00000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000  \n Median :1.0000   Median :0.0000   Median :1.0000   Median :0.00000  \n Mean   :0.7158   Mean   :0.4316   Mean   :0.5684   Mean   :0.07368  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.00000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.00000  \n                                                                     \n     jour_2           jour_1       cat_inf_20000     cat_20_40000   \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :0.0000   Median :1.0000   Median :0.0000   Median :0.0000  \n Mean   :0.2105   Mean   :0.7158   Mean   :0.2947   Mean   :0.3368  \n 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n                                                                    \n cat_sup_40000      fibre_oui        fibre_non        tel_pro_non    \n Min.   :0.0000   Min.   :0.0000   Min.   :0.00000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:1.0000   1st Qu.:0.00000   1st Qu.:0.0000  \n Median :0.0000   Median :1.0000   Median :0.00000   Median :0.0000  \n Mean   :0.3684   Mean   :0.9368   Mean   :0.06316   Mean   :0.3368  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.00000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.00000   Max.   :1.0000  \n                                                                     \n  tel_pro_oui     stress_toujours    stress_bcp       stress_peu    \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :1.0000   Median :0.0000   Median :0.0000   Median :1.0000  \n Mean   :0.6632   Mean   :0.1579   Mean   :0.2737   Mean   :0.5684  \n 3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n                                                                    \n```\n\n\n:::\n\n```{.r .cell-code}\nstr(ecran2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [95 × 65] (S3: tbl_df/tbl/data.frame)\n $ age                : Factor w/ 4 levels \"18 - 24 ans\",..: 2 3 3 3 2 4 2 2 2 2 ...\n $ genre              : Factor w/ 2 levels \"Femme\",\"Homme\": 1 1 1 2 1 1 1 2 2 1 ...\n $ csp                : Factor w/ 8 levels \"Agriculteurs exploitants\",..: 4 7 4 4 5 8 5 5 5 2 ...\n $ lieu_de_vie        : Factor w/ 3 levels \"Campagne\",\"Périurbaine/ Banlieue\",..: 3 1 2 3 1 1 1 2 2 3 ...\n $ nb_personnes       : num [1:95] 1 2 2 1 5 0 1 3 3 1 ...\n $ revenu             : Factor w/ 9 levels \"< 10 000\",\"10 000 - 20 000\",..: 4 5 8 8 7 2 3 5 5 4 ...\n $ temps_ecran        : num [1:95] 35 35 30 60 64 28 28 35 21 60 ...\n $ nb_appareils       : Factor w/ 11 levels \"1\",\"10\",\"2\",\"3\",..: 4 6 5 5 8 4 4 5 7 5 ...\n $ internet           : Factor w/ 4 levels \"Non\",\"Oui, avec l’ADSL\",..: 3 3 3 3 2 2 3 3 3 3 ...\n $ fibre              : Factor w/ 2 levels \"Non\",\"Oui\": 2 2 2 2 1 2 2 2 2 2 ...\n $ forfait_tel        : Factor w/ 9 levels \"0\",\"10 et 15 €\",..: 2 2 3 1 3 8 4 3 5 3 ...\n $ telephone_pro      : Factor w/ 2 levels \"Non\",\"Oui\": 2 1 2 2 1 1 1 2 2 2 ...\n $ ecran_travail      : Factor w/ 5 levels \"Fréquemment (Plus de la moitié du temps)\",..: 5 1 1 5 5 2 3 3 4 5 ...\n $ sommeil            : Factor w/ 4 levels \"3h – 5h\",\"5h – 7h\",..: 2 3 3 2 3 3 2 3 3 1 ...\n $ stress             : Factor w/ 5 levels \"Fréquemment\",..: 3 3 4 1 1 4 1 4 4 5 ...\n $ loisir             : num [1:95] 3 10 1 6 12 2 6 21 20 4 ...\n $ vie_sociale        : num [1:95] 14 15 2 8 8 7 10 20 10 14 ...\n $ ecran_jour         : Factor w/ 7 levels \"L’après midi\",..: 7 1 3 7 1 7 1 7 1 4 ...\n $ reseaux_sociaux    : Factor w/ 11 levels \"0\",\"1\",\"2\",\"3\",..: 6 3 2 1 1 1 2 4 3 7 ...\n $ nb_abonnements     : Factor w/ 9 levels \"0\",\"1\",\"10\",\"2\",..: 1 2 5 1 2 2 1 2 2 5 ...\n $ cat_reseau_0_2     : num [1:95] 0 1 1 1 1 1 1 0 1 0 ...\n $ cat_reseau_3_5     : num [1:95] 1 0 0 0 0 0 0 1 0 0 ...\n $ cat_reseau_6_sup6  : num [1:95] 0 0 0 0 0 0 0 0 0 1 ...\n $ cat_18_24          : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ cat_25_49          : num [1:95] 1 0 0 0 1 0 1 1 1 1 ...\n $ cat_plus_50        : num [1:95] 0 1 1 1 0 1 0 0 0 0 ...\n $ tel_inf_15         : num [1:95] 1 1 0 1 0 1 0 0 0 0 ...\n $ tel_15_25          : num [1:95] 0 0 1 0 1 0 1 1 0 1 ...\n $ tel_sup_25         : num [1:95] 0 0 0 0 0 0 0 0 1 0 ...\n $ appareils_1_2      : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ appareils_3_4      : num [1:95] 1 0 1 1 0 1 1 1 0 1 ...\n $ appareils_plus_4   : num [1:95] 0 1 0 0 1 0 0 0 1 0 ...\n $ abo_0              : num [1:95] 1 0 0 1 0 0 1 0 0 0 ...\n $ abo_1              : num [1:95] 0 1 0 0 1 1 0 1 1 0 ...\n $ abo_2              : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ abo_3_sup          : num [1:95] 0 0 1 0 0 0 0 0 0 1 ...\n $ homme              : num [1:95] 0 0 0 1 0 0 0 1 1 0 ...\n $ femme              : num [1:95] 1 1 1 0 1 1 1 0 0 1 ...\n $ pas_ville          : num [1:95] 0 1 1 0 1 1 1 1 1 0 ...\n $ ville              : num [1:95] 1 0 0 1 0 0 0 0 0 1 ...\n $ cat_Employes       : num [1:95] 0 0 0 0 1 0 1 1 1 0 ...\n $ cat_sans_activite  : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ cat_cadres         : num [1:95] 1 0 1 1 0 0 0 0 0 0 ...\n $ cat_autres         : num [1:95] 0 1 0 0 0 1 0 0 0 1 ...\n $ ecran_travail_plein: num [1:95] 1 0 0 1 1 0 0 0 0 1 ...\n $ ecran_travail_bcp  : num [1:95] 0 1 1 0 0 0 0 0 0 0 ...\n $ ecran_travail_peu  : num [1:95] 0 0 0 0 0 1 1 1 1 0 ...\n $ pas_internet       : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ internet_autre     : num [1:95] 0 0 0 0 1 1 0 0 0 0 ...\n $ internet_fibre     : num [1:95] 1 1 1 1 0 0 1 1 1 1 ...\n $ nuit_inf_7         : num [1:95] 1 0 0 1 0 0 1 0 0 1 ...\n $ nuit_5_7           : num [1:95] 0 1 1 0 1 1 0 1 1 0 ...\n $ jour_3             : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ jour_2             : num [1:95] 0 0 0 0 0 0 0 0 0 1 ...\n $ jour_1             : num [1:95] 1 1 1 1 1 1 1 1 1 0 ...\n $ cat_inf_20000      : num [1:95] 0 0 0 0 0 1 0 0 0 0 ...\n $ cat_20_40000       : num [1:95] 1 0 0 0 0 0 1 0 0 1 ...\n $ cat_sup_40000      : num [1:95] 0 1 1 1 1 0 0 1 1 0 ...\n $ fibre_oui          : num [1:95] 1 1 1 1 0 1 1 1 1 1 ...\n $ fibre_non          : num [1:95] 0 0 0 0 1 0 0 0 0 0 ...\n $ tel_pro_non        : num [1:95] 0 1 0 0 1 1 1 0 0 0 ...\n $ tel_pro_oui        : num [1:95] 1 0 1 1 0 0 0 1 1 1 ...\n $ stress_toujours    : num [1:95] 0 0 0 0 0 0 0 0 0 1 ...\n $ stress_bcp         : num [1:95] 0 0 0 1 1 0 1 0 0 0 ...\n $ stress_peu         : num [1:95] 1 1 1 0 0 1 0 1 1 0 ...\n```\n\n\n:::\n:::\n\n\n\n# Création 2 base de données\n\n-   Base sans les instruments et la deuxième avec les instruments. Les deux **avec** la variable de référence\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran_sans_instru <- ecran2[, -c(1,2,3,4,5,6,8,9,10,11,12,13,14,15,18,19,20,56,57,58,59,60,61,62,63,64,65)]\necran_avec_instru <- ecran2[, -c(1,2,3,4,6,8,9,10,11,12,13,14,15,18,19,20)]\n\n#save(ecran_sans_instru, file = \"data/ecran_sans_instru.rda\")\n#save(ecran_avec_instru, file = \"data/ecran_avec_instru.rda\")\n```\n:::\n\n\n\n-   Base sans instruments et la deuxième avec les instruments. Les deux **sans** la variable de référence\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\necran_sans_instru_sansref <- ecran_sans_instru[, -c(5,7,11,14,17,21,23,24,28,33,35,38)]\n\necran_avec_instru_sansref <- ecran_avec_instru[, -c(6,8,12,15,18,22,24,25,29,34,36,39,42,43,46,49)]\n\n#save(ecran_sans_instru_sansref, file = \"data/ecran_sans_instru_sansref.rda\")\n#save(ecran_avec_instru_sansref, file = \"data/ecran_avec_instru_sansref.rda\")\n```\n:::\n\n\n\n# Analyse économétrique\n\n## Récupération de données\n\nUtilisation de la base de données écran sans les instruments et sans la référence\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(here(\"data\", \"ecran_sans_instru_sansref.rda\"))\necran <- ecran_sans_instru_sansref\ndim(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 95 26\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [95 × 26] (S3: tbl_df/tbl/data.frame)\n $ temps_ecran      : num [1:95] 35 35 30 60 64 28 28 35 21 60 ...\n $ loisir           : num [1:95] 3 10 1 6 12 2 6 21 20 4 ...\n $ vie_sociale      : num [1:95] 14 15 2 8 8 7 10 20 10 14 ...\n $ cat_reseau_0_2   : num [1:95] 0 1 1 1 1 1 1 0 1 0 ...\n $ cat_reseau_6_sup6: num [1:95] 0 0 0 0 0 0 0 0 0 1 ...\n $ cat_25_49        : num [1:95] 1 0 0 0 1 0 1 1 1 1 ...\n $ cat_plus_50      : num [1:95] 0 1 1 1 0 1 0 0 0 0 ...\n $ tel_inf_15       : num [1:95] 1 1 0 1 0 1 0 0 0 0 ...\n $ tel_sup_25       : num [1:95] 0 0 0 0 0 0 0 0 1 0 ...\n $ appareils_1_2    : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ appareils_plus_4 : num [1:95] 0 1 0 0 1 0 0 0 1 0 ...\n $ abo_0            : num [1:95] 1 0 0 1 0 0 1 0 0 0 ...\n $ abo_2            : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ abo_3_sup        : num [1:95] 0 0 1 0 0 0 0 0 0 1 ...\n $ homme            : num [1:95] 0 0 0 1 0 0 0 1 1 0 ...\n $ pas_ville        : num [1:95] 0 1 1 0 1 1 1 1 1 0 ...\n $ cat_sans_activite: num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ cat_cadres       : num [1:95] 1 0 1 1 0 0 0 0 0 0 ...\n $ cat_autres       : num [1:95] 0 1 0 0 0 1 0 0 0 1 ...\n $ ecran_travail_bcp: num [1:95] 0 1 1 0 0 0 0 0 0 0 ...\n $ ecran_travail_peu: num [1:95] 0 0 0 0 0 1 1 1 1 0 ...\n $ pas_internet     : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ internet_autre   : num [1:95] 0 0 0 0 1 1 0 0 0 0 ...\n $ nuit_inf_7       : num [1:95] 1 0 0 1 0 0 1 0 0 1 ...\n $ jour_3           : num [1:95] 0 0 0 0 0 0 0 0 0 0 ...\n $ jour_2           : num [1:95] 0 0 0 0 0 0 0 0 0 1 ...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necran[4:26] <- lapply(ecran[4:26], as.factor)\nstr(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [95 × 26] (S3: tbl_df/tbl/data.frame)\n $ temps_ecran      : num [1:95] 35 35 30 60 64 28 28 35 21 60 ...\n $ loisir           : num [1:95] 3 10 1 6 12 2 6 21 20 4 ...\n $ vie_sociale      : num [1:95] 14 15 2 8 8 7 10 20 10 14 ...\n $ cat_reseau_0_2   : Factor w/ 2 levels \"0\",\"1\": 1 2 2 2 2 2 2 1 2 1 ...\n $ cat_reseau_6_sup6: Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 1 1 1 1 2 ...\n $ cat_25_49        : Factor w/ 2 levels \"0\",\"1\": 2 1 1 1 2 1 2 2 2 2 ...\n $ cat_plus_50      : Factor w/ 2 levels \"0\",\"1\": 1 2 2 2 1 2 1 1 1 1 ...\n $ tel_inf_15       : Factor w/ 2 levels \"0\",\"1\": 2 2 1 2 1 2 1 1 1 1 ...\n $ tel_sup_25       : Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 1 1 1 2 1 ...\n $ appareils_1_2    : Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 1 1 1 1 1 ...\n $ appareils_plus_4 : Factor w/ 2 levels \"0\",\"1\": 1 2 1 1 2 1 1 1 2 1 ...\n $ abo_0            : Factor w/ 2 levels \"0\",\"1\": 2 1 1 2 1 1 2 1 1 1 ...\n $ abo_2            : Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 1 1 1 1 1 ...\n $ abo_3_sup        : Factor w/ 2 levels \"0\",\"1\": 1 1 2 1 1 1 1 1 1 2 ...\n $ homme            : Factor w/ 2 levels \"0\",\"1\": 1 1 1 2 1 1 1 2 2 1 ...\n $ pas_ville        : Factor w/ 2 levels \"0\",\"1\": 1 2 2 1 2 2 2 2 2 1 ...\n $ cat_sans_activite: Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 1 1 1 1 1 ...\n $ cat_cadres       : Factor w/ 2 levels \"0\",\"1\": 2 1 2 2 1 1 1 1 1 1 ...\n $ cat_autres       : Factor w/ 2 levels \"0\",\"1\": 1 2 1 1 1 2 1 1 1 2 ...\n $ ecran_travail_bcp: Factor w/ 2 levels \"0\",\"1\": 1 2 2 1 1 1 1 1 1 1 ...\n $ ecran_travail_peu: Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 2 2 2 2 1 ...\n $ pas_internet     : Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 1 1 1 1 1 ...\n $ internet_autre   : Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 2 2 1 1 1 1 ...\n $ nuit_inf_7       : Factor w/ 2 levels \"0\",\"1\": 2 1 1 2 1 1 2 1 1 2 ...\n $ jour_3           : Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 1 1 1 1 1 ...\n $ jour_2           : Factor w/ 2 levels \"0\",\"1\": 1 1 1 1 1 1 1 1 1 2 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(ecran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  temps_ecran        loisir      vie_sociale    cat_reseau_0_2\n Min.   : 4.50   Min.   : 0.0   Min.   : 0.00   0:69          \n 1st Qu.:26.50   1st Qu.: 4.0   1st Qu.: 5.00   1:26          \n Median :35.00   Median :10.0   Median :10.00                 \n Mean   :35.88   Mean   :11.3   Mean   :15.12                 \n 3rd Qu.:45.00   3rd Qu.:15.0   3rd Qu.:20.50                 \n Max.   :85.00   Max.   :42.0   Max.   :50.00                 \n cat_reseau_6_sup6 cat_25_49 cat_plus_50 tel_inf_15 tel_sup_25 appareils_1_2\n 0:73              0:57      0:83        0:63       0:76       0:80         \n 1:22              1:38      1:12        1:32       1:19       1:15         \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n appareils_plus_4 abo_0  abo_2  abo_3_sup homme  pas_ville cat_sans_activite\n 0:72             0:78   0:74   0:71      0:70   0:49      0:66             \n 1:23             1:17   1:21   1:24      1:25   1:46      1:29             \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n cat_cadres cat_autres ecran_travail_bcp ecran_travail_peu pas_internet\n 0:78       0:79       0:70              0:63              0:94        \n 1:17       1:16       1:25              1:32              1: 1        \n                                                                       \n                                                                       \n                                                                       \n                                                                       \n internet_autre nuit_inf_7 jour_3 jour_2\n 0:69           0:54       0:88   0:75  \n 1:26           1:41       1: 7   1:20  \n                                        \n                                        \n                                        \n                                        \n```\n\n\n:::\n:::\n\n\n\n# MCO\n\n## Hypothèses sous-jacentes à la méthode des Moindres Carrés Ordinaires\n\n### Modèle linéaire\n\nModèle avec toutes les variables, ne sera pas utilisé dans notre analyse - voir méthode STEP\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodele1 <- lm(temps_ecran ~ loisir + vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + cat_25_49 + cat_plus_50 + tel_inf_15 + tel_sup_25 + appareils_1_2 + appareils_plus_4 + abo_0 + abo_2 + abo_3_sup + homme + pas_ville + cat_sans_activite + cat_cadres + cat_autres + ecran_travail_bcp + ecran_travail_peu + pas_internet + internet_autre + nuit_inf_7 + jour_3 + jour_2, data=ecran)\n\nsummary(modele1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temps_ecran ~ loisir + vie_sociale + cat_reseau_0_2 + \n    cat_reseau_6_sup6 + cat_25_49 + cat_plus_50 + tel_inf_15 + \n    tel_sup_25 + appareils_1_2 + appareils_plus_4 + abo_0 + abo_2 + \n    abo_3_sup + homme + pas_ville + cat_sans_activite + cat_cadres + \n    cat_autres + ecran_travail_bcp + ecran_travail_peu + pas_internet + \n    internet_autre + nuit_inf_7 + jour_3 + jour_2, data = ecran)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-24.503  -8.912  -0.815   7.447  35.558 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         41.0805     7.1099   5.778 1.99e-07 ***\nloisir              -0.1057     0.2103  -0.503  0.61685    \nvie_sociale         -0.1800     0.1570  -1.147  0.25549    \ncat_reseau_0_21     -4.0312     5.0592  -0.797  0.42830    \ncat_reseau_6_sup61   9.5478     5.3309   1.791  0.07767 .  \ncat_25_491          -1.4514     5.2351  -0.277  0.78242    \ncat_plus_501        -4.1037     8.7089  -0.471  0.63898    \ntel_inf_151         -2.6226     4.0957  -0.640  0.52409    \ntel_sup_251         -7.9265     4.6422  -1.707  0.09223 .  \nappareils_1_21      11.5977     5.2763   2.198  0.03130 *  \nappareils_plus_41    3.1873     4.2642   0.747  0.45734    \nabo_01              -8.1979     5.0213  -1.633  0.10710    \nabo_21              -6.6294     5.0091  -1.323  0.19005    \nabo_3_sup1          -3.6215     4.4330  -0.817  0.41678    \nhomme1               6.1879     4.1251   1.500  0.13816    \npas_ville1           6.5266     3.7579   1.737  0.08689 .  \ncat_sans_activite1   2.1203     4.8246   0.439  0.66169    \ncat_cadres1          8.2460     5.8445   1.411  0.16277    \ncat_autres1          3.4039     5.7235   0.595  0.55397    \necran_travail_bcp1 -11.5269     4.6034  -2.504  0.01465 *  \necran_travail_peu1 -12.9224     4.7990  -2.693  0.00889 ** \npas_internet1       13.0349    16.3039   0.799  0.42675    \ninternet_autre1      6.6674     3.8631   1.726  0.08884 .  \nnuit_inf_71         -0.7751     3.6011  -0.215  0.83020    \njour_31             -1.0904     6.9154  -0.158  0.87518    \njour_21              3.6913     4.1450   0.891  0.37627    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14.56 on 69 degrees of freedom\nMultiple R-squared:  0.3839,\tAdjusted R-squared:  0.1607 \nF-statistic:  1.72 on 25 and 69 DF,  p-value: 0.04026\n```\n\n\n:::\n:::\n\n\n\nR = 38.39% de la variance dans temps_ecran est expliquée par le modèle. R- ajusté : 16,07\n\nP-value associée au test de Fisher \\< 0,05 : H0 est refusée ==\\> 0.040, le modèle, dans son ensemble, est statistiquement significatif, mais pas très fortement.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(modele1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: not plotting observations with leverage one:\n  70\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-69-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-69-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-69-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-69-4.png){width=672}\n:::\n:::\n\n\n\nD’après les graphiques, le modèle1\n\n-   Ne suivent pas a priori une loi normale\n\n-   Ne vérifie pas à priori l'hypothèse d'homoscédasticité car variance de la variable Mesure augmente à droite\n\n#### Test de normalité de résidus\n\nHypothèse H0 : les erreurs suivent une loi normale au seuil de risque de 5 %\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(residuals(modele1))\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-70-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(residuals(modele1), breaks=30, main=\"Histogramme des Résidus\", xlab=\"Résidus\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-70-2.png){width=672}\n:::\n\n```{.r .cell-code}\nresidus<-residuals(modele1) \n\nshapiro.test(residus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residus\nW = 0.98024, p-value = 0.1614\n```\n\n\n:::\n\n```{.r .cell-code}\nks.test(residus, \"pnorm\", mean = mean(residus), sd = sd(residus))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact one-sample Kolmogorov-Smirnov test\n\ndata:  residus\nD = 0.071371, p-value = 0.6913\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n\np-value = 0,16 : hypothèse de normalité des résidus OK au seuil de risque de 5%\n\n#### **Test d'homoscédasticité des résidus**\n\nH0 = homoscedasticité\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbptest(modele1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modele1\nBP = 12.07, df = 25, p-value = 0.986\n```\n\n\n:::\n:::\n\n\n\np-value = 0.986 \\> 0,05 On ne rejette pas l'hypothèse nulle (à savoir l'homoscédasticité des résidus)\n\n#### Test de la linéarité de la forme fonctionnelle\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreset(modele1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  modele1\nRESET = 1.168, df1 = 2, df2 = 67, p-value = 0.3172\n```\n\n\n:::\n:::\n\n\n\np-value = 0.3172\n\np_value\\> 0,05 forme fonctionnelle linéaire du modèle spécifié est acceptée au seuil de 5%\n\n#### Analyse des observations influençant l'estimation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cooks.distance(modele1),type=\"h\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-73-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# OU option avec le seuil \n\ncooks_d <- cooks.distance(modele1)\n# Afficher le graphique des distances de Cook\nplot(cooks_d, type=\"h\", main=\"Distances de Cook\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-73-2.png){width=672}\n:::\n:::\n\n\n\n#### Vérification de la multicolinéarité après estimation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(modele1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           loisir       vie_sociale    cat_reseau_0_2 cat_reseau_6_sup6 \n         1.554233          1.759555          2.280368          2.266505 \n        cat_25_49       cat_plus_50        tel_inf_15        tel_sup_25 \n         2.947956          3.751426          1.679451          1.545372 \n    appareils_1_2  appareils_plus_4             abo_0             abo_2 \n         1.659030          1.495394          1.660307          1.936374 \n        abo_3_sup             homme         pas_ville cat_sans_activite \n         1.662921          1.478839          1.580720          2.212485 \n       cat_cadres        cat_autres ecran_travail_bcp ecran_travail_peu \n         2.249285          2.056297          1.841631          2.305654 \n     pas_internet    internet_autre        nuit_inf_7            jour_3 \n         1.240853          1.329520          1.425768          1.462933 \n           jour_2 \n         1.279849 \n```\n\n\n:::\n:::\n\n\n\nPas de problème de multicolinéarité entre les différentes variables explicatives du modèle\n\n# Step : Sélection des variables explicatives significatives (modèle linéaire = modele1 )\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodele0 <- (lm(temps_ecran~1,data=ecran))\nsummary(modele0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temps_ecran ~ 1, data = ecran)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-31.384  -9.384  -0.884   9.116  49.116 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    35.88       1.63   22.01   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.89 on 94 degrees of freedom\n```\n\n\n:::\n:::\n\n\n\n### Méthode ascendante\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep(modele0, scope=list(lower=modele0, upper=modele1), data=ecran, direction=\"forward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=526.5\ntemps_ecran ~ 1\n\n                    Df Sum of Sq   RSS    AIC\n+ ecran_travail_peu  1   1788.08 21952 521.06\n+ cat_reseau_6_sup6  1   1287.78 22452 523.20\n+ cat_reseau_0_2     1   1144.13 22596 523.81\n+ homme              1    915.94 22824 524.76\n+ jour_2             1    879.10 22861 524.92\n+ loisir             1    851.67 22889 525.03\n+ cat_cadres         1    659.84 23080 525.82\n+ cat_plus_50        1    545.29 23195 526.29\n<none>                           23740 526.50\n+ cat_sans_activite  1    441.91 23298 526.71\n+ abo_0              1    425.13 23315 526.78\n+ cat_autres         1    396.66 23344 526.90\n+ internet_autre     1    330.58 23410 527.17\n+ cat_25_49          1    264.11 23476 527.44\n+ tel_sup_25         1    243.20 23497 527.52\n+ jour_3             1    226.35 23514 527.59\n+ vie_sociale        1    222.86 23517 527.60\n+ nuit_inf_7         1    133.38 23607 527.96\n+ appareils_plus_4   1     36.83 23703 528.35\n+ tel_inf_15         1     14.77 23726 528.44\n+ abo_2              1     11.25 23729 528.45\n+ abo_3_sup          1      4.30 23736 528.48\n+ appareils_1_2      1      4.18 23736 528.48\n+ ecran_travail_bcp  1      2.74 23738 528.49\n+ pas_ville          1      1.20 23739 528.49\n+ pas_internet       1      0.79 23739 528.50\n\nStep:  AIC=521.06\ntemps_ecran ~ ecran_travail_peu\n\n                    Df Sum of Sq   RSS    AIC\n+ homme              1   1139.01 20813 518.00\n+ cat_reseau_6_sup6  1    945.82 21006 518.88\n+ cat_reseau_0_2     1    747.34 21205 519.77\n+ loisir             1    731.69 21220 519.84\n+ jour_2             1    556.61 21396 520.62\n+ ecran_travail_bcp  1    472.44 21480 520.99\n+ vie_sociale        1    461.79 21490 521.04\n<none>                           21952 521.06\n+ cat_25_49          1    316.88 21635 521.68\n+ abo_0              1    307.56 21645 521.72\n+ cat_sans_activite  1    240.24 21712 522.02\n+ cat_plus_50        1    233.15 21719 522.05\n+ internet_autre     1    210.96 21741 522.14\n+ cat_cadres         1    151.78 21800 522.40\n+ nuit_inf_7         1    125.19 21827 522.52\n+ cat_autres         1    122.97 21829 522.53\n+ abo_2              1    109.71 21842 522.58\n+ tel_sup_25         1     91.66 21860 522.66\n+ pas_ville          1     60.76 21891 522.80\n+ jour_3             1     44.64 21908 522.87\n+ appareils_1_2      1     32.05 21920 522.92\n+ pas_internet       1     16.07 21936 522.99\n+ appareils_plus_4   1     11.32 21941 523.01\n+ tel_inf_15         1      2.92 21949 523.05\n+ abo_3_sup          1      0.08 21952 523.06\n\nStep:  AIC=518\ntemps_ecran ~ ecran_travail_peu + homme\n\n                    Df Sum of Sq   RSS    AIC\n+ cat_reseau_6_sup6  1   1021.05 19792 515.22\n+ loisir             1    692.86 20120 516.78\n+ cat_reseau_0_2     1    644.59 20168 517.01\n+ vie_sociale        1    549.14 20264 517.46\n<none>                           20813 518.00\n+ cat_sans_activite  1    398.57 20415 518.16\n+ ecran_travail_bcp  1    393.38 20420 518.19\n+ jour_2             1    393.19 20420 518.19\n+ cat_plus_50        1    377.93 20435 518.26\n+ cat_25_49          1    320.40 20493 518.53\n+ abo_0              1    267.13 20546 518.77\n+ internet_autre     1    250.67 20562 518.85\n+ nuit_inf_7         1    173.35 20640 519.20\n+ cat_autres         1    150.06 20663 519.31\n+ pas_ville          1    138.11 20675 519.37\n+ tel_inf_15         1    105.85 20707 519.51\n+ abo_2              1     97.76 20715 519.55\n+ appareils_1_2      1     36.45 20777 519.83\n+ tel_sup_25         1     26.36 20787 519.88\n+ appareils_plus_4   1     16.65 20796 519.92\n+ jour_3             1      6.17 20807 519.97\n+ pas_internet       1      4.49 20809 519.98\n+ abo_3_sup          1      2.91 20810 519.99\n+ cat_cadres         1      1.20 20812 519.99\n\nStep:  AIC=515.22\ntemps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6\n\n                    Df Sum of Sq   RSS    AIC\n+ ecran_travail_bcp  1    500.53 19292 514.79\n<none>                           19792 515.22\n+ internet_autre     1    402.56 19390 515.27\n+ loisir             1    373.08 19419 515.41\n+ vie_sociale        1    371.53 19421 515.42\n+ cat_reseau_0_2     1    250.75 19541 516.01\n+ jour_2             1    191.15 19601 516.30\n+ cat_plus_50        1    188.68 19603 516.31\n+ appareils_1_2      1    180.11 19612 516.35\n+ pas_ville          1    151.31 19641 516.49\n+ tel_sup_25         1    123.32 19669 516.63\n+ tel_inf_15         1    122.30 19670 516.63\n+ nuit_inf_7         1    118.01 19674 516.65\n+ abo_0              1    112.54 19680 516.68\n+ cat_cadres         1    102.20 19690 516.73\n+ abo_3_sup          1    101.90 19690 516.73\n+ cat_autres         1     89.74 19702 516.79\n+ jour_3             1     71.74 19720 516.88\n+ cat_sans_activite  1     69.89 19722 516.88\n+ abo_2              1     56.34 19736 516.95\n+ appareils_plus_4   1     32.90 19759 517.06\n+ cat_25_49          1     29.19 19763 517.08\n+ pas_internet       1      0.01 19792 517.22\n\nStep:  AIC=514.79\ntemps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp\n\n                    Df Sum of Sq   RSS    AIC\n+ internet_autre     1    650.73 18641 513.53\n+ vie_sociale        1    416.49 18875 514.71\n<none>                           19292 514.79\n+ appareils_1_2      1    319.75 18972 515.20\n+ loisir             1    289.32 19002 515.35\n+ tel_sup_25         1    219.49 19072 515.70\n+ jour_2             1    213.87 19078 515.73\n+ pas_ville          1    189.54 19102 515.85\n+ cat_reseau_0_2     1    177.97 19114 515.91\n+ abo_2              1    175.09 19116 515.92\n+ nuit_inf_7         1    132.86 19159 516.13\n+ abo_0              1    105.66 19186 516.27\n+ tel_inf_15         1    103.24 19188 516.28\n+ cat_plus_50        1     93.26 19198 516.33\n+ cat_sans_activite  1     85.97 19206 516.36\n+ cat_cadres         1     64.55 19227 516.47\n+ cat_25_49          1     59.98 19232 516.49\n+ abo_3_sup          1     35.89 19256 516.61\n+ cat_autres         1     32.87 19259 516.62\n+ appareils_plus_4   1     27.87 19264 516.65\n+ jour_3             1     23.01 19269 516.67\n+ pas_internet       1     13.76 19278 516.72\n\nStep:  AIC=513.53\ntemps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp + internet_autre\n\n                    Df Sum of Sq   RSS    AIC\n+ vie_sociale        1    399.35 18242 513.47\n<none>                           18641 513.53\n+ loisir             1    356.70 18284 513.69\n+ appareils_1_2      1    312.00 18329 513.92\n+ jour_2             1    282.17 18359 514.08\n+ tel_sup_25         1    264.16 18377 514.17\n+ pas_ville          1    256.80 18384 514.21\n+ cat_reseau_0_2     1    174.27 18467 514.63\n+ abo_2              1    125.97 18515 514.88\n+ cat_cadres         1    110.88 18530 514.96\n+ abo_0              1    105.68 18535 514.99\n+ cat_plus_50        1     99.34 18542 515.02\n+ cat_autres         1     93.82 18547 515.05\n+ abo_3_sup          1     62.40 18578 515.21\n+ tel_inf_15         1     57.32 18584 515.23\n+ pas_internet       1     46.94 18594 515.29\n+ cat_sans_activite  1     31.00 18610 515.37\n+ appareils_plus_4   1     27.80 18613 515.39\n+ nuit_inf_7         1     25.83 18615 515.40\n+ cat_25_49          1     11.73 18629 515.47\n+ jour_3             1      4.38 18636 515.50\n\nStep:  AIC=513.47\ntemps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp + internet_autre + vie_sociale\n\n                    Df Sum of Sq   RSS    AIC\n<none>                           18242 513.47\n+ appareils_1_2      1    342.00 17900 513.67\n+ tel_sup_25         1    296.33 17945 513.91\n+ pas_ville          1    267.20 17974 514.07\n+ jour_2             1    267.04 17974 514.07\n+ cat_plus_50        1    258.27 17983 514.12\n+ abo_0              1    250.90 17991 514.15\n+ cat_reseau_0_2     1    133.87 18108 514.77\n+ cat_cadres         1    131.15 18110 514.78\n+ loisir             1    128.27 18113 514.80\n+ cat_autres         1    100.27 18141 514.95\n+ abo_3_sup          1     75.30 18166 515.08\n+ tel_inf_15         1     62.36 18179 515.14\n+ pas_internet       1     58.22 18183 515.17\n+ abo_2              1     44.64 18197 515.24\n+ appareils_plus_4   1     33.69 18208 515.29\n+ cat_25_49          1     10.91 18231 515.41\n+ nuit_inf_7         1      6.93 18235 515.43\n+ cat_sans_activite  1      3.03 18238 515.45\n+ jour_3             1      0.16 18241 515.47\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp + internet_autre + vie_sociale, data = ecran)\n\nCoefficients:\n       (Intercept)  ecran_travail_peu1              homme1  cat_reseau_6_sup61  \n           38.5981            -11.9641              8.2840              8.5305  \necran_travail_bcp1     internet_autre1         vie_sociale  \n           -7.4881              6.0100             -0.1663  \n```\n\n\n:::\n\n```{.r .cell-code}\n#AIC=513.47\n```\n:::\n\n\n\nStep: AIC=513.47\n\ntemps_ecran \\~ ecran_travail_peu + homme + cat_reseau_6_sup6 + ecran_travail_bcp + internet_autre + vie_sociale\n\n### Méthode descendante\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep(modele1, data=ecran,direction=\"backward\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=530.48\ntemps_ecran ~ loisir + vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    cat_25_49 + cat_plus_50 + tel_inf_15 + tel_sup_25 + appareils_1_2 + \n    appareils_plus_4 + abo_0 + abo_2 + abo_3_sup + homme + pas_ville + \n    cat_sans_activite + cat_cadres + cat_autres + ecran_travail_bcp + \n    ecran_travail_peu + pas_internet + internet_autre + nuit_inf_7 + \n    jour_3 + jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- jour_3             1      5.27 14631 528.52\n- nuit_inf_7         1      9.82 14636 528.55\n- cat_25_49          1     16.29 14642 528.59\n- cat_sans_activite  1     40.94 14667 528.75\n- cat_plus_50        1     47.06 14673 528.79\n- loisir             1     53.54 14679 528.83\n- cat_autres         1     74.97 14701 528.97\n- tel_inf_15         1     86.91 14712 529.05\n- appareils_plus_4   1    118.42 14744 529.25\n- cat_reseau_0_2     1    134.58 14760 529.35\n- pas_internet       1    135.49 14761 529.36\n- abo_3_sup          1    141.46 14767 529.40\n- jour_2             1    168.10 14794 529.57\n- vie_sociale        1    278.69 14904 530.28\n<none>                           14626 530.48\n- abo_2              1    371.26 14997 530.86\n- cat_cadres         1    421.95 15048 531.18\n- homme              1    476.96 15103 531.53\n- abo_0              1    564.99 15191 532.08\n- tel_sup_25         1    617.98 15244 532.41\n- internet_autre     1    631.41 15257 532.50\n- pas_ville          1    639.36 15265 532.55\n- cat_reseau_6_sup6  1    679.95 15306 532.80\n- appareils_1_2      1   1024.10 15650 534.91\n- ecran_travail_bcp  1   1329.03 15955 536.74\n- ecran_travail_peu  1   1536.95 16163 537.97\n\nStep:  AIC=528.52\ntemps_ecran ~ loisir + vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    cat_25_49 + cat_plus_50 + tel_inf_15 + tel_sup_25 + appareils_1_2 + \n    appareils_plus_4 + abo_0 + abo_2 + abo_3_sup + homme + pas_ville + \n    cat_sans_activite + cat_cadres + cat_autres + ecran_travail_bcp + \n    ecran_travail_peu + pas_internet + internet_autre + nuit_inf_7 + \n    jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- nuit_inf_7         1      7.39 14638 526.56\n- cat_25_49          1     14.17 14645 526.61\n- cat_sans_activite  1     38.94 14670 526.77\n- cat_plus_50        1     44.92 14676 526.81\n- loisir             1     51.00 14682 526.85\n- cat_autres         1     71.12 14702 526.98\n- tel_inf_15         1     83.22 14714 527.06\n- appareils_plus_4   1    114.40 14745 527.26\n- cat_reseau_0_2     1    130.89 14762 527.36\n- pas_internet       1    133.48 14764 527.38\n- abo_3_sup          1    155.66 14787 527.52\n- jour_2             1    183.96 14815 527.70\n- vie_sociale        1    284.41 14915 528.35\n<none>                           14631 528.52\n- abo_2              1    366.19 14997 528.86\n- cat_cadres         1    420.16 15051 529.21\n- homme              1    472.85 15104 529.54\n- abo_0              1    594.32 15225 530.30\n- tel_sup_25         1    613.01 15244 530.42\n- pas_ville          1    635.13 15266 530.55\n- internet_autre     1    636.44 15267 530.56\n- cat_reseau_6_sup6  1    766.45 15397 531.37\n- appareils_1_2      1   1048.54 15679 533.09\n- ecran_travail_bcp  1   1362.38 15993 534.97\n- ecran_travail_peu  1   1649.19 16280 536.66\n\nStep:  AIC=526.56\ntemps_ecran ~ loisir + vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    cat_25_49 + cat_plus_50 + tel_inf_15 + tel_sup_25 + appareils_1_2 + \n    appareils_plus_4 + abo_0 + abo_2 + abo_3_sup + homme + pas_ville + \n    cat_sans_activite + cat_cadres + cat_autres + ecran_travail_bcp + \n    ecran_travail_peu + pas_internet + internet_autre + jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- cat_25_49          1     17.50 14656 524.68\n- cat_sans_activite  1     41.53 14680 524.83\n- cat_plus_50        1     46.08 14684 524.86\n- loisir             1     46.88 14685 524.87\n- cat_autres         1     73.36 14712 525.04\n- tel_inf_15         1     78.50 14717 525.07\n- appareils_plus_4   1    110.81 14749 525.28\n- pas_internet       1    128.38 14767 525.39\n- cat_reseau_0_2     1    136.35 14775 525.45\n- abo_3_sup          1    173.37 14812 525.68\n- jour_2             1    178.05 14816 525.71\n- vie_sociale        1    306.70 14945 526.53\n<none>                           14638 526.56\n- abo_2              1    370.26 15009 526.94\n- cat_cadres         1    425.64 15064 527.29\n- homme              1    467.43 15106 527.55\n- tel_sup_25         1    605.68 15244 528.42\n- pas_ville          1    636.93 15275 528.61\n- internet_autre     1    694.92 15333 528.97\n- abo_0              1    697.95 15336 528.99\n- cat_reseau_6_sup6  1    760.35 15399 529.38\n- appareils_1_2      1   1042.75 15681 531.10\n- ecran_travail_bcp  1   1358.30 15997 532.99\n- ecran_travail_peu  1   1645.31 16284 534.68\n\nStep:  AIC=524.68\ntemps_ecran ~ loisir + vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    cat_plus_50 + tel_inf_15 + tel_sup_25 + appareils_1_2 + appareils_plus_4 + \n    abo_0 + abo_2 + abo_3_sup + homme + pas_ville + cat_sans_activite + \n    cat_cadres + cat_autres + ecran_travail_bcp + ecran_travail_peu + \n    pas_internet + internet_autre + jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- cat_plus_50        1     28.64 14684 522.86\n- loisir             1     45.40 14701 522.97\n- cat_autres         1     58.33 14714 523.06\n- cat_sans_activite  1     63.88 14720 523.09\n- tel_inf_15         1     78.99 14735 523.19\n- appareils_plus_4   1     99.94 14756 523.32\n- pas_internet       1    116.34 14772 523.43\n- abo_3_sup          1    161.44 14817 523.72\n- jour_2             1    170.05 14826 523.77\n- cat_reseau_0_2     1    172.53 14828 523.79\n<none>                           14656 524.68\n- vie_sociale        1    322.70 14978 524.75\n- abo_2              1    357.17 15013 524.97\n- cat_cadres         1    408.42 15064 525.29\n- homme              1    479.63 15135 525.74\n- tel_sup_25         1    648.76 15305 526.79\n- abo_0              1    682.84 15339 527.00\n- pas_ville          1    694.59 15350 527.08\n- internet_autre     1    771.34 15427 527.55\n- cat_reseau_6_sup6  1   1009.78 15666 529.01\n- appareils_1_2      1   1121.98 15778 529.69\n- ecran_travail_bcp  1   1385.80 16042 531.26\n- ecran_travail_peu  1   1656.65 16312 532.85\n\nStep:  AIC=522.86\ntemps_ecran ~ loisir + vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_inf_15 + tel_sup_25 + appareils_1_2 + appareils_plus_4 + \n    abo_0 + abo_2 + abo_3_sup + homme + pas_ville + cat_sans_activite + \n    cat_cadres + cat_autres + ecran_travail_bcp + ecran_travail_peu + \n    pas_internet + internet_autre + jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- loisir             1     34.35 14719 521.09\n- cat_autres         1     40.63 14725 521.13\n- cat_sans_activite  1     67.83 14752 521.30\n- tel_inf_15         1    101.08 14786 521.52\n- appareils_plus_4   1    101.61 14786 521.52\n- pas_internet       1    114.78 14799 521.60\n- abo_3_sup          1    190.11 14874 522.09\n- jour_2             1    200.76 14885 522.15\n- vie_sociale        1    294.10 14978 522.75\n<none>                           14684 522.86\n- cat_reseau_0_2     1    328.21 15013 522.96\n- cat_cadres         1    380.42 15065 523.29\n- abo_2              1    393.65 15078 523.38\n- homme              1    466.01 15150 523.83\n- tel_sup_25         1    671.22 15356 525.11\n- pas_ville          1    696.12 15381 525.26\n- abo_0              1    703.32 15388 525.31\n- internet_autre     1    767.42 15452 525.70\n- cat_reseau_6_sup6  1   1021.64 15706 527.25\n- appareils_1_2      1   1140.31 15825 527.97\n- ecran_travail_bcp  1   1493.29 16178 530.06\n- ecran_travail_peu  1   1820.54 16505 531.97\n\nStep:  AIC=521.09\ntemps_ecran ~ vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_inf_15 + tel_sup_25 + appareils_1_2 + appareils_plus_4 + \n    abo_0 + abo_2 + abo_3_sup + homme + pas_ville + cat_sans_activite + \n    cat_cadres + cat_autres + ecran_travail_bcp + ecran_travail_peu + \n    pas_internet + internet_autre + jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- cat_autres         1     35.01 14754 519.31\n- cat_sans_activite  1     75.94 14795 519.57\n- tel_inf_15         1     86.34 14805 519.64\n- appareils_plus_4   1    102.32 14821 519.74\n- pas_internet       1    120.40 14839 519.86\n- abo_3_sup          1    196.05 14915 520.34\n- jour_2             1    233.89 14953 520.58\n<none>                           14719 521.09\n- cat_reseau_0_2     1    330.41 15049 521.19\n- abo_2              1    406.30 15125 521.67\n- cat_cadres         1    408.57 15127 521.69\n- vie_sociale        1    445.52 15164 521.92\n- homme              1    456.91 15176 521.99\n- tel_sup_25         1    683.80 15403 523.40\n- abo_0              1    698.78 15418 523.49\n- pas_ville          1    718.12 15437 523.61\n- internet_autre     1    757.57 15476 523.85\n- cat_reseau_6_sup6  1   1099.26 15818 525.93\n- appareils_1_2      1   1127.62 15846 526.10\n- ecran_travail_bcp  1   1576.39 16295 528.75\n- ecran_travail_peu  1   1841.36 16560 530.28\n\nStep:  AIC=519.31\ntemps_ecran ~ vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_inf_15 + tel_sup_25 + appareils_1_2 + appareils_plus_4 + \n    abo_0 + abo_2 + abo_3_sup + homme + pas_ville + cat_sans_activite + \n    cat_cadres + ecran_travail_bcp + ecran_travail_peu + pas_internet + \n    internet_autre + jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- cat_sans_activite  1     49.42 14803 517.63\n- tel_inf_15         1     63.03 14817 517.72\n- appareils_plus_4   1    111.33 14865 518.03\n- pas_internet       1    118.11 14872 518.07\n- abo_3_sup          1    179.69 14934 518.46\n- jour_2             1    238.22 14992 518.83\n- cat_reseau_0_2     1    301.61 15055 519.23\n<none>                           14754 519.31\n- cat_cadres         1    373.56 15127 519.69\n- abo_2              1    401.86 15156 519.86\n- vie_sociale        1    466.73 15220 520.27\n- homme              1    472.56 15226 520.31\n- tel_sup_25         1    655.29 15409 521.44\n- pas_ville          1    683.30 15437 521.61\n- abo_0              1    684.14 15438 521.62\n- internet_autre     1    863.67 15618 522.72\n- cat_reseau_6_sup6  1   1094.96 15849 524.11\n- appareils_1_2      1   1124.81 15879 524.29\n- ecran_travail_bcp  1   1543.24 16297 526.76\n- ecran_travail_peu  1   1808.15 16562 528.29\n\nStep:  AIC=517.63\ntemps_ecran ~ vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_inf_15 + tel_sup_25 + appareils_1_2 + appareils_plus_4 + \n    abo_0 + abo_2 + abo_3_sup + homme + pas_ville + cat_cadres + \n    ecran_travail_bcp + ecran_travail_peu + pas_internet + internet_autre + \n    jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- tel_inf_15         1     54.91 14858 515.98\n- appareils_plus_4   1     86.29 14890 516.18\n- pas_internet       1    101.58 14905 516.28\n- abo_3_sup          1    221.50 15025 517.04\n- jour_2             1    224.29 15028 517.06\n<none>                           14803 517.63\n- cat_cadres         1    337.67 15141 517.77\n- cat_reseau_0_2     1    345.44 15149 517.82\n- abo_2              1    376.00 15179 518.01\n- homme              1    461.51 15265 518.55\n- vie_sociale        1    573.93 15377 519.24\n- tel_sup_25         1    608.76 15412 519.46\n- pas_ville          1    655.57 15459 519.75\n- abo_0              1    741.51 15545 520.27\n- internet_autre     1    938.33 15742 521.47\n- appareils_1_2      1   1189.94 15993 522.97\n- cat_reseau_6_sup6  1   1319.63 16123 523.74\n- ecran_travail_bcp  1   1503.17 16306 524.82\n- ecran_travail_peu  1   1875.51 16679 526.96\n\nStep:  AIC=515.98\ntemps_ecran ~ vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + appareils_plus_4 + abo_0 + abo_2 + \n    abo_3_sup + homme + pas_ville + cat_cadres + ecran_travail_bcp + \n    ecran_travail_peu + pas_internet + internet_autre + jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- appareils_plus_4   1     72.43 14931 514.44\n- pas_internet       1    121.13 14979 514.75\n- abo_3_sup          1    215.61 15074 515.35\n- jour_2             1    217.00 15075 515.36\n<none>                           14858 515.98\n- cat_cadres         1    367.23 15225 516.30\n- homme              1    409.71 15268 516.56\n- cat_reseau_0_2     1    435.31 15293 516.72\n- abo_2              1    448.59 15307 516.81\n- tel_sup_25         1    554.24 15412 517.46\n- vie_sociale        1    555.55 15414 517.47\n- pas_ville          1    654.08 15512 518.07\n- abo_0              1    829.91 15688 519.14\n- internet_autre     1    990.13 15848 520.11\n- appareils_1_2      1   1186.06 16044 521.28\n- cat_reseau_6_sup6  1   1269.59 16128 521.77\n- ecran_travail_bcp  1   1530.49 16389 523.29\n- ecran_travail_peu  1   1822.47 16681 524.97\n\nStep:  AIC=514.44\ntemps_ecran ~ vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + abo_2 + abo_3_sup + \n    homme + pas_ville + cat_cadres + ecran_travail_bcp + ecran_travail_peu + \n    pas_internet + internet_autre + jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- pas_internet       1    103.98 15034 513.10\n- jour_2             1    212.23 15143 513.78\n- abo_3_sup          1    231.08 15162 513.90\n<none>                           14931 514.44\n- cat_cadres         1    384.07 15315 514.86\n- homme              1    412.73 15343 515.03\n- cat_reseau_0_2     1    419.03 15350 515.07\n- abo_2              1    438.88 15369 515.19\n- tel_sup_25         1    501.82 15432 515.58\n- vie_sociale        1    552.94 15484 515.90\n- pas_ville          1    821.81 15752 517.53\n- abo_0              1    871.71 15802 517.83\n- internet_autre     1    998.77 15929 518.59\n- appareils_1_2      1   1117.91 16048 519.30\n- cat_reseau_6_sup6  1   1228.32 16159 519.95\n- ecran_travail_bcp  1   1497.76 16428 521.52\n- ecran_travail_peu  1   1750.53 16681 522.97\n\nStep:  AIC=513.1\ntemps_ecran ~ vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + abo_2 + abo_3_sup + \n    homme + pas_ville + cat_cadres + ecran_travail_bcp + ecran_travail_peu + \n    internet_autre + jour_2\n\n                    Df Sum of Sq   RSS    AIC\n- jour_2             1    188.89 15223 512.29\n- abo_3_sup          1    240.83 15275 512.61\n<none>                           15034 513.10\n- cat_cadres         1    348.74 15383 513.28\n- abo_2              1    388.22 15423 513.52\n- homme              1    419.97 15454 513.72\n- cat_reseau_0_2     1    453.04 15488 513.92\n- tel_sup_25         1    489.35 15524 514.14\n- vie_sociale        1    549.55 15584 514.51\n- abo_0              1    872.97 15908 516.46\n- pas_ville          1    886.23 15921 516.54\n- internet_autre     1    937.61 15972 516.85\n- appareils_1_2      1   1089.59 16124 517.75\n- cat_reseau_6_sup6  1   1160.41 16195 518.16\n- ecran_travail_bcp  1   1396.10 16431 519.54\n- ecran_travail_peu  1   1759.02 16794 521.61\n\nStep:  AIC=512.29\ntemps_ecran ~ vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + abo_2 + abo_3_sup + \n    homme + pas_ville + cat_cadres + ecran_travail_bcp + ecran_travail_peu + \n    internet_autre\n\n                    Df Sum of Sq   RSS    AIC\n- abo_3_sup          1    260.50 15484 511.90\n- cat_cadres         1    295.09 15518 512.11\n<none>                           15223 512.29\n- abo_2              1    449.54 15673 513.05\n- tel_sup_25         1    495.44 15719 513.33\n- homme              1    524.70 15748 513.51\n- vie_sociale        1    536.65 15760 513.58\n- cat_reseau_0_2     1    561.94 15785 513.73\n- internet_autre     1    868.19 16092 515.56\n- abo_0              1    877.55 16101 515.61\n- pas_ville          1    962.09 16186 516.11\n- appareils_1_2      1   1064.19 16288 516.71\n- cat_reseau_6_sup6  1   1233.28 16457 517.69\n- ecran_travail_bcp  1   1358.26 16582 518.41\n- ecran_travail_peu  1   1975.91 17199 521.88\n\nStep:  AIC=511.9\ntemps_ecran ~ vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + abo_2 + homme + pas_ville + \n    cat_cadres + ecran_travail_bcp + ecran_travail_peu + internet_autre\n\n                    Df Sum of Sq   RSS    AIC\n- abo_2              1    267.92 15752 511.53\n<none>                           15484 511.90\n- cat_cadres         1    332.59 15816 511.92\n- cat_reseau_0_2     1    483.16 15967 512.82\n- homme              1    487.25 15971 512.84\n- tel_sup_25         1    503.96 15988 512.94\n- vie_sociale        1    531.70 16016 513.11\n- abo_0              1    667.55 16152 513.91\n- internet_autre     1    835.51 16319 514.89\n- pas_ville          1    993.78 16478 515.81\n- cat_reseau_6_sup6  1   1157.27 16641 516.75\n- appareils_1_2      1   1182.63 16667 516.89\n- ecran_travail_bcp  1   1526.08 17010 518.83\n- ecran_travail_peu  1   1948.70 17433 521.16\n\nStep:  AIC=511.53\ntemps_ecran ~ vie_sociale + cat_reseau_0_2 + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + homme + pas_ville + \n    cat_cadres + ecran_travail_bcp + ecran_travail_peu + internet_autre\n\n                    Df Sum of Sq   RSS    AIC\n- cat_reseau_0_2     1    316.85 16069 511.42\n<none>                           15752 511.53\n- tel_sup_25         1    373.87 16126 511.76\n- cat_cadres         1    400.78 16153 511.92\n- homme              1    528.26 16280 512.66\n- abo_0              1    544.14 16296 512.76\n- vie_sociale        1    760.65 16512 514.01\n- internet_autre     1    916.88 16669 514.90\n- pas_ville          1    920.86 16673 514.93\n- appareils_1_2      1   1298.91 17051 517.06\n- ecran_travail_bcp  1   1321.22 17073 517.18\n- cat_reseau_6_sup6  1   1407.95 17160 517.66\n- ecran_travail_peu  1   1756.20 17508 519.57\n\nStep:  AIC=511.42\ntemps_ecran ~ vie_sociale + cat_reseau_6_sup6 + tel_sup_25 + \n    appareils_1_2 + abo_0 + homme + pas_ville + cat_cadres + \n    ecran_travail_bcp + ecran_travail_peu + internet_autre\n\n                    Df Sum of Sq   RSS    AIC\n<none>                           16069 511.42\n- cat_cadres         1    346.34 16415 511.45\n- tel_sup_25         1    380.31 16449 511.64\n- abo_0              1    550.44 16619 512.62\n- homme              1    596.09 16665 512.88\n- pas_ville          1    756.68 16825 513.79\n- vie_sociale        1    839.09 16908 514.26\n- internet_autre     1    895.35 16964 514.57\n- appareils_1_2      1   1198.48 17267 516.26\n- ecran_travail_bcp  1   1450.38 17519 517.63\n- cat_reseau_6_sup6  1   1862.34 17931 519.84\n- ecran_travail_peu  1   2018.44 18087 520.66\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temps_ecran ~ vie_sociale + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + homme + pas_ville + \n    cat_cadres + ecran_travail_bcp + ecran_travail_peu + internet_autre, \n    data = ecran)\n\nCoefficients:\n       (Intercept)         vie_sociale  cat_reseau_6_sup61         tel_sup_251  \n           36.4523             -0.2519             12.3794             -5.3294  \n    appareils_1_21              abo_01              homme1          pas_ville1  \n           11.8095             -6.8988              6.4134              6.3371  \n       cat_cadres1  ecran_travail_bcp1  ecran_travail_peu1     internet_autre1  \n            6.4451            -10.5870            -12.7396              7.2202  \n```\n\n\n:::\n\n```{.r .cell-code}\n# Step:  AIC=511.42\n```\n:::\n\n\n\nStep: AIC=511.42temps_ecran \\~ vie_sociale + cat_reseau_6_sup6 + tel_sup_25 + appareils_1_2 + abo_0 + homme + pas_ville + cat_cadres + ecran_travail_bcp + ecran_travail_peu + internet_autre\n\n### Méthode double\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#méthode dans les 2 sens\nstep(modele0, scope = list(upper=modele1),data=ecran,direction=\"both\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=526.5\ntemps_ecran ~ 1\n\n                    Df Sum of Sq   RSS    AIC\n+ ecran_travail_peu  1   1788.08 21952 521.06\n+ cat_reseau_6_sup6  1   1287.78 22452 523.20\n+ cat_reseau_0_2     1   1144.13 22596 523.81\n+ homme              1    915.94 22824 524.76\n+ jour_2             1    879.10 22861 524.92\n+ loisir             1    851.67 22889 525.03\n+ cat_cadres         1    659.84 23080 525.82\n+ cat_plus_50        1    545.29 23195 526.29\n<none>                           23740 526.50\n+ cat_sans_activite  1    441.91 23298 526.71\n+ abo_0              1    425.13 23315 526.78\n+ cat_autres         1    396.66 23344 526.90\n+ internet_autre     1    330.58 23410 527.17\n+ cat_25_49          1    264.11 23476 527.44\n+ tel_sup_25         1    243.20 23497 527.52\n+ jour_3             1    226.35 23514 527.59\n+ vie_sociale        1    222.86 23517 527.60\n+ nuit_inf_7         1    133.38 23607 527.96\n+ appareils_plus_4   1     36.83 23703 528.35\n+ tel_inf_15         1     14.77 23726 528.44\n+ abo_2              1     11.25 23729 528.45\n+ abo_3_sup          1      4.30 23736 528.48\n+ appareils_1_2      1      4.18 23736 528.48\n+ ecran_travail_bcp  1      2.74 23738 528.49\n+ pas_ville          1      1.20 23739 528.49\n+ pas_internet       1      0.79 23739 528.50\n\nStep:  AIC=521.06\ntemps_ecran ~ ecran_travail_peu\n\n                    Df Sum of Sq   RSS    AIC\n+ homme              1   1139.01 20813 518.00\n+ cat_reseau_6_sup6  1    945.82 21006 518.88\n+ cat_reseau_0_2     1    747.34 21205 519.77\n+ loisir             1    731.69 21220 519.84\n+ jour_2             1    556.61 21396 520.62\n+ ecran_travail_bcp  1    472.44 21480 520.99\n+ vie_sociale        1    461.79 21490 521.04\n<none>                           21952 521.06\n+ cat_25_49          1    316.88 21635 521.68\n+ abo_0              1    307.56 21645 521.72\n+ cat_sans_activite  1    240.24 21712 522.02\n+ cat_plus_50        1    233.15 21719 522.05\n+ internet_autre     1    210.96 21741 522.14\n+ cat_cadres         1    151.78 21800 522.40\n+ nuit_inf_7         1    125.19 21827 522.52\n+ cat_autres         1    122.97 21829 522.53\n+ abo_2              1    109.71 21842 522.58\n+ tel_sup_25         1     91.66 21860 522.66\n+ pas_ville          1     60.76 21891 522.80\n+ jour_3             1     44.64 21908 522.87\n+ appareils_1_2      1     32.05 21920 522.92\n+ pas_internet       1     16.07 21936 522.99\n+ appareils_plus_4   1     11.32 21941 523.01\n+ tel_inf_15         1      2.92 21949 523.05\n+ abo_3_sup          1      0.08 21952 523.06\n- ecran_travail_peu  1   1788.08 23740 526.50\n\nStep:  AIC=518\ntemps_ecran ~ ecran_travail_peu + homme\n\n                    Df Sum of Sq   RSS    AIC\n+ cat_reseau_6_sup6  1   1021.05 19792 515.22\n+ loisir             1    692.86 20120 516.78\n+ cat_reseau_0_2     1    644.59 20168 517.01\n+ vie_sociale        1    549.14 20264 517.46\n<none>                           20813 518.00\n+ cat_sans_activite  1    398.57 20415 518.16\n+ ecran_travail_bcp  1    393.38 20420 518.19\n+ jour_2             1    393.19 20420 518.19\n+ cat_plus_50        1    377.93 20435 518.26\n+ cat_25_49          1    320.40 20493 518.53\n+ abo_0              1    267.13 20546 518.77\n+ internet_autre     1    250.67 20562 518.85\n+ nuit_inf_7         1    173.35 20640 519.20\n+ cat_autres         1    150.06 20663 519.31\n+ pas_ville          1    138.11 20675 519.37\n+ tel_inf_15         1    105.85 20707 519.51\n+ abo_2              1     97.76 20715 519.55\n+ appareils_1_2      1     36.45 20777 519.83\n+ tel_sup_25         1     26.36 20787 519.88\n+ appareils_plus_4   1     16.65 20796 519.92\n+ jour_3             1      6.17 20807 519.97\n+ pas_internet       1      4.49 20809 519.98\n+ abo_3_sup          1      2.91 20810 519.99\n+ cat_cadres         1      1.20 20812 519.99\n- homme              1   1139.01 21952 521.06\n- ecran_travail_peu  1   2011.15 22824 524.76\n\nStep:  AIC=515.22\ntemps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6\n\n                    Df Sum of Sq   RSS    AIC\n+ ecran_travail_bcp  1    500.53 19292 514.79\n<none>                           19792 515.22\n+ internet_autre     1    402.56 19390 515.27\n+ loisir             1    373.08 19419 515.41\n+ vie_sociale        1    371.53 19421 515.42\n+ cat_reseau_0_2     1    250.75 19541 516.01\n+ jour_2             1    191.15 19601 516.30\n+ cat_plus_50        1    188.68 19603 516.31\n+ appareils_1_2      1    180.11 19612 516.35\n+ pas_ville          1    151.31 19641 516.49\n+ tel_sup_25         1    123.32 19669 516.63\n+ tel_inf_15         1    122.30 19670 516.63\n+ nuit_inf_7         1    118.01 19674 516.65\n+ abo_0              1    112.54 19680 516.68\n+ cat_cadres         1    102.20 19690 516.73\n+ abo_3_sup          1    101.90 19690 516.73\n+ cat_autres         1     89.74 19702 516.79\n+ jour_3             1     71.74 19720 516.88\n+ cat_sans_activite  1     69.89 19722 516.88\n+ abo_2              1     56.34 19736 516.95\n+ appareils_plus_4   1     32.90 19759 517.06\n+ cat_25_49          1     29.19 19763 517.08\n+ pas_internet       1      0.01 19792 517.22\n- cat_reseau_6_sup6  1   1021.05 20813 518.00\n- homme              1   1214.24 21006 518.88\n- ecran_travail_peu  1   1642.63 21435 520.79\n\nStep:  AIC=514.79\ntemps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp\n\n                    Df Sum of Sq   RSS    AIC\n+ internet_autre     1    650.73 18641 513.53\n+ vie_sociale        1    416.49 18875 514.71\n<none>                           19292 514.79\n+ appareils_1_2      1    319.75 18972 515.20\n- ecran_travail_bcp  1    500.53 19792 515.22\n+ loisir             1    289.32 19002 515.35\n+ tel_sup_25         1    219.49 19072 515.70\n+ jour_2             1    213.87 19078 515.73\n+ pas_ville          1    189.54 19102 515.85\n+ cat_reseau_0_2     1    177.97 19114 515.91\n+ abo_2              1    175.09 19116 515.92\n+ nuit_inf_7         1    132.86 19159 516.13\n+ abo_0              1    105.66 19186 516.27\n+ tel_inf_15         1    103.24 19188 516.28\n+ cat_plus_50        1     93.26 19198 516.33\n+ cat_sans_activite  1     85.97 19206 516.36\n+ cat_cadres         1     64.55 19227 516.47\n+ cat_25_49          1     59.98 19232 516.49\n+ abo_3_sup          1     35.89 19256 516.61\n+ cat_autres         1     32.87 19259 516.62\n+ appareils_plus_4   1     27.87 19264 516.65\n+ jour_3             1     23.01 19269 516.67\n+ pas_internet       1     13.76 19278 516.72\n- homme              1   1126.85 20418 518.18\n- cat_reseau_6_sup6  1   1128.20 20420 518.19\n- ecran_travail_peu  1   2129.96 21422 522.74\n\nStep:  AIC=513.53\ntemps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp + internet_autre\n\n                    Df Sum of Sq   RSS    AIC\n+ vie_sociale        1    399.35 18242 513.47\n<none>                           18641 513.53\n+ loisir             1    356.70 18284 513.69\n+ appareils_1_2      1    312.00 18329 513.92\n+ jour_2             1    282.17 18359 514.08\n+ tel_sup_25         1    264.16 18377 514.17\n+ pas_ville          1    256.80 18384 514.21\n+ cat_reseau_0_2     1    174.27 18467 514.63\n- internet_autre     1    650.73 19292 514.79\n+ abo_2              1    125.97 18515 514.88\n+ cat_cadres         1    110.88 18530 514.96\n+ abo_0              1    105.68 18535 514.99\n+ cat_plus_50        1     99.34 18542 515.02\n+ cat_autres         1     93.82 18547 515.05\n+ abo_3_sup          1     62.40 18578 515.21\n+ tel_inf_15         1     57.32 18584 515.23\n- ecran_travail_bcp  1    748.70 19390 515.27\n+ pas_internet       1     46.94 18594 515.29\n+ cat_sans_activite  1     31.00 18610 515.37\n+ appareils_plus_4   1     27.80 18613 515.39\n+ nuit_inf_7         1     25.83 18615 515.40\n+ cat_25_49          1     11.73 18629 515.47\n+ jour_3             1      4.38 18636 515.50\n- homme              1   1181.21 19822 517.36\n- cat_reseau_6_sup6  1   1366.47 20007 518.25\n- ecran_travail_peu  1   2124.03 20765 521.78\n\nStep:  AIC=513.47\ntemps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp + internet_autre + vie_sociale\n\n                    Df Sum of Sq   RSS    AIC\n<none>                           18242 513.47\n- vie_sociale        1    399.35 18641 513.53\n+ appareils_1_2      1    342.00 17900 513.67\n+ tel_sup_25         1    296.33 17945 513.91\n+ pas_ville          1    267.20 17974 514.07\n+ jour_2             1    267.04 17974 514.07\n+ cat_plus_50        1    258.27 17983 514.12\n+ abo_0              1    250.90 17991 514.15\n- internet_autre     1    633.59 18875 514.71\n+ cat_reseau_0_2     1    133.87 18108 514.77\n+ cat_cadres         1    131.15 18110 514.78\n+ loisir             1    128.27 18113 514.80\n+ cat_autres         1    100.27 18141 514.95\n+ abo_3_sup          1     75.30 18166 515.08\n+ tel_inf_15         1     62.36 18179 515.14\n+ pas_internet       1     58.22 18183 515.17\n+ abo_2              1     44.64 18197 515.24\n+ appareils_plus_4   1     33.69 18208 515.29\n+ cat_25_49          1     10.91 18231 515.41\n+ nuit_inf_7         1      6.93 18235 515.43\n+ cat_sans_activite  1      3.03 18238 515.45\n+ jour_3             1      0.16 18241 515.47\n- ecran_travail_bcp  1    796.88 19038 515.53\n- cat_reseau_6_sup6  1   1155.00 19396 517.30\n- homme              1   1246.50 19488 517.75\n- ecran_travail_peu  1   2388.87 20630 523.16\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp + internet_autre + vie_sociale, data = ecran)\n\nCoefficients:\n       (Intercept)  ecran_travail_peu1              homme1  cat_reseau_6_sup61  \n           38.5981            -11.9641              8.2840              8.5305  \necran_travail_bcp1     internet_autre1         vie_sociale  \n           -7.4881              6.0100             -0.1663  \n```\n\n\n:::\n\n```{.r .cell-code}\n#Step:  AIC=513.47\n```\n:::\n\n\n\ntemps_ecran \\~ ecran_travail_peu + homme + cat_reseau_6_sup6 + ecran_travail_bcp + internet_autre + vie_sociale\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# methode descendente \n\nmodele_d <- lm(temps_ecran ~ vie_sociale + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + homme + pas_ville + \n    cat_cadres + ecran_travail_bcp + ecran_travail_peu + internet_autre, data = ecran)\n\nsummary(modele_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temps_ecran ~ vie_sociale + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + homme + pas_ville + \n    cat_cadres + ecran_travail_bcp + ecran_travail_peu + internet_autre, \n    data = ecran)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-23.197 -10.084  -0.957   7.728  34.387 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         36.4523     4.1527   8.778 1.82e-13 ***\nvie_sociale         -0.2519     0.1210  -2.082  0.04043 *  \ncat_reseau_6_sup61  12.3794     3.9914   3.102  0.00263 ** \ntel_sup_251         -5.3294     3.8024  -1.402  0.16477    \nappareils_1_21      11.8095     4.7464   2.488  0.01484 *  \nabo_01              -6.8988     4.0914  -1.686  0.09552 .  \nhomme1               6.4134     3.6550   1.755  0.08300 .  \npas_ville1           6.3371     3.2054   1.977  0.05136 .  \ncat_cadres1          6.4451     4.8187   1.338  0.18471    \necran_travail_bcp1 -10.5870     3.8680  -2.737  0.00758 ** \necran_travail_peu1 -12.7396     3.9455  -3.229  0.00178 ** \ninternet_autre1      7.2202     3.3574   2.151  0.03442 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 13.91 on 83 degrees of freedom\nMultiple R-squared:  0.3231,\tAdjusted R-squared:  0.2334 \nF-statistic: 3.602 on 11 and 83 DF,  p-value: 0.000352\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n # methode ascendante \n\nmodele_a <-lm(temps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 +  ecran_travail_bcp + internet_autre + vie_sociale, data = ecran)\nsummary(modele_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp + internet_autre + vie_sociale, data = ecran)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-26.929 -11.771  -1.455   7.873  38.187 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         38.5981     3.5173  10.974  < 2e-16 ***\necran_travail_peu1 -11.9641     3.5243  -3.395  0.00103 ** \nhomme1               8.2840     3.3782   2.452  0.01617 *  \ncat_reseau_6_sup61   8.5305     3.6139   2.360  0.02046 *  \necran_travail_bcp1  -7.4881     3.8191  -1.961  0.05308 .  \ninternet_autre1      6.0100     3.4377   1.748  0.08390 .  \nvie_sociale         -0.1663     0.1198  -1.388  0.16864    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14.4 on 88 degrees of freedom\nMultiple R-squared:  0.2316,\tAdjusted R-squared:  0.1792 \nF-statistic: 4.421 on 6 and 88 DF,  p-value: 0.0005937\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# méthode double\nmodele_double <- lm(temps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 +  ecran_travail_bcp + internet_autre + vie_sociale, data = ecran)\nsummary(modele_double)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temps_ecran ~ ecran_travail_peu + homme + cat_reseau_6_sup6 + \n    ecran_travail_bcp + internet_autre + vie_sociale, data = ecran)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-26.929 -11.771  -1.455   7.873  38.187 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         38.5981     3.5173  10.974  < 2e-16 ***\necran_travail_peu1 -11.9641     3.5243  -3.395  0.00103 ** \nhomme1               8.2840     3.3782   2.452  0.01617 *  \ncat_reseau_6_sup61   8.5305     3.6139   2.360  0.02046 *  \necran_travail_bcp1  -7.4881     3.8191  -1.961  0.05308 .  \ninternet_autre1      6.0100     3.4377   1.748  0.08390 .  \nvie_sociale         -0.1663     0.1198  -1.388  0.16864    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14.4 on 88 degrees of freedom\nMultiple R-squared:  0.2316,\tAdjusted R-squared:  0.1792 \nF-statistic: 4.421 on 6 and 88 DF,  p-value: 0.0005937\n```\n\n\n:::\n:::\n\n\n\n# Modele_d - Tests\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresidus3<-residuals(modele_d) \n\nks.test(residus3, \"pnorm\", mean = mean(residus3), sd = sd(residus3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact one-sample Kolmogorov-Smirnov test\n\ndata:  residus3\nD = 0.055149, p-value = 0.9193\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\nreset(modele_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  modele_d\nRESET = 0.71814, df1 = 2, df2 = 81, p-value = 0.4907\n```\n\n\n:::\n\n```{.r .cell-code}\nbptest(modele_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modele_d\nBP = 10.579, df = 11, p-value = 0.4792\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(modele_d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      vie_sociale cat_reseau_6_sup6        tel_sup_25     appareils_1_2 \n         1.144620          1.391108          1.135186          1.469916 \n            abo_0             homme         pas_ville        cat_cadres \n         1.206856          1.271109          1.259208          1.674071 \necran_travail_bcp ecran_travail_peu    internet_autre \n         1.423566          1.706333          1.099522 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(cooks.distance(modele_d), type = \"h\", main = \"Distance de cook\")\n```\n\n::: {.cell-output-display}\n![](econometrie_files/figure-html/unnamed-chunk-82-1.png){width=672}\n:::\n:::\n\n\n\n### Possible endogénéité de certaines variables explicatives\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(here(\"data\", \"ecran_avec_instru_sansref.rda\"))\necran_i <- ecran_avec_instru_sansref\n```\n:::\n\n\n\nà partir base de données avec les instruments, nous allons choisir les variables que conforment le modèle retenue ultérieurement, le modele_d\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodele_di <- lm(temps_ecran ~ vie_sociale + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + homme + pas_ville + \n    cat_cadres + ecran_travail_bcp + ecran_travail_peu + internet_autre, \n    data = ecran_i)\nsummary(modele_di)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = temps_ecran ~ vie_sociale + cat_reseau_6_sup6 + \n    tel_sup_25 + appareils_1_2 + abo_0 + homme + pas_ville + \n    cat_cadres + ecran_travail_bcp + ecran_travail_peu + internet_autre, \n    data = ecran_i)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-23.197 -10.084  -0.957   7.728  34.387 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        36.4523     4.1527   8.778 1.82e-13 ***\nvie_sociale        -0.2519     0.1210  -2.082  0.04043 *  \ncat_reseau_6_sup6  12.3794     3.9914   3.102  0.00263 ** \ntel_sup_25         -5.3294     3.8024  -1.402  0.16477    \nappareils_1_2      11.8095     4.7464   2.488  0.01484 *  \nabo_0              -6.8988     4.0914  -1.686  0.09552 .  \nhomme               6.4134     3.6550   1.755  0.08300 .  \npas_ville           6.3371     3.2054   1.977  0.05136 .  \ncat_cadres          6.4451     4.8187   1.338  0.18471    \necran_travail_bcp -10.5870     3.8680  -2.737  0.00758 ** \necran_travail_peu -12.7396     3.9455  -3.229  0.00178 ** \ninternet_autre      7.2202     3.3574   2.151  0.03442 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 13.91 on 83 degrees of freedom\nMultiple R-squared:  0.3231,\tAdjusted R-squared:  0.2334 \nF-statistic: 3.602 on 11 and 83 DF,  p-value: 0.000352\n```\n\n\n:::\n:::\n\n\n\n-   variables endogènes = + tel_sup_25 + appareils_1_2 + abo_0 + internet_autre + vie_sociale\n\n-   variables exogènes = cat_reseau_6_sup6 + homme + pas_ville + cat_cadres + ecran_travail_bcp + ecran_travail_peu\n\n-   instruments =stress_toujours + stress_bcp + tel_pro_non + cat_inf_20000 + cat_20_40000 + nb_personnes + fibre_non\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ivreg\nreg_DMC <- ivreg(temps_ecran ~ vie_sociale + tel_sup_25 + appareils_1_2 + abo_0 + internet_autre + cat_reseau_6_sup6 + homme + pas_ville + cat_cadres + ecran_travail_bcp + ecran_travail_peu |  cat_reseau_6_sup6 + homme + pas_ville + cat_cadres + ecran_travail_bcp + ecran_travail_peu  +  tel_pro_non + cat_inf_20000 + cat_20_40000 + nb_personnes + fibre_non + stress_toujours + stress_bcp, data=ecran_i)\n\nsummary(reg_DMC, diagnostics = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nivreg(formula = temps_ecran ~ vie_sociale + tel_sup_25 + appareils_1_2 + \n    abo_0 + internet_autre + cat_reseau_6_sup6 + homme + pas_ville + \n    cat_cadres + ecran_travail_bcp + ecran_travail_peu | cat_reseau_6_sup6 + \n    homme + pas_ville + cat_cadres + ecran_travail_bcp + ecran_travail_peu + \n    tel_pro_non + cat_inf_20000 + cat_20_40000 + nb_personnes + \n    fibre_non + stress_toujours + stress_bcp, data = ecran_i)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-46.2686 -12.6582  -0.4241  11.7027  45.1387 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        42.2713    12.2165   3.460 0.000855 ***\nvie_sociale        -0.3865     0.6304  -0.613 0.541446    \ntel_sup_25        -17.0728    21.7994  -0.783 0.435751    \nappareils_1_2       2.7568    25.5274   0.108 0.914262    \nabo_0             -33.7151    27.1138  -1.243 0.217196    \ninternet_autre     25.8429    11.3253   2.282 0.025057 *  \ncat_reseau_6_sup6  11.3063    10.3542   1.092 0.278015    \nhomme               3.5460     6.1779   0.574 0.567533    \npas_ville           5.5357     8.4065   0.659 0.512034    \ncat_cadres          9.8941     9.8937   1.000 0.320198    \necran_travail_bcp -14.8904     9.0734  -1.641 0.104563    \necran_travail_peu  -7.9819     8.4362  -0.946 0.346820    \n\nDiagnostic tests:\n                                  df1 df2 statistic  p-value    \nWeak instruments (vie_sociale)      7  81     1.495 0.180661    \nWeak instruments (tel_sup_25)       7  81     1.034 0.413900    \nWeak instruments (appareils_1_2)    7  81     1.303 0.259589    \nWeak instruments (abo_0)            7  81     0.811 0.580768    \nWeak instruments (internet_autre)   7  81     4.839 0.000136 ***\nWu-Hausman                          5  78     1.814 0.119685    \nSargan                              2  NA     2.208 0.331536    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.61 on 83 degrees of freedom\nMultiple R-Squared: -0.4848,\tAdjusted R-squared: -0.6816 \nWald test: 1.529 on 11 and 83 DF,  p-value: 0.1367 \n```\n\n\n:::\n:::\n",
    "supporting": [
      "econometrie_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}