{
  "hash": "526fc2591190fd87598ad4a0766b0df1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Biostatistiques\"\nauthor: \n  - \"C. ORHAN\"\n  - \"Isabel PALACIO\"\ndate: \"2024-02\"\nformat: \n  html:\n    toc: true\n    toc_float: \n      collapsed: false\n      smooth_scroll: true\neditor: visual\nimage: \"crabe.jpeg\" \ncategories: [Imputation, MICE, Régression, ACP]\n---\n\n\n\n# Introduction\n\nNotre projet explore diverses stratégies pour gérer les valeurs manquantes, en s'appuyant sur un dataset provenant de la plateforme <https://www.kaggle.com/datasets>. Au cœur de notre approche se trouve une analyse descriptive, qui nous a permis de comprendre la distribution des données en examinant les tendances et la dispersion à travers des mesures comme la moyenne, la médiane et l'écart-type, et en utilisant des outils visuels tels que les histogrammes et les box-plots.\n\nConcernant le remplacement des N/A, nous avons opté pour trois techniques adaptées aux caractéristiques de notre dataset : La régression linéaire, l'imputation multiple par MICE (Multiple Imputation by Chained Equations) et l'imputation multiple par Analyse en Composantes Principales (ACP).\n\n# Présentation du code\n\nJe vous présente ci-dessous, le code utilisé pour mener à bien ce projet, avec les étapes et explications correspondantes.\n\n## Librairies\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({\nlibrary(naniar)\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(EnvStats)\nlibrary(corrplot)\nlibrary(RColorBrewer)\nlibrary(FactoMineR)\nlibrary(factoextra)\nlibrary(missMDA)\nlibrary(mice)\nlibrary(ggplot2)\nlibrary(car)\nlibrary(tinytex)\nlibrary(ranger)\nlibrary(here)\n})\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in check_dep_version(): ABI version mismatch: \nlme4 was built with Matrix ABI version 1\nCurrent Matrix ABI version is 0\nPlease re-install lme4 from source or restore original 'Matrix' package\n```\n\n\n:::\n\n```{.r .cell-code}\nvecteur_couleur <- c(\"F\"=\"darkred\", \"M\"=\"darkgreen\", \"I\"=\"darkblue\" )\n```\n:::\n\n\n\n## Téléchargement de la base de données\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe <- read.csv(here(\"data\", \"CrabAgePrediction.csv\")) \n```\n:::\n\n\n\n## Présentation de la base de données\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(crabe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,893\nColumns: 9\n$ Sex            <chr> \"F\", \"M\", \"I\", \"F\", \"I\", \"F\", \"F\", \"M\", \"I\", \"I\", \"M\", …\n$ Length         <dbl> 1.4375, 0.8875, 1.0375, 1.1750, 0.8875, 1.5500, 1.3000,…\n$ Diameter       <dbl> 1.1750, 0.6500, 0.7750, 0.8875, 0.6625, 1.1625, 1.0000,…\n$ Height         <dbl> 0.4125, 0.2125, 0.2500, 0.2500, 0.2125, 0.3500, 0.3250,…\n$ Weight         <dbl> 24.635715, 5.400580, 7.952035, 13.480187, 6.903103, 28.…\n$ Shucked.Weight <dbl> 12.332033, 2.296310, 3.231843, 4.748541, 3.458639, 13.5…\n$ Viscera.Weight <dbl> 5.5848515, 1.3749507, 1.6017467, 2.2821347, 1.4883488, …\n$ Shell.Weight   <dbl> 6.7471810, 1.5592225, 2.7640763, 5.2446575, 1.7009700, …\n$ Age            <int> 9, 6, 6, 10, 6, 8, 15, 10, 13, 7, 6, 10, 9, 10, 11, 12,…\n```\n\n\n:::\n:::\n\n\n\nÀ titre informatif, notre base de données est une base sur des crabes destinés à la consommation dans des restaurants de la région de Boston.\n\nLe type de crabe le plus commun à cet effet est le crabe bleu américain qui est natif des côtes atlantiques américaines.\n\nLe crabe bleu américain est pêché et consommé en grande quantité, principalement aux Etats-Unis et au Mexique. Chaque année, 58 000 tonnes sont prélevées ; son importance économique et culinaire est considérable sur la côte est des Etats-Unis, en particulier dans les états de Louisiane, du Maryland, de Caroline du Nord, du New Jersey et du Massachusetts.\n\n## Transformation de la BD\n\n### Traduction des noms de nos variables en français\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(crabe) <- c(\"sexe\", \"longueur\", \"diametre\", \"hauteur\", \"poids\",\"poids.chair\", \"poids.visceres\", \"poids.coquille\", \"age\")\n```\n:::\n\n\n\nNotre base de données est donc composée de 3894 crabes bleus et de 9 variables qui sont :\n\nVariables qualitatives :\n\n-   **Sexe du crabe** - Mâle (Male), Femelle (Female) et Indéterminé (Indeterminate).\n\nVariables quantitatives :\n\n-   **Longueur** : longueur du crabe (en pieds ; 1 pied = 30,48 cm).\n\n-   **Diamètre** : diamètre du crabe (en pieds ; 1 pied = 30,48 cm).\n\n-   **Hauteur** : hauteur du crabe (en pieds ; 1 pied = 30,48 cm).\n\n-   **Poids** : poids du crabe (en onces ; 1 livre = 16 onces).\n\n-   **Poids éviscéré** : poids du crabe sans sa coquille (en onces ; 1 livre = 16 onces).\n\n-   **Poids des viscères** : poids des viscères, qui sont les organes entourant la cavité abdominale (en onces ; 1 livre = 16 onces).\n\n-   **Poids** **de la coquille** : poids de la coquille du crabe (en onces ; 1 livre = 16 onces).\n\n-   **Age** : âge du crabe (en mois).\n\n### Conversion des variables à l'origine en pied en centimètre\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe$longueur <- crabe$longueur * 30.48\ncrabe$diametre <- crabe$diametre * 30.48\ncrabe$hauteur <- crabe$hauteur * 30.48\n```\n:::\n\n\n\n## Conversion des variables à l'origine en onces en kilogramme\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe$poids <- crabe$poids * 0.0283495\ncrabe$poids.chair <- crabe$poids.chair * 0.0283495\ncrabe$poids.visceres <- crabe$poids.visceres * 0.0283495\ncrabe$poids.coquille <- crabe$poids.coquille * 0.0283495\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(crabe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t3893 obs. of  9 variables:\n $ sexe          : chr  \"F\" \"M\" \"I\" \"F\" ...\n $ longueur      : num  43.8 27.1 31.6 35.8 27.1 ...\n $ diametre      : num  35.8 19.8 23.6 27.1 20.2 ...\n $ hauteur       : num  12.57 6.48 7.62 7.62 6.48 ...\n $ poids         : num  0.698 0.153 0.225 0.382 0.196 ...\n $ poids.chair   : num  0.3496 0.0651 0.0916 0.1346 0.0981 ...\n $ poids.visceres: num  0.1583 0.039 0.0454 0.0647 0.0422 ...\n $ poids.coquille: num  0.1913 0.0442 0.0784 0.1487 0.0482 ...\n $ age           : int  9 6 6 10 6 8 15 10 13 7 ...\n```\n\n\n:::\n:::\n\n\n\nNos variables sont bien classées, nous n'avons pas à les modifier.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(crabe)\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\nAprès un aperçu rapide de nos données, nous pouvons observer que :\n\nLes graphiques ont différentes tendances et degrés de corrélation. Certains indiquent une corrélation positive marquée, visible par les points qui forment une trajectoire nette ascendante de gauche à droite.\n\nDes points paraissent s'écarter de la tendance générale dans plusieurs scatter plots, suggérant la présence de valeurs aberrantes.\n\nNotre jeu de données ne présente pas de valeurs manquantes. Cependant, en ce qui concerne la variable qualitative \"sexe\", nous observons une anomalie qui nécessite une analyse plus détaillée. En effet, nous recensons trois catégories : M pour masculin, F pour féminin et I pour indéfini, ce qui pourrait indiquer une erreur.\n\nAfin de mieux comprendre nos données, nous allons réaliser une première analyse descriptive des variables qui présentent des valeurs atypiques.\n\n# Analyse descriptive exploratoire\n\nL'analyse descriptive exploratoire a pour objectif de déterminer la présence de valeurs aberrantes ou extrêmes au sein de nos données, afin de procéder à leur correction si nécessaire.\n\n## Calcul des mesures de dispersion\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(crabe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sexe              longueur         diametre         hauteur      \n Length:3893        Min.   : 5.715   Min.   : 4.191   Min.   : 0.000  \n Class :character   1st Qu.:34.290   1st Qu.:26.670   1st Qu.: 8.763  \n Mode  :character   Median :41.529   Median :32.385   Median :11.049  \n                    Mean   :39.969   Mean   :31.117   Mean   :10.649  \n                    3rd Qu.:46.863   3rd Qu.:36.576   3rd Qu.:12.573  \n                    Max.   :62.103   Max.   :49.530   Max.   :86.106  \n     poids           poids.chair        poids.visceres      poids.coquille    \n Min.   :0.001607   Min.   :0.0008037   Min.   :0.0004018   Min.   :0.001205  \n 1st Qu.:0.359251   1st Qu.:0.1514963   1st Qu.:0.0755473   1st Qu.:0.105284  \n Median :0.646170   Median :0.2704431   Median :0.1378335   Median :0.188868  \n Mean   :0.668121   Mean   :0.2893730   Mean   :0.1456185   Mean   :0.192659  \n 3rd Qu.:0.929472   3rd Qu.:0.4046600   3rd Qu.:0.2041383   3rd Qu.:0.265219  \n Max.   :2.270838   Max.   :1.1958969   Max.   :0.6108076   Max.   :0.807713  \n      age        \n Min.   : 1.000  \n 1st Qu.: 8.000  \n Median :10.000  \n Mean   : 9.955  \n 3rd Qu.:11.000  \n Max.   :29.000  \n```\n\n\n:::\n:::\n\n\n\n1.  **Longueur** : La longueur des crabes varie de 5.715 à 62.103 avec une moyenne d'environ 39.969. La médiane est de 41.529, ce qui suggère une distribution légèrement asymétrique vers les valeurs inférieures puisque la moyenne est inférieure à la médiane. Les valeurs sont concentrées principalement entre 34.290 et 46.863, qui représentent les premiers et troisième quartile, indiquant que 50 % des observations sont dans cette plage.\n\n2.  **Diamètre** : le diamètre varie de 4.191 à 49.530, avec une moyenne de 31.117. La médiane est de 32.385, suggérant une distribution similaire à celle de la longueur, avec une légère asymétrie. Le diamètre des crabes est généralement compris entre 26.670 et 36.576 (premier et troisième quartiles).\n\n3.  **Hauteur** : la hauteur présente une gamme plus étendue allant de 0 à 86.106, avec une moyenne de 10.649. La médiane de 11.049 est supérieure à la moyenne, ce qui pourrait indiquer une distribution asymétrique avec une queue de distribution vers les valeurs inférieures.\n\n4.  **Poids** : le poids total des crabes est compris entre 0.001607 et 2.270838, avec une moyenne de 0.668121. La médiane est de 0.646170, indiquant une distribution des poids assez symétrique autour de la valeur centrale.\n\n5.  **Poids de chair** : le poids de la chair varie de 0.0008037 à 1.1958969, avec une moyenne de 0.2893730. La médiane, à 0.2704431, est légèrement inférieure à la moyenne, suggérant une distribution modérément asymétrique.\n\n6.  **Poids des viscères** : le poids des viscères varie de 0.0004018 à 0.6108076, avec une moyenne de 0.1456185. La médiane est assez proche de la moyenne, ce qui indique une distribution assez équilibrée.\n\n7.  **Poids de la coquille** : le poids de la coquille a une plage allant de 0.001205 à 0.807713, avec une moyenne de 0.192659. La médiane est également proche de la moyenne, ce qui suggère une distribution régulière.\n\n8.  **Age** : l'âge varie de 1 à 29 mois, avec une moyenne proche de la médiane (9.955 contre 10), indiquant une distribution symétrique. La plupart des crabes ont entre 8 et 11 mois (premier et troisième quartiles), ce qui montre que les âges sont relativement concentrés.\n\n## Vérification de l’absence de doublons\n\nNotre jeu de données est composé de 3 893 entrées. Nous allons vérifier s'il contient des doublons.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe |>\n \tdistinct() |>\n \tnrow()\n```\n:::\n\n\n\n\\[1\\] 3893\n\nAucune ligne n'est répétée, nous pouvons donc conserver la totalité de nos données\n\n## Diagramme en camembert\n\n**Sexe**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe |>\n  count(sexe) |>\n  mutate(pourcentage = n / sum(n) * 100) |>\n  ggplot(aes(x = \"\", y = n, fill = sexe)) +\n  geom_bar(stat = \"identity\", width = 1) +\n  coord_polar(theta = \"y\") +\n  scale_fill_manual(values = vecteur_couleur) +\n  geom_text(aes(label = paste0(round(pourcentage, 1), \"%\")),\n   \t\t position = position_stack(vjust = 0.5),\n   \t\t color = \"white\") +  \n  labs(\n    title = \"Distribution des sexes dans le jeu de données \",\n    fill = \"Sexe\"\n  ) +\n  theme_void()  \n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\nIl illustre la distribution des sexes dans notre jeu de données. Les mâles représentent la plus grande proportion avec 36,9 %, tandis que les femelles et les indéfinis ont des proportions presque égales de 31,5 % et 31,7 % respectivement.\n\n## Représentation des valeurs aberrantes grâce à des boxplots\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe  |>\n    pivot_longer(\n      cols = longueur:age,\n      names_to = \"mesure\",\n      values_to = \"valeur\"\n      ) |>\n    ggplot() +\n    aes(y = valeur, x = sexe, color = sexe) +\n    geom_boxplot() +\n    geom_jitter(alpha = 0.3,  position = position_jitter(width = 0.2))  +\n    facet_wrap(~ mesure, scales = \"free_y\") +\n    scale_color_manual(values =vecteur_couleur)+\n    labs(title = \"Distribution des mesures par sexe\")+\n    theme_bw()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\nNous pouvons donc observer la présence de valeurs aberrantes ou extrêmes dans nos variables. Pour les identifier, nous avons utilisé le test de Rosner.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrosnerTest(crabe$longueur, k=10, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            crabe$longueur\n\nSample Size:                     3893\n\nTest Statistics:                 R.1  = 3.740649\n                                 R.2  = 3.456138\n                                 R.3  = 3.294960\n                                 R.4  = 3.299993\n                                 R.5  = 3.263207\n                                 R.6  = 3.226213\n                                 R.7  = 3.230957\n                                 R.8  = 3.151732\n                                 R.9  = 3.114132\n                                 R.10 = 3.118429\n\nTest Statistic Parameter:        k = 10\n\nAlternative Hypothesis:          Up to 10 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     0\n\n   i   Mean.i     SD.i  Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1  0 39.96859 9.157125  5.715    1331 3.740649   4.357703   FALSE\n2  1 39.97739 9.141820  8.382     754 3.456138   4.357646   FALSE\n3  2 39.98551 9.128947  9.906    1178 3.294960   4.357588   FALSE\n4  3 39.99325 9.117367  9.906    3729 3.299993   4.357531   FALSE\n5  4 40.00098 9.105761 10.287    1901 3.263207   4.357474   FALSE\n6  5 40.00863 9.094449 10.668     308 3.226213   4.357416   FALSE\n7  6 40.01617 9.083430 10.668     956 3.230957   4.357359   FALSE\n8  7 40.02373 9.072385 11.430    1135 3.151732   4.357302   FALSE\n9  8 40.03109 9.061943 11.811     694 3.114132   4.357244   FALSE\n10 9 40.03835 9.051785 11.811    2766 3.118429   4.357187   FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nrosnerTest(crabe$diametre, k=10, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            crabe$diametre\n\nSample Size:                     3893\n\nTest Statistics:                 R.1  = 3.558731\n                                 R.2  = 3.211973\n                                 R.3  = 3.166162\n                                 R.4  = 3.120107\n                                 R.5  = 3.124422\n                                 R.6  = 3.078090\n                                 R.7  = 3.082245\n                                 R.8  = 3.086418\n                                 R.9  = 3.090607\n                                 R.10 = 3.043926\n\nTest Statistic Parameter:        k = 10\n\nAlternative Hypothesis:          Up to 10 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     0\n\n   i   Mean.i     SD.i Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1  0 31.11683 7.566132 4.191    1331 3.558731   4.357703   FALSE\n2  1 31.12375 7.554779 6.858     754 3.211973   4.357646   FALSE\n3  2 31.12998 7.545724 7.239    1178 3.166162   4.357588   FALSE\n4  3 31.13612 7.536961 7.620    1135 3.120107   4.357531   FALSE\n5  4 31.14217 7.528488 7.620    3729 3.124422   4.357474   FALSE\n6  5 31.14822 7.519995 8.001     308 3.078090   4.357416   FALSE\n7  6 31.15417 7.511789 8.001     956 3.082245   4.357359   FALSE\n8  7 31.16013 7.503564 8.001    2913 3.086418   4.357302   FALSE\n9  8 31.16609 7.495321 8.001    3634 3.090607   4.357244   FALSE\n10 9 31.17206 7.487061 8.382    1648 3.043926   4.357187   FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nrosnerTest(crabe$hauteur, k=10, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            crabe$hauteur\n\nSample Size:                     3893\n\nTest Statistics:                 R.1  = 23.582729\n                                 R.2  =  9.658305\n                                 R.3  =  3.628763\n                                 R.4  =  3.635390\n                                 R.5  =  3.380918\n                                 R.6  =  3.255592\n                                 R.7  =  3.260460\n                                 R.8  =  3.134283\n                                 R.9  =  3.007441\n                                 R.10 =  3.011338\n\nTest Statistic Parameter:        k = 10\n\nAlternative Hypothesis:          Up to 10 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     2\n\n   i   Mean.i     SD.i  Value Obs.Num     R.i+1 lambda.i+1 Outlier\n1  0 10.64892 3.199676 86.106    2257 23.582729   4.357703    TRUE\n2  1 10.62953 2.962577 39.243     749  9.658305   4.357646    TRUE\n3  2 10.62217 2.927216  0.000     270  3.628763   4.357588   FALSE\n4  3 10.62490 2.922632  0.000    3868  3.635390   4.357531   FALSE\n5  4 10.62764 2.918035  0.762    1331  3.380918   4.357474   FALSE\n6  5 10.63017 2.914116  1.143    1124  3.255592   4.357416   FALSE\n7  6 10.63262 2.910514  1.143    3543  3.260460   4.357359   FALSE\n8  7 10.63506 2.906903  1.524     986  3.134283   4.357302   FALSE\n9  8 10.63740 2.903599  1.905     694  3.007441   4.357244   FALSE\n10 9 10.63965 2.900588  1.905    1135  3.011338   4.357187   FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nrosnerTest(crabe$poids, k=10, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            crabe$poids\n\nSample Size:                     3893\n\nTest Statistics:                 R.1  = 4.069788\n                                 R.2  = 3.984935\n                                 R.3  = 3.742623\n                                 R.4  = 3.540531\n                                 R.5  = 3.536432\n                                 R.6  = 3.538473\n                                 R.7  = 3.499292\n                                 R.8  = 3.483594\n                                 R.9  = 3.475026\n                                 R.10 = 3.473644\n\nTest Statistic Parameter:        k = 10\n\nAlternative Hypothesis:          Up to 10 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     0\n\n   i    Mean.i      SD.i    Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1  0 0.6681205 0.3938086 2.270838    2897 4.069788   4.357703   FALSE\n2  1 0.6677087 0.3930200 2.233868     773 3.984935   4.357646   FALSE\n3  2 0.6673062 0.3922674 2.135415    2572 3.742623   4.357588   FALSE\n4  3 0.6669288 0.3916107 2.053439     230 3.540531   4.357531   FALSE\n5  4 0.6665722 0.3910292 2.049420    2717 3.536432   4.357474   FALSE\n6  5 0.6662166 0.3904498 2.047813     539 3.538473   4.357416   FALSE\n7  6 0.6658611 0.3898704 2.030131     502 3.499292   4.357359   FALSE\n8  7 0.6655100 0.3893056 2.021693    1758 3.483594   4.357302   FALSE\n9  8 0.6651610 0.3887470 2.016067    1327 3.475026   4.357244   FALSE\n10 9 0.6648132 0.3881920 2.013254    3186 3.473644   4.357187   FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nrosnerTest(crabe$poids.chair, k=10, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            crabe$poids.chair\n\nSample Size:                     3893\n\nTest Statistics:                 R.1  = 5.095668\n                                 R.2  = 4.492498\n                                 R.3  = 4.493418\n                                 R.4  = 4.070734\n                                 R.5  = 4.045732\n                                 R.6  = 4.027361\n                                 R.7  = 4.001947\n                                 R.8  = 3.847766\n                                 R.9  = 3.846418\n                                 R.10 = 3.743692\n\nTest Statistic Parameter:        k = 10\n\nAlternative Hypothesis:          Up to 10 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     3\n\n   i    Mean.i      SD.i     Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1  0 0.2893730 0.1779009 1.1958969    2572 5.095668   4.357703    TRUE\n2  1 0.2891401 0.1773291 1.0857908    1950 4.492498   4.357646    TRUE\n3  2 0.2889354 0.1768912 1.0837816     773 4.493418   4.357588    TRUE\n4  3 0.2887310 0.1764541 1.0070288    2317 4.070734   4.357531   FALSE\n5  4 0.2885463 0.1761003 1.0010011    1294 4.045732   4.357474   FALSE\n6  5 0.2883631 0.1757518 0.9961789    3351 4.027361   4.357416   FALSE\n7  6 0.2881810 0.1754072 0.9901512    1327 4.001947   4.357359   FALSE\n8  7 0.2880004 0.1750678 0.9616201    3186 3.847766   4.357302   FALSE\n9  8 0.2878270 0.1747563 0.9600127     539 3.846418   4.357244   FALSE\n10 9 0.2876539 0.1744455 0.9407240     854 3.743692   4.357187   FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nrosnerTest(crabe$poids.visceres, k=10, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            crabe$poids.visceres\n\nSample Size:                     3893\n\nTest Statistics:                 R.1  = 5.286202\n                                 R.2  = 4.219961\n                                 R.3  = 3.757195\n                                 R.4  = 3.626516\n                                 R.5  = 3.628525\n                                 R.6  = 3.538250\n                                 R.7  = 3.415023\n                                 R.8  = 3.337302\n                                 R.9  = 3.342527\n                                 R.10 = 3.213223\n\nTest Statistic Parameter:        k = 10\n\nAlternative Hypothesis:          Up to 10 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     1\n\n   i    Mean.i       SD.i     Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1  0 0.1456185 0.08800062 0.6108076     773 5.286202   4.357703    TRUE\n2  1 0.1454990 0.08769532 0.5155698    1758 4.219961   4.357646   FALSE\n3  2 0.1454039 0.08750561 0.4741795     502 3.757195   4.357588   FALSE\n4  3 0.1453194 0.08735787 0.4621241    1205 3.626516   4.357531   FALSE\n5  4 0.1452379 0.08722122 0.4617223     539 3.628525   4.357474   FALSE\n6  5 0.1451565 0.08708457 0.4532835     692 3.538250   4.357416   FALSE\n7  6 0.1450772 0.08695537 0.4420318    1936 3.415023   4.357359   FALSE\n8  7 0.1450008 0.08683593 0.4347985    2317 3.337302   4.357302   FALSE\n9  8 0.1449262 0.08672250 0.4347985    2531 3.342527   4.357244   FALSE\n10 9 0.1448516 0.08660879 0.4231450    1828 3.213223   4.357187   FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nrosnerTest(crabe$poids.coquille, k=10, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            crabe$poids.coquille\n\nSample Size:                     3893\n\nTest Statistics:                 R.1  = 5.501712\n                                 R.2  = 4.744584\n                                 R.3  = 4.672147\n                                 R.4  = 4.685917\n                                 R.5  = 4.190527\n                                 R.6  = 4.072972\n                                 R.7  = 3.954369\n                                 R.8  = 3.816471\n                                 R.9  = 3.574841\n                                 R.10 = 3.573856\n\nTest Statistic Parameter:        k = 10\n\nAlternative Hypothesis:          Up to 10 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     4\n\n   i    Mean.i      SD.i     Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1  0 0.1926588 0.1117932 0.8077126    3296 5.501712   4.357703    TRUE\n2  1 0.1925008 0.1113718 0.7209137    2897 4.744584   4.357646    TRUE\n3  2 0.1923649 0.1110634 0.7112693    2726 4.672147   4.357588    TRUE\n4  3 0.1922316 0.1107655 0.7112693    3070 4.685917   4.357531    TRUE\n5  4 0.1920981 0.1104664 0.6550107     199 4.190527   4.357474   FALSE\n6  5 0.1919790 0.1102308 0.6409461    1486 4.072972   4.357416   FALSE\n7  6 0.1918635 0.1100094 0.6268814    1924 3.954369   4.357359   FALSE\n8  7 0.1917516 0.1098019 0.6108076    1826 3.816471   4.357302   FALSE\n9  8 0.1916437 0.1096100 0.5834820    1556 3.574841   4.357244   FALSE\n10 9 0.1915428 0.1094435 0.5826783    1847 3.573856   4.357187   FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nrosnerTest(crabe$age, k=10, alpha=0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nResults of Outlier Test\n-------------------------\n\nTest Method:                     Rosner's Test for Outliers\n\nHypothesized Distribution:       Normal\n\nData:                            crabe$age\n\nSample Size:                     3893\n\nTest Statistics:                 R.1  = 5.912886\n                                 R.2  = 5.316734\n                                 R.3  = 5.336843\n                                 R.4  = 5.043142\n                                 R.5  = 4.745335\n                                 R.6  = 4.443844\n                                 R.7  = 4.455752\n                                 R.8  = 4.150310\n                                 R.9  = 4.160079\n                                 R.10 = 4.169918\n\nTest Statistic Parameter:        k = 10\n\nAlternative Hypothesis:          Up to 10 observations are not\n                                 from the same Distribution.\n\nType I Error:                    5%\n\nNumber of Outliers Detected:     7\n\n   i   Mean.i     SD.i Value Obs.Num    R.i+1 lambda.i+1 Outlier\n1  0 9.954791 3.220967    29    1730 5.912886   4.357703    TRUE\n2  1 9.949897 3.206875    27    3070 5.316734   4.357646    TRUE\n3  2 9.945515 3.195613    27    3523 5.336843   4.357588    TRUE\n4  3 9.941131 3.184299    26      90 5.043142   4.357531    TRUE\n5  4 9.937002 3.174275    25    2424 4.745335   4.357474    TRUE\n6  5 9.933128 3.165474    24     374 4.443844   4.357416    TRUE\n7  6 9.929509 3.157827    24    3308 4.455752   4.357359    TRUE\n8  7 9.925888 3.150153    23     138 4.150310   4.357302   FALSE\n9  8 9.922523 3.143564    23     502 4.160079   4.357244   FALSE\n10 9 9.919156 3.136955    23    1215 4.169918   4.357187   FALSE\n```\n\n\n:::\n:::\n\n\n\nNous utilisons le test de Rosner pour identifier les observations qui peuvent être considérées comme aberrantes ou extrêmes, afin de les analyser en détail.\n\n-   Hauteur pour les observations numéros 2257 (86,106 cm) et 749 (39,24 cm)\n\n-   Poids de la chair pour les observations 2257 (1,19 kg), 1950 (1,08 kg) et 773 (1,08 kg)\n\n-   Poids des viscères pour l'observation 773 (0,61 kg)\n\n-   Poids de la coquille pour les observations 3296 (0,8 kg), 2897 (0,72 kg), 2726 (0,71 kg) et 3070 (0,71 kg)\n\n-   Age pour les observations 1730 (29 mois), 3070 (27 mois), 3535 (27 mois), 90 (26 mois), 2424 (25 mois), 374 (24 mois) et 3308 (24 mois).\n\nLors de nos recherches, nous avons cherché à comprendre la normalité de notre base de données.\n\nOn apprend ainsi que le crabe bleu à une longévité d'environ 3 ans donc nous décidons de conserver les valeurs extrêmes de la variable âge. Concernant les variables poids de la chair, poids des viscères et poids de la coquille, nous décidons également de les garder.\n\nPour la suite, nous allons donc traiter les deux valeurs de la variable \"hauteur\".\n\n**Observation n°2257**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe[2257,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sexe longueur diametre hauteur     poids poids.chair poids.visceres\n2257    F   34.671   27.051  86.106 0.4773943   0.2668265     0.09322852\n     poids.coquille age\n2257      0.1072932   8\n```\n\n\n:::\n\n```{.r .cell-code}\nresultat <- crabe %>%\n  filter(sexe == \"F\", age == 8) %>%\n  summarise(mean_hauteur = mean(hauteur))\nprint(resultat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mean_hauteur\n1     11.39628\n```\n\n\n:::\n:::\n\n\n\nNous constatons que la moyenne des hauteurs pour les crabes âgés de 8 mois et de sexe féminin est de 11,39. Nous pouvons donc supposer que notre valeur de 86,106 est une valeur aberrante, probablement due à une erreur de saisie de virgule, que nous pouvons corriger.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe[2257,\"hauteur\"]<-8.6106\n```\n:::\n\n\n\n# Première méthode de remplacement : Regression linéaire\n\n**Observation n°749**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe[749,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sexe longueur diametre hauteur    poids poids.chair poids.visceres\n749    M   53.721   43.053  39.243 1.776164   0.8900913      0.3909972\n    poids.coquille age\n749      0.4114914  10\n```\n\n\n:::\n\n```{.r .cell-code}\nresultat <- crabe %>%\n  filter(sexe == \"M\", age == 10) %>%\n  summarise(min_hauteur = min(hauteur))\nprint(resultat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  min_hauteur\n1       4.953\n```\n\n\n:::\n:::\n\n\n\nPar conséquent, cette valeur observée de 39,243 cm, n’est pas une valeur aberrante, mais semble être une valeur extrême compte tenu de la valeur minimum de 4,953 cm.\n\nNous avons choisi comme première méthode de remplacement pour cette valeur, une régression linéaire.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe[749,\"hauteur\"]<-NA\n```\n:::\n\n\n\nPour commencer, nous avons remplacé la valeur extrême identifiée par une valeur manquante \"NA\" afin de procéder à son remplacement.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression_linéaire <- lm (\n  hauteur ~ sexe + diametre + longueur + poids + poids.chair + poids.visceres + poids.coquille + age,\n  data=crabe\n  )\nsummary(regression_linéaire)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hauteur ~ sexe + diametre + longueur + poids + poids.chair + \n    poids.visceres + poids.coquille + age, data = crabe)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11.4907  -0.6381  -0.0373   0.6150   6.1299 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     1.850761   0.154990  11.941  < 2e-16 ***\nsexeI          -0.207460   0.054287  -3.822 0.000135 ***\nsexeM          -0.035236   0.043663  -0.807 0.419718    \ndiametre        0.140987   0.015275   9.230  < 2e-16 ***\nlongueur        0.045855   0.012403   3.697 0.000221 ***\npoids          -0.209082   0.477195  -0.438 0.661303    \npoids.chair    -0.218862   0.566617  -0.386 0.699324    \npoids.visceres  4.918407   0.844109   5.827 6.11e-09 ***\npoids.coquille  6.907514   0.734184   9.408  < 2e-16 ***\nage             0.079057   0.008096   9.765  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.114 on 3882 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.8556,\tAdjusted R-squared:  0.8552 \nF-statistic:  2555 on 9 and 3882 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nÀ travers cette régression linéaire, nous avons identifié les variables qui montrent des corrélations significatives avec la variable « hauteur ». Il apparaît que la variable significative liée au sexe est « sexeI », représentant le sexe indéterminé, tandis que « sexeF », qui sert de modalité de référence par défaut, et « sexeM », qui n'est pas significative, ne seront pas pris en compte dans notre analyse. Par conséquent, nous allons filtrer notre ensemble de données en se concentrant uniquement sur le sexe indéterminé.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsexeI <- crabe |> filter(sexe==\"I\")\nmodele <- regression_linéaire2 <-lm(\n  hauteur~diametre+poids.visceres+poids.coquille+age,\n  data=sexeI\n)\nsummary(regression_linéaire2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hauteur ~ diametre + poids.visceres + poids.coquille + \n    age, data = sexeI)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.3991 -0.5447 -0.0582  0.4965  4.8595 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     0.96519    0.17413   5.543 3.63e-08 ***\ndiametre        0.21139    0.01024  20.649  < 2e-16 ***\npoids.visceres  9.17354    1.57864   5.811 7.90e-09 ***\npoids.coquille  2.65358    1.30044   2.041   0.0415 *  \nage             0.13475    0.01558   8.646  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9279 on 1228 degrees of freedom\nMultiple R-squared:  0.8585,\tAdjusted R-squared:  0.858 \nF-statistic:  1863 on 4 and 1228 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nNous allons à présent utiliser les résultats de cette régression afin de générer des prédictions pour remplacer la valeur manquante.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe$hauteur[is.na(crabe$hauteur)] <- predict(modele, newdata = crabe[is.na(crabe$hauteur), ])\n```\n:::\n\n\n\nCette prédiction nous a permis d'utiliser les relations linéaires identifiées dans le modèle pour estimer et remplacer de manière précise la valeur manquante de l'observation n°749.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe[749,\"hauteur\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16.09228\n```\n\n\n:::\n\n```{.r .cell-code}\ncrabe_complet<-crabe\n```\n:::\n\n\n\nLa nouvelle valeur est donc 16,09 cm.\n\n# Création de nos valeurs manquantes\n\nNotre jeu de données est initialement complet, sans valeurs manquantes. Nous avons toutefois opté pour l'insertion aléatoire de données manquantes de façon contrôlée.\n\nPour garantir une reproductibilité fiable de ce processus aléatoire, nous employons la fonction set.seed, qui fixe la graine du générateur de nombres aléatoires. Cette étape est essentielle pour s'assurer que les résultats puissent être régénérés de manière identique lors de chaque exécution.\n\nAfin d'intégrer les valeurs manquantes (N/A) dans notre jeu de données, nous procédons de la manière suivante :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)  \nn <- nrow(crabe)  \np <- ncol(crabe)  \nm <- 50\n\ncols <- c(\"poids\", \"diametre\", \"age\")\n\nrow_indices <- sample(1:n, m)  \ncol_indices <- sample(cols, m, replace = TRUE)\n```\n:::\n\n\n\nExplication détaillée du script :\n\n**n \\<- nrow(crabe)** : cette commande calcule le nombre total d'observations dans le jeu de données crabe et stocke ce nombre dans la variable n.\n\n**p \\<- ncol(crabe)** : cette commande détermine le nombre total de variables présentes dans le jeu de données crabe et l'assigne à la variable p.\n\n**m \\<- 50** : cette instruction spécifie le nombre total de valeurs manquantes à générer dans le jeu de données, fixé ici à 50.\n\n**cols \\<- c (\"poids\", \"diametre\", \"age\")** : cette ligne crée un vecteur cols contenant les noms des variables pour lesquelles les valeurs manquantes seront introduites.\n\n**row_indices \\<- sample(1:n, m)** : cet appel à sample produit un vecteur row_indices composé de m indices de lignes choisies aléatoirement parmi toutes les lignes disponibles, allant de 1 à n.\n\n**col_indices** \\<- sample(cols, m, replace = TRUE) : cette instruction crée un vecteur col_indices de m éléments, sélectionnant aléatoirement et avec remplacement parmi les noms de colonnes spécifiés dans cols.\n\nPour injecter les valeurs manquantes dans le jeu de données, nous parcourons les indices générés et assignons NA à la position correspondante à chaque itération de la boucle :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (i in 1:m) {\n  crabe[row_indices[i], col_indices[i]] <- NA\n}\ncrabe_mice <- crabe\ncrabe_missMDA <- crabe\n```\n:::\n\n\n\n## Visualisation des valeurs manquantes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg_miss_upset(crabe)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_line()`: Each group consists of only one observation.\nℹ Do you need to adjust the group aesthetic?\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Description de la figure.](Final_projet_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\nLe graphique ci-dessus, illustre la répartition des valeurs manquantes (N/A) que nous avons générées et insérées de manière aléatoire dans les colonnes sélectionnées de notre jeu de données. Au total, 50 valeurs manquantes ont été introduites : 19 dans la colonne du poids, 16 dans celle du diamètre et 15 dans celle de l'âge.\n\nAfin de mieux comprendre la distribution des colonnes où nous avons inséré des valeurs manquantes, et pour déterminer les méthodes de remplacement les plus adaptées, nous procédons à l'examen de la normalité et à l'analyse de la corrélation entre nos variables.\n\n## Test de normalité\n\n**QQ plot Age**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(crabe$age, main = \"Q-Q plot - Age\")\nqqline(crabe$age, col = 2)\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n**QQ plot Poids**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(crabe$poids, main = \"Q-Q Plot - Poids\")\n\nqqline(crabe$poids, col = 2)\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n**QQ plot Diametre**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(crabe$diametre, main = \"Q-Q Plot - Diamètre\")\n\nqqline(crabe$diametre, col = 2)\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\nUn graphique Q-Q (quantile-quantile) est un outil visuel utilisé en statistique pour comparer deux distributions de probabilité en traçant leurs quantiles l'un contre l'autre. Il est souvent utilisé pour vérifier si deux ensembles de données suivent une même distribution. Si les points s'alignent approximativement sur une ligne droite, cela suggère que les deux distributions sont similaires.\n\nDans notre cas, les Q-Q plots ne suivent pas la droite de la loi normale, nous pouvons donc supposer qu'ils ne suivent pas une distribution normale.\n\n**Calculer la moyenne et l'écart-type de nos données**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoyenne_age <- mean(crabe$age, na.rm = TRUE)\necart_type_age <- sd(crabe$age, na.rm = TRUE)\n\nmoyenne_poids <- mean(crabe$poids, na.rm = TRUE)\necart_type_poids <- sd(crabe$poids, na.rm = TRUE)\n\nmoyenne_diametre <- mean(crabe$diametre, na.rm = TRUE)\necart_type_diametre <- sd(crabe$diametre, na.rm = TRUE)\n```\n:::\n\n\n\n**Test KS pour comparer nos données à une distribution normale**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage.ks<-ks.test(crabe$age, \"pnorm\", mean = moyenne_age, sd = ecart_type_age)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in ks.test.default(crabe$age, \"pnorm\", mean = moyenne_age, sd =\necart_type_age): ties should not be present for the Kolmogorov-Smirnov test\n```\n\n\n:::\n\n```{.r .cell-code}\nage.ks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  crabe$age\nD = 0.14369, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\npoids.ks<-ks.test(crabe$poids, \"pnorm\", mean = moyenne_poids, sd = ecart_type_poids)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in ks.test.default(crabe$poids, \"pnorm\", mean = moyenne_poids, sd =\necart_type_poids): ties should not be present for the Kolmogorov-Smirnov test\n```\n\n\n:::\n\n```{.r .cell-code}\npoids.ks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  crabe$poids\nD = 0.046722, p-value = 9.026e-08\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n```{.r .cell-code}\ndiametre.ks<-ks.test(crabe$diametre, \"pnorm\", mean = moyenne_diametre, sd = ecart_type_diametre)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in ks.test.default(crabe$diametre, \"pnorm\", mean = moyenne_diametre, :\nties should not be present for the Kolmogorov-Smirnov test\n```\n\n\n:::\n\n```{.r .cell-code}\ndiametre.ks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  crabe$diametre\nD = 0.080708, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n\nNous avons par la suite effectué les tests de Kolmogorov-Smirnov, notre échantillon étant composé de plus de 50 observations. Ces tests confirment ce qu'on a constaté avec les Q-Q plots, nos variables ne présentent pas une distribution normale. De ce fait, nous excluons l'option de remplacement par la moyenne.\n\n## Matrice de corrélation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe |>\n  select(longueur:age) |>\n  drop_na() |>\n  cor() |>\n  corrplot::corrplot.mixed()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\nNous observons une corrélation existante entre les variables âge, diamètre et poids.\n\n::: callout-warning\n## Risque de multicolinarité\n\nLes variables longueur, diamètre, hauteur, poids, poids.chair, poids.visceres, et poids.coquille ont des coefficients supérieurs à 0.9. Dans le cadre de notre projet, l'objectif est d'utiliser la régression pour prédire et imputer des valeurs manquantes plutôt que pour l'inférence statistique, la multicolinéarité est un peu moins problématique. Cependant, elle peut affecter la stabilité des coefficients de régression utilisés dans l'imputation.\n:::\n\nAinsi, pour la suite, nous opterons pour des méthodes d'imputation plus robustes telles que l'imputation MICE (Multiple Imputation by Chained Equations) et la méthode basée sur l'Analyse en Composantes Principales (ACP), ainsi qu'un remplacement global des valeurs manquantes.\n\n# Deuxième méthode de remplacement : l'imputation MICE des valeurs manquantes pour l'age, le poids, diamètre\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmd.pattern(crabe_mice, rotate.names = TRUE)\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sexe longueur hauteur poids.chair poids.visceres poids.coquille age\n3843    1        1       1           1              1              1   1\n19      1        1       1           1              1              1   1\n16      1        1       1           1              1              1   1\n15      1        1       1           1              1              1   0\n        0        0       0           0              0              0  15\n     diametre poids   \n3843        1     1  0\n19          1     0  1\n16          0     1  1\n15          1     1  1\n           16    19 50\n```\n\n\n:::\n:::\n\n\n\nNous pouvons donc observer nos 50 valeurs manquantes réparties dans nos trois variables. Chaque valeur manquante n'est que dans une seule variable par observation.\n\nNous allons par la suite imputer les valeurs manquantes par plusieurs méthodes telles que Prédictive Mean Matching et Random Forest :\n\n-   PMM() : pour une observation avec une valeur manquante, la méthode trouve un ensemble d'observations (par exemple, les plus proches voisins) dans les données complètes dont les valeurs prédites par le modèle sont proches de la valeur prédite pour l'observation manquante.\n\n-   RF (Forêt aléatoire) : dans une forêt aléatoire, chaque arbre de décision est entraîné sur un sous-ensemble de données et un sous-ensemble de caractéristiques. La prédiction finale résulte de la moyenne des prédictions de tous les arbres individuels.\n\n## Aléatoire\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_mice_aleatoire <- mice(crabe_mice, m = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n iter imp variable\n  1   1  diametre  poids  age\n  1   2  diametre  poids  age\n  1   3  diametre  poids  age\n  1   4  diametre  poids  age\n  1   5  diametre  poids  age\n  2   1  diametre  poids  age\n  2   2  diametre  poids  age\n  2   3  diametre  poids  age\n  2   4  diametre  poids  age\n  2   5  diametre  poids  age\n  3   1  diametre  poids  age\n  3   2  diametre  poids  age\n  3   3  diametre  poids  age\n  3   4  diametre  poids  age\n  3   5  diametre  poids  age\n  4   1  diametre  poids  age\n  4   2  diametre  poids  age\n  4   3  diametre  poids  age\n  4   4  diametre  poids  age\n  4   5  diametre  poids  age\n  5   1  diametre  poids  age\n  5   2  diametre  poids  age\n  5   3  diametre  poids  age\n  5   4  diametre  poids  age\n  5   5  diametre  poids  age\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Number of logged events: 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncrabe_mice_aleatoire$imp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$sexe\n[1] 1 2 3 4 5\n<0 rows> (or 0-length row.names)\n\n$longueur\n[1] 1 2 3 4 5\n<0 rows> (or 0-length row.names)\n\n$diametre\n          1      2      3      4      5\n195  39.624 41.148 39.624 38.862 38.481\n211  34.290 33.147 33.909 33.528 32.385\n348  34.671 36.195 34.671 36.195 36.576\n1038 39.624 39.624 39.624 38.862 39.243\n1614 14.478 14.097 14.097 14.097 14.097\n1790 21.717 22.479 20.955 20.955 22.860\n1842 39.624 41.148 41.529 40.005 39.243\n1866 39.624 38.100 37.338 39.243 36.957\n1895 30.480 29.337 30.480 30.099 30.480\n2013 33.909 31.623 34.290 33.147 33.909\n2074 27.051 27.051 27.432 26.670 26.670\n2592 34.671 35.433 34.290 33.147 34.290\n2888 20.574 21.717 23.622 24.003 20.574\n3693 32.385 32.766 31.623 34.290 33.528\n3721 29.718 29.337 29.337 31.242 28.575\n3840 19.050 19.812 19.050 20.193 19.812\n\n$hauteur\n[1] 1 2 3 4 5\n<0 rows> (or 0-length row.names)\n\n$poids\n             1         2         3         4         5\n555  0.3725122 0.3596531 0.3307201 0.3596531 0.3913991\n665  1.0315414 1.0335507 0.9993937 1.0214953 0.9993937\n1115 0.8511121 0.8708026 0.9226409 0.9226409 0.9178187\n1142 0.3785399 0.3873806 0.3938101 0.3913991 0.4191265\n1167 0.7410060 0.6984102 0.6984102 0.7128767 0.7494448\n1268 0.5236067 0.5300363 0.5191864 0.4753851 0.5280271\n1627 0.3262998 0.3443829 0.3359442 0.3415700 0.3142444\n1673 0.5171772 0.5027107 0.5171772 0.4826183 0.5091402\n1799 1.7637068 1.7464274 1.7464274 1.7464274 1.7464274\n2227 0.9138002 0.8824562 0.9431351 0.9700588 0.9700588\n2463 1.4824139 1.4824139 1.4599104 1.5864923 1.4599104\n2538 1.0652966 1.1062850 1.1175367 1.0773520 1.0869963\n2641 0.3528217 0.3496070 0.3443829 0.3283091 0.3403645\n2757 0.4673481 0.4737777 0.4902534 0.4633297 0.4673481\n2971 0.8503084 0.8760266 0.8667841 0.8511121 0.8358419\n2980 0.3958194 0.3873806 0.3938101 0.3913991 0.3966231\n2986 0.4323875 0.4356022 0.4147062 0.4323875 0.4356022\n3371 0.3186647 0.3041982 0.3106278 0.3041982 0.3262998\n3446 0.4609186 0.4962811 0.4906553 0.4773943 0.4609186\n\n$poids.chair\n[1] 1 2 3 4 5\n<0 rows> (or 0-length row.names)\n\n$poids.visceres\n[1] 1 2 3 4 5\n<0 rows> (or 0-length row.names)\n\n$poids.coquille\n[1] 1 2 3 4 5\n<0 rows> (or 0-length row.names)\n\n$age\n      1  2  3  4  5\n373   6  6  5  5  6\n526  11 13 10 13  9\n905   9 11 14  9  9\n953  14  9 12 10  9\n1011  8 11  9  8  8\n1017  9  9  9 10  9\n1047  7  8  8 10  6\n1253 17 10  9 14  9\n1379 10  9  9  7 10\n1450  8 11  5  8  9\n2511 10 11 13  7 11\n2567 12  9 10  9  9\n2650 12 10 11 11 19\n2892  8  8 10 11  9\n2985 10  8 11 15 12\n```\n\n\n:::\n\n```{.r .cell-code}\ncrabe_mice_aleatoire$method\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          sexe       longueur       diametre        hauteur          poids \n            \"\"             \"\"          \"pmm\"             \"\"          \"pmm\" \n   poids.chair poids.visceres poids.coquille            age \n            \"\"             \"\"             \"\"          \"pmm\" \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(crabe_mice_aleatoire)\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n\nLorsque nous effectuons la méthode de manière aléatoire, le logiciel propose d'effectuer l'imputation avec la méthode PMM.\n\n## Imputation par la PMM\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeth_pmm <- c(\"\", \"\", \"pmm\", \"\", \"pmm\", \"\", \"\", \"\", \"pmm\")\nset.seed(123)\ncrabe_pmm <- mice(crabe_mice, method = meth_pmm, m = 6, maxit = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n iter imp variable\n  1   1  diametre  poids  age\n  1   2  diametre  poids  age\n  1   3  diametre  poids  age\n  1   4  diametre  poids  age\n  1   5  diametre  poids  age\n  1   6  diametre  poids  age\n  2   1  diametre  poids  age\n  2   2  diametre  poids  age\n  2   3  diametre  poids  age\n  2   4  diametre  poids  age\n  2   5  diametre  poids  age\n  2   6  diametre  poids  age\n  3   1  diametre  poids  age\n  3   2  diametre  poids  age\n  3   3  diametre  poids  age\n  3   4  diametre  poids  age\n  3   5  diametre  poids  age\n  3   6  diametre  poids  age\n  4   1  diametre  poids  age\n  4   2  diametre  poids  age\n  4   3  diametre  poids  age\n  4   4  diametre  poids  age\n  4   5  diametre  poids  age\n  4   6  diametre  poids  age\n  5   1  diametre  poids  age\n  5   2  diametre  poids  age\n  5   3  diametre  poids  age\n  5   4  diametre  poids  age\n  5   5  diametre  poids  age\n  5   6  diametre  poids  age\n  6   1  diametre  poids  age\n  6   2  diametre  poids  age\n  6   3  diametre  poids  age\n  6   4  diametre  poids  age\n  6   5  diametre  poids  age\n  6   6  diametre  poids  age\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Number of logged events: 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncrabe_pmm$imp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$sexe\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$longueur\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$diametre\n          1      2      3      4      5      6\n195  38.862 38.862 39.243 38.481 39.243 38.481\n211  33.528 34.290 32.004 33.528 33.528 32.766\n348  35.433 35.814 34.671 36.576 36.195 35.433\n1038 39.243 38.481 39.624 39.624 39.624 41.910\n1614 13.716 14.097 13.716 14.097 14.478 13.716\n1790 20.955 21.717 21.717 23.622 22.479 21.717\n1842 41.529 40.005 41.148 41.529 40.005 39.243\n1866 38.100 36.957 38.100 37.338 38.862 38.481\n1895 30.861 30.480 29.718 30.099 30.480 30.099\n2013 34.671 31.242 33.528 33.909 33.909 33.528\n2074 26.670 27.432 27.432 26.670 25.146 26.670\n2592 33.909 34.290 35.814 34.290 33.147 32.766\n2888 21.717 22.860 23.241 22.860 22.479 21.336\n3693 33.528 33.909 35.052 33.528 32.004 35.052\n3721 28.575 28.956 29.337 31.242 30.480 30.480\n3840 19.431 19.431 19.812 19.050 18.669 19.812\n\n$hauteur\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$poids\n             1         2         3         4         5         6\n555  0.3592513 0.3913991 0.3913991 0.3556347 0.3913991 0.3576439\n665  0.9993937 1.0476153 1.0162713 0.9993937 1.0022066 1.0162713\n1115 0.8511121 0.8708026 0.8908950 0.8217773 0.8812506 0.8908950\n1142 0.4114914 0.3978286 0.3785399 0.4010434 0.3913991 0.3966231\n1167 0.7385949 0.7518559 0.7229229 0.7213155 0.7385949 0.7518559\n1268 0.5236067 0.5280271 0.5288308 0.5043181 0.5288308 0.5441009\n1627 0.3142444 0.3415700 0.3781381 0.3142444 0.3359442 0.3415700\n1673 0.4826183 0.4998978 0.4978885 0.5087384 0.5023088 0.5111495\n1799 1.7464274 1.7637068 1.7464274 1.7689308 1.7761641 1.7689308\n2227 0.9109873 0.9495646 0.9431351 1.0315414 1.0315414 0.9085762\n2463 1.5109450 1.4920582 1.5213930 1.5141598 1.5213930 1.4920582\n2538 1.0869963 1.0869963 1.0652966 1.0580633 1.0745391 1.0701188\n2641 0.3275054 0.3283091 0.3387571 0.3283091 0.3283091 0.3351405\n2757 0.4625260 0.4790017 0.4665445 0.4790017 0.4918608 0.4790017\n2971 0.8531213 0.8531213 0.8531213 0.8358419 0.8358419 0.8032923\n2980 0.4046600 0.4046600 0.3938101 0.3913991 0.4010434 0.3841658\n2986 0.4022489 0.4243505 0.3946138 0.4243505 0.4159117 0.4022489\n3371 0.3190666 0.3190666 0.3262998 0.3146463 0.3262998 0.3226832\n3446 0.4713666 0.5019070 0.4922627 0.4794036 0.4922627 0.4524798\n\n$poids.chair\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$poids.visceres\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$poids.coquille\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$age\n      1  2  3  4  5  6\n373   6  6  7  7  6 13\n526  10 11 11 15  9 11\n905  11  9 10 13 11 10\n953  10 10  9 11  9  9\n1011  9 10  8 13  9 10\n1017 10 10 12  8 11 12\n1047  9  9 11  9  8  9\n1253  9  9 12  9 13  9\n1379  8  8 13 10  9  9\n1450  5  6  9  6  7 10\n2511  9 10  8  8 10 11\n2567 10 10  9 11  7 10\n2650 13  9 23  8  9 10\n2892  8 12  9 12 11  7\n2985  9 10 11 11 10 15\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(crabe_pmm, main=\"Plot selon la méthode pmm\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n\n## Imputation par la RF\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nmeth_rf <- c(\"\", \"\", \"rf\", \"\", \"rf\", \"\", \"\", \"\", \"rf\")\ncrabe_rf <- mice(crabe_mice, method = meth_rf, m = 6, maxit = 6, )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n iter imp variable\n  1   1  diametre  poids  age\n  1   2  diametre  poids  age\n  1   3  diametre  poids  age\n  1   4  diametre  poids  age\n  1   5  diametre  poids  age\n  1   6  diametre  poids  age\n  2   1  diametre  poids  age\n  2   2  diametre  poids  age\n  2   3  diametre  poids  age\n  2   4  diametre  poids  age\n  2   5  diametre  poids  age\n  2   6  diametre  poids  age\n  3   1  diametre  poids  age\n  3   2  diametre  poids  age\n  3   3  diametre  poids  age\n  3   4  diametre  poids  age\n  3   5  diametre  poids  age\n  3   6  diametre  poids  age\n  4   1  diametre  poids  age\n  4   2  diametre  poids  age\n  4   3  diametre  poids  age\n  4   4  diametre  poids  age\n  4   5  diametre  poids  age\n  4   6  diametre  poids  age\n  5   1  diametre  poids  age\n  5   2  diametre  poids  age\n  5   3  diametre  poids  age\n  5   4  diametre  poids  age\n  5   5  diametre  poids  age\n  5   6  diametre  poids  age\n  6   1  diametre  poids  age\n  6   2  diametre  poids  age\n  6   3  diametre  poids  age\n  6   4  diametre  poids  age\n  6   5  diametre  poids  age\n  6   6  diametre  poids  age\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Number of logged events: 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncrabe_rf$imp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$sexe\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$longueur\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$diametre\n          1      2      3      4      5      6\n195  40.767 40.005 43.053 44.196 41.148 40.767\n211  33.528 33.909 34.290 32.766 31.242 31.623\n348  33.909 35.814 35.433 34.671 35.814 34.290\n1038 40.005 39.243 40.005 38.481 41.148 38.100\n1614 14.859 13.716 13.716 14.478 14.097 13.335\n1790 23.622 22.098 22.860 22.479 22.479 22.860\n1842 40.767 38.862 40.005 41.148 40.386 40.005\n1866 36.576 38.100 35.433 39.243 38.862 38.481\n1895 29.337 29.718 29.718 30.861 33.147 30.099\n2013 32.766 34.290 33.528 32.766 34.290 34.290\n2074 27.051 26.670 28.194 27.051 27.813 28.575\n2592 34.671 34.671 35.433 34.290 34.671 33.528\n2888 28.194 26.289 27.813 27.813 20.574 28.956\n3693 33.147 32.385 33.147 35.433 32.004 33.528\n3721 28.194 31.242 29.718 30.861 29.718 30.099\n3840 19.050 19.812 19.812 20.193 15.621 19.431\n\n$hauteur\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$poids\n             1         2         3         4         5         6\n555  0.3520180 0.3158518 0.3837640 0.3664845 0.3644753 0.3837640\n665  1.0918185 1.0255137 0.9853290 0.9198280 1.0701188 0.9853290\n1115 0.8495047 0.8495047 0.7803870 0.7988720 0.8282068 0.8008812\n1142 0.4167154 0.4263597 0.3753252 0.5119532 0.4130988 0.4287708\n1167 0.7430152 0.6546089 0.6449646 0.7036342 0.7076527 0.7277451\n1268 0.4769925 0.4633297 0.5617822 0.5091402 0.5549508 0.4633297\n1627 0.3013853 0.3106278 0.3230850 0.3013853 0.2684338 0.3371497\n1673 0.5123550 0.5123550 0.5224012 0.5436991 0.5726321 0.5075329\n1799 1.7464274 1.5306355 1.7761641 2.1354154 1.6110049 1.7966583\n2227 0.7920406 0.8764285 0.7393986 0.7715464 0.9644330 1.0435969\n2463 1.1561140 1.4120906 1.4599104 1.5519334 1.7464274 1.5326447\n2538 1.0906130 1.0669040 1.0504283 1.0427932 0.9487609 1.1870563\n2641 0.3226832 0.2985724 0.1056858 0.3271035 0.3391589 0.3226832\n2757 0.4970848 0.4649371 0.4544890 0.4621241 0.4540872 0.4247524\n2971 0.8844654 0.9278649 0.8559343 0.8491029 0.8852691 0.8683915\n2980 0.4159117 0.3733159 0.3701012 0.3950157 0.3845677 0.3789418\n2986 0.3475977 0.3596531 0.3479996 0.4396207 0.4472558 0.4392189\n3371 0.3182629 0.3488033 0.3158518 0.3037964 0.3415700 0.3210758\n3446 0.5441009 0.5091402 0.4998978 0.4942719 0.5111495 0.4544890\n\n$poids.chair\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$poids.visceres\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$poids.coquille\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$age\n      1  2  3  4  5  6\n373   6  8  6  5  6  6\n526  11 12 13  8 10  9\n905  10  9 13  9 19 10\n953   9 19  9 12  9  8\n1011  8  8  9  8  9  8\n1017  9  8 10 10  8 10\n1047  7 13 10 10  8 16\n1253 11 10  7 10  9 17\n1379  9 11 11 12  9 10\n1450  9  9  9  8  9  8\n2511  8  9  9  9 11  8\n2567  9  8 11  9  9  9\n2650  9  9 10 12  8 11\n2892 11 10 10 15 10  8\n2985 19 12 10 15 11 10\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(crabe_rf, main=\"Plot selon la méthode rf\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n\n## Imputation mix entre PMM et RF\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeth_mix <- c(\"\", \"\", \"pmm\", \"\", \"pmm\", \"\", \"\", \"\", \"rf\")\nset.seed(123)\ncrabe_mix <- mice(crabe_mice, method = meth_mix,m = 6, maxit = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n iter imp variable\n  1   1  diametre  poids  age\n  1   2  diametre  poids  age\n  1   3  diametre  poids  age\n  1   4  diametre  poids  age\n  1   5  diametre  poids  age\n  1   6  diametre  poids  age\n  2   1  diametre  poids  age\n  2   2  diametre  poids  age\n  2   3  diametre  poids  age\n  2   4  diametre  poids  age\n  2   5  diametre  poids  age\n  2   6  diametre  poids  age\n  3   1  diametre  poids  age\n  3   2  diametre  poids  age\n  3   3  diametre  poids  age\n  3   4  diametre  poids  age\n  3   5  diametre  poids  age\n  3   6  diametre  poids  age\n  4   1  diametre  poids  age\n  4   2  diametre  poids  age\n  4   3  diametre  poids  age\n  4   4  diametre  poids  age\n  4   5  diametre  poids  age\n  4   6  diametre  poids  age\n  5   1  diametre  poids  age\n  5   2  diametre  poids  age\n  5   3  diametre  poids  age\n  5   4  diametre  poids  age\n  5   5  diametre  poids  age\n  5   6  diametre  poids  age\n  6   1  diametre  poids  age\n  6   2  diametre  poids  age\n  6   3  diametre  poids  age\n  6   4  diametre  poids  age\n  6   5  diametre  poids  age\n  6   6  diametre  poids  age\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Number of logged events: 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncrabe_mix$imp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$sexe\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$longueur\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$diametre\n          1      2      3      4      5      6\n195  38.862 37.719 39.243 38.481 38.862 38.862\n211  30.480 29.718 32.385 34.290 32.004 33.909\n348  35.433 35.814 36.576 35.814 36.195 36.195\n1038 39.624 38.481 39.243 38.481 39.624 39.624\n1614 14.859 14.097 14.859 14.478 14.478 14.478\n1790 20.574 20.574 21.717 20.955 21.336 23.622\n1842 39.243 41.148 40.005 40.767 38.481 39.243\n1866 38.100 38.100 39.624 38.481 37.719 38.481\n1895 30.099 30.099 29.337 29.337 30.480 30.099\n2013 32.385 33.528 32.766 33.528 33.528 32.385\n2074 27.432 27.051 26.289 27.432 26.289 26.670\n2592 33.909 34.290 36.195 34.290 34.290 33.909\n2888 21.336 20.574 22.860 22.860 22.860 23.622\n3693 34.290 33.147 35.052 33.528 33.909 35.052\n3721 31.242 30.480 30.099 28.575 30.480 28.575\n3840 19.431 19.431 20.193 19.431 19.050 19.812\n\n$hauteur\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$poids\n             1         2         3         4         5         6\n555  0.3753252 0.3604568 0.3905954 0.3644753 0.3692975 0.3592513\n665  1.0222990 1.0158694 0.9977863 0.9977863 1.0142620 0.9977863\n1115 1.0407839 0.8732137 0.9178187 0.8752229 0.8217773 0.9226409\n1142 0.3873806 0.3978286 0.4130988 0.4191265 0.3785399 0.3978286\n1167 0.7128767 0.7044379 0.8044978 0.7518559 0.7329691 0.7385949\n1268 0.5441009 0.5280271 0.5215975 0.5441009 0.5304381 0.5441009\n1627 0.3262998 0.3311220 0.3781381 0.3387571 0.3142444 0.3142444\n1673 0.5027107 0.4826183 0.5171772 0.5091402 0.4978885 0.5027107\n1799 1.7464274 1.7637068 1.9135958 1.9135958 1.7689308 1.7464274\n2227 0.8776340 0.9652367 0.9495646 0.8824562 0.9226409 0.9495646\n2463 1.5109450 1.5897070 1.5864923 1.5141598 1.4824139 1.5141598\n2538 1.0745391 1.0652966 1.0994536 1.0693151 1.0532412 1.0604744\n2641 0.3391589 0.3347386 0.3283091 0.3528217 0.3387571 0.3283091\n2757 0.4625260 0.4625260 0.4665445 0.4673481 0.4665445 0.4681518\n2971 0.8772322 0.8667841 0.8503084 0.9065670 0.8478973 0.8603546\n2980 0.3479996 0.3990341 0.3958194 0.3958194 0.3938101 0.4046600\n2986 0.4468539 0.4231450 0.4356022 0.4319856 0.4243505 0.4468539\n3371 0.3371497 0.3319257 0.3262998 0.3070112 0.3041982 0.3166555\n3446 0.4886460 0.4609186 0.4962811 0.4725722 0.4886460 0.4886460\n\n$poids.chair\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$poids.visceres\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$poids.coquille\n[1] 1 2 3 4 5 6\n<0 rows> (or 0-length row.names)\n\n$age\n      1  2  3  4  5  6\n373   6  9  6  6  5  5\n526  10 11 11  9 10 10\n905  10  9 15 11 14  9\n953  13 10 12 12 12 17\n1011  8  8  8  8  8  9\n1017 11  9 11 12 11  8\n1047 10 12 12  7  9 12\n1253 10 10 11  8 15 12\n1379 12  9  8 12  9 12\n1450  8  9  9  7  9  9\n2511 10  8 10  9  9 10\n2567  8 10  8  9  9 11\n2650 11 14  9 10 10 11\n2892 11  9 18 10  9 11\n2985  9  8 18 12  8 10\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(crabe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"sexe\"           \"longueur\"       \"diametre\"       \"hauteur\"       \n[5] \"poids\"          \"poids.chair\"    \"poids.visceres\" \"poids.coquille\"\n[9] \"age\"           \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(crabe_mix, main=\"Plot avec la méthode mix\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n\nNous observons donc que la méthode de remplacement par la PMM n'est pas optimale, choisissons donc l'imputation par la méthode de random forest.\n\nAprès avoir analysé les graphiques, nous pouvons dire que la meilleure itération est la 2ème, c'est pourquoi nous procédons à l'imputation avec celle-ci.\n\n## Imputation des valeurs manquantes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_complet_mice_rf2 <- mice::complete(crabe_rf, 2)\n```\n:::\n\n\n\n## Vérification\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmd.pattern(crabe_complet_mice_rf2, rotate.names = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n /\\     /\\\n{  `---'  }\n{  O   O  }\n==>  V <==  No need for mice. This data set is completely observed.\n \\  \\|/  /\n  `-----'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sexe longueur diametre hauteur poids poids.chair poids.visceres\n3893    1        1        1       1     1           1              1\n        0        0        0       0     0           0              0\n     poids.coquille age  \n3893              1   1 0\n                  0   0 0\n```\n\n\n:::\n:::\n\n\n\nToutes les valeurs manquantes ont bien été imputées.\n\n# Troisième méthode: ACP (Analyse en composante principale)\n\nLa PCA est utilisée pour réduire la dimensionnalité des données tout en préservant autant que possible la variance des données. Elle s'effectue sur des variables exclusivement quantitatives.\n\nLe principe est d'itérer entre l'estimation des composantes principales et l’imputation des valeurs manquantes jusqu'à contingence.\n\nLa PCA elle-même ne fait pas d'hypothèses sur la distribution des données. Elle cherche à capturer la structure linéaire (corrélation) entre les variables.\n\nDans le contexte de l'imputation, l'objectif est de remplacer les valeurs manquantes de manières à préserver la structure globale des données.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_acp <- crabe_missMDA |>\n  drop_na()\n```\n:::\n\n\n\nCette première étape à permis de trier notre jeux de données en ne gardant que les valeurs non-manquantes afin d'effectuer l'ACP.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_acp |>\n    group_by(sexe) |>\n    summarize(\n      across(where(is.numeric),\n      \t\t median) ) |>\n           \t\t ungroup()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  sexe  longueur diametre hauteur poids poids.chair poids.visceres\n  <chr>    <dbl>    <dbl>   <dbl> <dbl>       <dbl>          <dbl>\n1 F         45.0     35.4   12.2  0.836       0.354         0.181 \n2 I         33.1     25.5    8.38 0.308       0.136         0.0651\n3 M         44.2     34.7   11.8  0.785       0.340         0.170 \n# ℹ 2 more variables: poids.coquille <dbl>, age <dbl>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nacp_simple <- crabe_acp |>\n    select(- sexe) |>\n    PCA()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-40-2.png){width=672}\n:::\n:::\n\n\n\nConcernant le cercle de corrélation :\n\n-   Nous observons dans un premier temps que l'axe 1 à une inertie de 85,3 %, ce qui signifie qu'il explique à lui seul 85,3 % de la variance totale des données. De plus, il représente de manière significative toutes nos variables, à l'exception de la variable age.\n\n-   Les angles de nos variables sont fermés ce qui nous permet d'affirmer que nos variables sont très corrélées entre elles.\n\nConcernant le graphique des individus :\n\n-   On observe des clusters d'individus contribuant soit positivement soit négativement aux composantes principales.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacp_simple$eig\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        eigenvalue percentage of variance cumulative percentage of variance\ncomp 1 6.826744442            85.33430552                          85.33431\ncomp 2 0.698233146             8.72791432                          94.06222\ncomp 3 0.187355572             2.34194465                          96.40416\ncomp 4 0.122746877             1.53433596                          97.93850\ncomp 5 0.082778256             1.03472820                          98.97323\ncomp 6 0.062872043             0.78590054                          99.75913\ncomp 7 0.012671889             0.15839862                          99.91753\ncomp 8 0.006597775             0.08247218                         100.00000\n```\n\n\n:::\n\n```{.r .cell-code}\nfviz_screeplot(acp_simple, addlabels = TRUE)\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n\nOn peut donc confirmer que la dimension 1 explique à elle seule 85,3% de la variance.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_sans_sexe <- crabe_acp |> select(-sexe)\n\nres.pca<-PCA(crabe_sans_sexe)\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-42-2.png){width=672}\n:::\n\n```{.r .cell-code}\ncontribution<-round(res.pca$var$contrib,2)\n\ncorrplot(contribution, is.corr=FALSE, method=\"circle\", tl.srt=45, tl.col=\"#002200\",\n     \tcol=brewer.pal(n=9, name=\"OrRd\"), addCoef.col=\"black\", main=\"Tableau des contributions\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-42-3.png){width=672}\n:::\n:::\n\n\n\nCe tableau des contributions permet de voir que toutes nos variables sont significatives pour la dimension 1 à l'exception de la variable âge qui est plus contributive pour la dimension 2.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacp <- PCA(\n  X = crabe_acp,\n  quali.sup = c(\"sexe\"))\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-43-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.PCA(acp, choix = \"ind\", label = \"quali\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot.PCA(acp, choix = \"ind\", habillage = \"sexe\", label = \"none\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-44-2.png){width=672}\n:::\n:::\n\n\n\nNous avons ensuite cherché à visualiser les individus dans l'ACP, en leur attribuant des couleurs ou des étiquettes en fonction de certaines variables qualitatives (comme le genre dans le deuxième cas), ce qui facilite la compréhension de la distribution des individus dans l'espace des composantes principales.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacp$eig\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        eigenvalue percentage of variance cumulative percentage of variance\ncomp 1 6.826744442            85.33430552                          85.33431\ncomp 2 0.698233146             8.72791432                          94.06222\ncomp 3 0.187355572             2.34194465                          96.40416\ncomp 4 0.122746877             1.53433596                          97.93850\ncomp 5 0.082778256             1.03472820                          98.97323\ncomp 6 0.062872043             0.78590054                          99.75913\ncomp 7 0.012671889             0.15839862                          99.91753\ncomp 8 0.006597775             0.08247218                         100.00000\n```\n\n\n:::\n:::\n\n\n\nNous travaillerons avec les dimensions 1 et 2 qui explique à elles seules 92,5 % de la variance.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_complet_acp <-  MIPCA(crabe_missMDA |> select(-sexe), scale=TRUE, ncp=2)\n```\n:::\n\n\n\nNous procédons donc maintenant à l'analyse en composante principales multiple imputation en excluant la variable \"sexe\", étant une variable qualitative, elle ne peut pas être utilisée dans l'acp qui est exclusivement quantitative. De plus, nous spécifions que nous travaillerons avec deux composantes principales avec le paramètre : ncp=2.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.MIPCA(crabe_complet_acp, choice = \"dim\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$PlotDim\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-47-2.png){width=672}\n:::\n:::\n\n\n\nLe premier graphique après imputation est la projection de nos variables selon les deux premières dimensions de l'ACP.\n\nComme toutes les flèches sont proches soit de l'axes 1 soit de l'axe 2, cela signifie que les axes sont stables. Cette stabilité nous permet d'interpréter les résultats de notre ACP.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.MIPCA(crabe_complet_acp, choice = \"var\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$PlotVar\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-48-2.png){width=672}\n:::\n:::\n\n\n\nCe graphique spécifie que l'on souhaite visualiser les variables originales dans l'espace des deux premières dimensions de l'ACP. On observe dans notre cas que le graphique ne montre pas d'auréoles, les données ont donc bien été traitées et elles sont représentées de manière cohérente dans nos deux dimensions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_complet_acp <-\n    bind_cols(\n      crabe_missMDA |> select(sexe),\n      crabe_complet_acp[[\"res.imputePCA\"]])\n```\n:::\n\n\n\nEnsuite, nous ajoutons notre variables \"sexe\" à notre base de données imputées des valeurs manquantes.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmd.pattern(crabe_complet_acp, rotate.names = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n /\\     /\\\n{  `---'  }\n{  O   O  }\n==>  V <==  No need for mice. This data set is completely observed.\n \\  \\|/  /\n  `-----'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sexe longueur diametre hauteur poids poids.chair poids.visceres\n3893    1        1        1       1     1           1              1\n        0        0        0       0     0           0              0\n     poids.coquille age  \n3893              1   1 0\n                  0   0 0\n```\n\n\n:::\n:::\n\n\n\nPour terminer, nous pouvons confirmer que toute nos variables ont bien été imputées.\n\n# Comparaison des deux analyses\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(tableau1, tableau2, tableau3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Mice          ACP Approche_retenue\n1  0.0033393270 0.0022554586              Acp\n2  0.0012722836 0.0023577737             Mice\n3 -0.0001155065 0.0001045964             Mice\n```\n\n\n:::\n:::\n\n\n\nEn observant les résultats, nous pouvons conclure que la meilleure approche pour notre base de données est l'imputation MICE puisqu'elle domine sur deux de nos variables.\n\n# Analyse descriptive sans N/A\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n summary(crabe_complet_mice_rf2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sexe              longueur         diametre         hauteur      \n Length:3893        Min.   : 5.715   Min.   : 4.191   Min.   : 0.000  \n Class :character   1st Qu.:34.290   1st Qu.:26.670   1st Qu.: 8.763  \n Mode  :character   Median :41.529   Median :32.385   Median :11.049  \n                    Mean   :39.969   Mean   :31.116   Mean   :10.623  \n                    3rd Qu.:46.863   3rd Qu.:36.576   3rd Qu.:12.573  \n                    Max.   :62.103   Max.   :49.530   Max.   :19.050  \n     poids           poids.chair        poids.visceres      poids.coquille    \n Min.   :0.001607   Min.   :0.0008037   Min.   :0.0004018   Min.   :0.001205  \n 1st Qu.:0.359251   1st Qu.:0.1514963   1st Qu.:0.0755473   1st Qu.:0.105284  \n Median :0.646170   Median :0.2704431   Median :0.1378335   Median :0.188868  \n Mean   :0.668005   Mean   :0.2893730   Mean   :0.1456185   Mean   :0.192659  \n 3rd Qu.:0.929472   3rd Qu.:0.4046600   3rd Qu.:0.2041383   3rd Qu.:0.265219  \n Max.   :2.270838   Max.   :1.1958969   Max.   :0.6108076   Max.   :0.807713  \n      age        \n Min.   : 1.000  \n 1st Qu.: 8.000  \n Median :10.000  \n Mean   : 9.958  \n 3rd Qu.:11.000  \n Max.   :29.000  \n```\n\n\n:::\n:::\n\n\n\nEn réexaminant les statistiques de notre jeu de données corrigé et en les comparant à l'analyse exploratoire initiale, nous observons que :\n\n-   La moyenne de la variable « hauteur » a été légèrement ajustée, passant de 10,649 à 10,623, tandis que la médiane est restée inchangée à 11,049.\n-   Concernant l'âge, la moyenne a été légèrement modifiée, évoluant de 9,955 à 9,958, sans pour autant altérer significativement l'interprétation de la distribution.\n-   Les autres statistiques relatives à la longueur, au diamètre, au poids, au poids de la chair, au poids des viscères et au poids de la coquille sont identiques à celles énoncées dans la description initiale.\n\n## Analyse descriptive univariée\n\nLes variables quantitatives sont longueur, diamètre, hauteur, poids, poids de la chair, poids des viscères, poids de la coquille et âge.\n\nEt nous avons une seule variable qualitative: le sexe.\n\n## Variable Qualitative\n\n**Tableau de contingence**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(crabe_complet_mice_rf2, sexe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sexe    n\n1    F 1225\n2    I 1233\n3    M 1435\n```\n\n\n:::\n:::\n\n\n\nNous avons trois catégories de sexe : femelle (F), indéterminé (I) et mâle (M), avec respectivement 1225, 1233 et 1435 individus dans chaque catégorie.\n\n## Variables quantitatives\n\n### Boite à moustache\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_complet_mice_rf2 |>\n \tpivot_longer(\n  \tcols = where(is.numeric)\n\t) |>\n\tggplot() +\n\taes(y = value) +\n\tfacet_wrap(~ name, scales = \"free_y\") +\n\tgeom_boxplot() +\n\ttheme_light()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\n\nAprès avoir vérifié et corrigé les deux valeurs aberrantes pour la variable « hauteur », nous avons décidé de conserver les valeurs extrêmes présentes pour les autres variables de type poids et taille. De même, concernant l'âge, étant donné que la longévité d'un crabe peut atteindre 3 à 4 ans et que nos données incluent des valeurs jusqu'à 30 mois, soit 2,5 ans, ces observations sont jugées cohérentes avec le comportement naturel des crabes.\n\n### Histogrammes\n\nPour enrichir l'analyse, nous visualisons la forme de la distribution à l'aide d'histogrammes et superposons une courbe de densité. Cela nous permet d'évaluer visuellement la normalité de la distribution et de souligner les modes ainsi que les asymétries.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| warning: false\nggplot(crabe_complet_mice_rf2, aes(x = longueur)) +\n  geom_histogram(aes(y = ..density..), binwidth = 1, fill = \"blue\", color = \"black\", alpha = 0.4) +\n  geom_density(color = \"red\", size = 1) +  \n  labs(title = \"Distribution de la longueur \", x = \"Longueur\", y = \"Densité\") +  \n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.\nℹ Please use `after_stat(density)` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\n\nLa distribution présente une légère asymétrie à droite. Cela signifie qu'il y a une proportion de crabes qui ont des longueurs plus grandes que la moyenne.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe, aes(x = diametre)) +\n  geom_histogram(aes(y = ..density..), binwidth = 1, fill = \"blue\", color = \"black\", alpha = 0.4) +  \n  geom_density(color = \"red\", size = 1) +  \n  labs(title = \"Distribution du diamètre  avec courbe de densité\",\n   \tx = \"Diamètre\",\n   \ty = \"Densité\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n\nLa distribution du diamètre n'est pas symétrique ; elle présente une forme qui semble multimodale et qui n'est pas normale en raison de ses multiples pics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe_complet_mice_rf2, aes(x = hauteur)) +\n  geom_histogram(aes(y = ..density..), binwidth = 0.5, fill = \"blue\",color = \"black\", alpha = 0.6) +\n  geom_density(color = \"red\", size = 1) +\n  labs(title = \"Distribution de la hauteur \", x = \"Hauteur\", y = \"Densité\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n:::\n\n\n\nLe graphique nous montre une distribution de la hauteur des crabes qui semble être multimodale, car il y a plusieurs pics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe_complet_mice_rf2, aes(x = poids)) +\n  geom_histogram(aes(y = ..density..), binwidth = 0.1, fill = \"orange\", color = \"black\", alpha = 0.6) +\n  geom_density(color = \"red\", size = 1) +\n  labs(title = \"Distribution du poids \", x = \"Poids\", y = \"Densité\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe_complet_mice_rf2, aes(x = poids.chair)) +\n  geom_histogram(aes(y = ..density..), binwidth = 0.01, fill = \"orange\",  alpha = 0.6) +\n  geom_density(color = \"red\", size = 1) +\n  labs(title = \"Distribution du poids de chair \", x = \"Poids de chair\", y = \"Densité\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe_complet_mice_rf2, aes(x = poids.visceres)) +\n  geom_histogram(aes(y = ..density..), binwidth = 0.01, fill = \"orange\",  alpha = 0.6) +\n  geom_density(color = \"red\", size = 1) +\n  labs(title = \"Distribution du poids des viscères \", x = \"Poids des viscères\", y = \"Densité\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe_complet_mice_rf2, aes(x = poids.coquille)) +\n  geom_histogram(aes(y = ..density..), binwidth = 0.01, fill = \"orange\",  alpha = 0.6) +\n  geom_density(color = \"red\", size = 1) +\n  labs(title = \"Distribution du poids de la coquille \", x = \"Poids de la coquille\", y = \"Densité\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n:::\n\n\n\nLes poids de viscères, de la coquille et de la chair, pressentent des distribution asymétriques à droite, avec une concentration plus élevée de valeurs faibles et une queue qui s'étend vers des valeurs plus élevées.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe_complet_mice_rf2, aes(x = age)) +\n  geom_histogram(aes(y = ..density..), binwidth = 1, fill = \"blue\", alpha = 0.6) +\n  geom_density(color = \"red\", size = 1) +\n  labs(title = \"Distribution de l'âge \", x = \" ge\", y = \"Densité\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n:::\n\n\n\nLa queue de la distribution s'étend jusqu'à environ 30 mois, avec une diminution progressive de la densité au fur et à mesure que l'âge augmente, indiquant moins de crabes plus âgés.\n\n# Analyse Bivariée\n\n## Quantitative - Quantitative\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n ggplot(crabe, aes(x = age, y = diametre, color = sexe)) +\n  geom_point() +\n  scale_color_manual(values = vecteur_couleur) +  \n  theme_minimal() +  \n  labs(title = \"Relation entre l'âge et le diamètre \",\n   \tx = \" ge\",\n   \ty = \"Diamètre\")  \n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-66-1.png){width=672}\n:::\n:::\n\n\n\nNous pouvons observer une tendance positive entre l'âge et le diamètre, ce qui signifie que, en général, le diamètre des crabes augmente avec l'âge. Et on peut aussi observer que les crabes de sexe indéfini sont très présents jusqu'à l'âge de 10 mois.\n\n**Corrélation (variables type poids)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(crabe_complet_mice_rf2[c(\"poids\", \"poids.chair\", \"poids.visceres\", \"poids.coquille\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   poids poids.chair poids.visceres poids.coquille\npoids          1.0000000   0.9689417      0.9655096      0.9552759\npoids.chair    0.9689417   1.0000000      0.9312796      0.8824063\npoids.visceres 0.9655096   0.9312796      1.0000000      0.9061047\npoids.coquille 0.9552759   0.8824063      0.9061047      1.0000000\n```\n\n\n:::\n:::\n\n\n\nEn ce qui concerne la relation entre le \"poids\", \"poids.chair\", \"poids.visceres\", \"poids.coquille\" les fortes corrélations indiquent que les différentes mesures de poids sont interdépendantes, ce qui n'est pas surprenant compte tenu de leur nature biologique.\n\nLes lignes de régression sont bien ajustées à la distribution des points, bien que quelques points éloignés (valeurs extrêmes) en particulier dans la plage supérieure des valeurs.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariables_quantitatives <- c(\"longueur\", \"diametre\", \"hauteur\", \"poids\")\n\n# Création de toutes les paires possibles sans répétition ni inversion\npaires <- combn(variables_quantitatives, 2, simplify = FALSE)\n\n\ngraphiques <- map(paires, ~ ggplot(crabe_complet_mice_rf2, aes_string(x = .[1], y = .[2], color = \"sexe\")) +\n\tgeom_point() +\n\tgeom_smooth(method = \"lm\", se = FALSE) +\n\tscale_color_manual(values = vecteur_couleur) +\n\tlabs(title = paste(\"Relation entre\", .[1], \"et\", .[2])) +\n\ttheme_classic()\n)\n\n\ngraphiques\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-68-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-68-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[3]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-68-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[4]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-68-4.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[5]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-68-5.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[6]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-68-6.png){width=672}\n:::\n:::\n\n\n\nToutes les relations que nous observons sont positives, par exemple la relation entre le diamètre et le poids signifie qu'à mesure que le diamètre augmente, le poids augmente aussi. La ligne de régression pour les femelles est légèrement supérieure à celle des mâles et des jeunes (I), indiquant que pour un même diamètre, les femelles ont tendance à être plus lourdes.\n\nLa relation linéaire entre longueur et diamètre, mais aussi le diamètre et la hauteur et elle est presque uniforme entre les sexes et les points autour des lignes de régression suggère une variance faible des résidus.\n\nEn examinant de plus près la répartition des points selon les catégories de sexe, nous constatons que les données des mâles et des femelles se superposent sur une large gamme de valeurs pour toutes les paires de variables étudiées, ce qui indique des caractéristiques similaires entre ces deux groupes. En revanche, les points représentant la catégorie indéterminée (I) se concentrent davantage sur les échelons inférieurs des variables mesurées, suggérant que les individus classés comme indéterminés tendent à avoir des longueurs, des diamètres et des poids inférieurs par rapport aux mâles et aux femelles.\n\n## Qualitative - quantitative\n\nAfin d'examiner les relations entre nos variables quantitatives et notre variable qualitative, nous procédons à une visualisations deux à deux :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe_complet_mice_rf2, aes(x = sexe, y = longueur)) +\n  geom_boxplot() +\n  labs(title = \"Comparaison de la taille entre les sexes \", x = \"Sexe\", y = \"Longueur\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-69-1.png){width=672}\n:::\n:::\n\n\n\nNous pouvons observer que la médiane semble être légèrement plus élevée pour les femelles que pour les mâles et aussi elles semblent avoir une étendue interquartile (entre le premier et le troisième quartile) plus étroite que celle des mâles. Cela indique que les longueurs des femelles sont moins dispersées autour de la médiane.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe_complet_mice_rf2, aes(x = sexe, y = poids)) +\n  geom_boxplot() +\n  labs(title = \"Comparaison du poids entre les sexes \", x = \"Sexe\", y = \"Poids\")\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-70-1.png){width=672}\n:::\n:::\n\n\n\nLes médianes semblent similaires entre les sexes.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crabe_complet_mice_rf2) +\n\taes(x = poids, fill = sexe) +\n\tgeom_histogram(bins = 50) +\n\tscale_fill_manual(values = vecteur_couleur) +\n\ttheme_bw()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-71-1.png){width=672}\n:::\n:::\n\n\n\nLes crabes féminins et masculins ont des distributions similaires, avec une gamme de poids étendue, tandis que les indéterminées ont une distribution plus concentrée vers les poids inférieurs.\n\n**Fréquences en fonction du sexe**\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ncrabe_complet_mice_rf2 |>\n  group_by(sexe, diametre) |>\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 266 × 3\n# Groups:   sexe, diametre [266]\n   sexe  diametre     n\n   <chr>    <dbl> <int>\n 1 F         14.9     1\n 2 F         16.0     1\n 3 F         16.8     1\n 4 F         17.1     2\n 5 F         17.5     1\n 6 F         19.0     1\n 7 F         19.4     2\n 8 F         19.8     3\n 9 F         20.2     3\n10 F         20.6     2\n# ℹ 256 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ncrabe_complet_mice_rf2 |>\n  group_by(sexe, poids) |>\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,093 × 3\n# Groups:   sexe, poids [3,093]\n   sexe   poids     n\n   <chr>  <dbl> <int>\n 1 F     0.0643     1\n 2 F     0.113      1\n 3 F     0.119      1\n 4 F     0.125      1\n 5 F     0.137      1\n 6 F     0.149      1\n 7 F     0.151      1\n 8 F     0.154      1\n 9 F     0.158      1\n10 F     0.161      1\n# ℹ 3,083 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ncrabe_complet_mice_rf2 |>\n  group_by(sexe, age) |>\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 68 × 3\n# Groups:   sexe, age [68]\n   sexe    age     n\n   <chr> <int> <int>\n 1 F         5     4\n 2 F         6    15\n 3 F         7    39\n 4 F         8   114\n 5 F         9   220\n 6 F        10   237\n 7 F        11   185\n 8 F        12   120\n 9 F        13    85\n10 F        14    54\n# ℹ 58 more rows\n```\n\n\n:::\n:::\n\n\n\n# Conclusion\n\nAinsi, notre base de données, visant à comprendre les caractéristiques des crabes de Boston, est complète. Les valeurs aberrantes, extrêmes et les valeurs manquantes ont été remplacées avec différentes méthodes telles que la régression linéaire et des méthodes d'imputation multiple comme la méthode MICE ou missMDA. Aussi, l'approche MICE est celle que nous avons retenue pour notre analyse descriptive finale, étant celle avec le moins de différence par rapport à la base de données d'origine.\n\nDe plus, à la suite de notre analyse descriptive, nous avons voulu montrer au travers d'une régression logistique (Annexe) une analyse permettant d’identifier les caractéristiques des crabes femelles et mâles afin de remplacer le sexe indéterminé, mais cela ne s'est pas révélé significatif.\n\n# Annexe: Régression Logistique\n\n## Base avec crabe jeune\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_jeune<-crabe |> filter (age<=9)\n```\n:::\n\n\n\n## Boite à moustache avec crabe jeune\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_jeune |>\n  pivot_longer(\n    cols = where(is.numeric)\n    ) |>\n  ggplot() +\n  aes(y = value) +\n  facet_wrap(~ name, scales = \"free_y\") +\n  geom_boxplot() +\n  theme_light()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 22 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-76-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabe_jeune|>\n  pivot_longer(\n    cols = longueur:age,\n    names_to = \"mesure\",\n    values_to = \"valeur\"\n    ) |>\n  ggplot() +\n  aes(y = valeur, x = sexe, color = sexe) +\n  geom_boxplot() +\n  geom_jitter(alpha = 0.3) +\n  scale_fill_manual(values = vecteur_couleur)+\n  facet_wrap(~ mesure, scales = \"free_y\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-77-1.png){width=672}\n:::\n:::\n\n\n\n## Regresion\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabes_reg <- crabe_jeune |>\n  mutate(sexe = case_when(\n    sexe == \"M\" ~ 0,\n    sexe == \"F\" ~ 1\n    ))\n\ncount(crabes_reg, sexe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sexe    n\n1    0  533\n2    1  390\n3   NA 1000\n```\n\n\n:::\n\n```{.r .cell-code}\ncrabes_reg |>\n  pivot_longer(\n    cols = longueur:age,\n    names_to = \"mesure\",\n    values_to = \"valeur\"\n    ) |>\n  ggplot() +\n  aes(y = valeur) +\n  geom_boxplot() +\n  facet_wrap(~ mesure, scales = \"free_y\") +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 22 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-78-1.png){width=672}\n:::\n\n```{.r .cell-code}\nstr(crabes_reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t1923 obs. of  9 variables:\n $ sexe          : num  1 0 NA NA 1 NA 0 0 NA NA ...\n $ longueur      : num  43.8 27.1 31.6 27.1 47.2 ...\n $ diametre      : num  35.8 19.8 23.6 20.2 35.4 ...\n $ hauteur       : num  12.57 6.48 7.62 6.48 10.67 ...\n $ poids         : num  0.698 0.153 0.225 0.196 0.813 ...\n $ poids.chair   : num  0.3496 0.0651 0.0916 0.0981 0.385 ...\n $ poids.visceres: num  0.1583 0.039 0.0454 0.0422 0.1917 ...\n $ poids.coquille: num  0.1913 0.0442 0.0784 0.0482 0.2049 ...\n $ age           : int  9 6 6 6 8 7 6 9 7 6 ...\n```\n\n\n:::\n:::\n\n\n\n**Séparation des données en ensembles d'entraînement et de test**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabes_entrainement <- crabes_reg |>\n  filter(!is.na(sexe)) |>\n  slice_sample(prop = 0.8)\n```\n:::\n\n\n\n**Vérification**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrabes_verification <- anti_join(\n  crabes_reg,\n  crabes_entrainement\n\n) |>\n  filter(!is.na(sexe))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(sexe, longueur, diametre, hauteur, poids,\npoids.chair, poids.visceres, poids.coquille, age)`\n```\n\n\n:::\n:::\n\n\n\n## Régression logistique\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression_logistique <- glm(\n  sexe ~ longueur + diametre + hauteur + poids + poids.chair + poids.visceres + poids.coquille + age,\n  data = crabes_entrainement,\n  family = binomial\n)\n\ncar::Anova(regression_logistique)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: sexe\n               LR Chisq Df Pr(>Chisq)  \nlongueur         2.5231  1    0.11219  \ndiametre         0.0935  1    0.75978  \nhauteur          0.0963  1    0.75633  \npoids            0.3523  1    0.55283  \npoids.chair      3.4108  1    0.06477 .\npoids.visceres   0.0200  1    0.88750  \npoids.coquille   0.4589  1    0.49813  \nage              0.0015  1    0.96905  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nSelon les résultats, aucun des prédicteurs n'est significatif au seuil traditionnel de 0.05, bien que **`poids.chair`** soit proche avec une valeur de p de 0.06477. Cela suggère qu'il pourrait y avoir une association entre le poids de la chair et le sexe des crabes.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression_logistique2 <- glm(\n  sexe ~ poids.chair,\n  data = crabes_entrainement,\n  family = binomial\n)\n\ncar::Anova(regression_logistique2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: sexe\n            LR Chisq Df Pr(>Chisq)    \npoids.chair   11.391  1   0.000738 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(regression_logistique2)\n```\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-82-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-82-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-82-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Final_projet_files/figure-html/unnamed-chunk-82-4.png){width=672}\n:::\n:::\n",
    "supporting": [
      "Final_projet_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}